cvat/apps/engine/task.py
- jpg doesnt support alpha channels
- when importing pictures with alpha channel error shows up
-- "Could not create the task. OSError: cannot write mode RGBA as JPEG"
- fix error by converting "RGBA" to "RGB" before saving image
=> enable the import of picture with alpha channel

cvat/apps/engine/annotation.py, cvat/apps/engine/static/engine/js/annotationParser.js, cvat/apps/engine/static/engine/js/shapeBuffer.js, cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapes.js
=> Data validation on client and server

README.md, cvat/apps/documentation/AWS-Deployment-Guide.md
I have added links and short setup guide on how to launch CVAT on AWS p3 instances for TF annotation app feature.
=> #35 CVAT - AWS-Deployment guide

cvat/apps/tf_annotation/docker_setup_tf_annotation.sh
Currently CUDA installation process is aborted with message:
```bash
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```
I think it problems with keys, but original CUDA docker files haven't been changed, i.e. they have the same problem.
=> Cuda installation has been fixed

cvat/apps/engine/static/engine/js/base.js, cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapeFilter.js, cvat/apps/engine/static/engine/js/shapes.js, cvat/apps/engine/templates/engine/annotation.html
=> Ability to change an opacity for selected shapes

cvat/apps/documentation/user_guide.md
Fix #67 (clarify how to create multiple labels)
=> Improve description how to specify labels with attributes.

cvat/apps/documentation/user_guide.md, cvat/apps/documentation/xml_format.md, cvat/apps/engine/annotation.py
- Increment version of XML format
- Update documentation
- Fix URL to documentation
=> Describe XML format v1.1

cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapes.js
* Bug has been fixed: invisible points actually are visible
* Bug has been fixed: impossible to lock/occlude object in AAM
=> Fixes from release 0.2

cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapes.js
I found some errors in my previous patch.  
Incremental collection update works bad in cases which we change outside/keyframe property.
=> Incremental collection update now works with outside/keyframe (Critical)

cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapes.js, cvat/apps/engine/static/engine/stylesheet.css
=> Switch hide/lock property for all object with specified label

cvat/apps/tf_annotation/views.py, cvat/settings/base.py, cvat/urls.py, supervisord.conf
- collectstatic always
- conditionally urls for cvat.apps.log_viewer
- more logs from django in production
=> Fix several problems with analytics

cvat/apps/engine/static/engine/js/annotationUI.js, cvat/apps/engine/static/engine/js/shapeCollection.js
In case of any changes during save request the state of exported shapes can be inconsistent. That leads to errors for future saves.
=> Fixed bug for save functionality:

cvat/apps/engine/models.py, cvat/apps/engine/task.py, cvat/apps/tf_annotation/static/tf_annotation/js/tf_annotation.js, cvat/apps/tf_annotation/urls.py, cvat/apps/tf_annotation/views.py, cvat/urls.py
Now we use rq queue instead of CVAT statuses in order to setup tf annotation view.
=> Tensorflow annotation update (rq queues instead of CVAT statuses)

cvat/apps/dashboard/static/dashboard/js/dashboard.js, cvat/apps/engine/annotation.py, cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/tf_annotation/views.py
Also fixed tf_annotation and  annotation uploading via dashboard.
=> Added more checks into validation client data function.

cvat/apps/engine/static/engine/js/3rdparty.patch, cvat/apps/engine/static/engine/js/shapes.js
* Text is deleted always after resize
* Mode is reset always after resize/drag
Resolved #176
=> Some fixes for resize. It becomes to work more stability.

cvat/apps/engine/annotation.py, cvat/apps/engine/static/engine/js/annotationUI.js, cvat/apps/engine/static/engine/js/attributeAnnotationMode.js, cvat/apps/engine/static/engine/js/coordinateTranslator.js, cvat/apps/engine/static/engine/js/player.js, cvat/apps/engine/static/engine/js/shapeBuffer.js, cvat/apps/engine/static/engine/js/shapeCollection.js, cvat/apps/engine/static/engine/js/shapeCreator.js, cvat/apps/engine/static/engine/js/shapeGrouper.js, cvat/apps/engine/static/engine/js/shapes.js, cvat/apps/engine/static/engine/stylesheet.css, cvat/apps/engine/templates/engine/annotation.html, tests/eslintrc.conf.js
Resolved #178 
Resolved #179
* Fixed: Sometimes attributes can be truncated. Dragging, resizing and drawing processes was improved 
* Fixed: both context menu are opened simultaneously 
* Fixed: bug with propagate when frames have different size
* Improvement: auto fit after AAM
=> Couple fixes

.gitignore, cvat/apps/dashboard/static/dashboard/js/dashboard.js, cvat/apps/engine/annotation.py, cvat/apps/engine/urls.py, cvat/apps/engine/views.py, cvat/apps/profiler.py, cvat/requirements/base.txt, cvat/requirements/development.txt, cvat/settings/__init__.py, cvat/settings/base.py, cvat/settings/development.py, cvat/settings/production.py, cvat/settings/staging.py, cvat/urls.py
Fix #123.
- I don't like the solution. It isn't good split annotations on several parts and submit one by one. Need to find a better solution.
- Add good profiler: Silk
- Optimize a little bit save_job
=> Fix upload big xml files for tasks

utils/coco/converter.py
@nmanovic Please take a look. Here is a fix for the bug described in [issue#239](https://github.com/opencv/cvat/issues/239) where calculated incorrect coordinates of bounding boxes for objects with more than one independent parts. Also were fixed areas of objects obtained via cocoapi function for these objects and added visualization for bounding boxes.
=> Fix for bounding boxes coordinates and areas in COCO converter

utils/coco/converter.py
@nmanovic Please take a look. It is a fix for the bug described in [isue#238](https://github.com/opencv/cvat/issues/238). Now polygons are sorted only if all of them (on the current image) have field `z_order`. Warning is displayed in case when at least one of images has incorrect number of `z_order` fields and it is not equal to number of polygons on the image.
=> Fix for annotations without z_order field in COCO converter

cvat/apps/engine/static/engine/js/shapeFilter.js, cvat/apps/engine/templates/engine/annotation.html
=> Memorizeable filter values

utils/coco/converter.py
@nmanovic This is a fix for [Issue#298](https://github.com/opencv/cvat/issues/298) with a corrected image id type. Please take a look.
=> Fix image id type to int in coco converter

README.md
This updates the README to include a section about a live demo environment.
=> Added Onepanel Demo link and supporting text.

cvat/apps/engine/templates/engine/annotation.html
UI Label fix: "Grid" (system of reference lines), instead of "Greed" (avarice).
=> Typo: Greed -> Grid.

cvat/apps/engine/task.py
Adding support for 16bit grayscale images for annotation
=>  Adding support for 16bit grayscale images for annotation

utils/coco/converter.py
@nmanovic Please take a look. There is a bug for small segments - if one object is segmented into several parts, it is possible that one or more its parts transformed to a line with area equal to `0`. For these segments `cocoapi` method returns the next bounding box `[0, 0, 0, 0]`. This is a bit unexpected behavior. Here is a fix where all segments with very small area are removed from result annotation.
=> Filter too small segments in coco converter

utils/coco/converter.md, utils/coco/converter.py
@nmanovic Please take a look. Here is reimplemented part of `coco converter` for getting labels. Was added option to define labels from a file which is set up as command line argument and this way is more appropriate than parsing original annotation for labels. It is useful when we have some different annotations and want use them for the same task and finally there will be (probably) list with different matching of label's name and its id. The script now firstly uses file with labels and if it is not defined tries to parse original annotation and sort all found labels to make the same order for all annotations with the same labels.
Additional:
* `--output` argument became non-obligatory and if this parameter is not defined, name of the output file is created from the input file with …
=> Reimplement logic of getting labels in coco converter

cvat/requirements/testing.txt
1. edit docker-compose.yml
1. `DJANGO_CONFIGURATION: "production"` to `"testing"`
2. docker-compose build
3. Got a failed message.
The problem is typo of python install command in requirements/testing.txt, I think.
=> Fix failed python install of testing environment

CHANGELOG.md, utils/README.md, utils/yolo/converter.md, utils/yolo/converter.py, utils/yolo/requirements.txt
Since we use Darknet / Yolo and decided to change our annotation tool from SCALABEL to CVAT, it was necessary to write export scripts for YOLO format
=> YOLO adapted version of PASCAL VOC converter.py

cvat/apps/auto_annotation/model_manager.py
This causes an error when using the `add_polygon` method
=> Static methods don't have a `self` variable

cvat/apps/auto_annotation/model_manager.py
Resolves error: `ErrorDetail(string='Expected a list of items but got type "str".', code='not_a_list')` when running auto annotations.
=> LabeledDataSerializer requires list, not string

Dockerfile
I found a really strange bug with dextr. It's installed to the directory ```/home/django/models/dextr```. At the same time this directory is mounted from the volume ```cvatpublic_cvat_models``` and dextr model isn't found. 
P.s. all our other predefined models (tf, reid) now store just in ~.
=> Fixed dextr installation

cvat/apps/auto_annotation/model_loader.py
Some of the openvino models require a significant amount of post processing. Specifically the [text detection model](https://github.com/opencv/open_model_zoo/blob/master/intel_models/text-detection-0002/description/text-detection-0002.md) outputs a [1x2x192x320] matrix and a [1x16x192x320] matrix that need to be combined together to create the bounding boxes.
Previously, there wasn't capability to get multiple outputs.
=> Allow multiple outputs for model

cvat/requirements/base.txt
CVE-2019-12308 More information
moderate severity
Vulnerable versions: >= 2.1.0, < 2.1.9
Patched version: 2.1.9
An issue was discovered in Django 1.11 before 1.11.21, 2.1 before 2.1.9, and 2.2 before 2.2.2. The clickable Current URL value displayed by the AdminURLFieldWidget displays the provided value without validating it as a safe URL. Thus, an unvalidated value stored in the database, or a value provided as a URL query parameter payload, could result in an clickable JavaScript link.
WS-2019-0037 More information
moderate severity
Vulnerable versions: < 3.9.1
Patched version: 3.9.1
Django-Rest-Framework, before 3.9.1, has a XSS vulnerability caused by disabled autoescaping in the default DRF Browsable API view templates.
=> Fix security issues

cvat/apps/engine/media_extractors.py
In docker container we use python 3.5 and f'{}' isn't available.
=> Fixed PDF extractor syntax error.

cvat/apps/auto_annotation/model_loader.py
This pull request is for conversation only, it's not meant to be merged in its current state.
In OpenVino 2019R1 the tensorflow API changed to have two inputs instead of a single input.
MO 2018R5 generates model IRs with these inputs:
```
network.inputs = ['image_tensor']
```
MO 2019R1 IRs:
```
network.inputs = ['image_tensor', 'image_info']
```
This breaks the auto annotation apps way of handling inputs.
The attached code is a brute force way of handling the change. Likely we'd want to all the user to drop in some custom code, similar to how the interpret code is currently handled that allows them to make the appropriate changes to the model.
=> OpenVino2019 handeling

cvatjs/src/annotations-collection.js, cvatjs/src/annotations-objects.js, cvatjs/src/annotations-saver.js, cvatjs/src/annotations.js, cvatjs/src/api-implementation.js, cvatjs/src/api.js, cvatjs/src/common.js, cvatjs/src/object-state.js, cvatjs/src/server-proxy.js, cvatjs/src/session.js, cvatjs/tests/mocks/server-proxy.mock.js
* ZOrder up/down
* Method annotations.hasUnsavedChanges()
* Method annotations.merge() 
* Methods annotations.split() and annotations.group() (definitions only)
* Some critical bug fixes
=> CVAT.js implemented API methods and bug fixes

cvatjs/src/annotations-collection.js, cvatjs/src/annotations-objects.js, cvatjs/src/annotations-saver.js, cvatjs/src/annotations.js, cvatjs/src/common.js, cvatjs/src/session.js, cvatjs/src/statistics.js
API implementations:
* annotations.split()
* annotations.group()
* annotations.clear()
* annotations.statistics()
* annotations.select()
Also fixes, typos, documentation changes.
=> CVAT.js other implemented API methods and bug fixes

CHANGELOG.md, cvat/apps/auto_annotation/admin.py, cvat/apps/auto_annotation/model_loader.py, cvat/apps/auto_annotation/model_manager.py, cvat/apps/auto_annotation/views.py
=> Handle invalid json labelmap file case correctly during create/update DL model stage.

Dockerfile
```
Collecting ruamel.yaml>=0.15.34 (from drf-yasg==1.15.0->-r /tmp/requirements/base.txt (line 34))
Downloading https://files.pythonhosted.org/packages/fd/f4/0a9044336f9ae455749a9e1ce6a7c8d6a47551f7eeddb8e9ea574d25b75c/ruamel.yaml-0.16.1.tar.gz (144kB)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-9rjnol9x/ruamel.yaml/setup.py", line 23, in <module>
from setuptools.namespaces import Installer as NameSpaceInstaller # NOQA
ImportError: No module named 'setuptools.namespaces'
```
Some of dependencies require newer version of python setuptools than Ubuntu16.04 repo contains.
ruamel.yaml>=0.16.1 installation guide(https://yaml.readthedocs.io/en/latest/install.html) requires setuptools>=20.6.8 …
=> fixed build

cvat/settings/base.py
Partial solution of #664
Common django issue.
=> Fixed: no such table: allauth_socialaccount

cvat/apps/engine/media_extractors.py, cvat/apps/engine/task.py
=> Selecting non images leads to 400 error

cvat/apps/engine/task.py
=> Fix the problem with duplicated frames in case of "share"

CHANGELOG.md, utils/cli/cli.py, utils/cli/core/__init__.py, utils/cli/core/core.py, utils/cli/core/definition.py, utils/cli/definition.py, utils/cli/requirements.txt, utils/cli/tests/test_cli.py
**Description**
This PR adds a simple command line interface for working with CVAT tasks. At the moment it implements a basic feature set but may serve as the starting point for a more comprehensive CVAT administration tool in the future.
Overview of functionality:
- Create new task (supports name, bug tracker, labels JSON, local/share/remote files)
- Delete tasks (supports deleting a list of task IDs)
- List all tasks (supports basic CSV or JSON output)
- Download JPEG frames (supports a list of frame IDs)
- Dump annotations (supports all formats via format string)
**Usage**
```
usage: cli.py [-h] [--auth USER:[PASS]] [--server-host SERVER_HOST]
[--server-port SERVER_PORT] [--debug]
{create,delete,ls,frames,dump} ...
Perform common operations related to CVAT tasks.
positional arguments: …
```
=> New command line tool for working with tasks

cvat/apps/engine/tests/test_rest_api.py, cvat/apps/engine/views.py
Fix #712 
Note: If a task doesn't have an assignee an observer can still change annotations.
=> Fix an issue with permissions (observer can change annotations)

cvat/apps/annotation/coco.py
Currently the annotation ID begins with 0 which is interpreted by cocoapi as a false detection. The array dtm saves the matches via the ground truth annotation ID. The variable dtm is initialized as an array of zeros. https://github.com/cocodataset/cocoapi/blob/636becdc73d54283b3aac6d4ec363cffbb6f9b20/PythonAPI/pycocotools/cocoeval.py#L269
https://github.com/cocodataset/cocoapi/blob/636becdc73d54283b3aac6d4ec363cffbb6f9b20/PythonAPI/pycocotools/cocoeval.py#L295
https://github.com/cocodataset/cocoapi/blob/636becdc73d54283b3aac6d4ec363cffbb6f9b20/PythonAPI/pycocotools/cocoeval.py#L375
=> COCO Annotation IDs should begin with 1

.travis.yml, .vscode/launch.json, Dockerfile, README.md, utils/cli/README.md, utils/cli/cli.py, utils/cli/core/core.py, utils/cli/tests/test_cli.py
Added README.md, run tests using travis, run CLI tests from VS code.
=> Slightly enhance command line interface feature

utils/cli/core/core.py
Python f-strings were replaced with `format()` in PR #746 and one case was missed, breaking the CLI  list feature.
=> Updating string format for case missed in PR #746.

CHANGELOG.md, cvat/apps/engine/serializers.py, cvat/apps/engine/tests/test_rest_api.py, cvat/apps/engine/views.py
Fix https://github.com/opencv/cvat/issues/750
=> Basic user information

cvat/apps/annotation/coco.py
When the bounding boxes had intersections and were exported with the COCO JSON format they were often cut off. I commented out the line with the function fix_segments_intersections and replaced it with lines of that function. This helped with the bounding boxes and keeps the masks as they are created with CVAT. It is probably inconvenient for the user to get something fixed in the export without an active agreement. Secondly letting a function automatically fix segments could result in a bad fix.
=> Disable fix_segments_intersections for now

cvat/apps/auto_annotation/model_loader.py
The security models from the open model zoo use the keyword 'im_info' instead of 'image_info'
=> allow security segmentation models to be used in auto annotation

CHANGELOG.md, README.md, cvat/__init__.py
=> Integration with Zenodo

docker-compose.yml
Without the `restart` flag for the `cvat_ui` container, the app does not successfully load on the HOST machine rebooting
=> Added restart tag to docker-compose for `cvat_ui`

components/openvino/README.md, cvat/apps/auto_annotation/README.md, cvat/apps/documentation/installation.md
Currently the documentation points to the application documentation rather than the component documentation. The app docs have usage instructions but not installation instructions.
=> Update documentation to point to OpenVino component documentation

utils/open_model_zoo/mask_rcnn_inception_resnet_v2_atrous_coco/interp.py
The image that I was developing with masked the off by one error. Other images do not.
=> fix off by one error in mask rcnn

utils/open_model_zoo/yolov3/interp.py
Got bit again by developing on an image that had the same height/width.
=> Fix Yolo: swap width, height; Change box coord order; parsing fix

.travis.yml, .vscode/launch.json, CHANGELOG.md, cvat/apps/git/git.py, cvat/apps/git/tests.py
=> Add support for ip git repo urls

CHANGELOG.md, README.md, cvat/apps/annotation/labelme.py, cvat/apps/annotation/settings.py
=> Add LabelMe format support

datumaro/datumaro/components/config_model.py, datumaro/datumaro/components/converters/ms_coco.py, datumaro/datumaro/components/extractor.py, datumaro/datumaro/components/extractors/ms_coco.py, datumaro/datumaro/components/importers/ms_coco.py, datumaro/tests/test_coco_format.py
Added:
- Auto inference and matching for instance annotation parts - masks, bboxes, polygons
Now, these elements are taken from the annotation group, and are inferred otherwise
- Project `source` options became a `dict`
- implemented `area()` method for polygons
- object polygon(-s) to mask conversion in `COCO` extractor option
=> [Datumaro] Coco format updates

datumaro/datumaro/components/converters/ms_coco.py, datumaro/datumaro/components/extractors/ms_coco.py, datumaro/tests/test_coco_format.py
Fixes the problem with COCO dataset export, where images could not be added to the resulting archive.
Adds multiple search paths for COCO-like dataset images:
- `images/[subset_name]/[image_name.jpg]`
- `images/[image_name.jpg]`
=> [Datumaro] Fix coco images export

datumaro/datumaro/util/image.py, datumaro/datumaro/util/image_cache.py, datumaro/tests/test_images.py
Temporarily fixes server OOM/swap DOS for large dataset export.
=> [Datumaro] Disable lazy image caching by default

CHANGELOG.md, cvat/apps/engine/pagination.py, cvat/settings/base.py
You can specify page_size=<number> or page_size=all to return all elements. It allows to avoid default limitation to get only 10 objects per a list.
Fix #868, #853
=> page_size parameter for all REST API methods

cvat-core/src/server-proxy.js, cvat-ui/src/actions/tasks-actions.ts, cvat-ui/src/components/cvat-app.tsx, cvat/apps/engine/views.py
- Fixed several simultaneous dumps for the same task 
- Fixed several simultaneous dumps for different tasks
=> Fixed some issues with dump

cvat/apps/dataset_manager/task.py, datumaro/datumaro/components/converters/__init__.py, datumaro/datumaro/components/converters/yolo.py, datumaro/datumaro/components/extractors/__init__.py, datumaro/datumaro/components/extractors/ms_coco.py, datumaro/datumaro/components/extractors/voc.py, datumaro/datumaro/components/extractors/yolo.py, datumaro/datumaro/components/formats/yolo.py, datumaro/datumaro/components/importers/yolo.py, datumaro/tests/test_image.py, datumaro/tests/test_yolo_format.py
Closes #891
Added:
- YOLO support in Datumaro
=> [Datumaro] Add YOLO converter

cvat/apps/dataset_manager/bindings.py, cvat/apps/dataset_manager/export_templates/extractors/cvat_rest_api_task_images.py, cvat/apps/dataset_manager/task.py, cvat/apps/engine/models.py, cvat/apps/engine/tests/test_model.py, datumaro/datumaro/cli/project/__init__.py, datumaro/datumaro/components/converters/__init__.py, datumaro/datumaro/components/converters/tfrecord.py, datumaro/datumaro/components/extractors/__init__.py, datumaro/datumaro/components/extractors/tfrecord.py, datumaro/datumaro/components/formats/tfrecord.py, datumaro/datumaro/components/importers/__init__.py, datumaro/datumaro/components/importers/tfrecord.py, datumaro/datumaro/components/project.py, datumaro/datumaro/util/image.py, datumaro/datumaro/util/image_cache.py, datumaro/datumaro/util/tf_util.py, datumaro/requirements.txt, datumaro/setup.py, datumaro/tests/test_image.py, datumaro/tests/test_tfrecord_format.py
Related #869 
Closes #866 
Added support for TFrecord format from TF detection API.
=> [Datumaro] Added tf detection api tfrecord import and export

cvat/apps/engine/static/engine/js/shapeCreator.js
This PR contains improvement for creating shape with shortkey.
Current behavior:
You click **N** key for new shape creation, but you got two red helper lines only if **mousemove** will trigger, which is is a little confusing.
As workaround:
I'm listening **mousemove** event and draw this lines when creation of new shape is triggered by shortkey
=> Improve UX with creating new shape by shortkey

datumaro/datumaro/cli/project/__init__.py, datumaro/datumaro/components/converter.py, datumaro/datumaro/components/converters/datumaro.py, datumaro/datumaro/components/converters/ms_coco.py, datumaro/datumaro/components/converters/voc.py, datumaro/datumaro/components/converters/yolo.py, datumaro/datumaro/components/extractors/datumaro.py, datumaro/datumaro/components/extractors/ms_coco.py, datumaro/datumaro/components/formats/ms_coco.py, datumaro/datumaro/components/importers/ms_coco.py, datumaro/datumaro/components/project.py, datumaro/datumaro/util/image.py, datumaro/tests/test_coco_format.py, datumaro/tests/test_datumaro_format.py, datumaro/tests/test_image.py
Closes #836 
Added:
- COCO export option to merge several instance polygons to one RLE
- Drop colormap application to masks for Datumaro own format
- Added support for CLI conevrter-specific options
Testing:
```
datum project export -d coco-export -f coco -- --save-images --merge-polygons
```
=> [Datumaro] COCO 'merge instance polygons' option

CHANGELOG.md, cvat/requirements/base.txt
scikit-image > 0.15 don't support python 3.5
Resolved #962
We also need to create a new release
=> Hotfix: fixed skikit-image version 

CHANGELOG.md, utils/auto_annotation/README.md, utils/auto_annotation/run_model.py
This should answer https://github.com/opencv/cvat/issues/914
=> added in label visualization to auto annotation runner

datumaro/datumaro/cli/project/__init__.py, datumaro/datumaro/cli/source/__init__.py, datumaro/datumaro/components/converters/voc.py, datumaro/datumaro/components/extractor.py, datumaro/datumaro/components/extractors/voc.py, datumaro/datumaro/components/formats/voc.py, datumaro/datumaro/util/mask_tools.py, datumaro/tests/test_voc_format.py
Closes #942 
Added:
- `labelmap.txt` file support in the dataset root dir
- `--overwrite` cli option for `source export` and `project export`
- label-specific attributes
- checks that imported source or project can be read
Labelmap file example:
```
background:0,0,0::
aeroplane:0,0,128::
bicycle:0,128,0::
bird:0,128,128::
boat:128,0,0::
bottle:128,0,128::
bus:128,128,0::
car:128,128,128::
cat:0,0,64::
chair:0,0,192::
cow:0,128,64::
diningtable:0,128,192::
dog:128,0,64::
horse:128,0,192::
motorbike:128,128,64::
person:128,128,192:head,hand,foot:other,jumping,phoning,playinginstrument,reading,ridingbike,ridinghorse,running,takingphoto,usingcomputer,walking
pottedplant:0,64,0::
sheep:0,64,128::
sofa:0,192,0::
```
Test:
```
datum project export -d test -f voc --overwrite -- …
```
=> [Datumaro] VOC labelmap support

datumaro/datumaro/cli/project/__init__.py, datumaro/datumaro/cli/source/__init__.py, datumaro/datumaro/components/converters/__init__.py, datumaro/datumaro/components/converters/datumaro.py, datumaro/datumaro/components/extractor.py, datumaro/datumaro/components/extractors/__init__.py, datumaro/datumaro/components/extractors/cvat.py, datumaro/datumaro/components/extractors/datumaro.py, datumaro/datumaro/components/extractors/ms_coco.py, datumaro/datumaro/components/formats/cvat.py, datumaro/datumaro/components/importers/__init__.py, datumaro/datumaro/components/importers/cvat.py, datumaro/datumaro/components/importers/datumaro.py, datumaro/datumaro/components/importers/ms_coco.py, datumaro/datumaro/components/importers/tfrecord.py, datumaro/datumaro/components/importers/voc.py, datumaro/datumaro/components/importers/yolo.py, datumaro/datumaro/components/project.py, datumaro/tests/test_coco_format.py, datumaro/tests/test_cvat_format.py, datumaro/tests/test_datumaro_format.py, datumaro/tests/test_project.py, datumaro/tests/test_tfrecord_format.py, datumaro/tests/test_voc_format.py, datumaro/tests/test_yolo_format.py
Added:
- CVAT extractor
- Additional logs in CLI
- Missing `yolo` importer to CLI
Fixes:
- Regularized importer and extractor logic
- Refactored format tests
- Refactored importers, `Datumaro` and `COCO` extractor
- Fixed the `project import` issue with `--overwrite` option, in which if the target dir had project data it would be imported into the new project. Resolved by cleaning of the existing dir.
Related: #937
=> [Datumaro] CVAT format import

cvat-ui/src/base.scss, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/annotation-page/styles.scss, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/model-runner-modal/model-runner-modal.tsx, cvat-ui/src/components/models-page/models-page.tsx, cvat-ui/src/components/task-page/task-page.tsx, cvat-ui/src/components/tasks-page/tasks-page.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx, cvat-ui/src/containers/task-page/task-page.tsx, cvat-ui/src/styles.scss
* A little bit improved annotation view
* Added two pages (task not found, job not found) in case of bad URL parameters or access reject
* base.scss now contains only vars (a lot of extra classes were defined before)
* A bug fixed with browser 100% CPU load when go to a task or a job using a text value instead of a number value in URL
=> UI Enhancements 

cvat/apps/engine/views.py, datumaro/datumaro/components/converters/tfrecord.py, datumaro/tests/test_tfrecord_format.py
Closes #970 
Added:
- Missing parameter in tfrecord converter constructor
Other:
- Renamed dataset export RQ task to be supported in logs
=> [Datumaro] Fix TFrecord converter constructor

cvat/apps/engine/static/engine/js/shapeMerger.js
Resolved #854
Explanations:
1. When we merge tracks, actually we shouldn't update zOrder for them shapes and set it as a maximum value within the shape frame. We can expect it has been already set automatically or by a user and it's right. 
2. When we merge shapes, we should not setup maximum or minimum values for closing outside shapes. Because they are invisible, so, let's just set 0.
=> Resolved performance bottleneck in merge function

cvat/apps/engine/static/engine/js/shapeCreator.js, cvat/apps/engine/templates/engine/annotation.html
Resolved #992 
Actually I suppose it's more Chrome issue.
=> Fixed issue: Unknown shape type found

cvat-core/src/annotations-saver.js, cvat/apps/engine/static/engine/js/annotationSaver.js
=> Couple of fixes in "save annotations"

utils/auto_annotation/README.md, utils/auto_annotation/run_model.py
This needs to be tested extensively and I'm not a spot to do it currently.
This should resolve https://github.com/opencv/cvat/issues/913
@nmanovic, do you want me to merge these two pull requests? I didn't think about it until now.
=> Add in ability to run Auto Annotation model using model name and task id

cvat-ui/src/components/file-manager/file-manager.tsx, cvat-ui/src/containers/file-manager/file-manager.tsx, cvat-ui/src/reducers/share-reducer.ts
=> Added root folder for share functionality

cvat/apps/engine/static/engine/js/polyshapeEditor.js, cvat/apps/engine/static/engine/js/shapeCreator.js, cvat/apps/engine/templates/engine/annotation.html
=> Improved feature: common borders

cvat/apps/documentation/AWS-Deployment-Guide.md
docker-compose.override.yml content specified to avoid problems with AWS deployment
=> AWS deployment guide updated #1009

cvat/apps/documentation/installation.md
=> Add info about auto segmentation to advanced topics of the installation guide

datumaro/datumaro/components/converters/__init__.py, datumaro/datumaro/components/converters/cvat.py, datumaro/tests/test_cvat_format.py
Added:
- CVAT xml for images format export
Closes #937
=> [Datumaro] Add cvat format export

datumaro/datumaro/cli/project/__init__.py, datumaro/datumaro/cli/source/__init__.py, datumaro/datumaro/components/config_model.py, datumaro/datumaro/components/converters/voc.py, datumaro/datumaro/components/dataset_filter.py, datumaro/datumaro/components/extractor.py, datumaro/datumaro/components/launcher.py, datumaro/datumaro/components/project.py, datumaro/tests/test_project.py
Added:
- Dataset annotations filter in CLI: `datumaro project extract -a`
To test:
```
-e FILTER, --filter FILTER 
XML XPath filter expression for dataset items.
Examples: 
- extract images with width < height:
'/item[image/width < image/height]'; 
- extract images with large-area bboxes: 
'/item[annotation/type="bbox" and annotation/area>2000]'
- filter out irrelevant annotations from items: 
'/item/annotation[label = "person"]'
-a, --filter-annotations 
Filter annotations instead of dataset items (default: False)
--remove-empty          
Remove an item if there are no annotations left after filtration
--dry-run         Print XML representations to be filtered and exit
datum project extract -a -e '/item/annotation[label = "person"]' --remove-empty -d temp
```
In general, to filter …
=> [Datumaro] Dataset annotations filter

cvat-ui/src/components/model-runner-modal/model-runner-modal.tsx, cvat-ui/src/containers/file-manager/file-manager.tsx
- Also fixed small bug with a share browsing
Resolved #1049
=> Added ability to match many model labels to one task labels

cvat/apps/documentation/xml_format.md
Just [fixing](https://i.redd.it/16bicltv08821.png) a few typos.
=> Fix typos in xml_format.md

.travis.yml, CONTRIBUTING.md, Dockerfile, Dockerfile.ci, components/auto_segmentation/install.sh, components/cuda/install.sh, components/tf_annotation/install.sh, cvat/apps/documentation/installation.md, cvat/requirements/base.txt, cvat/requirements/testing.txt, datumaro/datumaro/util/image.py, datumaro/requirements.txt, docker-compose.ci.yml, docker-compose.yml, utils/tfrecords/requirements.txt
Fixed https://github.com/opencv/cvat/issues/982
Fixed https://github.com/opencv/cvat/issues/1017
=> Cleanup Dockerfiles for CVAT

Dockerfile
I faced the same ImportError as raised in the https://gitter.im/opencv-cvat/public by @praffulkmr, while installing TF Object Detection API: Auto Annotation.
No such error is found and able to build the docker image successfully, if the pip upgrade is set to version 20.0.1 in the Dockerfile.
=> Resolved import error caused by pip 20.0

datumaro/datumaro/components/converters/voc.py, datumaro/datumaro/util/mask_tools.py, datumaro/tests/test_masks.py
Added:
- `paint_mask`, `unpaint_mask` and `remap_mask` significantly speeded up
- added mask operations tests
=> [Datumaro] Optimize mask conversions

cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/editHandler.ts, cvat-canvas/src/typescript/shared.ts, cvat-core/src/frames.js
@azhavoro 
Take a look this patch
``cvat-canvas`` here has migrated from SVGCanvas to HTMLCanvas
It should help with testing streaming patch in a new UI
=> SVG Canvas -> HTML Canvas frame

Dockerfile, datumaro/datumaro/plugins/openvino_launcher.py, datumaro/datumaro/plugins/tf_detection_api_format/converter.py, datumaro/datumaro/plugins/tf_detection_api_format/extractor.py, datumaro/requirements.txt, datumaro/setup.py, datumaro/tests/test_RISE.py, datumaro/tests/test_command_targets.py, datumaro/tests/test_voc_format.py
Fixes #1124
- TF is made optional for Datumaro, so it is not installed automatically
=> Fix tensorflow installation

datumaro/CONTRIBUTING.md
Added documentation for plugins.
=> [Datumaro] Add plugin system documentation

datumaro/datumaro/cli/contexts/project/__init__.py, datumaro/datumaro/components/project.py, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/datumaro/plugins/cvat_format/extractor.py, datumaro/datumaro/plugins/voc_format/converter.py, datumaro/datumaro/plugins/voc_format/format.py
Fixes:
- Failing `import` command
- Project names for spawned projects 
- VOC labelmap color order
- VOC and COCO converter parameters
- Extended CVAT format image search paths
=> [Datumaro] fixes

cvat-canvas/README.md, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/drawHandler.ts, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts
Hi, 
This is the reimplementation of [extreme clicking](https://arxiv.org/pdf/1708.02750.pdf) (#1111) in new UI with React and Ant Design. `Drawing Method` option is added in rectangle drawing popover. The conventional bbox drawing method (`By 2 Points`) is selected by default. Extreme clicking method is available with `By 4 Points`. Drawing finishes right after the fourth click, as it does in #1111. Here are sample images for this feature.
=> Add extreme clicking method in cvat-canvas and cvat-ui

cvat-canvas/src/typescript/canvasView.ts, cvat-core/package.json, cvat-core/src/annotations-collection.js, cvat-core/src/annotations-filter.js, cvat-core/src/annotations.js, cvat-core/src/api-implementation.js, cvat-core/src/enums.js, cvat-core/src/session.js, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss, cvat-ui/src/components/annotation-page/styles.scss, cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts
- Implemented filtering with using json path
- Implemented search which is faster than the previous one
- Frame URL
- Object URL
=> React UI: Objects filtering & search

cvat-core/src/server-proxy.js
=> Fixed dump for cases when special URL characters in task name

datumaro/datumaro/util/tf_util.py
Fixes:
- TF `eager execution` warning is now avoided
=> [Datumaro] Avoid tf deprecation warning

datumaro/datumaro/cli/contexts/project/__init__.py, datumaro/datumaro/cli/util/__init__.py
Added:
- CLI commands now generate output folder names using operation parameters such as output format name and transform name
Fixed:
- Failing `project info` command
=> [Datumaro] Pretty output folder names

README.md, cvat/apps/annotation/README.md, cvat/apps/annotation/mask.py, cvat/apps/dataset_manager/bindings.py, cvat/apps/engine/tests/test_rest_api.py, datumaro/datumaro/components/project.py, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/datumaro/plugins/transforms.py, datumaro/datumaro/plugins/voc_format/converter.py, datumaro/datumaro/util/annotation_tools.py, datumaro/datumaro/util/test_utils.py, datumaro/tests/test_project.py, datumaro/tests/test_transforms.py, datumaro/tests/test_voc_format.py
Added:
- Mask annotations export and **import** in CVAT, masks are imported as polygons
- `boxes_to_masks` transform
- updated documentation
- tests for `Dataset`
Fixed:
- Missing test for VOC `source` label map mode in converter
- `source` label map mode inserts `background` class as first by default
- Tests for extractors now check item subset as well
Mask format differs from the actual. 
Before:
```
instances.zip/
├── labelmap.txt
└── SegmentationObject/
└── image1.png
classes.zip/
├── labelmap.txt
├── SegmentationClass/
   └── image1.png
```
Now an archive includes both instance masks and class masks and looks like this:
```
archive.zip/
├── ImageSets/
│   └── Segmentation/
│       └── <subset_name>.txt
├── labelmap.txt
├── SegmentationClass/
│   └── image1.png
└── SegmentationObject/ …
```
=> Replace mask format support with Datumaro

cvat/apps/annotation/README.md, cvat/apps/annotation/pascal_voc.py, cvat/apps/annotation/yolo.py, cvat/apps/engine/tests/test_rest_api.py, datumaro/datumaro/plugins/voc_format/converter.py, datumaro/datumaro/plugins/voc_format/extractor.py, datumaro/tests/test_voc_format.py
VOC format support replaced with Datumaro implementation. Imported archive has the previous structure or the following. Exported archive structure is the following:
```
archive.zip/
├── Annotations/
│   └── image_name1.xml
├── ImageSets/
│   └── Main/
│       └── <subset_name>.txt
└── labelmap.txt
```
Depends on #1140
=> Replace VOC format support in CVAT with Datumaro

cvat/apps/engine/static/engine/js/3rdparty.patch
The key idea is to use ``splice`` instead of ``delete`` operator for the array.
If we use operator ``delete``, the method ``indexOf`` works much slower gradually. 
Related: #1141, #1182
=> Fixed lags when working with shapes

cvat-core/src/annotations-collection.js, cvat-core/src/annotations-objects.js, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Change color function now depends on ``colorBy`` flag and changes the color for an instance, a group, or a label
=> React UI: Changing color for a group

datumaro/datumaro/cli/contexts/project/__init__.py, datumaro/datumaro/cli/util/project.py, datumaro/datumaro/components/project.py
- Project layout is now `any_dir/.datumaro/config.yaml`, i.e. corresponds to the documented one
- In the case of errors during commands, generated directories are removed
=> [Datumaro] Move project directory

cvat/apps/engine/static/engine/js/3rdparty.patch, cvat/apps/engine/static/engine/js/3rdparty/svg.js
SVG.js was updated from 2.6.5 to 2.7.1
It resolves some critical memory issues and the bug introduced with #1197
New UI is already uses 2.7.1
=> Updated svg.js

cvat-canvas/README.md, cvat-canvas/src/typescript/canvas.ts, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/consts.ts, cvat-canvas/src/typescript/drawHandler.ts, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx, cvat-ui/src/cvat-canvas.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/settings-reducer.ts
Fix: issues with drawing (corner cases)
Fix: grid opacity doesn't work
Fix: putting shape out of canvas works wrong
Fix: reset zoom for images by default
Fix: selecting in grouping mode
Fix: selecting in panzoom mode
Fix: text for locked shapes aren't displayed
Fix: outside shapes can be activated
Fix: issues with code in ``cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx``
Fix: Disable tracks for polygons, polyshapes and points (because it isn't supported by server and algorithms can be changed in the future)
=> React UI: Batch of fixes

cvat/apps/annotation/pascal_voc.py, datumaro/datumaro/plugins/voc_format/extractor.py
Auto generate `labelmap.txt` during import of VOC annotations from the task. Produce meaningful error in the case of foreign labels.
=> Auto-generate labelmap during VOC import

datumaro/datumaro/plugins/transforms.py, datumaro/tests/test_transforms.py
Added random split transform.
```bash
datum project transform -p test_project -t random_split -- --subset train:0.6 --subset test:0.4
```
=> [Datumaro] Add random split transform

cvat/apps/annotation/cvat.py, cvat/apps/dataset_manager/bindings.py, cvat/apps/engine/tests/test_rest_api.py, datumaro/datumaro/plugins/cvat_format/converter.py, datumaro/datumaro/plugins/cvat_format/extractor.py, datumaro/tests/test_cvat_format.py
=> Add tags to cvat xml

cvat-canvas/src/typescript/canvasView.ts, cvat-core/src/annotations-objects.js, cvat-core/src/enums.js, cvat-core/src/object-state.js, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
* Enabled by default for all polyshapes
* Pinned shapes cannot be moved (resize, changing attributes, etc. work as usual)
* Undo/redo support
=> React UI: Pinned option was added

datumaro/datumaro/plugins/transforms.py, datumaro/tests/test_project.py, datumaro/tests/test_transforms.py
In the case of numeric errors during split size computations all the remainder is put to the last split.
=> [Datumaro] Fix remainder logic for subset splitting

cvat/apps/annotation/README.md, cvat/apps/annotation/pascal_voc.py, cvat/apps/dataset_manager/bindings.py, cvat/apps/documentation/user_guide.md, cvat/apps/engine/tests/test_rest_api.py, datumaro/datumaro/plugins/voc_format/converter.py
Related: #1062 
Depends on: #1200 
Depends on: #1167 
Added:
- Added import and export of tag annotations in VOC format as labels for classification task
=> Add tags support for VOC

cvat-canvas/src/typescript/canvasView.ts, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts
You can choose any of last ten filters
=> React UI: Filters history

cvat-canvas/src/typescript/drawHandler.ts, cvat-core/src/annotations-collection.js, cvat-core/src/session.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/actions/shortcuts-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/shortcuts-dialog/shortcuts-dialog.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/label-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/index.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts, cvat-ui/src/reducers/root-reducer.ts, cvat-ui/src/reducers/shortcuts-reducer.ts
- Used: https://www.npmjs.com/package/react-hotkeys
- Press F1 to view all available shortcuts on the page
- 44 shortcuts have been added
- Some shortcuts haven't been moved from old UI because I am not sure they are applicable in the new one:
- change_shape_label
- change_shape_color
- change_default_label
- next_shape_type
- prev_shape_type
TODO: In the future PRs: 
- Move all shortcuts to shortcuts state
- Add ability to change shortcuts from the UI
- Add UI elements to perform search (now shortcuts only)
Resolved #948
=> React UI: Added shortcuts

datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/datumaro/plugins/datumaro_format/converter.py, datumaro/datumaro/plugins/datumaro_format/extractor.py, datumaro/datumaro/util/mask_tools.py, datumaro/tests/test_masks.py
- `mask_to_rle` speeded up ~30x
- `as_class_mask`, `as_instance_mask` - ~8x
- datumaro format uses RLE-encoded (compressed) masks - ~3x space savings, 2.5x store speedup vs. png
=> [Datumaro] Optimize mask operations

datumaro/datumaro/cli/contexts/project/__init__.py, datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/coco_format/importer.py, datumaro/datumaro/plugins/cvat_format/importer.py, datumaro/datumaro/plugins/datumaro_format/importer.py, datumaro/datumaro/plugins/tf_detection_api_format/importer.py, datumaro/datumaro/plugins/voc_format/converter.py, datumaro/datumaro/plugins/voc_format/extractor.py, datumaro/datumaro/plugins/voc_format/importer.py, datumaro/datumaro/plugins/yolo_format/importer.py, datumaro/datumaro/util/log_utils.py, datumaro/tests/test_coco_format.py, datumaro/tests/test_cvat_format.py, datumaro/tests/test_datumaro_format.py, datumaro/tests/test_tfrecord_format.py, datumaro/tests/test_voc_format.py, datumaro/tests/test_yolo_format.py
Added:
- Format auto detection for `project import`
- Added detectors for each dataset format
- VOC extractor is split, VOC extractor is responsible only for 1 subset, VOC results are dropped
=> [Datumaro] Dataset format auto detection

CONTRIBUTING.md, Dockerfile, Dockerfile.ci, components/cuda/README.md, components/openvino/install.sh, cvat/apps/documentation/installation.md
By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages . 
By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.
This results in smaller downloads and installation of packages .
Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .
=> Some debian package manager tweaks

cvat/apps/documentation/xml_format.md
I realized the format description was completely wrong after dumping a CVAT XML file.
=> doc: fix description of attribute CVAT XML format

CONTRIBUTING.md, cvat-canvas/package-lock.json, cvat/requirements/development.txt
I experienced some issues with installation for development from scratch
There are some minor fixes
=> Installation issues for development environment

CHANGELOG.md, cvat/apps/annotation/pascal_voc.py
Fixes #1275 
VOC export now does not use official label map by default, but takes one from the source task to avoid primary class and class part clashing.
=> Use source label map for voc export

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py, datumaro/datumaro/plugins/yolo_format/extractor.py
Add extra frame matching way for videos: frames can be named `frame_XXXXXX[.ext]`. This should be revised when #1007 is merged.
Fixed YOLO image id reading for provided image meta list.
=> [Datumaro] Fix frame matching in video annotations import

CHANGELOG.md, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/tests/test_coco_format.py
- Allows annotation-less projects to be exported as valid empty datasets in COCO
Fixes #1277
=> [Datumaro] Allow empty COCO dataset export

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py
- Adds `occluded` and `z_order` attributes passing to Datumaro
=> [Datumaro] Fix occluded and z_order attributes export

CHANGELOG.md, cvat/apps/annotation/labelme.py, cvat/apps/engine/tests/test_rest_api.py, cvat/apps/git/git.py
Fixes #1259 
Added LabelMe format test
Added grouped annotations in tests
=> Fix LabelMe format

CHANGELOG.md, cvat/apps/auto_annotation/inference_engine.py, cvat/apps/auto_annotation/model_loader.py, cvat/apps/dextr_segmentation/dextr.py, cvat/apps/tf_annotation/views.py
I have a lack of ability to test this. Specifically I didn't test to make sure that OpenVINO 2019 still works with this, if the DEXTR model works, or if tf_annotation works.
I did load and test that this works with the auto_annotation model however. Just didn't want to leave the rest of it broken.
=> OpenVino 2020

datumaro/datumaro/plugins/coco_format/importer.py, datumaro/datumaro/plugins/cvat_format/importer.py, datumaro/datumaro/plugins/tf_detection_api_format/importer.py, datumaro/datumaro/plugins/yolo_format/importer.py
Adds recursive search for annotation files in COCO, CVAT, YOLO and TF detection api formats.
=> [Datumaro] Allow recursive search in importers

datumaro/datumaro/plugins/coco_format/converter.py, datumaro/datumaro/plugins/cvat_format/converter.py, datumaro/datumaro/plugins/datumaro_format/converter.py, datumaro/datumaro/plugins/mot_format.py, datumaro/datumaro/util/__init__.py, datumaro/tests/test_mot_format.py
Added support for MOT detection det and gt formats for video sequences.
=> [Datumaro] MOT format

datumaro/datumaro/components/dataset_filter.py
Fixes dataset filtering for items having attributes with spaces in names by replacing spaces with `-`.
=> [Datumaro] Fix attributes with spaces in names

datumaro/datumaro/cli/contexts/project/__init__.py, datumaro/datumaro/components/project.py
Fixes image info merging for sources and project's own dataset, which can be a problem for remote image downloading and other similar situations.
=> [Datumaro] Fix image merging

datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/coco_format/extractor.py, datumaro/datumaro/plugins/cvat_format/extractor.py, datumaro/datumaro/plugins/datumaro_format/extractor.py, datumaro/datumaro/plugins/image_dir.py, datumaro/datumaro/plugins/labelme_format.py, datumaro/datumaro/plugins/mot_format.py, datumaro/datumaro/plugins/tf_detection_api_format/extractor.py, datumaro/datumaro/plugins/voc_format/extractor.py
=> [Datumaro] Extract common extractor functionality

Dockerfile.ui, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/cvat-app.tsx, cvat-ui/webpack.config.js, cvat/apps/documentation/AWS-Deployment-Guide.md, cvat_proxy/nginx.conf, docker-compose.yml
- Fix https://github.com/opencv/cvat/issues/1287
- Fix https://github.com/opencv/cvat/issues/1261 (the same as above)
- Fix https://github.com/opencv/cvat/issues/1264 (the same as above)
The idea of the fix is don't use antd.less (https://ant.design/docs/react/customize-theme). Processing of the file using less by webpack will lead to huge memory consumption. Thus the CVAT UI built will be failed (in some cases silently). It leads to many different problems (see issues above).
=> Fix AWS deployment 

Dockerfile
```
django@870709cba294:/tmp$ git clone -q -v git@github.com:nmanovic/dummy-anno.git
Cloning into 'dummy-anno'...
The authenticity of host 'github.com (140.82.118.3)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
=> Fix known hosts issue in Git app

cvat-ui/src/actions/annotation-actions.ts
Sometimes this function returns null because of wrong initialization
=> Fixed zOrder range computing in case when there are tags

CHANGELOG.md, cvat-core/src/session.js, cvat-ui/src/components/annotation-page/annotations-filters-input.tsx
=> React UI: Added dialog window with some help info about filters

CHANGELOG.md, cvat-ui/src/components/settings-page/player-settings.tsx, cvat-ui/src/components/settings-page/styles.scss
=> React UI: Added button to reset color settings

CHANGELOG.md, cvat-canvas/README.md, cvat-canvas/src/typescript/canvas.ts, cvat-canvas/src/typescript/canvasController.ts, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/src/actions/settings-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/components/settings-page/styles.scss, cvat-ui/src/components/settings-page/workspace-settings.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/containers/settings-page/workspace-settings.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/settings-reducer.ts
=> React UI: Added option to display shape text always

CHANGELOG.md, cvat/apps/engine/media_extractors.py
Previous preview size was not optimal and led to a blurred image due to too small size.
Previous tasks will not be fixed by new ones should have a better preview size.
=> Increase preview size

cvat/apps/engine/frame_provider.py
- refactored code to remove duplication
- probably, fixed bug with chunk caching - last loaded chunk id and reader were not stored, but passed
=> Refactor frame provider

CHANGELOG.md, cvat-ui/src/components/create-model-page/create-model-content.tsx, cvat-ui/src/components/feedback/feedback.tsx, cvat-ui/src/components/file-manager/file-manager.tsx, cvat-ui/src/components/file-manager/styles.scss, cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/consts.ts
Message has been added to help users understand how to mount a shared storage
Manual testing
```python
#
```
Related #1341
=> React UI: Added message when share is empty or not mounted

datumaro/datumaro/plugins/coco_format/converter.py
- Resolved the issue with non-flat image file layout in COCO export by saving full image path
=> Save full image paths in coco

CHANGELOG.md, cvat/apps/git/git.py
resolve #1380
At the moment all repos data are saved in data/{tid}. Need change it according to new data layout.
```python
#
```
=> Fix git app paths

CHANGELOG.md, cvat/apps/auto_annotation/image_loader.py, cvat/apps/auto_segmentation/views.py, cvat/apps/tf_annotation/views.py
At the moment this applications don't work by reason of FrameProvider API changes.
Manual testing
```python
#
```
=> Fixed auto annotation, tf annotation and auto segmentation apps

CHANGELOG.md, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/tests/test_coco_format.py
Fixes a bug with duplicating keypoints in COCO keypoints export when there are solitary points and other solitary instance annotations presented.
Unit tests, manual testing.
```python
#
```
=> [Datumaro] Fix duplicating keypoints in COCO export

CONTRIBUTING.md, cvat-core/package.json, cvat-core/src/frames.js, cvat-ui/package-lock.json, cvat-ui/webpack.config.js
``npm`` installation doesn't work after versioning update for legacy node version like ``8.10``
Manual testing
P.S.
When we use ``npm 3.*`` and do ``npm install`` in ``cvat-ui`` directory, npm copies all local dependencies to ``node_modules`` of ``cvat-ui`` and installs all dependencies of these local dependencies to the same folder. It creates some issues like invalid imports in vscode when work with the whole project and …
=> Fixed versioning for npm 3

.vscode/launch.json, CHANGELOG.md, cvat/apps/documentation/installation.md, cvat/settings/base.py, cvat/settings/development.py, cvat_proxy/conf.d/cvat.conf.template
resolve #1234 
Manual testing
```python
#
```
=> Fixed 'Open task' button doesn't work

CHANGELOG.md, cvat-core/src/annotations-collection.js, cvat-core/src/session.js, cvat-core/tests/api/annotations.js
There aren't way to get information what objects have been just added with ```session.annotations.put()```. But sometimes we need this information to create some extra steps (for example, to automatically group them immediately after creating)
Updated unit tests
Resolved #1486
=> session.annotations.put() returns indexes of added objects

cvat-canvas/README.md, cvat-core/README.md, cvat-data/README.md, cvat-ui/README.md
We should follow the npm versioning rules in client part. This PR adds some hints about it to ``README.md`` files.
N/A
=> Updated README.md files (added info about versioning)

cvat/apps/dataset_manager/views.py, cvat/apps/engine/tests/_test_rest_api.py
Fixed new linter issues after #1352 PR merged
Manual testing
```python
#
```
=> fixed linter issues

CHANGELOG.md, datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/coco_format/converter.py, datumaro/datumaro/plugins/coco_format/extractor.py, datumaro/datumaro/plugins/coco_format/format.py, datumaro/datumaro/plugins/coco_format/importer.py, datumaro/datumaro/plugins/datumaro_format/converter.py, datumaro/datumaro/plugins/datumaro_format/extractor.py, datumaro/tests/test_coco_format.py, datumaro/tests/test_datumaro_format.py
Fixes the COCO import issue described in #1539.
Added `NotImplemented` warning when importing several sources containing labels, as such situation mostly lead to a conflict with different labels. In such situations will be used only one type of sources.
Added missing tests for skeleton joints.
Fixed a python 3.8 regression with `Enum` belonging checks.
Unit tests …
=> [Datumaro] Fix coco import conflict with labels

CHANGELOG.md, datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/voc_format/extractor.py, datumaro/tests/test_masks.py, datumaro/tests/test_voc_format.py
The problem is that in Datumaro there is more VOC labels than is used in VOC segmentation. The algorithm to decode masks did not expect that. The algorithm is changed to expect no more than 65k classes and 65k instances on a single image.
Fixes the problem with VOC dataset import in Datumaro described here: #1539 
Unit test. …
=> [Datumaro] Change alignment in mask parsing

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py, cvat/apps/dataset_manager/formats/cvat.py, cvat/apps/dataset_manager/formats/mot.py, cvat/apps/dataset_manager/tests/_test_formats.py, datumaro/datumaro/components/project.py, datumaro/datumaro/plugins/yolo_format/extractor.py
Closes #525 
This patch allows to export un-annotated images, so both annotated and un-annotated images are exported, where it makes sense to the target format.
Unit tests
```python
#
```
=> Include empty images in exported annotations

CHANGELOG.md, cvat/apps/auto_segmentation/views.py
Fixed auto_segmentation app
fixed `tf.placeholder() is not compatible with eager execution` exception for auto_segmentation performing
Manual testing
```python
#
```
=> Fixed auto_segmentation app

cvat/apps/dataset_manager/formats/README.md, datumaro/tests/test_voc_format.py
Added explanations for importing 1-channel segmentation masks.
Manual test
```python
#
```
=> Add VOC grayscale masks test and documentation

CHANGELOG.md, datumaro/datumaro/plugins/transforms.py, datumaro/tests/test_transforms.py
Fixes a warning message leading to an exception with unexisting field access.
Unit test
```python
#
```
=> [Datumaro] Fix mask to polygons warning

CHANGELOG.md, datumaro/datumaro/cli/__main__.py
Currently, to obtain debug logs for initialization user needs to define a specific env. variable. This was introduced as a workaround for 2-stage arg parsing. This patch simplifies the implementation and leaves only one way of setting log level.
Manual testing …
=> [Datumaro] Simplify log level setting

CHANGELOG.md, cvat/apps/git/git.py
Resolve #1569
Currently it doesn't work
Manual testing
```python
#
```
=> Fixed git synchronization

README.md
Updated Online Demo section of README
Necessary to update the section due to launch of CVAT public demo instance.
N/A
```python
#
```
=> updated Online Demo section of Readme

CHANGELOG.md, cvat/apps/engine/media_extractors.py
resolve #1411 
Fixed task creation for videos with uneven dimensions.
FFmpeg x264 implementation requires width and height must be divisible by 2 for yuv420p, but it's possible to get uneven dimensions for yuv420p format with other software - it's reason why we cannot use original pix_fmt. So, let's use yuv420p for original and compressed chunks and add padding if height or width are uneven.
Manual testing
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) …
=> Fixed task creation for videos with uneven dimensions.

CHANGELOG.md, cvat/apps/log_viewer/views.py, cvat/settings/base.py
Added settings to reduce access to analytics component
Sometimes it's not good that every user has access to the analytics page.
```python
#
```
=> added settings to reduce access to analytics component

CHANGELOG.md, cvat/apps/engine/serializers.py, cvat/apps/engine/tests/_test_rest_api.py
Now CVAT by default can return information about users (/api/v1/users end point). It contains basic information about the user including the e-mail. Need to hide e-mail by default.
Tests for cvat server were modified to address the change.
Feel free to …
=> Remove information about the email from the basic user information

cvat/apps/dataset_manager/views.py
Fix cached exported annotations file name.
```python
#
```
=> Fix cached exported annotations file name

datumaro/datumaro/plugins/cvat_format/converter.py, datumaro/datumaro/plugins/cvat_format/extractor.py, datumaro/datumaro/plugins/cvat_format/format.py, datumaro/tests/test_cvat_format.py
Preparation commit for #1463 
Synchronizes the expected format of CVAT dataset in Datumaro with CVAT dataset export output.
- Removed `annotations` subdirectory in dataset, annotations are expected in the root directory …
=> [Datumaro] Remove annotation dir for cvat dataset format

.gitignore, CHANGELOG.md, cvat/apps/documentation/installation.md
Update https install manual. Makes it easier and more robust. Includes automatic renewing of lets encrypt certificates.
This doc update has been tested on VPS manually.
```python
#
```
=> update https install section

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
This PR fixed #1611 
Manually
```python
#
```
=> Fixed activation bug with frame switching

datumaro/datumaro/components/extractor.py, datumaro/datumaro/plugins/datumaro_format/converter.py, datumaro/datumaro/plugins/datumaro_format/extractor.py, datumaro/datumaro/util/test_utils.py, datumaro/tests/test_datumaro_format.py
Preparation commit for #1463.
Added DatasetItem attributes. Added their support in Datumaro file format.
Unit tests.
```python
#
```
=> [Datumaro] Add DatasetItem attributes

datumaro/tests/test_cvat_format.py
Follow up for #1640. Added CVAT format tests for examples.
Unit tests.
```python
#
```
=> [Datumaro] Add importing tests for cvat format from examples

datumaro/datumaro/plugins/voc_format/extractor.py
Some debug output should help in understanding dataset import status and the source of errors.
Manual test
```python
#
```
=> [Datumaro] Add debug output in VOC import

datumaro/tests/test_coco_format.py
Tests for COCO examples added in #1640.
- Some simplifications for tests
- Added an example import test
```python
#
```
=> [Datumaro] Update COCO tests

cvat/apps/git/git.py, cvat/apps/git/tests.py
https://github.com/opencv/cvat/issues/1651
Adjusted regexes to cover multipart repositories. 
https://github.com/opencv/cvat/issues/1651
Using reproduction steps from the issue description. 
Used single part and multipart addresses in SSH form and HTTPS. 
~~- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canv …
=> Fixes regexes to accept multipart git repository address.

CHANGELOG.md, CONTRIBUTING.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-shape-popover.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/color-changer.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/label-item.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/label-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/reducers/shortcuts-reducer.ts
- Added shortcuts:
- Change color [Press ENTER when object is activated]
- Switch split mode [Alt + M]
- Added ability to search label when create an object or change a label in the side panel
- Added ``python-tk`` to installation guide. Debug server doesn't work for me without
- Resolved some eslint & remarklint issues
The PR provides some features that was requested by community and data annotation team
Manual testing
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data …
=> [React] Added shortcuts & ability to search a label

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/labels-editor/common.ts, cvat-ui/src/components/labels-editor/raw-viewer.tsx
When use raw representation of labels, some errors aren't validated. It confuses our users. What's more there is a warning in React related with unique keys. This PR fixes these issues.
Manual testing …
=> [CVAT-UI] Better labels validation and fixed React warning

datumaro/datumaro/util/tf_util.py
- Updated TF import check so that TF couldn't be re-imported with default `import` expression if an import error happens
Manual test
```python
#
```
=> Prevent reimports for TF

datumaro/datumaro/plugins/coco_format/extractor.py
If we add a file directly by its path, there is no reason to disallow arbitrary file names. The name should be used to recognize subset, but if it can't be done we can just use the default subset. This does not happen in official COCO format, but for custom annotation this improves quality of life.
Manual test …
=> [Datumaro] Allow any annotations file name in coco extractor

cvat/apps/dataset_manager/bindings.py, cvat/apps/dataset_manager/tests/_test_formats.py
Follow up for #1615
Added an exception when frames have invalid ids instead of silently skipping annotations on import.
Unit tests
```python
#
```
=> Throw an error on unknown frames

datumaro/datumaro/cli/commands/explain.py, datumaro/datumaro/cli/contexts/model/__init__.py, datumaro/datumaro/components/config.py, datumaro/datumaro/components/config_model.py, datumaro/datumaro/components/launcher.py, datumaro/datumaro/components/project.py, datumaro/datumaro/plugins/openvino_launcher.py
- Actualized RISE command line to be compatible with recent code changes and #1463
- Renamed `--progressive` to `--display`
- Updated `model` CLI:
- Added auto-generation of output directory names
- Simplified cli plugins for launchers
- Removed input image size hint in launcher as unnecessary
- Removed `model_dir` from config
- Changed iteration method for config to be like in `dict`
Manual test …
=> [Datumaro] Refactor explain and models CLI

cvat/requirements/base.txt
=> Fix 'django-compressor 2.4 has requirement rjsmin==1.1.0'

cvat/apps/engine/utils.py
=> Compatibility with python 3.6 and lower.

cvat/settings/production.py
Added env variables for Postgres DB and user names
Configurable DB name and user name are standard 
No special testing is needed, fallback in case of missing env vars is the previous value …
=> Continuation of https://github.com/opencv/cvat/pull/1641

CHANGELOG.md, cvat-core/package.json, cvat-core/src/annotations-collection.js, cvat-core/src/annotations-objects.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/labels-editor/label-form.tsx
1. Fixed propagation from the latest frame (issue of ``cvat-core``)
1. Fixed number validation (didn't work well with floats, issue of ``cvat-core``)
1. Adjusted attribute validation messages in ``cvat-ui ``
Resolve #1785
Some issues have been found and reported. Need to fix them
Manual testing …
=> Bug fixes: Propagation from the latest frame, number attribute validation

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py, cvat/apps/engine/tests/_test_rest_api.py, datumaro/datumaro/plugins/voc_format/converter.py, datumaro/datumaro/plugins/voc_format/extractor.py, datumaro/tests/test_voc_format.py
Closes #1518 
Allows any values in `pose` object attribute.
Allows to read and write annotation attributes in `attributes` element of VOC XML annotations.
Exporting is enabled by default and can be disabled with `--allow-attributes=False` CLI option of Datumaro export. …
=> Add attributes in VOC format

cvat-canvas/webpack.config.js, cvat-core/webpack.config.js, cvat-data/webpack.config.js, cvat-ui/src/index.html, cvat-ui/webpack.config.js
Adding hash to the js bundle name should solve the problem with the browser cache after updating cvat-* component(s).
Resolve #1545 
Manually
```python
#
```
=> Add hash to js bundle names

CHANGELOG.md, cvat-ui/src/containers/header/header.tsx
=> Bug fixes: logout

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts
One of bugs affects some functionality, more specific - propagation (reported on gitter).
Resolve #1819
Manual testing
```python
#
```
=> [CVAT-UI] Fixed displaying on canvas in some cases

Dockerfile
Fixed CVAT docker image build.
resolve #1851
Installation of python-ldap package is failed with `setuptools` 48.x and 49.0.x
CI
```python
#
```
=> Fixed CVAT docker image build.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvas.ts, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/groupHandler.ts, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/utils/redux.ts
The PR fixes several issues reported by internal team and open source community
@ActiveChooN Please, review it ASAP
Manual testing
```python
#
```
Resolve #1841
Resolve #1870
Resolve #1861
=> [CVAT-UI] Critical fixes

CHANGELOG.md, cvat/apps/dataset_manager/annotation.py, cvat/apps/dataset_manager/tests/test_annotation.py
Fixes #1869
Adds simple interpolation tests.
Unit tests
```python
#
```
=> Fix interpolation error

datumaro/datumaro/plugins/voc_format/converter.py
Annotation-less XMLs were not saved, while they should.
Manual test
```python
#
```
=> Allow saving empty XMLs in VOC

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py
Fixes #1893
Quite surprised it was working. Added a conversion from string to float for point values in import.
Manual test.
```python
#
```
=> Convert points to float in import

cvat/apps/engine/media_extractors.py
Removed redundant call of `av.datasets.curated` from `VideoReader` class.
This call is redundant.
Manually + CI
```python
#
```
=> Removed redundant call of av.dataset.curated method in VideoReader class

CHANGELOG.md, cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx, cvat/apps/documentation/user_guide.md
fixes #1900 
make intuitive and consistent definition of 'Image quality' parameter across Task creation context and documentation.
```python
#
```
=> Image quality parameter mismatch #1900

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/autoborderHandler.ts, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/editHandler.ts, cvat-core/package.json, cvat-core/src/annotations-objects.js, cvat/apps/dataset_manager/annotation.py
1. Fixed: Interpolation algorithm, array must be flatten
1. Fixed: When redraw polygon with enabled feature of autobordering previous points are visible
The PR fixes couple of bugs reported by internal team and our community …
=> CVAT-UI: Couple of fixes

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
Internal team complained about current details are too big. This patch does details smaller
Manual testing
```python
#
```
Resolve #1443
=> Smaller object details

cvat/apps/dataset_manager/formats/cvat.py
Currently, the cvat annotation import (upload) matches annotations to frames by id, so this works only on very specific cases like backups for the same task. When moving annotations between tasks, if the order doesn't match exactly or if there are more frames, or (in our case) if we generate cvat annotations for pre-annotation, nothing matched and it's useless.
This PR just uses the same matching as for coco files, so it works both for old use-cases like backup (if the ID matched, then the filenames will match) but also pre-annotation and others.
Manually, uploaded some files.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-us …
=> Match image by name (instead of id) on CVAT upload

datumaro/datumaro/components/extractor.py, datumaro/datumaro/components/project.py, datumaro/tests/test_coco_format.py, datumaro/tests/test_cvat_format.py, datumaro/tests/test_datumaro_format.py, datumaro/tests/test_labelme_format.py, datumaro/tests/test_mot_format.py, datumaro/tests/test_tfrecord_format.py, datumaro/tests/test_transforms.py, datumaro/tests/test_yolo_format.py
Tests are complex.  It's necessary to reduce nesting. 
To achieve this goal was implemented Dataset.from_iterable(), labelCategories.from_iterable() 
and PointsCategories.from_iterable(). The format tests was simplified.
It was tested using unittests. …
=> [Datumaro] Reducing nesting of tests

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-context-menu.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx
Resolve #1919 
Antd API is not enough to implement it. Some tricks with react hooks are used.
Manual testing
```python
#
```
=> Added tricky handling of a caret position in input element

datumaro/datumaro/plugins/tf_detection_api_format/converter.py, datumaro/datumaro/plugins/tf_detection_api_format/extractor.py
Closes #1829. It [looks](https://github.com/tensorflow/models/blob/master/research/object_detection/data_decoders/tf_example_decoder.py#L225) like this field is not mandatory.
Added `image/sha256` field to tfrecords.
Manual test …
=> Add image sha256 to tfrecord

datumaro/datumaro/cli/commands/convert.py
Updates `datum convert` command after converter interface changes.
Manual test
```python
#
```
=> [Datumaro] Fix convert command

cvat-core/package.json, cvat-core/src/annotations-objects.js, cvat-core/src/api.js, cvat-core/src/enums.js, cvat-core/src/object-state.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Switch source when change zOrder, occluded, outside, keyframe since they are part of position
Fixed double undo/redo actions on every change
Fixed undefined source on client
Some fixes for recent PR #1192 
Manual testing …
=> Fixed default undefined, fixed double change

CHANGELOG.md, utils/cli/README.md, utils/cli/cli.py, utils/cli/core/core.py, utils/cli/core/definition.py
=> add https flag to python cli

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/file-manager/file-manager.tsx
Currently the files and folders lists under share path in the task creation view are not sorted. This can be annoying to work with when creating tasks manually for a lot of folders. 
Added a path as share path with a lot of sub folders and checked manually that those folders are sorted alphabetically.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) -> have not found related issues. …
=> Sort files and folders in the share path

.travis.yml, CONTRIBUTING.md, Dockerfile.ci, docker-compose.ci.yml, tests/cypress.json, tests/cypress/integration/auth_page.js, tests/cypress_ci.json
Adding cypress support. And automation of running tests in CI.
```python
#
```
=> Add cypress support

CHANGELOG.md, utils/cli/core/core.py, utils/cli/core/definition.py, utils/cli/tests/_test_cli.py
Allow users to create the cvat task with multiple jobs through cvat python cli.
Since cli tools does not have the automatic test, I directly test it with my own task. 
The task create with default param:
The task create with `--overlap=0 --segment_size=31`: …
=> add overlap & segment_size flag for python cli task create

CHANGELOG.md, cvat-core/package.json, cvat-core/src/frames.js, cvat-core/src/session.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/plugins-actions.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts
Fixed one issue related with cached data and probably some ambiguity in data streaming
Added error message for case when plugins could not be initialized (infinite loading was before)
Manual testing …
=> [React UI] A couple of fixes

cvat/apps/engine/views.py
fix #1543 
Swagger Documentation is showing "/tasks[POST]" Request JSON for "/tasks/{id}/data" which is wrong.
Manual testing
```python
#
```
=> Fixed swagger API documentation for POST /tasks/{id}/data endpoint

README.md
Remove code beat badge because we don't use it.
N/A
```python
#
```
=> Remove codebeat badge

CHANGELOG.md, cvat/settings/base.py
Increase the amount of requests that an "unauthenticated" user can perform, to prevent throttling errors when using the CLI.
Hitting the /login endpoint from an unauthenticated user can trigger throttling. While throttling should be kept, as it is good practice, the rate can be increased as the user may have valid authentication. A reasonable level of 100 requests/minute should be enough to enforce good practices while preventing headaches for users trying to automate tasks with the CLI. 
(This rate was chosen to be similar to the [rate limiting docs](https://laravel.com/docs/7.x/routing#rate-limiting) for Laravel)
Manually.
~~- [ ] I have added tests to cover my …
=> Increase the rate of allowed requests

cvat/apps/dataset_manager/formats/datumaro/export_templates/plugins/cvat_rest_api_task_images.py, cvat/apps/dataset_manager/task.py
- Fixed REST API extractor for Datumaro format export
- Added job annotations export function
Manual testing
```python
#
```
=> Fix rest api task extractor, add job export function

CHANGELOG.md, serverless/openvino/dextr/nuclio/function.yaml, serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio/function.yaml, serverless/openvino/omz/intel/semantic-segmentation-adas-0001/nuclio/function.yaml, serverless/openvino/omz/intel/text-detection-0004/nuclio/function.yaml, serverless/openvino/omz/public/faster_rcnn_inception_v2_coco/nuclio/function.yaml, serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio/function.yaml, serverless/openvino/omz/public/yolo-v3-tf/nuclio/function.yaml
Fix #1977 
In some cases nuclio doesn't work well if a serverless function has `USER non-root` directive. It can lead to problems which are described in #1977 issue.
Possible fix in nuclio which needs to test: https://github.com/liranbg/nuclio/pull/22
Related issue on nuclio GitHub: https://github.com/nuclio/nuclio/issues/1782
It was confirmed by a couple of customers that the patch fixes the issue. …
=> Workaround a problem with deployment openvino serverless functions

components/analytics/docker-compose.analytics.yml
When I was building the repository with analytics (docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d --build), I got the following error.
Pulling cvat_kibana_setup (cvat:)...
ERROR: pull access denied for cvat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
To fix the build error, I changed this one line in the docker-compose.analytics
Again running docker-compose -f docker-compose.yml -f components/analytics/docker-compose.analytics.yml up -d --build. It builds then,
- [x ] I submit my changes into the `develop` branch
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request- …
=> analytics build fix

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/plugins-actions.ts, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/model-runner-modal/model-runner-modal.tsx, cvat-ui/src/components/models-page/models-page.tsx, cvat-ui/src/containers/model-runner-dialog/model-runner-dialog.tsx, cvat-ui/src/containers/models-page/models-page.tsx, cvat-ui/src/index.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts, cvat-ui/src/utils/plugin-checker.ts
Resolved #1965
Manual testing
```python
#
```
Now:
- CVAT works when nuclio dashboard is off
- UI shows message exactly about getting models, not about wrong plugin initialization
- Check …
=> Fixed issue related with deactivated nuclio dashboard

datumaro/datumaro/cli/contexts/project/__init__.py
Fixes #2020 (revert from #1973)
Manual test
```python
#
```
=> [Datumaro] Fix merge command cli

tests/cypress.json, tests/cypress/integration/issue_1919_check_text_attr.js, tests/cypress/support/commands.js
Add Cypress test for issue [1919](https://github.com/opencv/cvat/issues/1919)
```python
#
```
=> Cypress test for issue 1919

tests/cypress.json, tests/cypress/integration/issue_1870_cursor_not_jump_to_end.js, tests/cypress/support/commands.js
Add Cypress test for issue [1870](https://github.com/opencv/cvat/issues/1870)
```python
#
```
=> Cypress test for issue 1870

tests/cypress/integration/issue_1785_propagation_latest_frame.js, tests/cypress/plugins/createZipArchive/addPlugin.js, tests/cypress/plugins/createZipArchive/createZipArchiveCommand.js, tests/cypress/plugins/imageGenerator/addPlugin.js, tests/cypress/plugins/index.js, tests/cypress/support/commands.js, tests/package-lock.json, tests/package.json
Add test.
Add functionality for create zip archive with images.
Update package.json, package-lock.json.
Add Cypress test for issue [1785](https://github.com/opencv/cvat/issues/1785)
```python
# …
```
=> Cupress test for issue 1785

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/tasks-actions.ts, cvat-ui/src/components/create-task-page/create-task-content.tsx, cvat-ui/src/components/create-task-page/create-task-page.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/components/labels-editor/constructor-creator.tsx, cvat-ui/src/components/labels-editor/label-form.tsx, cvat-ui/src/components/labels-editor/labels-editor.tsx, cvat-ui/src/components/labels-editor/raw-viewer.tsx, cvat-ui/src/containers/create-task-page/create-task-page.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/tasks-reducer.ts, cvat/apps/engine/serializers.py, tests/cypress/support/commands.js
Added `Open task` button for task creation notification
Added links to header buttons. Related to #1419 
Fixed #2015 
Fixed #1054 
Manually
Feel free to …
=> Batch of fixes

CHANGELOG.md, cvat/apps/documentation/installation.md, cvat_proxy/conf.d/cvat.conf.template
Added django-rq to the proxy match pattern.
http://localhost:8080/django-rq/ doesn't work as expected.
Manually
```python
#
```
=> Added django-rq to the proxy match pattern.

tests/cypress/integration/issue_1841_hidden_points_cuboids_grouping.js, tests/cypress/support/commands.js
Cypress test for issue [1841](https://github.com/opencv/cvat/issues/1841)
```python
#
```
=> Cypress test for issue 1841

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/index.tsx
Used addEventListener instead of overriding window.onerror for global error handling
The global error handler can be overridden by web analytic framework and part of errors may be uncaught.
Manually …
=> Used addEventListener instead of overriding window.onerror for global error handling

Dockerfile.ui
Related #1862
Tried to build 
```python
#
```
Docker cannot display npm progress bar
One more option is to display some messages about installation (implemented) …
=> Added more info to output during ui build

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
Fixed error message
Manual testing
```python
#
```
Resolve #1456
=> Fixed error message

tests/cypress/integration/issue_1498_message_ui_raw_labels_wrong.js, tests/cypress/plugins/index.js, tests/cypress/support/commands.js
Add Cypress test for issue [1498](https://github.com/opencv/cvat/issues/1498)
```python
#
```
=> Cypress test for issue 1498

cvat/apps/dataset_manager/formats/cvat.py
When there are shapes, and there is a shape on the last frame, exporting as `CVAT for video` adds a 2-shape track, where the second shape has `outside=1` property. The second shape in such a track will be out of the task frame numbers, so annotations could not be imported.
Manual test …
=> CVAT for video format - fix shapes outside of the task frames

CHANGELOG.md, cvat/apps/dataset_manager/formats/cvat.py, cvat/apps/engine/tests/_test_rest_api.py
After #1807 there was a problem: after a frame is matched, a relative id is obtained. This relative id is then used for annotations where absolute id is expected. A relative id = absolute id / step.
Affected releases: 1.1.0-beta, 1.1.0
Unit tests
Feel …
=> Fix CVAT format import for frame stepped tasks

CHANGELOG.md, cvat-canvas/src/typescript/interactionHandler.ts, cvat-core/package-lock.json, cvat-core/package.json, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/actions/plugins-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-menu.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/utils/range.ts
The patch uses server-side implemented serverless tracking to get automatic bounding boxes on client.
Manual testing 
```python
#
```
=> UI Tracking with serverless functions

CHANGELOG.md, cvat/apps/engine/task.py
Fixes #2139 
Manual test
```python
#
```
=> Fix PDF reading - part 1

CHANGELOG.md, cvat/apps/dataset_manager/formats/utils.py, cvat/requirements/base.txt
Switched from pyhash to default hashlib library due to avx2 instructions dependency
#Fixed #2123 
Manually
~~- [] I have updated the [documentation]( …
=> Removed pyhash dependency

tests/cypress.json, tests/cypress/integration/case_2_register_user_change_pass.js, tests/cypress/support/commands.js
Cypress test to check:
- User registration
- Change user password
- Login with the new password
```python
#
```
=> Cypress test to check registration, change password, login

tests/cypress/integration/case_3_task_start_stop_step_frame.js, tests/cypress/integration/issue_1425_highlighted_attribute_correspond_chosen_attribute.js, tests/cypress/integration/issue_1944_loading_screen_switch_job.js, tests/cypress/support/commands.js
Cypress test to check if parameters "startFrame", "stopFrame", "frameStep" works as expected
```python
#
```
=> Cypress test to check task parameters frame

tests/cypress/integration/case_6_image_scale_fit.js
Cypress test to check scale and fit image.
```python
#
```
=> Cypress test to check scale and fit image.

tests/cypress/integration/case_5_image_rotate.js
Cypress test to check image rotate.
```python
#
```
=> Cypress test to check image rotate.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/svg.patch.ts, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-point-context-menu.tsx, cvat-ui/src/reducers/models-reducer.ts
Resolve #2115
Resolve #2012
Manual testing
```python
#
```
=> Using "alt" instead of "ctrl" to delete a point, fixed reducer

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/tasks-page/task-item.tsx, cvat-ui/src/components/tasks-page/tasks-page.tsx
- Fixed the blinking notification
- A bit changed the notification message
- Fixed bug when a task with 0 jobs is displayed as a completed
Resolve #2089
Manual testing
```python
#
```
=> Fixed blinking notification

cvat-core/src/server-proxy.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/tasks-actions.ts, cvat-ui/src/components/labels-editor/constructor-updater.tsx, cvat-ui/src/components/labels-editor/label-form.tsx, cvat-ui/src/components/labels-editor/labels-editor.tsx, cvat-ui/src/components/labels-editor/raw-viewer.tsx, cvat-ui/src/components/task-page/task-page.tsx, cvat-ui/src/containers/task-page/details.tsx, cvat-ui/src/containers/task-page/task-page.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/tasks-reducer.ts, tests/cypress/support/commands.js
There is a bug on cvat.org (doesn't reproduced locally without decreasing the bandwidth between the client and the server)
We can add a label and go to task view fast (if it was opened before), then try to create an object with the label and UI gets some error messages. 
Manual testing. Cypress covers this issue, but the issue is reproduced only when bandwidth is low …
=> Fixed failure after updating a label on cvat.org

CHANGELOG.md, CONTRIBUTING.md
=> Add Mac OS dependencies notes

CHANGELOG.md, components/analytics/docker-compose.analytics.yml, components/serverless/docker-compose.serverless.yml, docker-compose.ci.yml, docker-compose.yml
Resolves #2232 
I have removed the `gateway` key because it was not supported in dockercompose file [version3](https://github.com/docker/docker.github.io/pull/1636). But, if you specify subnet, docker automatically choose relevant [gateway](https://docs.docker.com/engine/reference/commandline/network_create/#specify-advanced-options). So, dockercompose network gateway is still `172.28.0.1`.
Moreover, I have added `driver` key with `default` value. docker-compose was already using default value. …
=> Dockercompose version update 2.3 --> 3.3

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/webpack.config.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/webpack.config.js
PR added @babel/plugin-proposal-optional-chaining plugin for `cvat-ui` and `cvat-core` to support optional chaining feature ([propossal](https://github.com/tc39/proposal-optional-chaining))
Manually …
=> Optional chaining plugin for cvat-ui and cvat-canvas

cvat/apps/dataset_manager/bindings.py, cvat/apps/dataset_manager/formats/cvat.py, cvat/apps/engine/frame_provider.py, cvat/apps/engine/media_extractors.py, cvat/requirements/base.txt
Depends on https://github.com/openvinotoolkit/datumaro/pull/27
- Allows to copy raw images instead of recoding on dataset export
- Improves dataset export performance (4-6x +)
```python
#
``` …
=> Raw image copying in dataset export

tests/cypress/integration/case_11_polylines_shape_track_label_points.js, tests/cypress/integration/issue_1391_delete_point.js, tests/cypress/support/commands.js
Try to draw a polylines shape/track
Try to use parameter “number of points”, polylines drawing should automatically stop after this number of points is achieved
Try to switch a label and draw one more polylines
Check if everything works here
Adapt the tests to use the updated polygon drawing function.
Redesigned the polygon drawing function for using an object as an argument. …
=> Cypress test. Actions on polylines.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/editHandler.ts
Resolved #2306
Manual testing
```python
#
```
=> Fixed bug: 'Cannot read property each of undefined', fixed points size

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-context-menu.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/canvas-context-menu.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
I am not sure, but I hope the PR fixes issue #1823
I was not able to reproduce it, but watching an additional output, it seems to be that it might be 3rdparty issue. 
Manual testing
```python
# …
```
=> Fixed: cannot read property 'label' of undefined

tests/cypress.json
Up "defaultCommandTimeout" to 25 sec.
Spontaneous test crashes when it is impossible to access UI elements. The reasons may be a temporary slowdown of the server. Increasing the value of this parameter should help solve this problem.
Feel free to …
=> Increase Cypress parameter "defaultCommandTimeout"

CHANGELOG.md, cvat-ui/package.json
Disable prettier autoformat for ui module
```python
#
```
=> Disable prettier autoformat for ui module

.nycrc, .travis.yml, package.json, tests/cypress.json, tests/cypress/integration/auth_page.js, tests/cypress/plugins/index.js, tests/cypress/support/index.js, tests/package-lock.json, tests/package.json
Update Cypress to 5.3 (Firefox support is out of beta)
The use of the plugin "@cypress/code-coverage" for running tests after code instrumentations. 
Speed up passing tests after code instrumentation using the Firefox browser. This change made it possible to reduce the launch time of each test by more than 3 times. In addition, don't need to run tests via Google Chrome to measure coverage. …
=> The change in the measurement of CVAT-UI code coverage.

CHANGELOG.md, cvat/apps/dataset_manager/bindings.py, cvat/apps/dataset_manager/tests/test_formats.py
Fixes the problem with `CVAT for images` export - first track frames marked `outside` were presented in the output files.
Closes #2339 
Unit test, manual test.
```python
#
```
=> Don't export outside frames in frame-based formats

tests/cypress/integration/actions_tasks_objects/case_10_polygon_shape_track_label_points.js, tests/cypress/integration/actions_tasks_objects/case_11_polylines_shape_track_label_points.js, tests/cypress/integration/actions_tasks_objects/case_12_points_shape_track_label.js, tests/cypress/integration/actions_tasks_objects/case_8_rectangle_shape_track_label.js, tests/cypress/integration/actions_tasks_objects/case_9_cuboid_shape_track_label.js, tests/cypress/integration/actions_tasks_objects/issue_1425_highlighted_attribute_correspond_chosen_attribute.js, tests/cypress/support/commands.js
Cypress. Saving the label name before creating the object. 
Checking the main parameters of the created object moved to commands.js.
There were situations when a new shortcut added to the task was placed at the top of the list of shortcuts. In this case, when creating an object, the new shortcut is placed first in the drop-down menu. This may affect the passing of tests that check this value. …
=> Cypress. Saving the label name before creating the object.

cvat-ui/.eslintrc.js, cvat-ui/src/consts.ts
Repository links updated from ``opencv`` to ``openvinotoolkit``.
N/A. Minor change
```python
#
```
=> Updated internal links in the tool

cvat/apps/dataset_manager/formats/README.md, cvat/apps/dataset_manager/formats/imagenet.py, cvat/apps/dataset_manager/formats/registry.py, cvat/apps/dataset_manager/tests/test_formats.py, cvat/apps/engine/tests/test_rest_api.py
Add ImageNet format support
Unit tests
```python
#
```
=> Add ImageNet format

tests/cypress/integration/actions_tasks_objects/case_14_appearance_features.js
The test was not successful in Firefox because the click on the cuboid when trying to deactivate all objects. In this browser, the object is activated. In the Google Chrome browser, a click is made on ".cvet-canvascontainer" through the cuboid.
Added coordinates for the click. The click is made slightly below the cuboid. …
=> Fix Cypress test "Appearance features".

CHANGELOG.md, cvat/apps/engine/task.py
=> Fixed saving of relative paths in dummy chunks instead of absolute

Dockerfile.ui
Output of installing procedure is too much. It creates difficulties for investigating in CI. 
Manual testing
```python
#
```
=> Removed extra output when installing node packages

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/labels-editor/label-form.tsx
Resolved #2411 
Manual testing
@dvkruchinin Please, write a test for the issue
Scenario is:
1. Open the create task page
2. Go to Raw labels editor
3. Insert there:
```json
[
{
"name": "person",
"color": "#ff6037",
"attributes": [
{
"name": "lower_body",
"input_type": "select",
"mutable": true,
"values": [
"__undefined__",
"long",
"short",
"n/a"
]
},
{
"name": "hair_color",
"input_type": "select",
"mutable": true,
"values": [
"__undefined__",
"black",
"brown",
"blond",
"grey",
"other",
"n/a"
]
},
{
"name": "cellphone",
"input_type": "select",
"mutable": true,
"values": [
"__undefined__",
"yes",
"no",
"n/a"
]
}
]
}
]
```
4. Press done
5. Go to constructor tab, be sure that the label "person" appeared there
6. Start editing it
7. Try to remove the average attribute "hair_color", be sure it …
=> Fixed bug: wrong attribute is removed in label constructor

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/containers/annotation-page/standard-workspace/canvas-context-menu.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Resolve #1823 
Manual testing
@dvkruchinin Could you please write a test for the issue?
Scenario is quite interesting, so, probably need to think how implement the test better. 
1. First we need a task with at least two images and chunk size === 1 (there can be other conditions, but anyway during the test we need to fetch another chunk. In this simplest way it is achieved just by jumping to the next frame)
1. On the first frame need to create a shape
1. Next we need to go to another frame (chunk fetching procedure must be run [circle loading progress bar at the center of canvas, element #cvat_canvas_loading_circle])
1. During this procedure (duration depends on client-server bandwidth) need to open context menu for a shape
1. Before fix UI is expected to be crashed with this exception …
=> Fixed issue: Cannot read property label of undefined

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/task-page/user-selector.tsx
Resolved #2440 
Manual testing
```python
#
```
=> Fixed: Value must be a user instance

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Resolved #2174
Manual testing
```python
#
```
=> Fixed: Reset zoom option doesn't work in tag annotation mode

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/top-bar/player-buttons.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
Resolve #1922
Manual testing
@dvkruchinin Could you please write a test for the issue.
Scenario is:
1. Open a job (should contain at least two images)
2. Draw a shape on the first image
3. Draw a shape on the second image
4. Switch player back button mode to "back with a filter" (right click by the button and select)
5. Start resizing (or dragging) a shape on the second frame
6. Press the shortcut [D] to go to the first frame
7. CVAT goes to fail view before the fix and nothing happens after fix
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#v …
=> Fixed: Canvas is busy

docs/rest_api_design.md
We should keep our REST API consistent. Just described general ideas behind the current REST API of CVAT.
To prevent typical issues when people try to add new endpoints into our REST API.
N/A …
=> REST API design based on our experience and popular articles

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/session.js
This PR provide ability to patch only changed fields in cvat-core `job` and `task` entities 
Manually …
=> Partly update fields with PATCH requests

tests/cypress/integration/actions_tasks_objects/issue_2306_ui_not_throw_error_specify_one_point.js
Update of the object creation functionality.
```python
#
```
=> Fix cypress test for check issue 2306.

tests/cypress/integration/actions_tasks_objects/case_21_canvas_color_feature.js
Cypress test. Canvas color feature.
```python
#
```
=> Cypress test. Canvas color feature.

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/projects-page/project-list.tsx, cvat-ui/src/components/projects-page/styles.scss
Hotfix for projects layout
@bsekachev, review it asap, please, because it's quite critical for cvat.org
Manually …
=> Projects layout fix 

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/tasks-actions.ts, cvat/apps/engine/views.py
Fixed the tasks view (infinite loading) when it is impossible to get a preview of the task
Manually …
=> Task view hotfix

CHANGELOG.md, cvat/apps/engine/media.mimetypes, cvat/apps/engine/tests/test_rest_api.py
Added support of mxf videos
resolve #2469 
Manually + unitests
https://github.com/opencv/cvat/blob/develop/LICENSE) that covers …
=> Added support of mxf videos

tests/cypress/integration/actions_tasks_objects/case_23_canvas_grid_feature.js
Test execution error in travis-ci via Firefox browser.
By default, Cypress clicks on the object in the center. Locally in Chrome and Firefox, this value is 49% on the slider. But in Travis-ci in Firefox, this value is 50%, so checking the value failed with an error. Reworked the test for moving the slider 20 points to the left, which is 80%.
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#v …
=> Fix cypress test case 23.

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-menu.tsx, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/notifications-reducer.ts, tests/cypress/integration/actions_tasks_objects/case_24_delete_unlock_lock_object.js
Cypress test. Delete unlock and lock object.
Add cssSelectors for elements.
```python
#
```
=> Cypress test. Delete unlock and lock object.

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/projects-actions.ts, cvat-ui/src/actions/review-actions.ts, cvat-ui/src/actions/tasks-actions.ts, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/projects-page/project-list.tsx, cvat-ui/src/components/task-page/task-page.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/review-reducer.ts, cvat-ui/src/reducers/tasks-reducer.ts
Resolved #2523
Also fixed a couple of React warnings
Manual testing + cypress tests are in progress
```python
#
```
=> Fixed: TypeError: Cannot read property 'id' of undefined

Dockerfile.ui
Fixed cvat_ui image build
resolve #2538 
Time to time the `node-sass` package cannot be installed properly for a reason(cannot download prebuilt binary linux_musl-x64-83_binding.node for example), also there is the error message for the optional dependency installation - `fsevents`.
Manually …
=> Fixed cvat_ui image build

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx, cvat-ui/src/components/projects-page/project-list.tsx, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/components/tasks-page/task-item.tsx, cvat-ui/src/components/tasks-page/task-list.tsx
- Fixed: Cannot read property "key" of undefined  (3rdparty error, fixed in https://github.com/react-component/virtual-list/pull/90). Fixed by emporary installation of the newest version to project dependencies.
- Fixed: Extra pagination parameters appeared in new Antd version (Disabled)
- Fixed: Canvas doesn't fit after sidebar collapsing
- Fixed: Wrong CSS styles for task progress on a taskItem
- Fixed: Copy reviewer when pressing "Copy" button
Manual testing …
=> Antd4 migration minor fixes found on cvat.org

supervisord.conf
Closes #2543 
Before the change, rqscheduler was initalized with hardcoded "redis" value as a host - instead of using the ENV_CVAT_REDIS_HOST env variable. Due to this error there was no possibility to change the name of the container with redis. The problem appeared when CVAT was installed on kubernetes pod - where the suggested host for accessing containers within the same pod is localhost. Lack of possibility to change this address led to delays in starting CVAT pod - as the kubernetes needs some time to register the "redis" name - while if rqscheduler uses localhost as an address of "redis" connection is made quickly.
I've tested it by running the CVAT deployment on kubernetes. After correction there were no problems with accessing the "redis" container since the start of the CVAT …
=> Wrong parametrization of the rqscheduler instance

CHANGELOG.md, README.md, cvat/apps/dataset_manager/formats/README.md, cvat/apps/dataset_manager/formats/camvid.py, cvat/apps/dataset_manager/formats/registry.py, cvat/apps/dataset_manager/tests/test_formats.py, cvat/apps/engine/tests/test_rest_api.py, cvat/requirements/base.txt
Add CamVid format support
Unit tests
```python
#
```
=> Add CamVid format

.travis.yml
At the moment, an error is observed in CI in the CRON type when migrating the database. This patch was created to solve it.
Added a command to wait for a response with the status 401 from the page ```localhost:8080/api/v1/server/about```
Feel free to …
=> Fix migration error in CRON type of CI.

tests/cypress/integration/actions_tasks_objects/case_33_always_show_object_details_feature.js, tests/cypress/integration/actions_tasks_objects/case_36_always_show_object_details_feature.js
Cypress test. Always show object details feature.
```python
#
```
=> Cypress test. Always show object details feature.

tests/cypress/integration/actions_tasks_objects/case_15_group_features.js, tests/cypress/support/commands.js, tests/package-lock.json, tests/package.json
Cypress test. Group color feature.
To add this test, I thought it would be better to use an existing test. Added the necessary checks.
```python
#
```
=> Cypress test. Group color feature.

CHANGELOG.md, cvat-data/package-lock.json, cvat-data/package.json, cvat-data/src/js/cvat-data.js
Frame preloading doesn't work due improperly initialization of `FrameProvider` by this commit https://github.com/openvinotoolkit/cvat/commit/7512fd6883829ff2692ef42a5a41a06f3805da14#diff-44a538d6db30ba4db0034acd80cc53f908c457d6a69cecd55bc9a968c43cb26fL29
Manually …
=> Fix frame preloading

cvat-ui/src/components/tasks-page/top-bar.tsx, tests/cypress/integration/actions_tasks_objects/case_35_search_task_feature.js
Cypress test. Search task feature.
```python
#
```
=> Cypress test. Search task feature.

cvat-ui/src/components/cvat-app.tsx, tests/cypress/integration/actions_tasks_objects/case_15_group_features.js, tests/cypress/integration/actions_users/issue_1810_login_logout.js, tests/cypress/support/commands.js, tests/cypress/support/index.js
A warning window appears about an unsupported platform when using cy.visit() or cy.reload()
Adding a css class to minimize the use of ant-* classes.
```python
#
```
=> Fix multiple tests for the Firefox browser

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/handle-popover-visibility.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss, tests/cypress/support/commands.js
To solve some issues during testing we need additional css classes, that appear after any popover animations. 
Manual testing
```python
#
```
=> Added css classes depending on popover state

CHANGELOG.md, Dockerfile
resolve #2670
resolve #2662
Added apt ca-certificates package which is required if using ssl connections. …
=> Fix ssl verification error

tests/cypress.json, tests/cypress/integration/actions_tasks_objects/registration_involved/case_39_issue_2572_rename_task.js
Also contains the issue #2572 check.
```python
#
```
=> Cypress test. Rename task feature.

tests/cypress/support/commands.js
In Firefox, deleting a filter may fail if the filter value is equal to or longer than the length of the filter value input field.
What it looks like in Firefox:
What it looks like in Chrome:
At the moment, removing the filter in the test is performed by removing the filter itself. This raises an error in Firefox browser:
```
`<span class="ant-select-selection-item-remove" style="user-select: none;" unselectable="on" aria-hidden="true">...</span>`
is being covered by another element:
`<svg viewBox="64 64 896 896" focusable="false" data-icon="close-circle" width="1em" height="1em" fill="currentColor" aria-hidden="true">...</svg>`
```
I rework the cypress command deleting the filter value by clearing the filter input field. This change does not affect the passing of the test in the Chrome …
=> Cypress. Fix remove annotation filter fail Firefox browser.

tests/cypress/integration/actions_tasks_objects/case_41_add_delete_label_attribute.js
Add Cypress test. Add/delete labels and attributes.
```python
#
```
=> Cypress test. Add/delete labels and attributes.

tests/cypress/integration/actions_tasks_objects/case_43_create_label_with_existing_label_name.js
Add cypress test. Creating a label with existing label name.
```python
#
```
=> Cypress test. Creating a label with existing label name.

cvat-ui/src/components/labels-editor/common.ts
Encountered an error when inserting raw labels with colors. Even though CVAT itself produces color HEXes with uppercase letters, they are not accepted when manually put in the "raw" field. This gives the error: "Label "xxxx". Type of label color must be only a valid color string. Got value #2B7D70"".
By adding uppercase letters as a possibility in the RegEx, this is fixed. …
=> Fix reject of color hex that contains uppercase letters

tests/cypress/integration/actions_tasks_objects/case_42_change_label_name_via_label_constructor.js
An error occurred in CI when passing the test steps
```
`<button type="submit" class="ant-btn ant-btn-primary ant-tooltip-open" ant-click-animating-without-extra-node="false" style="width: 150px;">...</button>`
This element `<button.ant-btn.ant-btn-primary.ant-tooltip-open>` is not visible because it has CSS property: `position: fixed` and it's being covered by another element:
`<div class="ant-tooltip ant-tooltip-placement-top " style="left: 277px; top: 493px; transform-origin: 50% 46px;">...</div>`
```
Added ```force: true``` when the button is clicked. …
=> Fix cypress test "Changing label name via label constructor".

cvat/apps/dataset_manager/formats/cvat.py, cvat/requirements/base.txt
- Datumaro is now installed by package name instead of repository
- Datumaro updated from 0.1.4 to 0.1.5.1
- Fixed CVAT format w.r.t. changes
```python
#
```
=> Update Datumaro installation

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/top-bar/statistics-modal.tsx
Resolved #2663
Manual testing
```python
#
```
=> Fixed: Cuboids are missed in annotations statistics

CHANGELOG.md, cvat/apps/lambda_manager/views.py
Fixed #2644, fixed #2529
Manually …
=> Fixed lambda project labels

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-details.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
Resolved #2732 
Resolved #2621 
```python
#
```
=> Fixed a couple of css-related issues

tests/cypress/integration/actions_tasks_objects/case_44_changing_default_value_for_attribute.js, tests/cypress/support/commands.js
=> Cypress test. Changing a default value for an attribute.

tests/cypress/integration/actions_tasks_objects/case_34_drawing_with_predefined_number_points.js
I think the problem is in the interaction of Cypress and Firefox. Cypress uses scroll to the element when interacting: https://docs.cypress.io/guides/core-concepts/interacting-with-elements.html#Scrolling
It looks like this:
Chrome:
Firefox:
And tries to produce a “mousemove” event on the element. In this case, it failed with an error
```
is being covered by another element:
`<svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" id="cvat_canvas_content" …
``` …
=> Fix cypress test "Drawing with predefined number of points" due fail in Firefox browser.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/regionSelector.ts
This one is probably browser issue, not CVAT. 
If width or height of a SVG rectangle are 0, than getBBox() returns all 0 (even for x1, x2 which are actually not 0 according to current element attributes). Chrome works correct in this case, Firefox doesn't. Workaround-ed. 
Resolved #2633 
Manual testing …
=> Fixed: Issue with point region doesn't work in Firefox

tests/cypress/integration/actions_users/issue_2524_2633_issue_not_reset_after_change_task_issue_point_firefox.js, tests/cypress/support/commands_review_pipeline.js
Adding creation an issue as a point. Check #2633 
```python
#
```
=> Update Cypress test. Some parts of the Redux state (issues) isn't reset after changing a task.

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Resolved #2753
The same issue for other popovers.
@dvkruchinin Could you please write a test with the next scenario:
1. Open a task
2. Open draw polygon popup, set 4 points to be drawn
3. Draw a polygon
4. Open the popup again
5. Be sure that 4 points are still entered (empty value is expected before the fix)
Manual testing …
=> Do not call HOC component each render

tests/cypress/integration/actions_tasks_objects/issue_2753_call_HOC_component_each_render.js
Add Cypress test for issue #2753 
```python
#
```
=> Cypress test. Call HOC component each render.

tests/cypress/integration/actions_tasks_objects/case_31_label_constructor_color_label.js, tests/cypress/integration/actions_tasks_objects/case_47_export_dataset.js, tests/cypress/integration/actions_tasks_objects/issue_1568_cuboid_dump_annotation.js, tests/cypress/integration/actions_tasks_objects/pr_2203_error_cannot_read_property_at_saving_job.js, tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js, tests/cypress/support/commands.js
Remove the annotation before running the test body if any object already exists. This can help in the case of a failed test in which the work is being saved but the annotation was not removed due to the failure of the previous test steps.
Feel free to …
=> Cypress. Remove annotation before spec if an object exist.

tests/cypress/integration/actions_projects/registration_involved/base_actions_project_task_user.js, tests/cypress/integration/actions_tasks_objects/case_50_settings_player_speed.js
Add goToTaskList() before user logout. Due to the fact that when logging out of the task, it can be transferred to 
http://localhost:8080/auth/login/?next=/tasks/<task_id> and and when you go to /auth/login, it automatically jumps to the task page.
Added wait() for the dropdown menu transition. …
=> Update Cypress tests.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/editHandler.ts
Resolved #2807 
The bug appeared with this PR #2276 because of changing in implementation of svg.draw.js
@dvkruchinin Could you please write a test? Steps are described in the issue
Manual testing …
=> Fixed polygon editing

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/handle-popover-visibility.tsx
Resolved #2713
Resolved #2230
Manual testing
@dvkruchinin 
We need a test to cover this case
Good gif to reproducing: https://user-images.githubusercontent.com/1630974/105646611-0fa2b880-5ea1-11eb-95ea-45a9c214491e.gif …
=> Improved maintanance of popups visibility

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx, cvat-ui/src/components/labels-editor/styles.scss
- Using target='_blank' when download files to fix tests in dev environment
- Fixed some TypeScript issues (added extra types)
- Minor style fix for Firefox
Manual testing. Downloading works in Chrome and Firefox. 
Feel free to contact the maintainers …
=> Using target="_blank" when downloading annotations

tests/cypress/integration/actions_tasks_objects/case_1_create_delete_task.js, tests/cypress/integration/actions_users/registration_involved/case_4_assign_taks_job_users.js
Fix Cypress tests for antd 4.12.0
```python
#
```
=> Cypress. Fix some tests for antd 4.12.0

.github/workflows/pylint.yml
Resolve the error
```ModuleNotFoundError: No module named 'django'```
when running static code analysis via pylint.
```python
#
```
=> Fix issue pylint "No module named 'django' "

CHANGELOG.md, cvat/apps/lambda_manager/views.py
Fixed of receiving 'function' variable.
Resolve #2769 
```python
#
```
=> Fixed of receiving 'function' variable

CHANGELOG.md, utils/cli/core/core.py
This small PR helps to do many things using the current cli.
By returning the currently available tasks instead of just printing them, we can manipulate tasks using the CLI easily, e.g. removing tasks, dumping automatically, and uploading annotations.
It also helped me understand the data structure behind tasks in CVAT by analyzing the output tasks. 
Missing functionality: Creating projects using cli.
=> CLI- Task list improvement

tests/cypress/integration/actions_tasks_objects/case_43_create_label_with_existing_label_name.js
Update Cypress test for PR #2879 
```python
#
```
=> Update Cypress test "Creating a label with existing label name" for PR 2879

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/control-visibility-observer.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/cursor-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/fit-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/group-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/merge-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/move-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
Resolved #2823
Win 10 when scaled 150%
Manual testing
```python
#
```
=> Added simple extra popover to keep other controls out of display

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/labels-editor/label-form.tsx, tests/cypress/integration/actions_tasks_objects/case_43_create_label_with_existing_label_name.js
This PR fix label form validator to prevent creating labels with the same name.
Manually.
@dvkruchinin, can you change test case 43 appropriate way to check form item validator additionally, please? …
=> Label form validator fix

cvat-ui/.eslintrc.js
Because of some reasons it does not work anymore for ``cvat-ui`` without explicit declaration. Other modules are fine.
Manual testing
```python
#
```
=> Added linting rule to specify import ordering

cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx, tests/cypress/integration/actions_tasks_objects/case_55_repeat_draw_feature.js
=> Cypress test. Repeat draw feature.

cvat-ui/src/components/actions-menu/actions-menu.tsx, cvat-ui/src/reducers/notifications-reducer.ts, tests/cypress/integration/actions_tasks_objects/case_52_dump_upload_annotation.js
Add upload annotation to task.
```python
#
```
=> Cypress test. Update case "Dump/upload annotation"

CHANGELOG.md, cvat/apps/engine/media_extractors.py
Resolve #2956
My previous PR #2895 has a bug in case of a tasks created from images.
Manually
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#ver …
=> Fixed image quality for tasks created from images

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/labels-editor/label-form.tsx
Resolved #2968
```python
#
```
=> Fixed: Cannot update attributes if a task contain at least one number attribute 

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/create-task-page/create-task-content.tsx
Resolved #2967
Manual testing
```python
#
```
=> Fixed: Incorrect text on the warning when specifying an incorrect link to the issue tracker.

cvat-ui/src/components/annotation-page/styles.scss, tests/cypress/integration/actions_tasks_objects/case_13_merge_split_features.js, tests/cypress/integration/actions_tasks_objects/case_51_settings_auto_save.js
Several tests failed with an error in nightly CI. This patch is intended to solve the issue.
```python
#
```
=> Cypress. Fix some tests. Rework margin.

tests/cypress/integration/canvas3d_functionality/case_56_canvas3d_functionality_basic_actions.js, tests/cypress/integration/canvas3d_functionality/case_62_canvas3d_functionality_views_resize.js
Depends on #2891 
Cypress test. Checking for resizing views.
```python
#
```
=> Cypress test. Canvas 3d-m4. Check resize views.

cvat-core/src/annotations-filter.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/top-bar/filters-modal.tsx
Using ``.replaceAll`` was not the best solution because it is not well supported. 
The patch changes method to ``replace(`` with global regex
.replaceAll support
.replace support
```python
#
```
=> Fixed unsupported methods

tests/cypress/integration/canvas3d_functionality/case_56_canvas3d_functionality_basic_actions.js, tests/cypress/integration/canvas3d_functionality/case_63_canvas3d_functionality_control_button_mouse_interaction.js, tests/cypress/support/commands_canvas3d.js, tests/cypress/support/index.js
Cypress test to check canvas 3D functionality.
```python
#
```
=> Cypress test. Canvas 3D. Control button mouse interaction.

CHANGELOG.md, utils/cli/core/core.py, utils/cli/core/definition.py
It would be useful to programmatically attach a git repository for annotation synchronization.
Closes #2976.
Tested this in a personal deployment of CVAT over HTTPS.
```python
#
```
=> Add dataset URI to Task from CLI

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/projects-page/search-field.tsx, cvat-ui/src/components/search-tooltip/search-tooltip.tsx, cvat-ui/src/components/search-tooltip/styles.scss, cvat-ui/src/components/task-page/job-list.tsx, cvat-ui/src/components/tasks-page/styles.scss, cvat-ui/src/components/tasks-page/top-bar.tsx
Resolved #2959
Manual testing
```python
#
```
=> Added filters and sorting options for job list, added tooltip for tasks filters

package.json
Need to remove old husky configuration file before next adding a hook
Otherwise lint-staged runs several times after several ``npm ci``
Manual testing
```python
#
```
=> Remove old husky config file before next husky add 

package.json
Build fails in some cases
Manual testing
```python
#
```
=> Fixed prepare command in case when there aren't husky config

tests/cypress/integration/actions_tasks_objects/case_33_button_continue_label_editor.js, tests/cypress/support/commands.js
Update cypress command.
Add check adding a label with empty name via ```Continue``` button.
```python
#
```
=> Update Cypress test "Button "Continue" in label editor".

tests/cypress/integration/actions_tasks_objects/case_31_label_constructor_color_name_label.js
Adding a reset/cancel buttons interaction.
```python
#
```
=> Update cypress test. Label constructor. Color label. Label name editing.

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/shared.ts
Resolved #3083 
Manual testing + CI
```python
#
```
=> Fixed: Changing a label on canvas does not work when 'Show object details' enabled

tests/cypress/integration/actions_tasks_objects/case_72_hotkeys_change_labels.js
Add cypress test to check #3070 #3084 
```python
#
```
=> Cypress test. Hotkeys to change labels feature.

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/frames.js
* Added upper limit to stop property of active chunk request
Fixes #3080. The unzip_imgs web worker was not getting terminated when loading the last chunk in a task. I added a stopFrame limit to the chunk request so that the web worker gets properly terminated once it unzips all images.
I manually tested this by uploading 71 frames, all 2048 x 2448 to exceed the cache limit, and made sure that the web worker is correctly terminated after loading the last chunk. I also made sure that scrolling back through the previous frames worked and that frames that had been removed from the cache are successfully loaded back in.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-iss …
=> Fix bug with hung web worker

CHANGELOG.md, utils/dicom_converter/README.md, utils/dicom_converter/requirements.txt, utils/dicom_converter/script.py
CVAT does not support DICOM format natively. 
One way to annotate DICOM data is to convert them to regular images first. The patch adds a script to support some kinds of DICOM files to .png
Manual testing, converted:
- [CHAOS training set](https://zenodo.org/record/3362845) CT/MT
- Some multi-frame DICOM files from [here](https://www.aliza-dicom-viewer.com/download/datasets) …
=> Added DICOM conversion script

utils/cli/core/core.py, utils/cli/core/definition.py
The new project feature is helpful, but it is not yet compatible with the CLI create task script. This PR adds the `--project_id` option for the create task and sets the labels to an empty list, which defaults to the project's labels.
The main changes are:
- add `project_id` paramater to the `task_create_parser` that defaults to `None`
- add `project_id` param to `tasks_create` in core.py
- sets labels to `[]` if using a project id, which defaults to the project's existing labels
- `project_id` follows formatting of `lowercase_param_name` used in other (eg `resource_type`)
Main goal is to be able to batch import via CLI into existing projects with existing label sets.
Minimally tested using the following command:
```
docker exec -it cvat bash -ic \
"python3 utils/cli/cli.py \
--auth …
```
=> add --project_id argument for create task

cvat-ui/src/reducers/notifications-reducer.ts, tests/cypress/integration/actions_tasks_objects/issue_2473_import_annotations_frames_dots_in_name.js
Cypress test for check #3091 
```python
#
```
=> Cypress test. Import annotations for frames with dots in the name.

.remarkrc.js, CHANGELOG.md
=> Fixed CHANGELOG.md (remarklint issues)

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/cvat-app.tsx
Fixed #3138. Due to we have not logged yet for the first time `user` is not available and we can't call `loadAuthActions`. It is applicable for the change pass, but not for reset pass option.
Manually …
=> Fixed reset password link unavailable

tests/cypress/integration/actions_tasks3/case_44_changing_default_value_for_attribute.js, tests/cypress/support/commands_filters_feature.js
Periodic test crashes when using Firefox.
```python
#
```
=> Fix cypress command.

tests/cypress/integration/actions_users/case_73_reset_password_notification.js
Cypress test for #3140 
Increase coverage.
```python
#
```
=> Cypress test. Reset password notification.

cvat-ui/src/components/create-task-page/create-task-page.tsx, tests/cypress/integration/actions_tasks2/case_76_try_create_task_incorrect_dataset_repo.js
Add cypress test. Increase code coverage.
```python
#
```
=> Cypress test. Try to create a task with an incorrect dataset repository.

tests/cypress/integration/actions_tasks3/case_44_changing_default_value_for_attribute.js
A large number of drops when using ```.not('.ant-select-dropdown-hidden')``` in CI.
```python
#
```
=> Cypress test. Fix case 44. Revert use .not('.ant-select-dropdown-hidden')

CHANGELOG.md, cvat/apps/engine/log.py, cvat/apps/engine/migrations/0038_manifest.py
[Motivation](https://github.com/openvinotoolkit/cvat/pull/3146#issuecomment-832090946)
Manually …
=> Move migration logger initialization

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/tsconfig.json
Resolved #3178
Hi @dvkruchinin 
A test for this case would be good. 
Manual testing
```python
#
```
=> Fixed cropping polygon in some corner cases

tests/cypress/integration/actions_tasks3/case_44_changing_default_value_for_attribute.js
Any attempts to wait for the attribute value to change to positive failed. I reworked it so that the label change button was visible otherwise I got the ```Detached from the DOM``` error. Perhaps at this time react finishes processing the asynchronous function and the necessary elements get positive values. …
=> Cypress test. Fix "Changing a default value for an attribute"

tests/cypress/integration/actions_objects2/case_77_cropping_polygon_in_some_corner_cases.js
Cypress test for PR #3184 
```python
#
```
=> Cypress test. Cropping polygon in some corner cases.

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/api-implementation.js, cvat-core/src/project.js, cvat-core/tests/api/projects.js, cvat-core/tests/mocks/server-proxy.mock.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/projects-actions.ts, cvat-ui/src/components/project-page/project-page.tsx, cvat-ui/src/components/project-page/styles.scss, cvat-ui/src/components/projects-page/project-item.tsx, cvat-ui/src/components/projects-page/project-list.tsx, cvat-ui/src/components/projects-page/styles.scss, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/projects-reducer.ts, cvat/apps/engine/serializers.py
Resolve #3128. Trying to avoid unnecessary requests while fetching projects API.
Manually
```python …
```
=> Project tasks loading only when needed

utils/cli/core/core.py, utils/cli/core/definition.py
When using CLI to upload images to create tasks, we would like to have control over some advanced configuration like frame step and image quality. 
It has been tested using the tasks_create API by including additional kwargs (image_quality, frame_step):
`CLI.tasks_create(cli, name=name, labels=[], overlap=0, segment_size=0,
resource_type=ResourceType.argparse('local'),
resources=images, image_quality=iq, frame_step=frame_step,
project_id=pid, bug='')`
Maybe someone can help creating a test script ?
- [ X] I submit my changes into the `develop` branch …
=> add cli kwargs for image_quality and frame_step when creating task

CHANGELOG.md, cvat-core/src/api-implementation.js, cvat/apps/engine/views.py, tests/cypress/support/commands_review_pipeline.js
Closes #3183 by adding `is_active` filter to user list.
Tested with api swagger.
```python
#
```
=> Add is_active field in UserFilter

CHANGELOG.md, utils/cli/core/core.py
=> Fix cli create git fail

cvat-core/tests/api/tasks.js, cvat-core/tests/mocks/dummy-data.mock.js
Unit test for PR #3164 
```python
#
```
=> Unit test. Moving a task between/to project.

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/annotations-collection.js, cvat-core/src/annotations-saver.js, cvat-core/tests/api/annotations.js
Resolved #3216 
Added a unit test. This is cvat-core error, end-to-end tests aren't required to cover it.
```python
#
```
=> Fixed issue: is not a constructor when create object, save, undo, save, redo save

.github/workflows/main.yml
Disabling headless mode for running Canvas3D tests in the develop branch.
At the moment, several tests are falling in the ```develop``` branch. It is related to the bug of creating screenshots of Cypress. …
=> Cypress. Disabling headless mode for running Canvas3D tests in the develop branch.

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/appearance-block.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss, cvat-ui/src/components/annotation-page/standard-workspace/context-image/context-image.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/issues-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-side-bar.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss, cvat-ui/src/components/annotation-page/tag-annotation-workspace/styles.scss, cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/shortcuts-reducer.ts, cvat-ui/src/utils/mousetrap-react.tsx
Resolved #3250 
Manual tested
```python
#
```
=> Some JS code was simplified by using css, a reported issue was fixed in this way

cvat-ui/src/components/create-project-page/create-project-content.tsx, cvat-ui/src/components/move-task-modal/label-mapper-item.tsx, tests/cypress/integration/actions_projects/case_94_move_task_between_projects.js, tests/cypress/integration/actions_projects/case_95_move_task_to_project.js, tests/cypress/support/commands.js, tests/cypress/support/commands_projects.js
Cypress tests for PR #3164 
```python
#
```
=> Cypress tests. Move a task between/to projects.

CHANGELOG.md, cvat/apps/engine/views.py
=> Fix meta request performance

cvat/apps/dataset_manager/tests/assets/annotations.json, cvat/apps/dataset_manager/tests/assets/tasks.json, cvat/apps/dataset_manager/tests/test_rest_api_formats.py
Add test for wrong attribute import in tracks #3229
```python
#
```
=> Add test for wrong attribute import in tracks

tests/cypress/integration/actions_tasks/case_65_create_task_with_manifest.js
Deleting the task creation notification check. The verification of this notification was moved earlier to the task creation function.
Workflow https://github.com/openvinotoolkit/cvat/actions/runs/919807651 failed for this reason. …
=> Cypress test. Case 65. Removed the extra check from the test.

cvat-ui/src/components/labels-editor/constructor-viewer-item.tsx, tests/cypress/integration/actions_tasks3/case_44_changing_default_value_for_attribute.js
This test often fails due to the ```aria-label="edit"``` visibility check when changing label attributes. 
```
Timed out retrying after 25000ms: `cy.should()` failed because this element is detached from the DOM.
```
Adding additional checks for the existence and visibility of the parent elements should solve this problem. This version of the updated test was tested in my fork by restarting jobs about 40 times. The test never failed with an error. …
=> Cypress. Case 44. Adding additional checks.

CHANGELOG.md, serverless/openvino/dextr/nuclio/model_handler.py
It improves model performance quality
Related #2515
Manual testing
```python
#
```
=> Added some fixes to DEXTR model handler

cvat/apps/dataset_manager/tests/test_rest_api_formats.py, cvat/apps/engine/tests/test_rest_api.py
Related to https://github.com/openvinotoolkit/cvat/pull/3122
```python
#
```
=> Server tests for context images for 2D tasks

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/api-implementation.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/task-page/user-selector.tsx, tests/cypress/support/commands_review_pipeline.js
Resolved #3339
@dvkruchinin Can we prepare a test for the issue?
```python
#
```
=> Fixed UI fails when inactive user is assigneed to a task/job

.nycrc
Increase code coverage by about 1%
File name | Comment
-- | --
/cvat-ui/src/actions/models-actions.ts | The code is not called in the standard CVAT build
/cvat-ui/src/actions/boundaries-actions.ts | If the application is running correctly, the code is not called.
/cvat-ui/src/containers/models-page/models-page.tsx | The code is not called in the standard CVAT build
/cvat-ui/src/reducers/models-reducer.ts | The code is not called in the standard CVAT build
/cvat-ui/src/utils/platform-checker.ts | Measure coverage conducted on a supported platform …
=> Cypress. Exclude some files from instrumentation.

cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasModel.ts
Don't show a notification about a frame rejected by cvat-data if that frame is no longer needed
resolve #3126 
```python
#
```
=> Fixed extra notifications about frame rejection during navigation

.eslintignore, CHANGELOG.md, cvat-core/src/config.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/cvat-core-wrapper.ts, cvat-ui/webpack.config.js
Added proxy to webpack dev server config to exclude server API variable from UI code and make cypress tests executable on the local environment.
No tests …
=> Webpack dev server proxy

CHANGELOG.md, cvat/apps/engine/models.py, cvat/requirements/base.txt, cvat/settings/testing.py
There is one commit in Django 3.1.11 which change the logic of file name validation (https://github.com/django/django/commit/b7d4a6fa650f97982cf9ca246ddfa623d685487b). Before this commit it checked file name and transformed it by CVAT function to full upload path. After commit at first CVAT function give absolute path then Django check obtained path and failed with error SuspiciousFileOperation because it is the absolute path.
It leads to failures with response code 400 while trying to create a new task.
It is needed to change function `upload_path_handler` in `cvat/cvat/apps/engine/models.py` and don’t use absolute paths to avoid this error.
https://help.github.com/en/github/managing-your-work-on-github/linki …
=> Update to Django 3.1.12.

CHANGELOG.md, Dockerfile.ui
Fixed cvat_ui image build in case of OOM error.
There seems to be a bug in npm v6.x with signal handling on alpine based images only https://github.com/npm/cli/issues/2103 and it won't be fixed for v6.x. This bug is not reproducible on debian buster based images and is not reproducible for npm v 7.x.
We are currently unable to switch to npm 7 easily, so I suggest using a buster based image as the first stage.
resolve #2989
Previously, building the image with the following command `docker build --memory 500M -f Dockerfile.ui .` was successful, although` npm run build` was killed; for now it handles correctly …
=> Fixed cvat_ui image build in case of OOM error

site/content/en/docs/administration/basics/installation.md
Based on my own experience of installation in Win10, I found that in the docs of installation use winpty to execute docker and create superuser. Wihout winpty it seemd has problem to create superuser directly using one command line. Therefore, I have found out just entering the docker and execute the creation can solve the issue.
I tested myself during installation on Win10 and helped other friends to succeed in the same way. …
=> Add other option to create superuser for win10 during installation

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/reducers/annotation-reducer.ts
Fixed #3266
@dvkruchinin Could you please prepare a test?
Manual testing
```python
#
```
=> Fixed issue when save filtered object in AAM

CHANGELOG.md, cvat/apps/engine/task.py
Resolved #3123 
Manual testing
@MashaSS Could you please add a server tests to cover the issue?
```python
#
```
=> Fixed combined image and directory extractors

cvat-core/src/annotations-objects.js
Implements #2755 and #3294. Basically, when changing label class, attributes are retained **IF and only** there is an attribute with the same name and type, and the old value is still valid in the new configuration.
Tested manually on rectangle labels with various attributes. …
=> Added smart attribute keeping when changing label

tests/cypress/integration/actions_tasks3/case_90_context_image.js
Testing #3416 
```python
#
```
=> Cypress test. Update case 90 for check issue "Context image disappears after undo/redo".

tests/cypress/integration/actions_tasks/case_72_hotkeys_change_labels.js
Adding a check "Attribute keeping when changing label" feature.
```python
#
```
=> Cypress. Update case72. Adding a check "Attribute keeping when changing label" feature.

tests/cypress/integration/actions_objects2/case_16_z_order_features.js
In CI nightly, the unsuccessful completion of the case 16 test. It is reproduced in Firefox browser in headless mode.
In the test, the shape is activated by pointing the cursor at it (mouse events). One of the steps of the shape activation test:
Activation is not performed.
In this patch, I just changed the activation method via sidebar item.
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui# …
=> Cypress. Fix case "Actions on polygon" for Firefox.

cvat-ui/src/components/create-task-page/project-subset-field.tsx, tests/cypress/integration/actions_projects_models/registration_involved/base_actions_project_task_user.js, tests/cypress/support/commands.js
Increasing code coverage.
```python
#
```
=> Cypress test. Adding a subset when creating a task from a project.

tests/cypress/integration/actions_projects_models/case_94_move_task_between_projects.js
Checking the scenario corrected in #3475 
```python
#
```
=> Cypress test. Activating the test scenario for check "Move a task between projects".

tests/cypress/integration/actions_objects2/case_10_polygon_shape_track_label_points.js, tests/cypress/integration/actions_objects2/case_11_polylines_shape_track_label_points.js, tests/cypress/integration/actions_objects2/case_12_points_shape_track_label.js, tests/cypress/support/commands.js
Updating tests for drawing points, polygons, and polylines. Added the use of the "Done" button when drawing shapes.
PR #3417 
```python
#
```
=> Update Cypress tests. Added the use of the "Done" button.

CHANGELOG.md, site/content/en/docs/manual/advanced/cli.md, utils/cli/core/definition.py
Fixed #3494
Feel free to contact the maintainers …
=> Fixed task creating CLI parameter

components/analytics/logstash/logstash.conf
This is a fix for this https://github.com/openvinotoolkit/cvat/pull/2531 PR
Now logs from logstash will be distributed across multiple indexes according to current year and month. This is done for better flexibility and index management.
It was tested manually …
=> Logstash PR fix

tests/cypress/integration/actions_objects2/case_14_appearance_features.js, tests/cypress/integration/actions_tasks2/case_101_opencv_basic_actions.js
Cypress test for "Selected opacity" slider now defines opacity level of shapes being drawn. PR #3473 
```python
#
```
=> Cypress test. Update case 14. "Selected opacity" level of shapes being drawn.

CHANGELOG.md, utils/cli/core/core.py, utils/cli/core/definition.py
When importing data into CVAT from the share mount the user can uncheck `copy_data` and check `use_cache` to avoid creating multiple copies of the data on the server, this functionality wasn't available in the cli.  So I added it.  It was previously proposed in #2862 and is under the backlog of the project planning as work to be completed [here](https://github.com/openvinotoolkit/cvat/projects/20)
When a user downloads images to their CVAT server, then imports into the CVAT application, it is not memory efficient to make 3 copies of the image (raw, original, and compressed) - this functionality allows the user to disable creating these copies.
I imported images with the code changes and verified that by default it does not cause the images to be duplicated and the hard drive space does …
=> Add arguments to cli to disabling copying image data in share

tests/cypress/integration/actions_projects_models/case_104_project_export_3d.js
Added a Cypress test to cover the feature.
```python
#
```
=> Cypress test. Export project with 3d task.

tests/cypress/integration/actions_tasks2/case_101_opencv_basic_actions.js
Update Cypress test to check "Intelligent scissors blocking feature". PR #3510 
```python
#
```
=> Update Cypress test to cover "Intelligent scissors blocking feature".

tests/cypress/integration/actions_tasks2/case_101_opencv_basic_actions.js
Fixing the test fail in Firefox browser.
https://github.com/openvinotoolkit/cvat/actions/runs/1148654935
```python
#
```
=> Cypress. Fix case "OpenCV. Intelligent scissors. Histogram Equalization" for Firefox.

site/layouts/partials/head.html
This PR updates jQuery on the site. To do this, the `head.html` template moved to the repository and replaced the link to jQuery (line 26)
```python
#
```
=> Update jQuery on website

cvat-ui/webpack.config.js
Sometimes need to setup dev environment somewhere else then ``localhost``.
With this PR you can do it with for example: ``CVAT_UI_HOST='192.168.0.111' npm start``
```python
#
```
=> Added ability to setup UI host in dev environment

cvat/apps/dataset_manager/bindings.py
In #3612 it was noticed that 3D formats do not support images with dots in the name, this leads to a fall in the unit test.
```python
#
```
=> Small fix. Allow dots in image name for 3D formats

site/content/en/docs/administration/advanced/installation_automatic_annotation.md
This PR enhances documentation for running serverless functions with GPU support under WSL docker setup. The necessity of this first appeared in testing PR #3571.
No tests. …
=> Added documentation for GPU support in WSL

cvat/apps/dataset_manager/annotation.py
The function `get_intepolated_shapes` saves all interpolated shapes for each track. And they can take up a lot of RAM.
At the same time, cached shapes are not used anywhere.
Therefore, they can be removed without consequences.
Fixed #3456.
- ~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning), …
=> Remove save interpolated shapes

tests/cypress/integration/actions_tasks/issue_2473_import_annotations_frames_dots_in_name.js
Fix of the test by analogy with the fix made during the migration to the new version of Cypress.
https://github.com/openvinotoolkit/cvat/pull/3372/checks?check_run_id=3619560749
```python
#
```
=> Cypress. Fix test for issue 2473.

tests/cypress/integration/canvas3d_functionality/case_85_canvas3d_functionality_cuboid_cancel_drawing.js
One of the files with tests was named in the wrong encoding causing some internal automation to fail
This was checked with the custom job on top of develop branch, however the fix is quite trivial to be seamlessly cherry-picked to any of branches.
Feel …
=> Rename file in the wrong encoding

cvat/apps/dataset_manager/tests/test_rest_api_formats.py
Without the comma, the string literals are joined together, so only one test case is run instead of two.
N/A
- ~~[ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning), …
=> Add a missing comma

tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
The test failed on https://github.com/openvinotoolkit/cvat/pull/3690/checks?check_run_id=3638617102
The work was checked in the form of multiple launches in CI. The error is not reproduced. …
=> Cypress. Fix case 28. Adding additional element visibility checks.

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/download.worker.js, cvat-core/src/server-proxy.js
Resolve #3719 
Manually
```python
#
```
=> Fix problem with getting cloud storages in Firefox

tests/cypress/integration/actions_tasks/case_52_dump_upload_annotation.js
Need to adjust upload annotation test to it covers the issues appeared after migration to the new antd.
Test behavior before/after fixing the issue:
```python
#
```
=> Fixed upload test

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/task-page/job-list.tsx
Works incorrect. ``Job #2 : /?id=2`` is not a link to job anymore, baseURL now empty because of using proxy. 
After fix:
```Job #2 : http://localhost:3000/tasks/2/jobs/2: [0-2166]```
Manual …
=> Fixed copy job list feature

tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
The test crashes from time to time.
With these changes, I conducted restarts in my fork, the problem was not reproduced.
```python
#
```
=> Cypress. Fix case 28.

CHANGELOG.md, site/content/en/docs/contributing/development-environment.md
This change adds a note about manually starting the redis server inside wsl. This is necessary because installing the redis-server package does not start it when systemd is not available.
Multiple people ran into this problem and reported it on gitter.  Also it's not obvious that you have to start it manually.
Manually
~~- [ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canva …
=> Add note about redis server in wsl

tests/cypress/integration/canvas3d_functionality_2/case_56_canvas3d_functionality_basic_actions.js
The main reason is the point cloud. Most likely, in some cases, the animation of changing the position of the point cloud had time to finish before checking the wheel. In this case, an error is issued that the images are not different.
At the moment, this functionality is disabled. …
=> Cypress. Case 56. Moved wheel check on perspective view to different test and skipping it.

cvat/apps/engine/backup.py
Resolved #3926
```python
#
```
=> Fixed issue: rotation property is not dumped when backup a task

README.md
Adds the integration between [FiftyOne](https://fiftyone.ai) and CVAT to the Partners section of the README.
```python
#
```
=> Add FiftyOne to partners list

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/autoborderHandler.ts
=> Fixed issue: autoborder points are visible for invisible shapes

CHANGELOG.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/scss/canvas.scss, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/settings-actions.ts, cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx, cvat-ui/src/components/header/settings-modal/player-settings.tsx, cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx, cvat-ui/src/containers/header/settings-modal/player-settings.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/settings-reducer.ts
Added switcher
**Smoothed:**
**Pixelized:**
Customer request
```python
#
```
=> Added smooth image option
