cvat-ai/cvat

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-details.tsx
resolve #2952 
Manually
```python
#
```
=> Preserve the order of the label attributes in the object item details.

site/content/en/docs/administration/basics/installation.md
Resolve #3868
This PR update `Installation Guide`
Preview: https://tosmanov.github.io/cvat/docs/administration/basics/installation/#sources-for-users-from-china
```python
#
```
=> Update documentation for China users

cvat-core/src/cloud-storage.js, cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx, cvat-ui/src/components/create-cloud-storage-page/styles.scss, cvat/apps/engine/serializers.py
https://github.com/openvinotoolkit/cvat/pull/3919#discussion_r757457678
Manually
~~- [ ] …
=> Remove key_file_path field

tests/cypress/integration/actions_objects2/case_108_rotated_bounding_boxes.js
Related to #3832 
Adding a test to test functionality "Rotated bounding boxes"
```python
#
```
=> Cypress. Test "Rotated bounding boxes"

tests/cypress/integration/actions_objects2/case_108_rotated_bounding_boxes.js
Related #3961
I slightly reworked the test due to the fact that in Firefox the shape does not have the css ```transform``` property.
A solution of the form 
```
const shapeAttrs = shape2.attr('transform').split('(')[1].split(')')[0].split(',');
```
it looks ugly.
Found a solution using ```getCTM()```.
CI for check: https://github.com/dvkruchinin/cvat/runs/4394611968?check_suite_focus=true …
=> Cypress. Fix case 108 for Firefox.

tests/cypress/integration/actions_tasks3/case_105_cloud_storage.js
Related:
#3919 
#3959 
Adding a test to check "Google cloud storage" provider fields.
```python
#
```
=> Cypress. Update case 105. Add check "Google cloud storage" provider fields.

CHANGELOG.md, cvat/apps/lambda_manager/views.py
resolves #3358 
I have a full-frame classifier nuclio lambda and needed a way to save these tags.
* I ran the code in development using `docker-compose -f docker-compose.yml -f components/serverless/docker-compose.serverless.yml up -d`
* Invoke my nuclio classifier from the task summary page (full video) and from the annotator (single frame)
* See new tags appear in the UI.
I did see that the author of #3358 has included confidence values, which I do not believe are supported by tags. If I should support this somewhere, please LMK.
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~ I do not see any documentation about what response types are supported for nuclio functions, so I don't think there's any documentation to update.  New documentation could be …
=> Support automatic tag annotation

tests/cypress/integration/actions_objects/case_60_autoborder_feature.js
Related: #3931 
Adding a check for "Autoborder points are visible for invisible shapes"
```python
#
```
=> Cypress. Update case 60 for check fix "Autoborder points are visible for invisible shapes"

tests/cypress/integration/actions_tasks2/case_97_export_import_task.js
Related: #3932 
The test has been redesigned to test the functionality of preserving the rotation of the rectangle after importing the task.
```python
#
```
=> Cypress. Update case 97 for check "Fixed issue: rotation property is not dumped when backup a task"

CHANGELOG.md, cvat/apps/engine/serializers.py, cvat/apps/engine/views.py
External bug report
No tests, due to no issue reproduction on development setup. …
=> Fixed labels order

CHANGELOG.md, site/content/en/docs/administration/basics/installation.md
Resolves #4013 
The installation guide should mention about exporting CVAT_HOST variable so that CVAT can be access over the network. The current installation method only supports accessing CVAT using http://localhost:8080. This information about exporting CVAT_HOST variable can be derived from AWS-Deployment Guide
[source here](https://github.com/openvinotoolkit/cvat/blob/develop/site/content/en/docs/administration/basics/AWS-Deployment-Guide.md)
[actual here](https://openvinotoolkit.github.io/cvat/docs/administration/basics/aws-deployment-guide/)
This is document level change, therefore the markdown has been checked for sanity.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-req …
=> Updated installation.md with respect to information about CVAT_HOST for local installation

tests/cypress/integration/actions_tasks/case_110_settings_smooth_image_option.js
Related on #3933 
Check added option "Smooth image"  by checking the appearance of class ```cvat_canvas_pixelized``` to element ```cvat_canvas_background``` when the option is disabled.
```python …
```
=> Cypress. Adding test to check "Smooth image" option.

cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts
Changing font size does not work in Firefox
```python
#
```
=> Fixed font-size in firefox

cvat-ui/src/components/header/settings-modal/workspace-settings.tsx, tests/cypress/integration/actions_objects/case_36_always_show_object_details_feature.js, tests/cypress/integration/actions_tasks2/case_111_settings_text_size_position.js
Related on: #3972 
Adding a test to check the change in the size of the text and its position when changing the corresponding settings.
```python
#
```
=> Cypress. Test for "Switch text font size and position".

tests/cypress/integration/actions_tasks3/case_1_create_delete_task_label_color.js
Related on #4007 
Updating the test to check for label color collisions.
I wrote a small script to identify color collisions of labels with different names.
```python
from cvat.apps.dataset_manager.formats.utils import get_label_color
import itertools
label_color = {}
dublicates = {}
lst = [''.join(x) for x in itertools.product('abcdifg', repeat=4)]
for i in lst:
label_color[i] = get_label_color(i, label_color.keys())
for key, value in label_color.items():
dublicates.setdefault(value, set()).add(key)
dubl = [values for key, values in dublicates.items() if len(values) > 1]
print(dubl)
```
As a result , I got the names of the labels:
```adaf``` and ```adia```
Which had the same color before the fix ```rgb(50, 182, 148)```.
Based on these data, the test has been redesigned. …
=> Cypress. Update case_1. Added check label color.

CHANGELOG.md, cvat-ui/src/components/file-manager/file-manager.tsx, cvat/apps/engine/task.py, cvat/apps/engine/views.py, utils/dataset_manifest/__init__.py, utils/dataset_manifest/core.py
Resolve #3968 
- Added support for uploading a manifest with any name
- Added manifest structure validation
Manually …
=> Support any name for a manifest

CHANGELOG.md, cvat-core/src/server-proxy.js, cvat-ui/src/actions/tasks-actions.ts
In recent patches `onUpdate` cvat-ui status callback signature was changed. Tus client upload used old signature that led to bug in progress bar:
Manual testing
- ~~I have updated the [documentation](
- ~~I have added tests to cover my changes~~
- ~~I have linked related issues ([read github docs]( …
=> Fix task data upload progress bar

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/top-bar/statistics-modal.tsx, cvat-ui/src/reducers/organizations-reducer.ts
Resolved #4140 
Manual testing
```python
#
```
=> Fixed statistics modal when the job is assigned to someone

cvat/apps/engine/cache.py
Issue Summary: File downloaded from cloud storage is not flushed. In case of lot of files, for some files, changes don't reflect in the actual physical file. Actual file is later accessed by filename, which leads to read error.
Issue Error logs:
```
2022-01-05 09:54:14,992 DEBG 'runserver' stderr output:
[Wed Jan 05 09:54:14.992125 2022] [wsgi:error] [pid 330:tid 139683931096832] [remote 172.20.0.2:56868] [2022-01-05 09:54:14,991] ERROR cvat.server.task_12: cannot get requested data type: chunk, number: 0, quality: Quality.COMPRESSED
[Wed Jan 05 09:54:14.992147 2022] [wsgi:error] [pid 330:tid 139683931096832] [remote 172.20.0.2:56868] Traceback (most recent call last):
[Wed Jan 05 09:54:14.992152 2022] [wsgi:error] [pid 330:tid 139683931096832] [remote 172.20.0.2:56868]   File …
```
=> BUG FIX: Fixed temp_file flush issue for cloud storage in cache.py

CHANGELOG.md, cvat/apps/organizations/serializers.py
Fixed https://github.com/openvinotoolkit/cvat/issues/4096
Manually. Tests will be covered by the PR: https://github.com/openvinotoolkit/cvat/pull/4143
- [-] I have updated the [documentation](
- [-] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning),
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#v …
=> Email in org invitations should be case insensitive

CHANGELOG.md, README.md, serverless/pytorch/ultralytics/yolov5/nuclio/function.yaml, serverless/pytorch/ultralytics/yolov5/nuclio/main.py
Integration of YOLOv5 as a serverless nuclio function that can be used for auto-labeling. Ultralytics has released YOLOv5 a while ago and it's one of the most used computer vision libraries and therefore it would make sense to support it in CVAT. The integration is quite simple into CVAT as Ultralytics maintains a Pytorch Hub model (https://github.com/ultralytics/yolov5/issues/36) and a docker image (https://hub.docker.com/r/ultralytics/yolov5).
Related issues from ultralytics repo: https://github.com/ultralytics/yolov5/issues/5427
Automatic annotation was run using YOLOv5 on a custom dataset.
The serverless function was deployed using 
```
nuctl deploy --project-name cvat \
--path serverless/pytorch/ultralytics/yolov5/nuclio \
--volume `pwd`/serverless/common:/opt/nuclio/common \ …
```
=> Added YOLOv5 serverless function for auto labeling

CHANGELOG.md, cvat-canvas/README.md, cvat-canvas/package-lock.json, cvat-canvas/package.json, cvat-canvas/src/scss/canvas.scss, cvat-canvas/src/typescript/canvas.ts, cvat-canvas/src/typescript/canvasController.ts, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/canvas-context-menu.tsx, cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/review-workspace/controls-side-bar/issue-control.tsx, cvat-ui/src/components/annotation-page/review/create-issue-dialog.tsx, cvat-ui/src/components/annotation-page/review/hidden-issue-label.tsx, cvat-ui/src/components/annotation-page/review/issue-dialog.tsx, cvat-ui/src/components/annotation-page/review/issues-aggregator.tsx, cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx, cvat-ui/src/reducers/review-reducer.ts, cvat-ui/src/utils/math.ts
Resolved #3975 
```python
#
```
=> Fixed: Issues disappear when using a zoom

cvat/apps/iam/rules/projects.rego
All in organization could see the list of projects due to incorrent `filter` definition in the rules (it cannot be covered by opa tests and Django tests are not here yet).
Manually
<del> - [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file </del>
<del> - [ ] I have updated the [documentation](
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly </del>
<del> - [ ] I have added tests to cover my changes </del>
<del> - [ ] I have linked related issues ([read github docs](
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) </del>
<del> - [ ] I have increased versions of npm packages if it is …
=> Fix project permissions: anybody in org could see the list of projects

cvat/apps/engine/views.py, cvat/apps/iam/filters.py, cvat/apps/iam/views.py, cvat/apps/lambda_manager/views.py, cvat/apps/organizations/views.py, cvat/apps/restrictions/views.py
There 3 modes for IAM:
1. `org=slug` only corresponding objects for the organization are visible
2. `org=` only objects outside an organization are visible
3. `None` all own or assigned objects are visible (admin can see all objects)
Manually
<del> - [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file </del>
<del> - [ ] I have updated the [documentation](
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly </del>
<del> - [ ] I have added tests to cover my changes </del>
<del> - [ ] I have linked related issues ([read github docs](
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)) </del> …
=> Filtering for sandbox

tests/cypress/integration/actions_objects2/case_115_ellipse_shape_track_label.js, tests/cypress/support/commands.js
Related on #4229 
Activation of the text occurrence check when the ellipse rotates.
```python
#
```
=> Cypress. Enabled check text with an ellipse rotation.

site/content/en/docs/manual/advanced/cli.md
Resolve #4244 
```python
#
```
=> Update documentation. Fix mistakes in CLI section

CHANGELOG.md, cvat-core/package-lock.json, cvat-core/package.json, cvat-core/src/api-implementation.js, cvat-core/src/frames.js, cvat-core/src/server-proxy.js, cvat-core/src/session.js, cvat-core/tests/mocks/server-proxy.mock.js, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/jobs-actions.ts, cvat-ui/src/base.scss, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/components/header/styles.scss, cvat-ui/src/components/jobs-page/job-card.tsx, cvat-ui/src/components/jobs-page/jobs-content.tsx, cvat-ui/src/components/jobs-page/jobs-page.tsx, cvat-ui/src/components/jobs-page/styles.scss, cvat-ui/src/components/jobs-page/top-bar.tsx, cvat-ui/src/reducers/interfaces.ts, cvat-ui/src/reducers/jobs-reducer.ts, cvat-ui/src/reducers/notifications-reducer.ts, cvat-ui/src/reducers/root-reducer.ts, cvat/apps/engine/views.py
With IAM integration users don't see the tasks with jobs assigned to them anymore, so, dedicated page with a list of job is necessary for annotators. 
```python
#
```
=> Added a page with jobs

CHANGELOG.md, Dockerfile, cvat/apps/engine/backup.py, cvat/apps/engine/views.py, cvat/apps/opencv/views.py, cvat/requirements/base.txt, cvat/settings/base.py, cvat/settings/development.py, cvat/settings/production.py, tests/cypress/support/commands_projects.js
CVAT image build takes too long time, i.e. https://github.com/openvinotoolkit/cvat/runs/5004804799?check_suite_focus=true
Probably related with https://github.com/pypa/pip/issues/10557
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versionin …
=> Bump pip from 21.0.1 to 22.0.2, setuptools from 53.0.0 to 60.6.0, wheel from 0.36.2 to 0.37.1

tests/cypress/support/commands.js
Because of updated REST API scheme one of recently merged tests does not work as expected
```python
#
```
=> Fix URL scheme in cypress tests related with removing labels

cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/components/login-page/login-page.tsx, cvat-ui/src/consts.ts
Keep referrer for openvino link
Go to the link, open devtool, check `document.referrer` value
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~ …
=> Changed openvino link, kept referer

CHANGELOG.md, cvat-ui/package-lock.json, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/annotation-page/styles.scss, cvat-ui/src/components/jobs-page/styles.scss, cvat-ui/src/components/jobs-page/top-bar.tsx, cvat-ui/src/components/project-page/styles.scss, cvat-ui/src/components/project-page/top-bar.tsx, cvat-ui/src/components/task-page/styles.scss, cvat-ui/src/components/task-page/top-bar.tsx, cvat-ui/src/components/task-page/user-selector.tsx, cvat-ui/src/components/tasks-page/styles.scss, cvat-ui/src/components/tasks-page/task-item.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx
Manual testing
```python
#
```
=> Coninue from frame N, advanced user selector on jobs page

CHANGELOG.md, cvat/apps/engine/views.py
=> Fix content type

cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/annotation-page/styles.scss, tests/cypress/integration/actions_tasks/continue_frame_n.js
=> Added cypress tests for the feature: 'continue frame n'

cvat/apps/engine/serializers.py
In the api document, the 'dimension' attribute of the /api/projects endpoint (post,patch) should be marked as "readOnly: true" or excluded in the request body schema section. #4367 
```python
# …
```
=> Fix the dimension field on ProjectSerializer to read_only

CHANGELOG.md, cvat/apps/engine/task.py, cvat/requirements/base.txt
=> Added validation for URLs which used as remote data source

cvat/apps/engine/views.py, cvat/apps/iam/permissions.py, tests/rest_api/test_organizations.py, tests/rest_api/utils/config.py
Now some requests with OPTIONS method to a REST API endpoint lead to an exception. For example, OPTIONS https://cvat.org/api/organizations -> 500 (Server Error). Others to permissions denied. 
Added a test into tests/rest_api
```python
#
```
=> Fix OPTIONS request to REST API methods

cvat-ui/src/containers/annotation-page/standard-workspace/controls-side-bar/setup-tag-popover.tsx
Resolved #4503 
```python
#
```
=> Fixed bug: Draw new label/tag by shortcut after annotate a tag blocks "Rectangle" selection button in side-bar

CHANGELOG.md, cvat/requirements/base.txt
This change fixes a dependency conflict that causes a very old version
of Jinja2 to be installed (see #4618). Open3D is only used for PCD
conversion, so this reverting to an older version is acceptable.
This is a temporary workaround. As a future update we'd like to get rid
of the Open3D dependency, since it pulls in a bunch of unnecessary
dependencies. Also, we'd like to make python dependency resolution more
robust by pinning all (recursive) dependencies to specific versions with
a tool like pip-tools or poetry.
Fixes #4618. 
Not tested yet. Will rely on CI to test. 
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-ke …
=> Revert Open3D to 0.11.2

cvat/apps/lambda_manager/views.py
* Enable detector type auto-annotators to annotate the group_id of a shape.
```python
#
```
=> fix auto-annotation group_id issue (#3676)

.github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/schedule.yml, site/content/en/docs/contributing/running-tests.md
Recently cvat server container has changed name from `cvat` to `cvat_server`.
Mostly such change has been applied in original PR, but in some workflow configurations this changes has not been applied, this PR fix it.  …
=> Hotfix: fix container name

docker-compose.https.yml
`cvat` service in `docker-compose.https.yml` has become `cvat_server`
I tried to build with ` docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.https.yml -f components/analytics/docker-compose.analytics.yml build` but got the following message:
```
ERROR: The Compose file is invalid because:
Service cvat has neither an image nor a build context specified. At least one must be provided.
```
Tested with the above command following the proposed changes and it successfully built. …
=> Fix docker-compose.https.yml service names

CHANGELOG.md, cvat-core/package.json, cvat-core/src/api-implementation.ts
=> Fixed project filtration

README.md, cvat-ui/README.md, cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx, cvat-ui/src/consts.ts, cvat/settings/base.py, utils/README.md
Since the migration to the opencv org, github pages links have been broken. This is a very small PR to help update links to the newer org.
See issue [4873](https://github.com/opencv/cvat/issues/4873) for reference …
=> [WIP] Fix github pages base URL

cvat-canvas/package.json, cvat-canvas/src/scss/canvas.scss, cvat-canvas/src/typescript/canvasView.ts, cvat-core/package.json, cvat-core/src/annotations-collection.ts, cvat-core/src/annotations-objects.ts, cvat-core/src/annotations-saver.ts
=> Some fixes for skeleton patch related with merge & delete, undo/redo

.github/workflows/main.yml, docker-compose.yml, utils/update_version/update_version.py
Added update_version.py script
`latest` tag is used for the latest build from the develop branch instead of `dev`.
resolve #4816  …
=> Initial version of update_version.py script to bump CVAT version

CHANGELOG.md, cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx, cvat/apps/engine/models.py, cvat/apps/engine/serializers.py
Currently, CVAT only does not support Oracle OCI Buckets because of the lenght limit of the access and secret keys, as discussed in https://github.com/opencv/cvat/issues/4783. This simple PR increases the limit of the access and secret keys to the current lenghts of the Oracle OCI keys.
Closes https://github.com/opencv/cvat/issues/4783.
Related: https://github.com/opencv/cvat/issues/4582, https://github.com/opencv/cvat/pull/4584.
I updated the CVAT locally and checked that I could successfully add and use Oracle OCI Buckets. We have been using Oracle OCI Buckets in CVAT for weeks now.
- ~I have added tests to cover my changes~
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-reque …
=> Add support for Oracle OCI Buckets

cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, tests/cypress/integration/skeletons_pipeline.js
=> Fixed redrawing a skeleton (Shift+N)

cvat-cli/requirements/base.txt, cvat-cli/src/cvat_cli/version.py, cvat-sdk/.gitignore, cvat-sdk/MANIFEST.in, cvat-sdk/gen/generate.sh, cvat-sdk/gen/templates/MANIFEST.in, cvat/settings/base.py, tests/python/requirements.txt
- Fixed SDK package build problem with missing requirements file
- Removed generated MANIFEST.in file from SDK sources
- Aligned server API, SDK and CLI versions to 2.1.0
=> Align server api, sdk and cli versions to 2.1.0

CHANGELOG.md, cvat-cli/README.md, cvat-cli/src/cvat_cli/cli.py, cvat-cli/src/cvat_cli/parser.py, cvat-sdk/cvat_sdk/core/client.py, cvat-sdk/cvat_sdk/core/downloading.py, cvat-sdk/cvat_sdk/core/exceptions.py, cvat-sdk/cvat_sdk/core/git.py, cvat-sdk/cvat_sdk/core/proxies/jobs.py, cvat-sdk/cvat_sdk/core/proxies/model_proxy.py, cvat-sdk/cvat_sdk/core/uploading.py, cvat-sdk/cvat_sdk/exceptions.py, site/content/en/docs/manual/advanced/cli.md, tests/python/sdk/fixtures.py, tests/python/sdk/test_client.py
This PR simplifies usage of SDK/CLI in simple cases, when CVAT is deployed with default parameters. Now, we don't need to specify schema or port in these cases.
- Added schema autodetection in SDK
- SDK uses default http (80) and https (443) ports for connections
- Removed the `--https` CLI arg
Unit tests …
=> Add host schema auto-detection in SDK

CHANGELOG.md, README.md, site/content/en/docs/manual/advanced/formats/format-coco.md
=> Update COCO documentation

cvat-canvas/package.json, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/editHandler.ts, cvat-canvas/src/typescript/groupHandler.ts, cvat-canvas/src/typescript/mergeHandler.ts, cvat-canvas/src/typescript/splitHandler.ts
some private fields of classes used in cvat-canvas are type-declared as non-null, whereas they are actually assigned the null value.
=> fix type declaration of private fields in cvat-canvas which are possibly null

CHANGELOG.md, cvat/__init__.py, docker-compose.yml
- Added ability to delete frames from a job based on (<https://github.com/openvinotoolkit/cvat/pull/4194>)
- Support of attributes returned by serverless functions based on (<https://github.com/openvinotoolkit/cvat/pull/4506>)
- Project/task backups uploading via chunk uploads
- Fixed UX bug when jobs pagination is reset after changing a job
- Progressbars in CLI for file uploading and downloading
- `utils/cli` changed to `cvat-cli` package
- Support custom file name for backup
- Possibility to display tags on frame
- Support source and target storages (server part)
- Tests for import/export annotation, dataset, backup from/to cloud storage
- Added Python SDK package (`cvat-sdk`) (<https://github.com/opencv/cvat/pull/4813>)
- Previews for jobs
- Documentation for LDAP authentication …
=> Release v2.2.0

CHANGELOG.md, cvat-core/src/server-proxy.ts
FIX: Remove possibly duplicated encodeURI() to prevent double encode non-ascii path (Issue #4428 Cannot connect file share，cannot recognize non-ascii path)
Resolved #4428
When you create a task and trying to select files from "Connected file share",
you get multiple "Could not load share data from the server" error popups
if you try to expand a directory named in non-ascii code.
Following documentation https://opencv.github.io/cvat/docs/administration/basics/installation/#share-path,
setup a share path for CVAT, which contains (sub)directory encoded in non ascii code.
- Create a project and task, and then "Connected file share" tab under Select files section.
- Click/expand directories until you encounter the non-ascii named directory.
- Expand the non-ascii named directory and see that …
=> FIX: Remove a possibly duplicated encodeURI() (Issue #4428)

cvat-ui/src/components/create-project-page/create-project-content.tsx, cvat-ui/src/components/create-task-page/create-task-content.tsx, cvat-ui/src/styles.scss
Currently advanced configuration on `/projects/create` and `/tasks/create` looks a bit odd.
Changed to:
=> Fixed advanced configuration header styles

components/analytics/docker-compose.analytics.yml
Tag for cvat/server in compose file for analytics differ from tag for cvat/server in docker-compose.yml file. I haven't seen any errors related to this issue, but I've noticed that when I run CVAT with analytics, I pull cvat/server twice.
This PR makes the tags the same
https://github.com/cvat-ai/cvat/blob/develop/LICENSE) …
=> Fix tag for analytics compose file

CHANGELOG.md, cvat/apps/dataset_manager/task.py, tests/python/rest_api/test_tasks.py
- Fixed #4985, #4990 
Added REST API test
=> Fix project export with skeletons

CHANGELOG.md, tests/cypress/integration/actions_tasks2/case_97_export_import_task.js, tests/cypress/support/commands_projects.js
Resolved #4995
The problem with restore tests arises when network runs slow, which can happen from time to time. After backup was uploaded tests were checking for restoring status. If its in progress, server returned `202`, if it ended server returned `201`. When network is fast enough `202` is returned, and if its slow, backup restore is ended already which leads to `201` response. Hence we need to make waiting for `202` response optional. …
=> Fixed unstable e2e restore tests

.github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/schedule.yml
PR resolves reason of [failed CI nightly](https://github.com/opencv/cvat/actions/runs/3161953098).
=> Workflows: update value of status for `waiting server` step

tests/python/requirements.txt
It doesn't make sense for this entry to be there:
* If `cvat-sdk` is not already installed by the time you run `pip install -r tests/python/requirements.txt`, this entry will install the latest release, which will not match the tests.
* If it is, then this entry will do nothing.
I created a new development venv and made sure the tests ran.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an …
=> Remove `cvat-sdk` from `tests/python/requirements.txt`

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/labels-editor/constructor-viewer-item.tsx, cvat-ui/src/components/labels-editor/styles.scss
Related #5031 
**Before:**
**After:**
=> Fixed invisible label view in label constructor

tests/cypress/integration/actions_tasks3/case_107_connected_file_share.js
https://github.com/opencv/cvat/pull/5058#issuecomment-1275763837
- ~[ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file~
- ~[ ] I have updated the [documentation](
https://github.com/cvat-ai/cvat/blob/develop/README.md#documentation) accordingly~
- ~[ ] I have added tests to cover my changes~
- ~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning), …
=> Fix Cypress tests after b029bc9d

serverless/pytorch/ultralytics/yolov5/nuclio/function-gpu.yaml
Fixes #4851
This change enables leveraging an NVIDIA GPU when using a YOLOv5 serverless function.
This change speeds up auto labeling with a YOLOv5 model.
Deploying the script using `deploy_gpu.sh` and checking if it uses the NVIDIA GPU with NVIDIA-SMI while auto-labeling.
https://github.com/cvat-ai/cvat/blob/develop/LICENSE) …
=> add yolov5 serverless function leveraging nvidia gpu

CHANGELOG.md, cvat/apps/engine/views.py
=> Fixed issue with deleted frames in a multijob task

.github/workflows/main.yml, cvat/settings/base.py, tests/python/cli/test_cli.py, tests/python/rest_api/test_analytics.py, tests/python/rest_api/test_auth.py, tests/python/rest_api/test_check_objects_integrity.py, tests/python/rest_api/test_cloud_storages.py, tests/python/rest_api/test_invitations.py, tests/python/rest_api/test_issues.py, tests/python/rest_api/test_jobs.py, tests/python/rest_api/test_memberships.py, tests/python/rest_api/test_organizations.py, tests/python/rest_api/test_projects.py, tests/python/rest_api/test_remote_url.py, tests/python/rest_api/test_resource_import_export.py, tests/python/rest_api/test_server.py, tests/python/rest_api/test_tasks.py, tests/python/rest_api/test_users.py, tests/python/rest_api/test_webhooks.py, tests/python/rest_api/test_webhooks_sender.py, tests/python/sdk/fixtures.py, tests/python/sdk/test_client.py, tests/python/sdk/test_issues_comments.py, tests/python/sdk/test_jobs.py, tests/python/sdk/test_tasks.py, tests/python/sdk/test_users.py, tests/python/shared/fixtures/init.py
Recently we used workaround with increasing throttle rate to make our tests green.
This PR resolve root cause of the "throttle error" problem in our tests
=> Fix SDK tests: login once per class

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/states-ordering-selector.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/index.ts
Resolved #5142
Resolved #2180
Related #3942
- Fixed issue when changing an object causes changing of the current z layer
- Added sorting by z order
- If the sorting is applied, additional indication added to the sidebar …
=> Minor improvements of z order feature

site/content/en/docs/manual/advanced/shortcuts.md, site/content/en/docs/manual/basics/workspace.md
=> Updated docs about some of shortcuts

CHANGELOG.md, cvat-ui/src/actions/projects-actions.ts, cvat-ui/src/actions/tasks-actions.ts, cvat-ui/src/containers/task-page/task-page.tsx, cvat-ui/src/reducers/tasks-reducer.ts
=> Fixed error: could not fetch task in a corner case

CHANGELOG.md, cvat-ui/src/components/resource-sorting-filtering/filtering.tsx, cvat-ui/src/components/resource-sorting-filtering/sorting.tsx
=> No extra rerender of different pages with each click

.dockerignore, .github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/schedule.yml, .vscode/launch.json, Dockerfile, cvat/apps/iam/apps.py, cvat/apps/iam/utils.py, cvat/apps/iam/views.py, cvat/settings/base.py, docker-compose.dev.yml, docker-compose.yml, helm-chart/Chart.yaml, helm-chart/templates/cvat_backend/server/deployment.yml, site/content/en/docs/contributing/development-environment.md
=> /api/auth/rules endpoint implementation improvements

CHANGELOG.md, cvat-core/package.json, cvat-core/src/server-proxy.ts
=> Fixed issue: cannot assign a resource to a user who has an organization

cvat-sdk/cvat_sdk/core/helpers.py, cvat-sdk/cvat_sdk/core/uploading.py
tqdm does not necessarily redraw the progress bar after every update, and without the call to `close` it might not update it to the final state.
I discovered this while writing a test in which the progress bar is updated in chunks, and the last chunk is smaller than the previous ones.
Indirectly through the test I'm about to add to #5204. …
=> cvat-sdk: make sure to redraw the progress bar after use

cvat-data/src/ts/cvat-data.ts, cvat-data/tsconfig.json
By converting it into an ES6 module.  Also, fix `tsconfig.json` so that ESLint knows that the file is actually in the project.
I checked that viewing frames in the UI still works. …
=> Fix ESLint errors in `cvat-data.ts`

CHANGELOG.md, cvat-sdk/cvat_sdk/core/uploading.py, mod_wsgi.conf, tests/python/sdk/test_tasks.py
Previously, `mod_wsgi` would convert `HEAD` requests into `GET`, which would be rejected, so clients were unable to resume an upload that failed midway through.
To make use of this, update the SDK code to enable upload resumption.
Fixes #4839.
SDK unit tests. For the old server workaround, I manually disabled the fix and checked that the tests still pass. …
=> Fix TUS offset queries in production environments

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/components/logout-component.tsx, cvat-ui/src/utils/redux.ts, tests/cypress/integration/actions_users/issue_1810_login_logout.js
Resolved #5265
Implemented by logging out via a component which saves logs
Also the component has dedicated URL ``/auth/logout`` and when a user goes there, the browser suggests to save unsaved changes on annotation view.  …
=> Improved UX of user logout

CHANGELOG.md, cvat-core/src/enums.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss, cvat-ui/src/components/annotation-page/canvas/brush-tools.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/labels-list.tsx, cvat-ui/src/components/annotation-page/standard3D-workspace/controls-side-bar/controls-side-bar.tsx, cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/shortcuts-select.tsx, cvat-ui/src/components/annotation-page/tag-annotation-workspace/tag-annotation-sidebar/tag-annotation-sidebar.tsx, cvat-ui/src/components/labels-editor/label-form.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx, cvat-ui/src/cvat-core-wrapper.ts, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/index.ts, cvat-ui/src/utils/filter-applicable-labels.ts, cvat/apps/engine/serializers.py, tests/cypress/integration/actions_tasks/case_72_hotkeys_change_labels.js
=> Supported type for all labels

CHANGELOG.md, cvat/apps/engine/models.py, cvat/apps/engine/serializers.py, cvat/apps/engine/views.py
Optimized working with DB for several endpoints. For example, /api/jobs, /api/tasks, /api/projects.
I used Silk profiler to measure the number of DB queries.
=> Significantly reduced the number of queries to DB for several endpoints

cvat-ui/src/reducers/shortcuts-reducer.ts, site/content/en/docs/contributing/setup-additional-components.md, site/content/en/docs/manual/advanced/annotation-with-polygons/edit-polygon.md, site/content/en/docs/manual/advanced/export-import-datasets.md, site/content/en/docs/manual/basics/3d-object-annotation-basics.md, site/content/en/docs/manual/basics/objects-sidebar.md, tests/cypress/integration/actions_projects_models/case_95_move_task_to_project.js, tests/cypress/integration/actions_tasks3/case_18_filters_functionality.js, tests/cypress/integration/actions_users/registration_involved/issue_1599_pl_user_registration.js, tests/cypress/integration/issues_prs/issue_1886_point_coordinates_not_duplicated.js, tests/cypress/integration/issues_prs/pr_2203_error_cannot_read_property_at_saving_job.js, tests/cypress/integration/issues_prs2/issue_1391_delete_point.js, tests/cypress/support/commands_filters_feature.js
The only change in production code is the one in `shortcuts-reducer.ts`.  It makes no functional difference, however, because the shortcut in question is not handled by the regular shortcut mechanism; the control key is handled separately in `interactionHandler.ts`, while the string "ctrl" in `shortcuts-reducer.ts` is only used for display purposes.
Fix ESLint errors in altered files, as well.
These Cyrillic Cs interfere with searching and can cause confusion.
I'm relying on GitHub Actions.
- ~~[ ] I have added tests to cover my …
=> Replace unintended Cyrillic C letters with Latin C

CHANGELOG.md, cvat-core/package.json, cvat-core/src/server-proxy.ts, cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/components/login-with-token/login-with-token.tsx, tests/cypress/integration/actions_users/issue_1810_login_logout.js
Before merging this, need to fix getting token from server during social authentication 
Sometimes login token can be missing in our browser(cleared local storage). In cvat we use two different types of authentication, so most operations will work good without token(but not all of them). In the future we can implement only one type of authentication, but for now lets force app to keep two methods of authentication.
We run `authorized` function when app is starting, here we make request about current user. If it fails with `401` cookies will be automatically reset by server, and then we clear token. If it goes well, then we can be sure that we have correct auth cookies. So then we check token and if its missing, we forcibly logging out a user. …
=> Added force logout on CVAT app start if token is missing

cvat-ui/src/components/labels-editor/label-form.tsx, tests/cypress/integration/actions_tasks/task_rectangles_only.js, tests/cypress/support/commands_filters_feature.js
=> Added cypress test to create a task with only bounding boxes

cvat-sdk/cvat_sdk/core/proxies/tasks.py, tests/python/sdk/test_tasks.py
I will need it for the PyTorch data adapter. …
=> SDK: add a high-level method to download task data chunks

CHANGELOG.md, serverless/pytorch/saic-vul/fbrs/nuclio/main.py
resolve #5299 
```python
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension
```
manually on images with and w/o alpha channel
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning …
=> Fixed FBRS runtime dimension error on images with alpha channel

CHANGELOG.md, cvat-canvas3d/package.json, cvat-canvas3d/src/typescript/canvas3d.ts, cvat-canvas3d/src/typescript/canvas3dController.ts, cvat-canvas3d/src/typescript/canvas3dModel.ts, cvat-canvas3d/src/typescript/canvas3dView.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/canvas-wrapper3D.tsx, cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper3D.tsx, tests/cypress/integration/canvas3d_functionality/case_83_canvas3d_functionality_cuboid_grouping.js, tests/cypress/integration/canvas3d_functionality_2/case_82_canvas3d_functionality_cuboid_opacity_outlined_borders.js
plus code refactoring
Related #3438 
Default perspective view after the fix:
=> Adjusted initial camera position, enabled 'Reset zoom' option for 3D canvas

.github/workflows/isort.yml
`isort --version` prints a large banner, which, after shell processing, is collapsed into one line, and the result is an unreadable mess. Use `--version-number` instead, which prints just the number.
I ran the echo command manually to make sure it produces the desired result. 🙂  …
=> Fix isort version output in the workflow

CHANGELOG.md, cvat-sdk/cvat_sdk/core/downloading.py, cvat-sdk/cvat_sdk/core/proxies/jobs.py, cvat-sdk/cvat_sdk/core/proxies/projects.py, cvat-sdk/cvat_sdk/core/proxies/tasks.py, cvat-sdk/cvat_sdk/core/uploading.py, tests/python/cli/test_cli.py, tests/python/sdk/test_issues_comments.py, tests/python/sdk/test_jobs.py, tests/python/sdk/test_tasks.py
For user-facing functions, keep accepting `str` paths to maintain compatibility and flexibility, but add support for arbitrary path-like objects. For internal functions (in `downloading.py` and `uploading.py`), don't bother and require `pathlib.Path`.
The only code that isn't converted is build-time code (e.g. `setup.py`) and code that came from openapi-generator.
`pathlib` enables simpler, more type-safe code. This also makes the API more convenient for users who are already using `pathlib` (or an alternative path library).
Unit tests. …
=> Migrate to using pathlib in most of the SDK

.github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/schedule.yml, CHANGELOG.md, cvat-sdk/cvat_sdk/pytorch/__init__.py, cvat-sdk/gen/templates/openapi-generator/setup.mustache, tests/python/sdk/test_pytorch.py, tests/python/shared/utils/helpers.py
Unit tests; custom demo script. …
=> SDK: Add an adapter layer that presents a CVAT task as a torchvision dataset

Dockerfile, site/content/en/docs/contributing/development-environment.md, site/content/en/docs/manual/advanced/dataset_manifest.md, utils/dataset_manifest/create.py, utils/dataset_manifest/requirements.txt
Extracted from #5083 
Related #5096 
- Improved dataset manifest docs
- Dataset manifest requirements are now installed in the server image
- Package dependencies are aligned with the server
=> Improve dataset manifest installation

cvat-cli/src/cvat_cli/parser.py
- Reduced request status checks period to 2 sec.
- Fixed parameter help message
=> Little UX improvements in CLI

cvat-sdk/cvat_sdk/pytorch/__init__.py, tests/python/sdk/test_pytorch.py
* Make the extractors return tensors instead of Python data structures.
* Let the user specify custom label IDs.
See the commit messages for more details.
This adds functionality that I found to be missing while making a demo script for an object detection scenario.
Unit tests and the aforementioned demo script.
- ~~[ ] I have increased versions of npm packages if it is …
=> SDK: Improve the PyTorch adapter layer

CHANGELOG.md, cvat-sdk/cvat_sdk/core/proxies/projects.py, cvat-sdk/cvat_sdk/core/uploading.py
You have to use the `import_status` action in order to query the input status. Otherwise, the `/api/projects/{id}/dataset/` endpoint initiates a dataset export. Currently, `import_dataset` inadvertently monitors the status of that export, not the original import.
This bug breaks the CI run for #5456. I've no idea why it hadn't caused the test suite to fail before...
Unit tests.
- ~~[ ] I have increased …
=> SDK: fix `Project.import_dataset` incorrectly waiting for completion

components/analytics/docker-compose.analytics.yml, components/serverless/docker-compose.serverless.yml, docker-compose.yml, tests/python/shared/fixtures/init.py
See the individual commits for more information.
I don't want to keep seeing warnings and interleaved docker-compose/pytest output each time I run the tests.
By running the tests. 🙂  …
=> Make the Python test log less messy

.github/workflows/main.yml
=> Fix workflows for release 

.github/workflows/main.yml
- SDK section in docs (<https://github.com/opencv/cvat/pull/4928>)
- An option to enable or disable host certificate checking in CLI (<https://github.com/opencv/cvat/pull/4928>)
- REST API tests with skeletons (<https://github.com/opencv/cvat/pull/4987>)
- Host schema auto-detection in SDK (<https://github.com/opencv/cvat/pull/4910>)
- Server compatibility checks in SDK (<https://github.com/opencv/cvat/pull/4935>)
- Objects sorting option in the sidebar, by z order. Additional visualization when the sorting is applied
(<https://github.com/opencv/cvat/pull/5145>)
- Added YOLOv5 serverless function NVIDIA GPU support (<https://github.com/opencv/cvat/pull/4960>)
- Mask tools are supported now (brush, eraser, polygon-plus, polygon-minus, returning masks
from online detectors & interactors) …
=> CVAT v2.3.0

cvat-sdk/cvat_sdk/core/proxies/projects.py, tests/python/rest_api/test_cloud_storages.py, tests/python/rest_api/test_jobs.py, tests/python/rest_api/test_projects.py, tests/python/rest_api/test_tasks.py, tests/python/sdk/test_jobs.py, tests/python/sdk/test_projects.py, tests/python/sdk/test_tasks.py
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file~~
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and …
=> Added tests for preview endpoints

CHANGELOG.md, cvat-sdk/cvat_sdk/core/client.py, cvat-sdk/cvat_sdk/pytorch/__init__.py, cvat-sdk/gen/templates/openapi-generator/setup.mustache, cvat-sdk/gen/templates/requirements/base.txt, tests/python/sdk/test_pytorch.py
This is useful for people whose home directory is too small/not fast enough. It also lets us make the tests less hacky.
Unit tests. I also ran my old demos to make sure the default cache location remained the same. …
=> SDK: make the dataset cache directory customizable

CHANGELOG.md, cvat-sdk/cvat_sdk/pytorch/__init__.py, tests/python/sdk/test_pytorch.py
It's the analog of `TaskVisionDataset` for projects.
Unit tests.
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~ …
=> SDK: add a ProjectVisionDataset class

tests/python/rest_api/test_tasks.py
This PR fixes a problem with local running of tests introduced in #5498. When running tests locally, there can be multiple tags available, while we need the `dev` tag, which should be created right before tests are executed.
- Added the missing image tag in the docker run command …
=> Fix docker command in tests

site/content/en/docs/administration/advanced/ldap.md, site/content/en/docs/administration/basics/installation.md, site/content/en/docs/administration/basics/social-accounts-configuration.md, site/content/en/docs/faq.md
I was supposed to do this in #5524 when I was removing them everywhere else, but I didn't think to search the documentation. Compose override files must have the same format as the base file, otherwise Docker Compose rejects them.
Fixes #5544.
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#v …
=> Remove version fields from Docker Compose override file examples

.vscode/launch.json, components/serverless/docker-compose.serverless.yml, cvat/apps/dataset_manager/views.py, cvat/apps/dataset_repo/dataset_repo.py, cvat/apps/dataset_repo/views.py, cvat/apps/engine/backup.py, cvat/apps/engine/mixins.py, cvat/apps/engine/task.py, cvat/apps/engine/views.py, cvat/apps/lambda_manager/views.py, cvat/apps/webhooks/signals.py, cvat/settings/base.py, docker-compose.dev.yml, docker-compose.yml, helm-chart/Chart.yaml, helm-chart/templates/cvat_backend/worker_annotation/deployment.yml, helm-chart/templates/cvat_backend/worker_export/deployment.yml, helm-chart/templates/cvat_backend/worker_import/deployment.yml, helm-chart/values.yaml, supervisord/all.conf, supervisord/worker.annotation.conf, supervisord/worker.export.conf, supervisord/worker.import.conf, tests/docker-compose.file_share.yml, tests/values.test.yaml
=> Splitted default queue to import/export, fixed django-rq admin page

.github/workflows/search-cache.yml
Added separate workflow that search cache, it will allow us to remove duplication of this logic in `main.yml`, `full.yml` and `schedule.yml`
! This solution won't work if PR changes search-cache.yml, but this workflow is supposed to almost never change
https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that covers the …
=> Add search cache workflow

CHANGELOG.md, cvat/apps/engine/cache.py, cvat/apps/engine/frame_provider.py, cvat/apps/engine/views.py, cvat/settings/base.py
Usage of `diskcache.Cache` class leads to ignorig cache settings from base.py 
=> Fixed chunk and preview cache usage

CHANGELOG.md, serverless/pytorch/saic-vul/hrnet/nuclio/main.py
This is pretty much the same fix applied to f-BRS in #5384. We've been using HRNet for a while and now an then we receive "500 errors" just as reported in #5299 when someone forgets to drop the alpha-channel from our images.
The RuntimeError is a little bit different, but comes from the same issue: RGBA instead of RGB images:
> RuntimeError: Given groups=1, weight of size [16, 3, 1, 1], expected input[*, 4, *, *] to have 3 channels, but got 4 channels instead.
I created a task with images with and w/o alpha channel, and the interactor works on both now.
~~I have updated the [documentation](
~~I have added tests to cover my changes~~
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pu …
=> Fix HRNet dimension error on images with alpha channel

CHANGELOG.md, cvat-sdk/cvat_sdk/core/client.py
This is a very simple pull request. The type of the credentials parameter of `make_client` is currently `Optional[Tuple[int, int]]`, but it should be `Optional[Tuple[str, str]]` as used by `Client#login`. This PR makes that change.
The typing does not affect the functionality of the code (just the warnings I get in an IDE). …
=> Fix typing of credentials parameter of make_client in the Python SDK

.github/workflows/main.yml, Dockerfile.ci, cvat/apps/engine/serializers.py, cvat/apps/iam/tests/test_rest_api.py
There seems to be a bug somewhere in the Docker ecosystem (it's probably either Docker Compose, Docker Buildx or BuildKit) that causes `docker compose build` to ignore base images that are already present in the system, and instead fetch them from Docker Hub, if there's a custom Buildx builder configured. There's a bug report here:
<https://github.com/docker/compose/issues/9939>.
This bug means that when the build pipeline builds the `cvat_ci` image, it's based on the latest release of `cvat/server` from Docker Hub instead of the version that we just built. Consequently, we run the unit tests against that release instead of the development version.
Fortunately, we don't actually need to set up a Buildx builder in most jobs (including the `unit_testing` job), so just don't do that.
Also, …
=> Fix a CI issue that causes unit tests to run against the wrong version of CVAT

.eslintrc.js, cvat-core/tests/api/projects.js, cvat-core/tests/api/tasks.js, cvat-ui/src/components/move-task-modal/label-mapper-item.tsx, cvat-ui/src/components/project-page/details.tsx, cvat-ui/src/utils/opencv-wrapper/histogram-equalization.ts, tests/cypress/integration/actions_organizations/case_113_new_organization_pipeline.js, tests/cypress/integration/actions_projects_models/case_57_project_label_deleting_feature.js, tests/cypress/integration/actions_projects_models/registration_involved/base_actions_project_task_user.js, tests/cypress/integration/actions_tasks3/case_19_all_image_rotate_features.js, tests/cypress/integration/issues_prs/issue_1882_polygon_interpolation.js, tests/cypress/integration/issues_prs/issue_1886_point_coordinates_not_duplicated.js, tests/cypress/support/const.js
The only ESLint errors that remain are in the Cypress tests (and files that are ignored). …
=> Fix more ESLint errors

CHANGELOG.md, cvat/apps/webhooks/signals.py, site/content/en/docs/administration/advanced/webhooks.md
Run code snippet that verifies webhook signature (see webhook documentation)
=> Fix webhook signature

cvat-sdk/cvat_sdk/core/client.py, cvat-sdk/gen/templates/requirements/base.txt
Turns out, appdirs is not very well maintained; even its own README suggests
switching: <https://github.com/ActiveState/appdirs>. …
=> Replace appdirs with platformdirs

CHANGELOG.md, serverless/pytorch/dschoerk/transt/nuclio/function-gpu.yaml, serverless/pytorch/dschoerk/transt/nuclio/function.yaml, serverless/pytorch/foolwood/siammask/nuclio/function-gpu.yaml, serverless/pytorch/foolwood/siammask/nuclio/function.yaml
While deploying I got the following error:
```
./Miniconda3-latest-Linux-x86_64.sh: 438: [[: not found
./Miniconda3-latest-Linux-x86_64.sh: 444: [[: not found
CondaFileIOError: '/root/miniconda3/pkgs/envs/*/env.txt'. [Errno 2] No such file or directory: '/root/miniconda3/pkgs/envs/*/env.txt'
``` …
=> Fix SiamMask and TransT serverless functions

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx
=> Remove limit on maximum number of manifest files that can be added for cloud storage

cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
Currently user have to delete current frame and enter needed one, then press enter.
With this change, when user click on InputNumber, this field automatically clears and user don't need to do it manually.
It was tested manually …
=> UI change frame optimization

CHANGELOG.md, cvat-sdk/cvat_sdk/core/client.py, cvat-sdk/cvat_sdk/core/proxies/organizations.py, site/content/en/docs/api_sdk/sdk/highlevel-api.md, tests/python/sdk/test_client.py, tests/python/sdk/test_organizations.py
This consists of two parts:
* API to work with organizations;
* API to work with other resources in the context of an organization.
SDK unit tests. …
=> SDK: Add organization support to the high-level layer

docker-compose.yml
The root process of the container is `/bin/sh`, which ignores the initial `SIGTERM` that Docker sends. So Docker has to wait 10 seconds and then kill everything with `SIGKILL`.
Make Grafana itself the root process instead. Grafana handles the `SIGTERM` and shuts down quickly.
It takes 10 seconds to shut down Grafana without this change, and less than 1 with it.
`docker compose down`
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-reque …
=> Fix slow shutdown for the Grafana container

.vscode/launch.json
- Fixed naming and added a missing debug config for rq workers
=> Fix debug configurations for vs code

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/import-backup/import-backup-modal.tsx, cvat-ui/src/components/import-dataset/import-dataset-modal.tsx, cvat-ui/src/components/import-dataset/styles.scss, cvat-ui/src/components/select-cloud-storage/select-cloud-storage.tsx
Resolved #5633
Also fixed storage selection when uploading a dataset
=> Lock 'Ok' button when there is no selected file to upload

cvat-sdk/cvat_sdk/core/proxies/issues.py, cvat-sdk/cvat_sdk/core/proxies/jobs.py, cvat-sdk/cvat_sdk/core/proxies/projects.py, cvat-sdk/cvat_sdk/core/proxies/tasks.py, cvat/apps/engine/filters.py, cvat/apps/engine/views.py, cvat/apps/organizations/views.py, cvat/apps/webhooks/views.py, tests/python/rest_api/test_issues.py, tests/python/rest_api/test_labels.py, tests/python/rest_api/test_projects.py, tests/python/rest_api/test_tasks.py, tests/python/rest_api/utils.py
This PR implements typed query params for simple filters, making SDK interface clearer.
=> Allow typed simple filters

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/containers/annotation-page/annotation-page.tsx
=> Fixed freezing browser when request a job by NaN id

CHANGELOG.md, docker-compose.yml
=> Fix missing CVAT_BASE_URL env

site/content/en/docs/administration/basics/installation.md
There are some poorly written sentences in documentation pages. For example:
> You can use a share storage for data uploading during you are creating a task. To do that you can mount it to CVAT docker container. 
These make the documentation look a little informal, and since Installation Guide is probably the first page most new CVAT users visit, I updated some of the sentences on this page to have a better structure / sound more formal.
This change did not require any tests. …
=> Minor English-language improvements in installation.md

CHANGELOG.md, cvat/apps/engine/serializers.py, tests/python/rest_api/test_projects.py, tests/python/rest_api/test_tasks.py, tests/python/rest_api/utils.py
Fixed adding skeletons to a task or project
Added REST API tests
=> Fix: skeletons cannot be added to a task or project

CHANGELOG.md, site/content/en/docs/administration/advanced/ldap.md
Update documentation to use the proper service when enabling LDAP authentication. 
The current documentation references a service (`cvat`) that is now renamed to `cvat_server`. This change makes this apparent.
Used the same configs as described in the guide with a Windows Server 2022 instance, and only deviated from the instructions as to select the correct docker service. This PR has this change. …
=> Use correct service name in LDAP authentication documentation

CHANGELOG.md, cvat-ui/src/components/projects-page/actions-menu.tsx
=> Fix warning `key` is undefined on project page

.github/CODEOWNERS, .github/workflows/full.yml, .github/workflows/helm.yml, .github/workflows/main.yml, .github/workflows/schedule.yml, .vscode/launch.json, cvat-sdk/.gitignore, cvat-sdk/gen/generate.sh, cvat/schema.yml, site/content/en/docs/api_sdk/sdk/developer-guide.md
Instead of generating the schema during the SDK build, store it in the repository. Add a CI check that verifies that the schema matches the server.
This has the following benefits:
* It becomes easy to see if and how a pull request affects the API (syntactically, at least). Since the schema is generated dynamically by drf-spectacular, it's not always obvious what effects a code change will have on the declared API. By requiring PRs to explicitly change the schema, we enable such changes to be reviewed directly.
* It removes one step from the SDK generation procedure, making it easier for people to contribute. The schema generation step was, IMO, the most annoying (because you have to build the server) and the most error-prone (because it's easy to use the wrong version of the server). …
=> Commit the API schema to the repository

CHANGELOG.md, cvat-core/package.json, cvat-core/src/server-proxy.ts
This is mostly just refactoring, but there are a couple of bugfixes:
* `deleteTask` now correctly sets the `org` parameter (although I don't know why this parameter is needed to begin with);
* `getCloudStorageContent` now works correctly when the manifest name contains special characters. …
=> Clean up server-proxy.ts

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/export-dataset/export-dataset-modal.tsx, cvat-ui/src/components/import-dataset/styles.scss, cvat-ui/src/components/storage/storage-with-switch-field.tsx, cvat-ui/src/cvat-core-wrapper.ts, tests/cypress/e2e/issues_prs/issue_5381_empty_project_formats.js
=> Fixed export formats for empty project

CHANGELOG.md, cvat-canvas3d/package.json, cvat-canvas3d/src/typescript/canvas3d.ts, cvat-canvas3d/src/typescript/canvas3dController.ts, cvat-canvas3d/src/typescript/canvas3dModel.ts, cvat-canvas3d/src/typescript/canvas3dView.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/views/canvas3d/canvas-wrapper3D.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/components/header/settings-modal/settings-modal.tsx, cvat-ui/src/reducers/settings-reducer.ts, tests/cypress/e2e/actions_tasks/case_100_settings_default_number_of_points_in_polygon_approximation.js, tests/cypress/e2e/actions_tasks/case_68_saving_settings_local_storage.js
=> Receive value for 'Reset zoom' option from settings saved by user

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/base.scss, cvat-ui/src/components/cloud-storages-page/styles.scss, cvat-ui/src/components/jobs-page/styles.scss, cvat-ui/src/components/models-page/styles.scss, cvat-ui/src/components/projects-page/styles.scss, cvat-ui/src/components/task-page/styles.scss, cvat-ui/src/components/tasks-page/styles.scss
=> Make empty previews responsive to page resize

.vscode/launch.json, site/content/en/docs/contributing/development-environment.md
Currently, if you try to generate the API schema with the VS Code launch configuration, it'll remove the `minimum` and `maximum` attributes from the definition of some of the integer fields. This is because those attributes come from the configured database engine in use. The "canonical" version of the schema is generated from the Docker image, which uses the production configuration, and thus PostgreSQL; while using the VS Code launch configuration will default to the development configuration, and thus SQLite.
Fix it by aligning the configurations. Since ultimately, the schema is for the production version of the server, override the configuration to production for the VS Code launch configuration.
Note that there's one more discrepancy that remains; that of the API version number. I …
=> Fix most discrepancies between the different ways of generating the API schema

supervisord/server.conf
Currently when user try to open the task with git repository connected he will see this (screenshot)
This happens after first synchronization and reloading the page. The cause of this is ssh-agent, that is not running in cvat_server container.
This PR will enable ssh-agent on cvat_server so this issue disappears.
It was tested manually
[cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#vers …
=> Git sync fix

cvat/requirements/base.txt, cvat/requirements/production.txt, site/content/en/docs/contributing/development-environment.md
While testing the development environment setup instructions in #5889, I found that some of the Python packages have problems with installing on newer Linuxes. Fortunately, most such problems can be resolved by bumping the versions: 
* `psycopg2-binary` to enable support for Python 3.10+ (the current version does work with these Pythons, but it doesn't have prebuilt wheels for them).
* `python-ldap` to enable support for OpenLDAP 2.5+ (on systems that don't include a compatibility `libldap_r.so` symlink, like Arch).
`pip install` in a Docker container of Arch Linux and on Ubuntu 22.04.
- ~~[ ] I have …
=> Bump Python dependency versions

cvat/apps/engine/migrations/0067_alter_cloudstorage_credentials_type.py
Merging both #4649 and #5855 broke migrations.
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versio …
=> Resolve migration conflict

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/resource-sorting-filtering/index.ts, tests/cypress/e2e/issues_prs/issue_5566_filter_url.js
Or rather, just don't needlessly unescape it.
Fixes #5566.
Cypress test.
=> URL-escape the filter in the generated URLs

cvat/apps/engine/models.py, cvat/apps/engine/views.py, cvat/apps/events/cache.py, cvat/apps/events/handlers.py, cvat/apps/events/utils.py, cvat/requirements/staging.txt, tests/python/rest_api/test_analytics.py
=> Reduce deletion time of task and projects

CHANGELOG.md, cvat/apps/events/serializers.py
Wrong calculation of `working_time` field. 
https://docs.python.org/3/library/datetime.html#datetime.timedelta.total_seconds …
=> Fix working time calculation

CHANGELOG.md, cvat/__init__.py, cvat/apps/dataset_manager/task.py, cvat/apps/engine/mixins.py, cvat/apps/engine/serializers.py, cvat/apps/events/serializers.py, docker-compose.yml, helm-chart/values.yaml
- Optimized annotation fetching up to 10 times (<https://github.com/opencv/cvat/pull/5974>)
- Incorrect calculation of working time in analytics (<https://github.com/opencv/cvat/pull/5973>)
=> Hotfix for v2.4.0 -> Release v2.4.1

cvat-core/package.json, yarn.lock
After 40232858, the JavaScript tests print a warning about TypeScript 5 not being supported. This fixes it.
Running the JS tests.
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#ve …
=> Bump the version of ts-jest to support TypeScript 5

CHANGELOG.md, cvat/apps/engine/serializers.py, cvat/apps/engine/utils.py, cvat/apps/engine/view_utils.py, cvat/apps/engine/views.py, cvat/schema.yml
As explained in the comment in `_tus_chunk_action`, I don't think we need explicit documentation for these endpoints. Hiding them makes the documentation a bit cleaner, especially because these endpoints were indistinguishable from one another.
It also removes the corresponding SDK code, which is good, since clients should follow the URL returned by the creation endpoint, not invoke the chunk endpoints directly.
CI.
- ~~[ ] I have increased versions of npm packages if it is …
=> Remove the tus chunk endpoints from the schema

tests/python/shared/fixtures/init.py
=> Remove default containers rebuild when running REST API tests

docker-compose.yml
OPA currently logs every request to the console and this results in huge docker log files.
I don't think these logs can be useful for enabling docker-level log size limits.
=> Disable OPA container logs 

cvat/apps/engine/serializers.py, cvat/schema.yml, tests/python/rest_api/test_issues.py
This PR fixes a problem with WriteOnceSerializer that it affected only the fields declared in the `Meta.fields`, while the manually declared fields were left unaffected. This PR also fixes several issues with invalid field declarations.
Feel free to …
=> Fix write once fields

CHANGELOG.md, cvat-sdk/cvat_sdk/core/client.py, tests/python/sdk/test_client.py
- Added missing compatibility with micro- and smaller releases
Unit test
=> Fix version checks in SDK

CHANGELOG.md, README.md, serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/sam/nuclio/function.yaml, serverless/pytorch/facebookresearch/sam/nuclio/main.py, serverless/pytorch/facebookresearch/sam/nuclio/model_handler.py
Idea of the PR is to finish this one #5990
Deploy for GPU: ``./deploy_gpu.sh pytorch/facebookresearch/sam/nuclio/``
Deploy for CPU: ``./deploy_cpu.sh pytorch/facebookresearch/sam/nuclio/``
If you want to use GPU, be sure you setup docker for this [guide](https://github.com/NVIDIA/nvidia-docker/blob/master/README.md#quickstart).  
Manual testing
Resolved issue #5984
But the interface probably can be improved
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versionin …
=> Added Segment Anything interactor for GPU/CPU

CHANGELOG.md, cvat/apps/engine/mixins.py
Manually by set `--processes 3` for `mod_wsgi` settings
=> Fix tus loading if multiple apache processes are used

Dockerfile
This speeds up the build when the entire step can't be cached (e.g. the requirements file changed), but the package list remains mostly the same.
The savings are... rather underwhelming, actually. I have observed about a minute in savings, although it obviously depends on the network connection speed. I think this is because pip is inefficient at loading from its own cache (I have observed it loading the entire cached file into memory, for example).
Still, savings are savings, and we're getting them basically for free, so why not.
Note that I only persist the HTTP cache, and not the wheel cache. That's because any wheels that pip builds could depend on the system packages, and I don't want old wheels to be reused if the system packages change.
Also, disable the pip autoupdate checks, …
=> Dockerfile: retain the pip download cache between builds

CHANGELOG.md, cvat/requirements/base.txt, cvat/requirements/testing.txt, docker-compose.yml
This originally started as a security update for redis-py (see <https://github.com/redis/redis-py/releases/tag/v4.5.3>, <https://github.com/redis/redis-py/releases/tag/v4.5.4>). However, I also had to update other Redis-related components because of incompatibilities.
* The old version of fakeredis is not compatible with the redis-py 4.x, so I bumped it too. This also allowed me to remove the six workaround.
* redis-py 4.1.0 and newer don't support Redis < 5, so I bumped Redis itself in `docker-compose.yml`. Note that the Helm chart is already using Redis 7.0.x.
Obsoletes #5946.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pu …
=> Update Redis and Redis accessories

.github/workflows/publish_docker_images.yml, CHANGELOG.md, Dockerfile, docker-compose.dev.yml
The policy that mandated this is no longer relevant now that CVAT is no longer developed by Intel. Moreover, the source code included was not even complete (it didn't contain Python or NPM packages).
This saves ~1.6 GB in the unpacked image (and probably a bunch of build time too, but I didn't measure it). …
=> Stop adding package source code into the release Docker images

Dockerfile
This way, it can be done in parallel with pip fetching all other packages in the main build stage. In practice, I find that the build of PyAV finishes before pip is done downloading, so we basically get it done for free (in terms of time).
With this change, I measured a build time of 9:09 (starting from scratch).
Not a whole lot; I just ran `python manage.py` in the container as a sanity check.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking- …
=> Dockerfile: build PyAV and its dependencies in a separate stage

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/cvat-core-wrapper.ts
=> Set default TUS chunk size from 100 to 2 MB

CHANGELOG.md, serverless/pytorch/dschoerk/transt/nuclio/function-gpu.yaml, serverless/pytorch/dschoerk/transt/nuclio/function.yaml, serverless/pytorch/saic-vul/hrnet/nuclio/function.yaml
When tracking multiple objects at once, the current size of the request body may not be enough, especially on large images, so let's increase this value based on 100 objects + the size of the 4k image.  …
=> Increase request body size for TransT tracker

CHANGELOG.md, cvat/apps/engine/cloud_provider.py
The problem is that If a user tries to export annotations to the Azure container and the file with such name already exists, then an exception will be raised by default. This is not suitable for us, because our side should not be affected by this and we should have the same behavior for different CS providers.
Manually …
=> Fix issue azure.core.exceptions.ResourceExistsError: The specified blob already exists.

CHANGELOG.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx
=> Fixed fit for images with different resolution

CHANGELOG.md, cvat/apps/lambda_manager/views.py, cvat/settings/base.py
Currently, this only happens when running in Kubernetes. This option lets CVAT use Nuclio that's deployed to Kubernetes without being deployed to Kubernetes itself, or just to use Nuclio that is deployed on another machine.
I manually tested both options.
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning) …
=> Add an option to call Nuclio functions via the dashboard

serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml
Without these variables, the container cannot actually use CUDA. At least that was my experience on AWS; it's possible that in other configurations the defaults are different.
See <https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/user-guide.html>.  …
=> pth-facebookresearch-sam-vit-h: add NVIDIA environment variables to the GPU image

site/content/en/docs/manual/advanced/formats/format-camvid.md, site/content/en/docs/manual/advanced/formats/format-cityscapes.md, site/content/en/docs/manual/advanced/formats/format-coco.md, site/content/en/docs/manual/advanced/formats/format-cvat.md, site/content/en/docs/manual/advanced/formats/format-icdar.md, site/content/en/docs/manual/advanced/formats/format-imagenet.md, site/content/en/docs/manual/advanced/formats/format-kitti.md, site/content/en/docs/manual/advanced/formats/format-labelme.md, site/content/en/docs/manual/advanced/formats/format-lfw.md, site/content/en/docs/manual/advanced/formats/format-market1501.md, site/content/en/docs/manual/advanced/formats/format-mot.md, site/content/en/docs/manual/advanced/formats/format-mots.md, site/content/en/docs/manual/advanced/formats/format-openimages.md, site/content/en/docs/manual/advanced/formats/format-tfrecord.md, site/content/en/docs/manual/advanced/formats/format-vggface2.md, site/content/en/docs/manual/advanced/formats/format-voc.md, site/content/en/docs/manual/advanced/formats/format-widerface.md, site/content/en/docs/manual/advanced/formats/format-yolo.md
- Added dataset example links
- Fixed COCO links to Datumaro docs
=> Add dataset examples and update some links in docs

serverless/deploy_cpu.sh
This PR solves issue #6247 "Error while enabling SAM on CPU".
It looks like the `--file` argument to `nuctl deploy` was inadvertently removed in the most recent release. This causes the process to fail with `**Error - Function name cannot be empty`. I was able to reproduce this error on my own system.
This change fixes a minor error.
I tested this by reproducing the bug with the command from the `cvat/components` directory:
`nuctl deploy --project-name cvat --path "./serverless/pytorch/foolwood/siammask/nuclio" --platform local`
I then edited the `deploy_cpu.sh` file, executed the same command, and completed a successful deployment, which I verified with `nuctl get functions`.
- ~~[ ] I have added a description of my changes into the …
=> Error while enabling SAM on CPU

tests/python/rest_api/test_tasks.py
=> Disable failed REST API tests

site/content/en/docs/administration/advanced/iam_system_roles.md
Followup to discussion from: https://github.com/opencv/cvat/issues/6224
This issue is linked with: https://github.com/opencv/cvat/pull/3788 which introduced IAM, but not docummented some aspets.
This is my small attempt to fill part of docs which describes how to change default permissions.
It would be great if @nmanovic would also fill part describing default groups. …
=> docs: Describe changing default OPA permissions

CHANGELOG.md, cvat-cli/src/cvat_cli/__main__.py, cvat-cli/src/cvat_cli/parser.py, site/content/en/docs/api_sdk/cli/_index.md, tests/python/cli/test_cli.py
This is the CLI equivalent of #5718.
Unit tests.
=> Add organization support to the CLI

cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
This is quick-fix for errors that occur in AI tools errors. Generally, we need to throw errors via errors-state.
=> Added support for react-markown in AI tools errors

cvat/nginx.conf, supervisord/server.conf
Using a unix socket for Uvicorn as recommended in the documentation:
https://www.uvicorn.org/deployment/#running-behind-nginx
=> Use unix domain socket instead of tcp for Uvicorn

CHANGELOG.md, cvat/apps/dataset_manager/task.py, cvat/apps/dataset_manager/util.py, cvat/apps/engine/migrations/0070_add_job_type_created_date.py, cvat/apps/quality_control/quality_reports.py
Optimizes several DB request memory issues, introduced in #6204 
- Optimized memory use in job annotation retrieval
- Optimized migration
=> Optimize DB requests

CHANGELOG.md, cvat/apps/engine/serializers.py, cvat/apps/organizations/serializers.py, cvat/apps/webhooks/serializers.py, cvat/schema.yml, tests/python/rest_api/test_cloud_storages.py, tests/python/rest_api/test_invitations.py, tests/python/rest_api/test_organizations.py, tests/python/rest_api/test_projects.py, tests/python/rest_api/test_tasks.py
The owner field can be null if the user was removed after the object had been created, but API schema doesn't support this. This PR fixes the schema.
=> Fix API schema for the owner field

CHANGELOG.md, cvat/apps/engine/media_extractors.py
=> Fixed extension when compute original chunks

.github/workflows/main.yml
It was accidentally disabled in #6173.
Also, refactor the build steps to make the log easier to read. …
=> Re-enable testing for the PyTorch adapter

.github/workflows/main.yml
Most of the time it's useless and just clogs up the build queue. When it's useful (e.g. when removing "[Dependent]" from the title), it's easy enough to retrigger the build manually by updating your branch.
Fixes #5921.
([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cva …
=> Don't rerun the tests when the PR description is edited

tests/python/sdk/test_pytorch.py
Currently, any kind of import error will disable the tests. This makes it far too easy to disable the tests accidentally by messing up the imports.
Only disable the tests if PyTorch or torchvision are not found.
Manual testing with various artificially-introduced errors. …
=> Make the PyTorch adapter tests less likely to be disabled by accident

CHANGELOG.md, cvat-sdk/cvat_sdk/pytorch/caching.py, tests/python/sdk/test_pytorch.py
This was broken in 4fc494f4.
Add a test to cover this case.
Fixes #6047.
Unit tests. …
=> PyTorch adapter: fix loading tasks that have already been cached

cvat-cli/src/cvat_cli/cli.py
For unclear reasons, when this setting is enabled, the OpenAPI Generator runtime becomes unable to parse `AnnotationsRead` values from JSON.
Specifically, it thinks that the JSON value is ambiguous, because it can be parsed both as `LabeledData` and as `IOBase`. The former makes sense, but the latter does not. I think it's just a bug in the runtime.
This line is why the issue only occurs when `discard_unknown_keys` is set:
https://github.com/OpenAPITools/openapi-generator/blob/v6.0.1/modules/openapi-generator/src/main/resources/python/model_utils.mustache#L1139
The CLI currently doesn't parse `AnnotationRead` anywhere, so this patch doesn't have any user-visible effects. However, I'm prototyping a new CLI command which will need to parse annotations.
Change `tasks_create` so that it …
=> CLI: don't set `discard_unknown_keys`

CHANGELOG.md, cvat/apps/lambda_manager/views.py
The intent of the `try`/`except` statement is to catch accesses to missing members of the `data` dictionary, but due to the large amount of code in the `try` block, it may end up catching entirely unrelated `KeyError`s. Those unrelated `KeyError`s should not be converted to `ValidationError`s, since they might not have anything to do with input validation, and the conversion will make it harder to debug these exceptions.
An example of these misapplied conversions is a recent bug where a `KeyError` was coming from inside `_get_image` (fixed by f6420eb7).
To fix this, make sure to only catch `KeyError`s emitted by accesses to `data`.
I manually checked that a) invoking functions still works, and b) omitting required parameters still results in a 400 error.
- ~~[ ] I have updated the …
=> Fix overly broad exception conversion in `LambdaFunction.invoke`

CHANGELOG.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-attribute.tsx, cvat-ui/src/components/labels-editor/label-form.tsx, tests/cypress/e2e/actions_tasks/mutable_attributes.js, tests/cypress/e2e/issues_prs/issue_1919_check_text_attr.js, tests/cypress/e2e/issues_prs2/issue_1425_highlighted_attribute_correspond_chosen_attribute.js, tests/cypress/support/commands.js
=> Supported multi-line input, fixed issue in aam with losing selection

.github/workflows/hadolint.yml
I ran the new version on our Dockerfiles.
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) …
=> Bump Hadolint version

cvat/apps/engine/backup.py
When users try to backup a task with cloud storage data they get such error:
And after that, they have no idea what's wrong with this task and why they cannot backup it.
=> Add error message

.github/workflows/helm.yml
Duplicate https://github.com/opencv/cvat/pull/6373 for Helm tests
=> No helm tests on edit

CHANGELOG.md, cvat-core/package.json, cvat-core/src/annotations-collection.ts, cvat-core/tests/api/annotations.js
=> Fixed calculating statistics in case with removed frames

CHANGELOG.md, cvat/__init__.py, cvat/apps/engine/media_extractors.py, cvat/schema.yml, docker-compose.yml, helm-chart/values.yaml
- Memory leak related to unclosed av container (<https://github.com/opencv/cvat/pull/6501>)
=> Release v2.5.1

cvat/settings/testing.py, cvat/settings/testing_rest.py
Disable silk progiler for unit tests, adjust disk utilization threshold for rest tests
rest api test fail by disk usage threshold
https://github.com/opencv/cvat/actions/runs/5599104736/jobs/10259789498
unit tests take 50 min vs 25 min without profiling
https://github.com/opencv/cvat/actions/runs/5599991927/jobs/10248711685 …
=> Minor CI improvements

cvat-ui/plugins/sam_plugin/src/ts/index.tsx
Previous one can lead to race condition, because plugin is listening for getting jobs requests. 
If the weights loaded later than request occurs, it does not have opened job in memory and raises an error.
Rare but possible case.  …
=> Adjusted plugin registration way

tests/python/cli/util.py, tests/python/sdk/test_jobs.py, tests/python/sdk/test_tasks.py, tests/python/shared/utils/helpers.py
It doesn't make much sense to encode the image as JPEG if the given file name is "image.png". Instead, let PIL select the format based on the requested file name.
This was originally a part of #6483, but it's not directly related to the topic of that PR, so I decided to submit it separately.
Unit tests. …
=> generate_image_file: don't hardcode the file format

cvat/apps/engine/views.py, cvat/apps/iam/permissions.py
Resolved #6550 
```python
ERROR:django.request:Internal Server Error: /api/server/annotation/formats
Traceback (most recent call last):
File "/home/andrey/workspace/cvat.ai/cvat/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "/home/andrey/workspace/cvat.ai/cvat/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
response = response.render()
File "/home/andrey/workspace/cvat.ai/cvat/.env/lib/python3.10/site-packages/django/template/response.py", line 114, in render
self.content = self.rendered_content
File "/home/andrey/workspace/cvat.ai/cvat/.env/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
ret = renderer.render(self.data, …
```
=> Fix BrowsableAPIRenderer for server viewset

CHANGELOG.md, cvat-cli/src/cvat_cli/cli.py, cvat-sdk/cvat_sdk/core/downloading.py, cvat-sdk/cvat_sdk/core/helpers.py, cvat-sdk/cvat_sdk/core/progress.py, cvat-sdk/cvat_sdk/core/uploading.py, tests/python/pytest.ini, tests/python/sdk/test_progress.py, tests/python/sdk/util.py
There are several problems with how progress reporting is handled in the SDK, both on the interface and implementation level:
* The user is supposed to know, for a given function, which units it will report progress in. This is unnecessary coupling and prevents us from switching to different units, or to have several progress bars using different units.
* To create a TqdmProgressReporter, you have to create a tqdm instance, which immediately draws a progress bar. This works poorly if the function prints any log messages before the progress actually starts.
* There's no easy way to automatically call `finish` on a progress bar, so some functions don't (for example, `Downloader.download_file`). This can cause unexpected output, since tqdm will refresh the progress bar in a background thread …
=> Revamp the progress reporting API

CHANGELOG.md, cvat/apps/engine/views.py, cvat/settings/base.py
Current default assets limitations are too strict
=> Increased default guide assets limitations

.github/workflows/bandit.yml, .github/workflows/black.yml, .github/workflows/isort.yml, .github/workflows/pylint.yml
Use pipx (preinstalled on GitHub-hosted runners), which takes care of
virtual environments for us. Remove the apt-get commands; we don't actually
need the packages that they're installing.
I added a test commit to this PR to make sure the linters still run correctly. …
=> Simplify Python linter workflows

CHANGELOG.md, Dockerfile
When I integrated pip-compile, I neglected to notice that in the generated `*.txt` files the --no-binary=av option is on its own line, and therefore is stripped away by the sed command.
Hardcode this option in the Dockerfile to make sure we build PyAV from source. Also, add a workaround for the fact that PyAV is incompatible with recently-released Cython 3. …
=> Fix accidental prebuilt PyAV usage in the Dockerfile

cvat-sdk/README.md, site/content/en/docs/api_sdk/cli/_index.md, site/content/en/docs/api_sdk/sdk/_index.md, site/content/en/docs/api_sdk/sdk/auto-annotation.md
Documentation for #6483.
- ~~[ ] I submit _my code changes_ under the …
=> Add documentation for auto-annnotation in SDK/CLI

Dockerfile.ui, cvat-ui/webpack.config.js
Need to hide somehow proprietary code.
If ``SOURCE_MAPS_TOKEN`` env token is specified during building cvat-ui module, it will hide the source maps as ``${SOURCE_MAPS_TOKEN}/assets/<name>.map``.
Since this token is hidden, the code is not available for anyone. 
https://github.com/opencv/cvat/blob/develop/LICENSE) that covers …
=> Support hidden source maps

cvat-cli/setup.py, cvat-sdk/cvat_sdk/auto_annotation/interface.py, cvat-sdk/cvat_sdk/core/proxies/model_proxy.py, cvat-sdk/cvat_sdk/core/utils.py, cvat-sdk/cvat_sdk/pytorch/transforms.py, cvat-sdk/gen/generator-config.yml, site/content/en/docs/api_sdk/cli/_index.md, site/content/en/docs/api_sdk/sdk/_index.md
Upstream support for Python 3.7 ended on 2023-06-27.
Feel free to …
=> Drop Python 3.7 support in the SDK and CLI

CHANGELOG.md, cvat-core/package.json, cvat-core/src/frames.ts, cvat-core/src/session-implementation.ts, cvat-core/src/session.ts, cvat-data/src/ts/cvat-data.ts, cvat-ui/package.json, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/canvas/views/canvas3d/canvas-wrapper3D.tsx, cvat-ui/src/components/annotation-page/styles.scss, cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx, cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx, cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/index.ts
Depends on #6585
Resolved #8
Decoded range is red:
=> Added cached frames indication

CHANGELOG.md, cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
=> release notes update

tests/cypress/e2e/actions_tasks2/fit_image_different_res.js
It may not to work sometimes because check: ``cy.get('.cvat-canvas-container').should('exist').and('be.visible');`` passes even before the command ``cy.visit(`/tasks/${taskID}/jobs/${jobID}`);`` takes effect.
Added interceptor …
=> Fixed unstable test (fit_images_different_resolutions)

tests/python/shared/fixtures/init.py
I encountered an issue where the server process fails at startup due to being unable to create `/home/django/cache/events`, due to `/home/django/cache` being owned by `root`.
I'm not sure how exactly that happened, but there are several commands involving Django or CVAT data that the test suite runs as root, and it had to be one of them that caused it.
I don't think there's any reason to run these commands as root, so use `docker_exec_cvat` for them instead of `docker_exec`. This way, they will run as the Django user instead.
Unit tests.
- ~~[ ] I have …
=> tests: don't run commands in the server container as root

tests/python/shared/fixtures/init.py
* represent the command accurately using shell quoting;
* show the exit code;
* show both stdout and stderr.
This helped me debug #6717.
Unit tests. …
=> tests/python: improve reporting when a command fails

CHANGELOG.md, cvat-sdk/cvat_sdk/core/utils.py
`atomic_writer` is supposed to overwrite the destination file, but `os.rename` doesn't do that on Windows. We have to use `os.replace` instead. …
=> SDK: Fix `FileExistsError`s on Windows when a dataset is loaded from cache

cvat/schema.yml, cvat/utils/version.py
IMO, two-component version numbers should only be used when a project doesn't make patch releases at all. Having two version components for some releases and three for others is just pointless inconsistency.
Two-component version numbers are also inconsistent with our tag names. …
=> Don't hide the patch version number when it's 0

CHANGELOG.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts
=> Fixed fail for masks & skeletons with centered text

CHANGELOG.md, cvat-ui/package.json, cvat-ui/src/components/create-cloud-storage-page/cloud-storage-form.tsx
Specifically, with the AWS credential fields:
* Replace SHOUTY CAPS with normal sentence case.
* Remove the word "ID" from the label of the second field; it's a key, not an ID.
* Remove gratuitous snake_case from the validation messages.
The shouty caps were mildly irritating, and once I started fixing them, I decided I might as well fix some other issues too. …
=> Fix cosmetic issues in the cloud storage creation form

CHANGELOG.md, helm-chart/Chart.yaml, helm-chart/templates/cvat_backend/initializer/job.yml, helm-chart/templates/cvat_backend/server/deployment.yml, helm-chart/values.yaml
To do that, remove the running of migrations from the server pod(s), and add a Kubernetes job to do it instead.
This will prevent Django from corrupting the database when two or more instances are started up at the same time. …
=> helm-chart: make sure database migrations are only run by one process

Dockerfile, Dockerfile.ci, cvat/asgi.py, manage.py
There are a few issues with it:
* It doesn't work for the Enterprise version, because its settings module is not located under `cvat.settings`.
* The name `DJANGO_CONFIGURATION` suggests that it's defined by Django, but it isn't. It's a CVAT-specific variable. There's also a 3rd-party module that uses this variable (django-configurations), but with different semantics, which could cause confusion.
* It's just redundant to have two variables that effectively do the same thing (`DJANGO_CONFIGURATION` and `DJANGO_SETTINGS_MODULE`).
Besides its runtime effect, `DJANGO_CONFIGURATION` is also used in the Dockerfile to select the packages to install. I could see that still being useful, so replace it with a build-only variable named `CVAT_CONFIGURATION`.
I built the Docker image with various …
=> Remove the DJANGO_CONFIGURATION environment variable

CHANGELOG.md, cvat-ui/src/components/header/header.tsx, cvat-ui/src/utils/git-utils.ts, cvat-ui/src/utils/opencv-wrapper/opencv-wrapper.ts
Now we have proxy on both development (webpack) and production (traefik).
So, we do not need to specify origin anymore.
Moreover there was a bug #6237
Resolved #6237
=> Removed prefix where not necessary

CHANGELOG.md, cvat/apps/engine/frame_provider.py, cvat/apps/engine/media_extractors.py
=> Fixed error for non-jpeg compressed images in original chunks

CHANGELOG.md, cvat/settings/base.py
Currently, it's possible (even if unlikely) for multiple backend processes to create and use different Django `SECRET_KEY` values, because the following scenario can happen:
* process 1: fail to import `secret_key.py`
* process 2: fail to import `secret_key.py`
* process 1: generate a new `secret_key.py`
* process 1: import `secret_key.py`
* process 2: generate a new `secret_key.py`
* process 2: import `secret_key.py`
Fix this by making it so that `secret_key.py` is created atomically, and never overwritten if it already exists.
In addition, only generate the secret key if the import fails due to the module not being found, since other failure reasons suggest incorrect configuration or data corruption, and so require administrator attention.
- ~~[ ] I have updated the …
=> Fix a race condition with initial secret_key.py creation

CHANGELOG.md, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-buttons.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-buttons.tsx, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
=> Display hide/show buttons in review mode

CHANGELOG.md, cvat/settings/base.py, supervisord/server.conf
There are two independent problems that cause some log messages to be printed twice:
* In the CVAT logging configuration, we attach a console handler to the `cvat` and `django` loggers. However, when any library[1] used by CVAT uses one of the top-level `logging` functions (e.g. `logging.info`), then it will cause the root logger to get autoconfigured with another console handler. Since `cvat` and `django` are configured to propagate events to the ancestor logger's handlers, those events are passed to _two_ console handlers, so they are printed twice.
Fix it by moving our handlers to the root logger. If the root logger has handlers, it will no longer get autoconfigured when top-level `logging` functions are invoked; so there will only be one console handler in the logger chain.
An …
=> Fix log message duplication

cvat/apps/lambda_manager/views.py
See these several issues. They are connected to each other in some way. 
The thing is that nuclio has a default timeout of 1 minute. With this change we can force nuclio dashboard not to terminate the connection.
https://github.com/nuclio/nuclio/issues/3016
https://github.com/opencv/cvat/issues/3301
https://github.com/opencv/cvat/issues/6041 …
=> Setup nuclio timeout

CHANGELOG.md, cvat/apps/engine/task.py, cvat/apps/engine/views.py
=> Fixed task progress report for 3rdparty users

cvat/apps/engine/frame_provider.py, cvat/apps/engine/media_extractors.py
* We do not need custom exif rotation method, since PIL already has one.
* Added some closings for PIL Images
> The lifecycle of a single-frame image is relatively simple. The file must remain open until the load() or close() function is called or the context manager exits.
https://pillow.readthedocs.io/en/stable/reference/open_files.html#image-lifecycle
Means, that if we opened file and load() was not called internally, the file will stay opened. So, I added context manager and called close() in somewhere just in case …
=> [Refactoring] Removed custom exif rotation method

CHANGELOG.md, cvat/apps/engine/task.py, utils/dataset_manifest/core.py
They are not reliable.
In particular, MP4 has a feature called "edit lists" that allows you to set a custom playback order for the media data. With edit lists, you could only specify that a particular range of frames should be played, or that a range should be played multiple times, etc. See the following for technical details:
https://developer.apple.com/documentation/quicktime-file-format/edit_list_atom
FFmpeg follows edit lists when decoding videos. However, the frame count returned by PyAV's `Stream.frames` property is the number of frames in the raw media data and does not reflect the modifications applied by an edit list.
When we build a video manifest, we use `Stream.frames` if it's non-zero. Therefore, in the presence of an edit list we will obtain a frame count that does not …
=> Avoid relying on PyAV-provided video frame count

utils/dataset_manifest/core.py
As far as I can see, the `only_key_frames` parameter to `VideoManifestManager.link` is not, and has never been, used, and therefore `KeyFramesVideoStreamReader` is unused as well. …
=> Remove unused class KeyFramesVideoStreamReader

CHANGELOG.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/review/hidden-issue-label.tsx, cvat-ui/src/components/annotation-page/review/issue-dialog.tsx, cvat-ui/src/components/annotation-page/review/styles.scss, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/issues-list.tsx, cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss, cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
* The latest comment shown in the sidebar
* Added ability to copy comments content
* Fixed some inconvenient behavior when canvas fit/moved or context menu for a shape opened when user acts on issue dialog
* Fixed blur effect appearing in some cases by changing css rules …
=> Improved issues comments pipeline

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, changelog.d/fragment.j2, changelog.d/legacy.md, changelog.d/scriv.ini
This is beneficial in multiple ways:
* No more `CHANGELOG.md` merge conflicts and mis-merges.
* At release time all you need to do to update the changelog is run `scriv collect --version X.Y.Z`.
Scriv can also create GitHub releases, although I haven't evaluated this feature yet.
Configure scriv so that its output format is the same as what we currently use for our changelog. There are only a few minor differences:
* scriv prepends an HTML anchor to every version heading.
* scriv puts blank lines between list items (in CommonMark terms, the lists are loose rather than tight).
- ~~[ ] I have linked related …
=> Switch to using scriv for maintaining the changelog

cvat-ui/src/components/create-cloud-storage-page/manifests-manager.tsx, tests/cypress/e2e/actions_tasks3/case_105_cloud_storage.js
=> Added test for manifest filetype

cvat-core/src/download.worker.js, cvat-core/src/server-proxy.ts
=> Added temporary workaround to fix corrupted zip file

changelog.d/20231006_155231_persist_image_filters.md, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/gamma-filter.tsx, cvat-ui/src/reducers/settings-reducer.ts, cvat-ui/src/utils/fabric-wrapper/gamma-correciton.ts
=> Persist image filters across jobs

.github/workflows/prepare-release.yml, dev/update_version.py
This automates the first half of the current release process. The second half will be implemented by another workflow.
The reason why it can't all be done in a single workflow is that it's useful to let developers inspect what'll go into the release before actually publishing it, and to apply any last-minute fixes, if necessary. It also allows CI to complete for the release PR.
To support the new workflow, add a `--set` option to `update_version.py` that sets the version to a custom value.
Manual testing on my fork of CVAT. See a test run here: <https://github.com/SpecLad/cvat/actions/runs/6459901481>.
- ~~[ ] I have linked related issues …
=> Add a GitHub workflow to prepare a release pull request

cvat-core/src/server-proxy.ts
Do not pollute local storage by TUS records.
Details are here: https://github.com/tus/tus-js-client/blob/main/docs/api.md#storefingerprintforresuming 
=> Disabled TUS resume upload option (not used, but pollutes local storage)

changelog.d/20231011_153251_andrey_fix_siammask.md, serverless/pytorch/foolwood/siammask/nuclio/main.py
```python
"Exception caught in handler - \"not enough values to unpack (expected 3, got 2)\": Traceback (most recent call last):
File \"/opt/nuclio/_nuclio_wrapper.py\", line 143, in serve_requests
await self._handle_event(event)
File \"/opt/nuclio/_nuclio_wrapper.py\", line 397, in _handle_event
entrypoint_output = self._entrypoint(self._context, event)
File \"/opt/nuclio/main.py\", line 29, in handler
shape, state = context.user_data.model.infer(image, shape, states[i] if i < len(states) else None)
File \"/opt/nuclio/model_handler.py\", line 56, in infer
self.config['hp'], device=self.device)
File \"/opt/nuclio/SiamMask/tools/test.py\", line 152, in siamese_init
z_crop = get_subwindow_tracking(im, target_pos, p.exemplar_size, s_z, avg_chans)
File \"/opt/nuclio/SiamMask/tools/test.py\", …
```
=> Fixed Siammask tracker error on grayscale images

.editorconfig
I realized that I was fighting my editor, because we indent YAML files with 2 spaces, but `.editorconfig` specifies 4 spaces for all files.
Align the config with reality.
I checked that the settings were applied correctly with the CLI `editorconfig` tool. …
=> Override EditorConfig settings for YAML files

changelog.d/20231012_095633_klakhov_fix_memory.md, cvat-ui/src/components/annotation-page/review/issues-aggregator.tsx
=> Fixed object states memory leak

changelog.d/20231012_105902_sekachev.bs_fixed_crash.md, cvat-ui/src/actions/annotation-actions.ts
=> Fixed crash related to issue tries to mount to not existing parent

changelog.d/20231012_131418_sekachev.bs_fixed_google_translator.md, cvat-ui/src/index.html
=> Disabled translation the page causing the issues

changelog.d/20231012_113210_andrey_update_nginx_config.md, cvat/nginx.conf
=> Enabled nginx proxy buffering

changelog.d/20231012_145036_maria_fix_getting_cs_content_when_s3_contains_empty_dirs.md, cvat/apps/engine/cloud_provider.py
This PR fixes retrieving cloud storage content for an AWS S3 bucket containing manually created "directories" (AWS ListObjectsV2 API returns such objects within the content).
A similar problem can be found [here](https://stackoverflow.com/questions/75620230/aws-s3-listobjectsv2-returns-folder-as-an-object). In this case, I prefer to simply filter keys from keys with a trailing slash, rather than filter from objects with 0 size.
Manually
~~- [ ] I have increased versions of npm …
=> Fix getting CS content when S3 bucket contains created manually directories

changelog.d/20231013_095118_boris_optimize_masks.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/groupHandler.ts, cvat-canvas/src/typescript/interactionHandler.ts, cvat-canvas/src/typescript/masksHandler.ts, cvat-canvas/src/typescript/shared.ts, cvat-core/package.json, cvat-core/src/annotations-collection.ts, cvat-core/src/annotations-objects.ts, cvat-core/src/api.ts, cvat-core/src/exceptions.ts, cvat-core/src/object-utils.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Snapshot 5 after playing the frames twice before the patch
Snapshot 6 after playing the frames twice after the patch
Resolved #6994
TODO: 
=> Significant memory optimization when working with masks

changelog.d/20231016_144002_maria_gcs_skip_manually_created_dirs.md, cvat/apps/engine/cloud_provider.py
The same problem for GCS as was fixed for AWS S3 https://github.com/opencv/cvat/pull/6997 …
=> [GCS] Skip manually created dirs

README.md
This PR adds two links to the CVAT README `Links` section. The first link is a tutorial written by the Roboflow team on how to use CVAT and the second link shows the Roboflow guide to using models for automatic labeling in CVAT. I would love for the Roboflow + CVAT integration to be more accessible to new users; the faster someone can label, the quicker they can get a model into production.
=> Add new community links to the `Links` README section

.github/workflows/main.yml, dev/check_changelog_fragments.py
This'll help prevent simple mistakes that would cause scriv to assemble the changelog incorrectly. …
=> Add basic checks for changelog fragments to CI

.github/workflows/finalize-release.yml, .github/workflows/prepare-release.yml, dev/gh_release_notes.sh
This automates the second half of the release process (the first being automated by `prepare-release.yml`). After this workflow completes, the only action that should remain for the releaser to do is to merge the `dev-release-*` pull request. We can't do that as part of this workflow, because CI has to finish first, and it seems pointless to create another workflow just to merge 1 PR.
Apply some of the aspects of this pipeline to `prepare-release.yml` as well:
* Make the release notes extraction process more sophisticated to work around GitHub's frustrating handling of line breaks in PR and release descriptions.
* Use GitHub app credentials in order to be able to trigger other pipelines.
I tried the pipelines on my CVAT fork.
- ~~[ ] I have …
=> Add a GitHub workflow for finalizing a release

changelog.d/20231018_103441_maria_add_test_for_retrieving_bucket_content_with_manually_created_dirs.md, tests/python/rest_api/test_cloud_storages.py
=> Add test for retrieving bucket content when bucket contains manually created dirs

changelog.d/20231017_194639_roman_auto_annotate_no_load.md, cvat-sdk/cvat_sdk/auto_annotation/driver.py, cvat-sdk/cvat_sdk/datasets/common.py, cvat-sdk/cvat_sdk/datasets/task_dataset.py, tests/python/sdk/test_datasets.py
We don't need existing annotations in order to re-annotate a task, but they were being fetched anyway, because that's how the underlying `TaskDataset` class works.
Add an option to `TaskDataset` to disable annotation loading, and use it in `auto_annotate` to prevent those unnecessary fetches.
Unit tests.
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning …
=> Don't fetch existing annotations in `cvat_sdk.auto_annotation.annotate_task`

cvat-sdk/cvat_sdk/core/client.py
I think the spirit of the `SUPPORTED_SERVER_VERSIONS` constant is to allow the same and the next minor versions as the SDK, so just derive those versions automatically instead of bumping them every minor release.
I examined `cvat_sdk.Client.SUPPORTED_SERVER_VERSIONS` in the REPL.
- ~~[ ] I have linked related issues~~ (see [GitHub docs]( …
=> SDK: determine supported server versions automatically

changelog.d/20231024_105610_boris_fix_detectron.md, serverless/pytorch/facebookresearch/detectron2/retinanet_r101/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/detectron2/retinanet_r101/nuclio/function.yaml
Resolved #6895
Can't deploy. See the issue: https://github.com/facebookresearch/detectron2/issues/5010 
Manual testing
=> Fixed:  module 'PIL.Image' has no attribute 'LINEAR'

changelog.d/20231025_101044_boris_keypoints.md, cvat-canvas/package.json, cvat-canvas/src/typescript/canvasView.ts, tests/cypress/e2e/features/masks_basics.js
=> Fixed: a mask becomes visible even if hidden after changing opacity level 

backend_entrypoint.sh, changelog.d/20231024_190737_roman_docker_compose_external_db.md, cvat/settings/base.py, docker-compose.external_db.yml, site/content/en/docs/administration/basics/installation.md
This would help users who don't want or need the complexity of Kubernetes, but would still like to use an external database.
With Docker Compose, you can initialize a secret from an environment variable, but you can't load a secret _into_ an environment variable. So in order to be able to read the DB password from a secret, I had to introduce a new `CVAT_POSTGRES_PASSWORD_FILE` variable.
([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-c …
=> Support running CVAT with an external database via Docker Compose

changelog.d/20231030_124607_maria_test_for_default_prefix.md, cvat/apps/engine/cloud_provider.py, tests/python/rest_api/test_cloud_storages.py, tests/python/rest_api/test_tasks.py, utils/dataset_manifest/core.py
This PR contains REST API tests for https://github.com/opencv/cvat/pull/6943
~~- [ ] I have created a changelog fragment ~~ …
=> REST API tests for default bucket prefix

changelog.d/20231106_112434_boris_fixed_opencv_runtime_init.md, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx, cvat-ui/src/utils/opencv-wrapper/opencv-wrapper.ts
=> Fixed opencv runtime initialization

changelog.d/20231107_145655_maria_handle_task_creation_withvideo_from_cs_and_cache.md, cvat/apps/engine/task.py
This PR ignores the `use cache` option on the server when creating tasks with cloud storage data (except images) …
=> Handle task creation with unsupported data types from cloud storage with cache enabled

changelog.d/20231104_113802_mzhiltsov_fix_atomic_uses.md, cvat/apps/engine/serializers.py
It's possible to get more than 1 GT job in a task in the case of concurrent creation requests.
This PR fixes this by introducing a task row-level lock in the DB for the update transaction.
- Fixed GT job creation race condition …
=> Fix GT job creation races

changelog.d/20231110_134452_roman_helm_keep_pvc.md, helm-chart/Chart.yaml, helm-chart/templates/cvat_backend/storage.yml
Currently, Helm will delete the PVC when you uninstall your CVAT release, which makes it easy to unintentionally lose data. Add a `helm.sh/resource-policy` annotation to prevent that from happening.
This makes the data PVC consistent with the other PVCs created as part of the Helm chart (ones belonging to PostgreSQL, KeyDB and Clickhouse), which are also not deleted upon uninstall, albeit for a different reason: they are created by the corresponding StatefulSets, and StatefulSets retain their volumes when they are deleted.
I installed and uninstalled the chart, and verified that the PVC stayed behind. …
=> Helm: keep the data PersistentVolumeClaim after uninstall

changelog.d/20231113_174833_roman_refactor_values.md, helm-chart/templates/cvat_backend/initializer/job.yml, helm-chart/templates/cvat_backend/server/deployment.yml, helm-chart/templates/cvat_backend/utils/deployment.yml, helm-chart/templates/cvat_backend/worker_analyticsreports/deployment.yml, helm-chart/templates/cvat_backend/worker_annotation/deployment.yml, helm-chart/templates/cvat_backend/worker_export/deployment.yml, helm-chart/templates/cvat_backend/worker_import/deployment.yml, helm-chart/templates/cvat_backend/worker_qualityreports/deployment.yml, helm-chart/templates/cvat_backend/worker_webhooks/deployment.yml
The templates for the various backend service deployments differ in many ways, but a lot of those differences can be eliminated. That way, it becomes easier to compare different templates, to create new services, and to make changes across all templates.
Specific differences which are eliminated are as follows:
* Different sets of values are used for customization. This can be mitigated by putting the specific set of values in a local variable once. That way, only the variable assignment needs to differ.
* Containers and volumes are named differently. There's no need for this, since these names are local to a pod. Just name all analogous containers/volumes the same thing.
* Some deployments use different values for the `app` label. This just seems incorrect, since they all belong to the …
=> helm-chart: make backend templates more uniform

changelog.d/20231116_140728_roman_backend_settings.md, helm-chart/templates/cvat_backend/initializer/job.yml, helm-chart/templates/cvat_backend/server/deployment.yml, helm-chart/templates/cvat_backend/utils/deployment.yml, helm-chart/templates/cvat_backend/worker_analyticsreports/deployment.yml, helm-chart/templates/cvat_backend/worker_annotation/deployment.yml, helm-chart/templates/cvat_backend/worker_export/deployment.yml, helm-chart/templates/cvat_backend/worker_import/deployment.yml, helm-chart/templates/cvat_backend/worker_qualityreports/deployment.yml, helm-chart/templates/cvat_backend/worker_webhooks/deployment.yml, helm-chart/values.yaml
Since backend pods are all fairly similar, it stands to reason that users would want to apply similar configuration to them. Add some `cvat.backend.*` parameters that are applied to all backend deployments/jobs. …
=> helm-chart: add a way to easily set parameters for all backend pods

changelog.d/20231107_183551_roman_traefik_logs.md, docker-compose.https.yml, docker-compose.yml, helm-chart/values.yaml
This will be useful for debugging issues and gathering statistics.
Use the JSON format, since that allows us to include more information than the traditional HTTP access logs. Switch the other logs to JSON as well, for ease of parsing. …
=> Turn on Traefik access logs

changelog.d/20231121_105913_sekachev.bs_fixed_multiple_changing_job_state.md, cvat-core/src/session.ts
403 code when updating job state many times. Steps to reproduce:
1. Open a job from Supervisor user in an organization
2. Change job state to any other >> Works.
3. Change job state one more time >> 403 code.
4. Reload the page, change job state again >> Works.
Manually …
=> Fixed multiple changing job state

changelog.d/20231122_111559_sekachev.bs_fixed_exif.md, cvat/apps/engine/media_extractors.py, tests/python/rest_api/test_tasks.py
=> Fixed missed exif rotation

changelog.d/20231122_124701_klakhov_fix_ux_issues_models_page.md, cvat-ui/src/components/models-page/empty-list.tsx, cvat-ui/src/components/models-page/styles.scss
- Fixed centering of empty block
- Fixed inconsistency in top bar
- Fixed padding of page numbers
- ~~[] I have updated the documentation accordingly~~
[cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~ …
=> Fix UX issues on models page

changelog.d/20231123_093015_sekachev.bs_fixed_drawn_marker.md, cvat-canvas/src/typescript/masksHandler.ts
=> Fixed drawn marker

changelog.d/20231129_112017_canyigitozen_helm_traefik_middleware.md, helm-chart/templates/analytics/middlewares/forwardauth.yaml, helm-chart/templates/analytics/middlewares/stripprefix.yaml
This PR is complementary to #7132. 
#7132 updated ingress templates to work with `traefik.enabled=false` and `ingress.enabled=true` values.
However the templates in `templates/analytics/middlewares` path lead to creation of resources of kind `Middleware`, which is a Traefik CRD. Helm install fails if Traefik is not installed on the cluster.
Changing the top-level conditional from `ingress.enabled` to `traefik.enabled` solves the issue.
=> [Helm] Don't try to install Traefik Middleware when Traefik is disabled

tests/cypress/e2e/issues_prs/issue_7176_opacity_reset.js
Cypress test for #7186  #7176 
=> Added test for opacity reset

serverless/openvino/omz/intel/text-detection-0004/nuclio/model_handler.py
I noticed this while I was redeploying this function. `is`-based comparisons against numeric literals are not guaranteed to work.
I tested the function manually. …
=> Fix a SyntaxWarning in serverless/openvino/omz/intel/text-detection-0004

changelog.d/20231129_112732_canyigitozen_helm_chart_kube_version.md, helm-chart/Chart.yaml
Fixes #7182 by including pre-release versions as explained in the [helm docs](https://helm.sh/docs/chart_template_guide/function_list/#working-with-prerelease-versions).
=> [Helm] Allow pre-release k8s versions to fix AWS EKS deployments

changelog.d/20231009_140340_roman_HEAD.md, serverless/onnx/WongKinYiu/yolov7/nuclio/function-gpu.yaml
Currently, we install plain `onnxruntime`, which means that when the function is deployed with `deploy_gpu.sh`, it ends up using the CPU anyway.
Fixes #6793.
[cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning) …
=> YOLOv7: use the correct version of ONNX Runtime for GPU

Dockerfile.ui, cvat-ui/webpack.config.js
=> Added ability to disable source maps generation

cvat/apps/lambda_manager/views.py
Since [rq Job.fetch_many](https://github.com/rq/rq/blob/d11094af95188c197a5e11b1c4fa05b000485370/rq/job.py#L604) can return `None` we must explicitly check that job exists.
=> Fix LambdaQueue.get_jobs method

changelog.d/20231204_141903_roman_ui_retry_429.md, cvat-core/package.json, cvat-core/src/axios-config.ts, cvat-core/src/download.worker.ts, cvat-core/src/server-proxy.ts, yarn.lock
This should help reduce breakage if a user hits an API rate limit. …
=> cvat-core: retry HTTP requests if a 429 status is returned

changelog.d/20231204_124652_roman.md, serverless/onnx/WongKinYiu/yolov7/nuclio/function-gpu.yaml, serverless/pytorch/dschoerk/transt/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/detectron2/retinanet_r101/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml, serverless/pytorch/foolwood/siammask/nuclio/function-gpu.yaml, serverless/pytorch/saic-vul/hrnet/nuclio/function-gpu.yaml, serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio/function-gpu.yaml, serverless/tensorflow/matterport/mask_rcnn/nuclio/function-gpu.yaml
Having both CPU and GPU images use the same image name and tag is confusing, since you can't tell which one you have on your system without deep inspection.
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) …
=> Use different tags for GPU versions of serverless functions

changelog.d/20231207_143832_roman_revert_keydb.md, docker-compose.yml, helm-chart/Chart.yaml, helm-chart/values.yaml
That KeyDB version turned out rather unstable in practice, with multiple crashes and freezes observed in production.
Resolved #7238
This reverts commit 118cc720ca6da62ffdf8048d2d150b8a44ba48bf. …
=> Revert "Update keydb to 6.3.4 (#7118)"

changelog.d/20231208_152516_andrey_workarround_cache_corrupted_data.md, cvat/apps/engine/cache.py
=> Recreate a chunk in case of UnpicklingError

changelog.d/20231205_204101_jootten_fix_validation.md, cvat/apps/engine/serializers.py
It is not possible to attach a GCS cloud storage bucket which name contains a dot. As stated [here](https://cloud.google.com/storage/docs/buckets#naming), GCS bucket names allow dots. This is a major problem for us, and this PR fixes this issue.
No tests required. …
=> Fix GCS bucket name validation

changelog.d/20231123_141337_roman_fix_docker_compose_compat.md, docker-compose.yml
In 6ae1cffd, I accidentally left behind the empty `command:` key. This works, but only with Docker Compose v2.17.1+. Since we don't actually need this key, we might as well remove it and restore compatibility with older versions.
Also, rearrange the commented out code so that you only need to uncomment one block to enable the Traefik dashboard.
Fixes #7153. …
=> Fix compatibility with older versions of Docker Compose

docker-compose.ci.yml, docker-compose.dev.yml, site/content/en/docs/contributing/development-environment.md
The advantages of this are as follows:
* It's much easier for a developer to use one `docker compose up` command to bring everything up than to run a custom command for each service.
* We eliminate possible divergence of configuration (e.g. versions, command-line parameters) between what we actually use and what's listed in the documentation.
* It makes it easier to update the developer guide if new dependencies are introduced.
* And speaking of new dependencies, we have KeyDB now, which hasn't been added to the dev guide.
The disadvantage is that we have to run an extra copy of the CVAT server, because otherwise OPA can't fetch its rules. I don't think it's a significant issue, since it doesn't prevent you from debugging anything.
Working on #7245, I realized that I don't want to add …
=> Simplify the dev environment setup instructions by reusing Compose files

.github/workflows/full.yml, .github/workflows/main.yml
Currently, the testing pipeline downloads a copy of OPA from the official site. But we already have a perfectly usable copy in the Docker image that we download for the Django unit tests. So just use that copy instead.
This reduces the amount of downloading the pipeline has to do, and eliminates a hardcoded version number.
I ran the new test command locally. …
=> Use OPA from the Docker image for testing

.vscode/settings.json
See <https://devblogs.microsoft.com/python/python-in-visual-studio-code-november-2023-release/>.
You're now supposed to enable Pylint by installing the [Pylint extension](https://marketplace.visualstudio.com/items?itemName=ms-python.pylint). …
=> Remove deprecated VS Code settings

Dockerfile, changelog.d/20231215_165536_roman_split_redis.md, cvat/settings/base.py, docker-compose.dev.yml, docker-compose.yml, helm-chart/Chart.yaml, helm-chart/templates/_helpers.tpl, helm-chart/templates/cvat-redis-secret.yml, helm-chart/values.yaml, site/content/en/docs/contributing/development-environment.md, supervisord/utils.conf, supervisord/worker.analytics_reports.conf, supervisord/worker.annotation.conf, supervisord/worker.export.conf, supervisord/worker.import.conf, supervisord/worker.quality_reports.conf, supervisord/worker.webhooks.conf, tests/python/rest_api/test_queues.py, tests/python/rest_api/test_tasks.py, tests/python/shared/fixtures/init.py, wait_for_deps.sh
These types of data have different characteristics and we have different expectations on them:
* job queues are small and we'd rather not lose them (although losing them is not fatal);
* cached chunks are large and we don't care if we lose them.
We currently store both in KeyDB, which has shown itself to not be especially reliable. A few times we've had to clear the KeyDB store due to data corruption, which destroyed the queues as well. While we'll probably end up replacing KeyDB with something else, it would still be useful to have the ability to just clear the cache volume without taking out the job queues in the process.
As a solution to this, add a Redis service to be used only for the queues (and potentially for other small data items). Using the original Redis instead of KeyDB …
=> Use separate services for storing job queues and cache

cvat-ui/src/config.tsx, site/build_docs.py, site/config.toml
=> Fixed docs building

changelog.d/20231225_115001_boris_retry_if_504.md, cvat-core/package.json, cvat-core/src/annotations-actions.ts, cvat-core/src/annotations-collection.ts, cvat-core/src/annotations-objects.ts, cvat-core/src/annotations-saver.ts, cvat-core/src/exceptions.ts, cvat-core/src/server-proxy.ts, cvat-core/src/server-response-types.ts, cvat/apps/dataset_manager/task.py
=> 504 on save annotation, workaround

changelog.d/20231228_131558_boris_fixed_couple_of_gt_bugs.md, cvat-canvas/src/typescript/canvas.ts, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/shared.ts, cvat-core/package.json, cvat-core/src/api-implementation.ts, cvat-core/src/quality-conflict.ts, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-context-menu.tsx, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/review/issues-aggregator.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/review-reducer.ts
1. When there are conflicts on the first frame, they are not highlighted properly if CHANGE_FRAME_SUCCESS is not fired yet
2. UI crash if to hide some annotations related to a conflict and hover mouse over the conflict …
=> Fixed two issues with GT annotations

cvat-core/src/annotations-saver.ts
In some cases IDs assigned by the server are not updated after saving (e.g. in tracks and skeleton elements)
That does not affect UX, but it makes the server to remove and recreate objects instead of updating them
Feel free to contact the maintainers …
=> Correct updating server ID after patching annotations

changelog.d/20240118_100807_boris_better_errors_messaging.md, cvat-core/src/download.worker.ts, cvat-core/src/server-proxy.ts, cvat-ui/src/components/cvat-app.tsx, cvat/apps/iam/serializers.py
Resolved #7365
instead of
instead of 
instead of
instead of
instead of
=> Enhanced errors notifications

tests/cypress/e2e/features/masks_basics.js
Added tests for #7295 with various UI improvements considering empty masks …
=> Added test for empty masks issues

changelog.d/20240126_130427_klakhov_fix_opencv_tracker_frame_late.md, cvat-ui/package.json, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx, tests/cypress/e2e/actions_tasks2/case_101_opencv_basic_actions.js
=> Fixed TrackerMIL one frame late

changelog.d/20240130_184639_roman.md, docker-compose.yml
I saw several hundreds of zombie processes accumulate in the Kvrocks container in production. This should fix that. See the comment in `docker-compose.yml` for more explanation.
Note that as far as I'm aware, Kubernetes does not use healthcheck commands configured in Docker images, so this issue should be irrelevant for Kubernetes deployments.
([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas# …
=> Prevent zombie processes from accumulating in the Kvrocks container

changelog.d/20240129_190242_roman_HEAD.md, cvat/apps/events/handlers.py
`traceback.format_exception` adds a `\n` to each element of the resulting list, so the message will always have a pointless `\n` at the end. Removing it makes CSV reports that include the message easier to parse visually, because there's no longer a linebreak in the middle of each line.
Manual testing by triggering an exception. …
=> Strip useless linebreak in the payload of send:exception events

changelog.d/20240201_123603_boris_fixed_exception.md, cvat-canvas/src/typescript/canvasView.ts
We have many exceptions like this: `Cannot read properties of undefined (reading 'toLowerCase')` on app.cvat.ai
It happens because `event.code` property has undefined value.
It is not clear why the value may be undefined, because even with synthetic event it equals empty string in my case. 
So, small fix allows us to reduce number of exceptions …
=> Fixed "Cannot read properties of undefined (reading 'toLowerCase')"

changelog.d/20240201_123339_boris_fixed_exception_1.md, cvat-canvas/src/typescript/sliceHandler.ts
Not affects users somehow, just want to get rid of extra logged exceptions. 
=> Fixed exception "Cannot read properties of null (reading 'plot')"

cvat-ui/src/components/tasks-page/task-item.tsx, tests/cypress/e2e/actions_projects_models/issue_2900_creating_more_one_tasks_from_project_per_time.js
Test creates two tasks in a row
After first task created notification appears: "Task was created"
Immediately after that code creates one more task and checks the notification
But if previous notification is still visible, Cypress sees it and considers as a message for the newest task
Then it goes to project page, but can't find the newest task there because it was not created yet. …
=> Stabilized cypress test: issue_2900_creating_more_one_tasks_from_project_per_time.js

.github/workflows/bandit.yml, .github/workflows/black.yml, .github/workflows/cache.yml, .github/workflows/codeql-analysis.yml, .github/workflows/eslint.yml, .github/workflows/full.yml, .github/workflows/hadolint.yml, .github/workflows/helm.yml, .github/workflows/isort.yml, .github/workflows/main.yml, .github/workflows/publish-artifacts.yml, .github/workflows/pylint.yml, .github/workflows/remark.yml, .github/workflows/schedule.yml, .github/workflows/stylelint.yml, .github/workflows/update-yarn-lock.yml
v3 of these actions use Node 16, which is deprecated in GitHub Actions:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ …
=> Bump actions/checkout and actions/setup-node to v4

cvat/apps/events/event.py, cvat/apps/events/handlers.py
This is a preparatory PR before I add more events. …
=> Reduce repetitive code in cvat/apps/events/handlers.py

changelog.d/20240209_171518_roman_handle_after_transaction.md, cvat/apps/analytics_report/signals.py, cvat/apps/engine/signals.py, cvat/apps/engine/tests/test_rest_api.py, cvat/apps/quality_control/signals.py, cvat/apps/webhooks/signals.py
Non-database actions like deleting directories, sending webhooks, scheduling reports should only be done after the current transaction is committed. If we do it immediately, and the transaction is later aborted, then we will have (for example) sent a webhook about an event that didn't actually happen.
There's also a secondary benefit to moving this action outside of the transaction; the less time we spend inside a transaction, the better, since a transaction may lock out other clients from working on the affected DB rows.
In addition, prevent the affected actions from crashing the view handler with an exception (using the `robust=True` option). I don't think it's reasonable to (for example) return a 500 response to a `PATCH` request just because we failed to send the corresponding …
=> Defer most signal handling code until after the end of the current transaction

cvat/apps/dataset_manager/task.py, cvat/apps/engine/models.py, cvat/apps/engine/signals.py, cvat/apps/engine/views.py, cvat/apps/events/signals.py, cvat/apps/organizations/models.py, cvat/apps/webhooks/models.py, cvat/schema.yml
Currently, there are a lot of places where changing one object requires updating the `updated_date` field on other objects. Usually, the `.save` method is used for this purpose, which results in a generic SQL `UPDATE` query that replaces the values in all columns.
Introduce and use a specialized method that only changes the date. This provides the following advantages:
* Prevents the date updates from overwriting updates to other fields that may happen at the same time.
* Possibly makes the updates more efficient due to fewer columns being updated (I have no data on this, though).
* Makes it easier to recognize the purpose of the query when analyzing logs/live statistics.
* Makes the purpose of the code more obvious.
Additionally, update `__save_job_handler`, where we don't want to save …
=> Don't save all fields of a model when bumping the update date

changelog.d/20240213_010700_roman_import_export_events.md, cvat/apps/engine/views.py, cvat/apps/events/event.py, cvat/apps/events/handlers.py, site/content/en/docs/administration/advanced/analytics.md
This can provide useful statistics on the use of this functionality.
Note that I chose to use the same scope for operations on projects, tasks and jobs, because the import/export operations work more-or-less the same on each of them and have the same parameters. It's still possible to distinguish which type of object the operation was performed on by examining the various `*_id` fields in the event. …
=> Add events for importing/exporting annotations/datasets

changelog.d/20240223_131040_roman_better_timekeeping.md, cvat-core/src/logger.ts, cvat/apps/events/serializers.py, cvat/apps/events/tests/test_events.py, cvat/schema.yml
The first problem is that in the following case, the algorithm would accrue more working time than was actually spent:
A
|-----------|
---------+------------+------> time
B            C
A, B and C are events. Let's say that Te(A) is the timestamp of the end of A, while T(B) and T(C) are the timestamps of B and C, respectively.
The current code in `ClientEventsSerializer.to_internal_value` adjusts `last_timestamp` after processing every event. After A is processed, `last_timestamp` is set to Te(A). After B is processed, `last_timestamp` goes _backwards_ to T(B). So when the algorithm calculates the working time for C, it gets T(C) - T(B), when the correct answer is T(C) - Te(A). The span from T(B) to Te(A) gets counted twice.
Fix this by rewriting the algorithm, so that `last_timestamp` …
=> Fix several problems with the calculation of working time per client event

cvat/apps/iam/rules/tasks.rego
In https://github.com/opencv/cvat/blob/b7cc5627daa04958ed045e4b3fe9fd68ec3c9e01/cvat/apps/iam/rules/tasks.rego#L29-L41, `resource` has a `project` `id` field according to the comment. But in
https://github.com/opencv/cvat/blob/b7cc5627daa04958ed045e4b3fe9fd68ec3c9e01/cvat/apps/iam/permissions.py#L1035-L1052, there is no corresponding `project` `id` field. According to @bsekachev's [suggestion](https://github.com/opencv/cvat/pull/7432#issuecomment-1933675588), this PR removes the `project` `id` in the comment of `tasks.rego`  (cvat/apps/iam/rules/tasks.rego). …
=> Remove project id in the comment of `tasks.rego`

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
Fixes #7531 
I have replaced the previous link with the correct link to the documentation.
~- [ ] I have created a changelog fragment ~
~- [ ] I have updated the documentation accordingly~
~- [ ] I have added tests to cover my changes~
~- [ ] I have increased versions of npm packages if it is necessary~ …
=> Fixed the docs link in ISSUE_TEMPLATE

changelog.d/20240229_185536_sekachev.bs_disable_gt_button.md, cvat-ui/package.json, cvat-ui/src/components/create-job-page/job-form.tsx
=> Disable submit button while creating GT job

cvat-ui/src/components/annotation-page/single-shape-workspace/single-shape-sidebar/single-shape-sidebar.tsx, tests/cypress/e2e/features/single_object_annotation.js
=> Added test for single shape annotation mode

changelog.d/20240305_193358_roman_less_bumpy.md, cvat/apps/dataset_manager/task.py
Currently, `JobAnnotation.update` needlessly bumps the `updated_date` of the job and the task twice (both via `_delete` and `_create`). These updates are costly in terms of time due to the various side effects associated with them (such as webhook sending and event logging), so it's better to avoid doing them gratuitously.
Change the code so that the bumps only happen once.
I simplified the code a bit; previously, the code in `_delete` would only bump the date if something was actually deleted (i.e., the annotations passed in actually existed in the database). Now we just check if there were any annotations we _wanted_ to delete. This means that if a request only deletes non-existent annotations, the date will still get bumped. I don't think it's a significant issue, since this is a …
=> Remove double `updated_date` bumping when saving annotations

cvat/apps/events/signals.py
Diffing the old and new state of the object is fairly costly, so it helps to avoid doing that when it isn't necessary.
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versio …
=> Optimize `update:*` event logging when only `updated_date` is changed

changelog.d/20240308_193911_roman_extra_encoding.md, cvat/settings/base.py
The `PASSWORD` setting is not a URL, so it should not be URL-encoded. …
=> Fix password handling for in-mem Redis

changelog.d/20240305_171241_roman_webhooks_lazy_rendering.md, cvat/apps/webhooks/signals.py
The signal handling code in `cvat.apps.webhooks.signals` always fetches the old version of the resource from the database and serializes it. But if no webhook is defined for the current resource, this work is pointless.
Select the webhooks first, and only then (if necessary) serialize the old resource. Also, move the diffing of the old and new versions to the `post_save` signal handler, to avoid serializing the new version a second time. This leads to a considerable speedup for resources with complicated serializers, such as tasks and jobs, when no webhooks are attached. In my experiments, saving of annotations was sped up by 20-25% with this patch.
This patch also makes the signal handlers more hygienic with the use of temporary attributes. Both the attributes it uses are now prefixed …
=> Speed up resource updates when there are no matching webhooks

changelog.d/20240308_175130_roman_efficient_analytics_debounce.md, cvat/apps/analytics_report/report/create.py
Currently, `schedule_analytics_report_autoupdate_job` attempts to debounce job scheduling by examining existing jobs before scheduling a new one. Unfortunately, the `scheduler.get_jobs` function, which it uses for this purpose, scales poorly. Not only does it fetch IDs of all scheduled jobs (and not just ones related to the current object), but it then fetches information about every job, one by one. The current logic doesn't even need this information, but RQ Scheduler provides no method to get just the IDs.
Replace the current logic with a new lightweight approach that uses a custom Redis key to block scheduling of additional jobs.
- ~~[ ] I have linked related issues …
=> Make analytics report update job scheduling more efficient

changelog.d/20240314_162039_boris_added_scroll_aam.md, cvat-ui/package.json, cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
=> Added overflow scroll in attribute annotation editor

changelog.d/20240314_105752_boris_fixed_ssa.md, cvat-ui/src/components/annotation-page/single-shape-workspace/single-shape-sidebar/single-shape-sidebar.tsx, tests/cypress/e2e/features/single_object_annotation.js
=> Fixed using single shape annotation mode with multiple labels

changelog.d/20240313_014112_umangapatel123_refactor_into_usereducer.md, cvat-ui/src/components/import-dataset/import-dataset-modal.tsx
Refactor code to use useReducer instead of useState. Fixes #7428
'file' and 'fileName' in the uploadParams were not set to null after import. To avoid this change the code to set 'file' and 'fileName' to null after importing is done.
This change is required to make the code clear. The previous code uses many `useState` to manage the state but this version uses `useReducer` to manage all the states.
In the previous code `file` and `fileName` in the `uploadParams` were not set to null after importing was done but this version set it to null so it can not use the previous file while importing annotation.
it solves issue #7428
The changes have been tested manually. The code was tested using different sequences of annotation uploads. The state of each parameter is tested by logging its state …
=> [GSoC2024] fix and refactor import-dataset-modal code (#7428)

cvat/apps/quality_control/quality_reports.py
The existing code creates a row and column for each category in the dataset, plus an extra row/column at the end for unmatched annotations. However, it's not immediately clear what order these rows/columns are in, because all access is done indirectly through the `confusion_matrix_labels_rmap` dictionary.
IMO, this is an unnecessary level of indirection, which obscures the structure of the matrix. It's easier to just assign rows/columns 0..(N-1) to the categories and N to "unmatched".
Do just that. Additionally, factor out the code creating the matrix into a function, because it's used in two places.
- ~~[ ] I have linked …
=> quality_control: refactor confusion matrix initialization

cvat/apps/quality_control/quality_reports.py
In addition, remove code creating an unused annotation summary object from `generate_report`. …
=> quality_control: factor out duplicate annotation summary creation logic

changelog.d/20240318_203856_kavikumarceo.md, cvat-ui/src/components/jobs-page/jobs-page.tsx, cvat-ui/src/components/jobs-page/styles.scss, cvat-ui/src/components/labels-editor/labels-editor.tsx
ref issue: https://github.com/opencv/cvat/issues/7620
I've created a class called `cvat-empty-jobs-list` and added it to a div to make the empty component in the job page aligned in the middle as all other pages having empty component aligned to its center.
=> [GSoC24] Resolved Issue #7620 (Changed the alignment of the empty component in job page)

.vscode/launch.json
The old python debugger configuration will soon be deprecated so I changed it to use debugpy which is the new configuration.
=> Update python debugger configuration

changelog.d/20240321_153828_roman_fix_accuracy_display.md, cvat-core/src/quality-report.ts, cvat-core/src/server-response-types.ts, cvat/apps/quality_control/serializers.py, cvat/schema.yml, tests/python/shared/assets/quality_reports.json
The current formula the UI uses to calculate accuracy is incorrect. The denominator is supposed to be the total sample count, but ds_count + gt_count - valid_count is not the same value. To illustrate:
****      ***.        *...         ****
****      ***.        .*..         ****
****      ***.        ..*.         ****
....      ***.        ....         ***.
ds_count  gt_count  valid_count  total_count (expected)
Each value is the sum of the values in the confusion matrix marked by `*`. The current formula essentially adds values that are off the diagonal twice.
Instead of trying to derive the total count from other values, just transmit the correct value from the server and use it in the UI.
- ~~[ ] I have added …
=> Fix annotation accuracy display in the UI

cvat/apps/engine/backup.py, cvat/apps/engine/models.py, cvat/apps/engine/serializers.py, cvat/apps/engine/tests/test_rest_api.py
This was only used by the Git synchronization functionality, which was removed in #6904. …
=> Remove the per-task `artifacts` directory

site/content/en/docs/administration/advanced/k8s_deployment_with_helm.md
**Issue: ** #7605 
Currently, the command used in the official documentation is not working, and giving error: 
1. **Command Used**: 
```shell
BACKEND_POD_NAME=$(kubectl get pod --namespace $HELM_RELEASE_NAMESPACE -l tier=backend,app.kubernetes.io/instance=$HELM_RELEASE_NAME -o jsonpath='{.items[0].metadata.name}') &&\
kubectl exec -it --namespace $HELM_RELEASE_NAMESPACE $BACKEND_POD_NAME -c cvat-backend-app-container -- python manage.py createsuperuser
```
2. **Actual Output**:
3. **Expected Output**: 
I have run a minikube cluster, and run the as it is command in cluster, which gives error: 
```shell
error: cannot exec into a container in a completed pod; current phase is Succeeded
```
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linki …
=> [GSoC2024] update helm documentation for creating superuser

changelog.d/20240319_142812_klakhov_fix_remove_underlying_pixels.md, cvat-ui/package.json, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/brush-tools.tsx
There is a bug in remove underlying pixels feature. If we enable a feature while drawing a mask it wouldnt be applied. Only the next drawn mask will use the feature.
That happens because core config is not updated properly …
=> Fixed remove underlying pixels feature

CHANGELOG.md, changelog.d/20240326_150326_vidit.agarwal.eee20_changelog_confusion_matrix.md
Added entry to `changelog.md` for PR fixing accumulation of confusion matrix across jobs. As mentioned in https://github.com/opencv/cvat/pull/7604 this is a PR where the necessary changelog entry has been added.
~- [ ] I have updated the documentation accordingly~
~- [ ] I have added tests to cover my changes~
~- [ ] I have linked related issues (see [GitHub docs](
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))~
~- [ ] I have increased versions of npm packages if it is necessary …
=> [GSoC2024] added entry to changelog.md for PR fixing accumulation of confusion matrix across jobs

changelog.d/20240326_133323_roman_segmentation_fix.md, cvat/apps/engine/task.py, tests/python/requirements.txt, tests/python/rest_api/test_tasks.py, tests/python/shared/utils/helpers.py
1. When a task has non-zero overlap and exactly as many frames as needed to create 1 or more complete segments, the current algorithm generates a redundant segment at the end. For example, if size is 5, segment size is 3, and overlap is 1, it generates segments (0, 2), (2, 4), and (4, 4).
The algorithm attempts to compensate for this, but it only works in the case where the segment size is unspecified (and defaults to the total size).
Update the algorithm to handle this correctly in the general case.
2. The algorithm selects a default overlap size of 5 if the media file is a video. However, this might not be a valid value if the task has a very small segment size. In this case, a range of undesirable behaviors may occur, depending on the segment size:
* segments getting generated such …
=> Fix two problems with the task segmentation algorithm

changelog.d/20240326_195957_tahamukhtar20.md, cvat-data/src/ts/cvat-data.ts
Fixes: #7394 
This PR fixes the issue stated in the above-mentioned issue, the issue was caused when a 90 deg-rotated video was added with "Prefer Zip Chunks" disabled, and the image loaded was warped, which is now fixed using the static cropImage function found in this [commit](https://github.com/opencv/cvat/commit/844a72b82c241c2f612debc113de54b2f3612e7e#diff-2ca4b22442f076f5f5c3086ee757649fbaa903a75baca70991e419e2bd1d822fR281) as this was the commit where this issue initially started
Added various images to test the bug fix, this did not require any new test cases. …
=> [GSoC2024] fix warped image loading

.github/workflows/docs.yml, .github/workflows/main.yml
It has occurred to me that the documentation build happens inside the main workflow, which is configured to ignore changes to the docs when determining whether to run. So if a PR only changes the docs... we don't build the docs. That makes no sense.
Fix this by extracting the documentation job into its own workflow, that always runs. The downside of this is that we have to duplicate the work of generating the SDK, but IMO, it's an acceptable sacrifice.
A side effect of this is that a failure to build the docs no longer prevents the publishing of Docker images, but I don't think that was needed in the first place.
- ~~[ ] I have linked …
=> Split off documentation building into its own pipeline

changelog.d/20240312_163919_roman_throttling_quality_reports.md, cvat/apps/analytics_report/report/create.py, cvat/apps/quality_control/quality_reports.py, cvat/utils/background_jobs.py
See #7576 for more details. This patch extracts the high-level throttling functionality added in that patch and reuses it for quality reports.
Note: in that patch I referred to this functionality as debouncing, but throttling seems like a more accurate description. It would be debouncing if the autoupdate job only ran after no updates occurred for a period, which is not how it actually works. …
=> Use the same algorithm to throttle quality reports as analytics reports

changelog.d/20240322_193952_roman_clean_data_serializer.md, cvat/apps/engine/backup.py, cvat/apps/engine/serializers.py, cvat/schema.yml
`original_chunk_type` and `compressed_chunk_type` have no effect, because the task creation code overwrites these values based on `use_zip_chunks`. With `size`, the code relies on the default of zero, and attempting to overriding it will just lead to an incorrect value being saved to the database.
([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas# …
=> Remove several fields from `DataSerializer`

tests/cypress/e2e/actions_objects2/case_17_lock_hide_features.js, tests/cypress/e2e/issues_prs/issue_2485_navigation_empty_frames.js, tests/cypress/support/commands.js
#7654 changed the sidebar layout in such a way that mousing over the "Switch hidden property" button for an object can show a tooltip that obscures the "Switch hidden property for all" button. This is exactly what happens in this test at the end of the "Go to polygon" section.
The test is supposed to work around this, by hiding the tooltips before each section, but the workaround is insufficiently robust. Sometimes, the workaround executes _before_ the tooltip is shown, so it does nothing. Then the tooltip appears and covers up the "Switch hidden property for all" button. Then the next section tries to click this button, and fails.
Fix this by taking another workaround from `issue_2485_navigation_empty_frames.js`, moving it into the `hideTooltips` command, and then using that command in …
=> Fix spurious failures in `case_17_lock_hide_features.js`

changelog.d/20240410_160047_boris_pixelated_masks_layer.md, cvat-canvas/src/scss/canvas.scss, cvat-canvas/src/typescript/masksHandler.ts
Drawn and editable mask before the patch:
After the patch:
=> Mask stays pixelated during editing

cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-basics.tsx, tests/cypress/e2e/features/ground_truth_jobs.js
Update ground truth job test by covering the case in https://github.com/cvat-ai/cvat/pull/7714
=> Check ground truth annotations in GT job

changelog.d/20240415_122324_boris_fixed_admin_504.md, changelog.d/20240415_124543_boris_fixed_504_organization.md, cvat/apps/engine/admin.py
- Using autocomplete to avoid fetching all resources and rendering huge lists
- Disabled some operations to avoid breaking data
- Added some more models (e.g. AnnotationGuide, Assets)
=> Fixed 504 gateway timeout on admin page

cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Just fixed typescript issues, a little bit refactored code.
Should not affect users.
=> Fixed typescript issues in 'tools-control.tsx'

.vscode/launch.json, cvat/apps/iam/apps.py, cvat/apps/iam/utils.py, cvat/apps/iam/views.py, cvat/settings/base.py, docker-compose.yml, helm-chart/templates/cvat_backend/server/deployment.yml
There are three changes here:
* Don't save the bundle to a file. There seems to be no reason to do that; the bundle is very small (<8000 bytes), and we already load it fully into memory to generate the ETag, so just generate it in memory and keep it there.
This also fixes a possible race condition where a server process starts to read the bundle file right as another server process starts up and overwrites it.
* Generate the bundle on-demand rather than at startup. This obviates the need for the `IAM_OPA_BUNDLE` environment variable.
* Generate the ETag once, instead of on every request. There's no reason to hash the same bundle over and over.
A patch I'm working on (the sequel to #7734) requires the bundle to be generated on-demand (and it seems to me like a simpler approach in general). …
=> Improve code for working with the OPA bundle

changelog.d/20240423_142255_klakhov_fix_missing_annotations.md, cvat-canvas/src/typescript/canvasModel.ts, cvat-core/package.json, cvat-ui/package.json, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/containers/annotation-page/annotation-page.tsx, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/index.ts
After the PR #7714 annotations are not loaded to the store with `GET_JOB_SUCCESS` action, instead we load them in separate async action `fetchAnnotationsAsync`. 
That leads to the problem: `CanvasWrapper` component is initially mounted with empty `annotations` array. That leads to such function calls: `updateCanvas` -> ` canvasInstance.setup` -> [the promise is created](https://github.com/cvat-ai/cvat/blob/develop/cvat-canvas/src/typescript/canvasModel.ts#L600) that will set this.data.objects to empty array.
Then the annotations are put to the store, `CanvasWrapper` runs update hook, where the chain is called again: `updateCanvas` -> ` canvasInstance.setup` -> but instead of promise, [the objects are assigned right away](https://github.com/cvat-ai/cvat/blob/develop/cvat-canvas/src/typescri …
=> Fixed showing annotations at 0 frame

changelog.d/20240425_161412_sekachev.bs.md, cvat/apps/iam/permissions.py
To avoid extra requests to the database, opa container and code execution on the server
=> Disable further checking permissions if at least one is False

changelog.d/20240520_121027_boris_fixed_wrapping_bbox.md, cvat-canvas/src/typescript/masksHandler.ts
Because `getDrawnObjectsWrappingBox` returns incorrect [right, bottom] values in case if some shapes are drawn out of the image. See the gif: 
Also it does not disable eraser and polygon-minus tools when it is necessary  …
=> Fixed one way to create an empty mask

.vscode/settings.json
=> Aborted enabling black linter onsave in vscode

cvat-core/src/project.ts, cvat-ui/src/components/create-task-page/create-task-content.tsx, cvat-ui/src/components/create-task-page/project-subset-field.tsx, cvat-ui/src/components/task-page/details.tsx
Requests before fix when changing job stage (task in a project, project not in app state):
After fix:
=> Fixed extra server requests

changelog.d/20240807_113114_boris_support_sam_rect.md, cvat-canvas/src/typescript/interactionHandler.ts, cvat-core/src/core-types.ts, cvat-core/src/ml-model.ts, cvat-ui/plugins/sam/src/ts/index.tsx, cvat-ui/src/actions/annotation-actions.ts, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx, cvat-ui/src/components/annotation-page/standard-workspace/styles.scss, cvat-ui/src/cvat-canvas-wrapper.ts, cvat-ui/src/reducers/annotation-reducer.ts, cvat-ui/src/reducers/index.ts, cvat/apps/lambda_manager/views.py, serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/sam/nuclio/function.yaml
=> Segment Anything: supported bounding box input

cvat-ui/src/components/projects-page/top-bar.tsx, cvat-ui/src/components/tasks-page/top-bar.tsx
=> Added loading icon while importing a task/project backup

.github/PULL_REQUEST_TEMPLATE.md, changelog.d/20250115_190017_roman_rm_ui_versions.md, cvat-canvas/README.md, cvat-canvas/src/typescript/canvas.ts, cvat-canvas3d/README.md, cvat-canvas3d/src/typescript/canvas3d.ts, cvat-core/README.md, cvat-core/src/api.ts, cvat-core/src/index.ts, cvat-data/README.md, cvat-ui/README.md, cvat-ui/package.json, cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx, cvat-ui/src/components/header/header.tsx, cvat-ui/src/cvat-canvas-wrapper.ts, cvat-ui/src/cvat-canvas3d-wrapper.ts, cvat-ui/src/reducers/about-reducer.ts, cvat-ui/src/reducers/index.ts, dev/update_version.py
The only reason to display separate UI and server version (IMO) is that sometimes they can diverge due to deployment issues, and the information can help with diagnostics. So it seems much more useful to use the same version numbering as for the server, since:
* This makes it much easier to see whether a divergence exists.
* We can automate updates to it, eliminating annoying busywork for developers.
* We don't need to show multiple versions for different UI components, simplifying the code and the UI. …
=> Peg the UI version to the server version

tests/python/shared/fixtures/init.py
- Removed warnings about unsafe authentication in Helm test logs
`DEBUG    shared.fixtures.init:init.py:111 Output (stderr): Warning: Using a password with '-a' or '-u' option on the command line interface may not be safe.`
=> Remove redis-cli auth warnings in helm test logs

cvat-data/README.md, package.json
The `server` commands were removed from the sub-packages in #5912 and #7208.
=> Remove obsolete npm scripts

changelog.d/20250121_135206_sekachev.bs_fixed_rendering.md, cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx, cvat-ui/src/components/annotation-page/single-shape-workspace/single-shape-workspace.tsx, cvat-ui/src/components/annotation-page/standard-workspace/standard-workspace.tsx
=> Fixed: Extra shortcuts enabled from brush tools on views where not necessary

changelog.d/20250120_142814_klakhov_fix_start_points.md, cvat-canvas/src/typescript/canvasView.ts
Related: #8859
One of the possible reasons to the issue is `Cannot read properties of undefined (reading 'startPoints')` error. For some unknown reason `handler` object inside of svg js event becomes undefined making an error in dragend hander. This leads to not dispatching `canvas.dragend` event so new object state coords are not saved. When the error occurs, object is visually moved but if we change frame and go back the annotation will be on the previous place.
In this fix, we will use `shape` as source of start point coordinates …
=> Fix: Cannot read properties of undefined (reading 'startPoints')

tests/python/rest_api/test_webhooks_sender.py, tests/python/rest_api/utils.py
Reduces changes of getting problems like these:
https://github.com/cvat-ai/cvat/actions/runs/12830112733/job/35777856334?pr=8943
https://github.com/cvat-ai/cvat/actions/runs/12830417963/job/35778560490?pr=8962
=> Extend some timeouts in tests

tests/cypress/e2e/actions_projects_models/markdown_base_pipeline.js, tests/cypress/e2e/features/skeletons_pipeline.js, tests/cypress/e2e/remove_users_tasks_projects_organizations.js, tests/cypress/support/commands.js
1. For us there should not be difference between clearAllCookies and clearCookies as we only use one domain. Thus using clearAllCookies was removed. 
2. Minimized using of clearCookies, preferred custom command headlessLogout
=> Slightly cleaned up cypress tests

cvat-canvas/src/typescript/canvasView.ts
As skeletons implemented via groups, current approach does not work for them. Thus `shape.x()`, or `shape.y()` are always zero.
The `SVGGraphicsElement.getBBox()` or (`bbox()` in context of svg.js) method allows us to determine the coordinates of the smallest rectangle in which the object fits. The coordinates returned are with respect to the current SVG space (after the application of all geometry attributes on all the elements contained in the target element).
=> Fixed dragging method for skeletons

tests/cypress/e2e/actions_objects/test_annotations_saving.js, tests/cypress/e2e/actions_projects_models/markdown_base_pipeline.js, tests/cypress/e2e/actions_tasks2/test_default_attribute.js, tests/cypress/e2e/actions_users/registration_involved/case_28_review_pipeline_feature.js, tests/cypress/support/commands.js
`headlessCreateUser` now looks easier
`headlessLogin` is more efficient. It allows to get logged in user and immediately go to the target page, additionally handling logout logic. 
=> Refactored couple of Cypress commands

changelog.d/20250127_161502_roman.md, cvat-sdk/cvat_sdk/auto_annotation/functions/_torchvision.py
"N/A" is how torchvision marks the gaps in the COCO label list. Since these "labels" should never be output by the models, we should avoid declaring them.
=> cvat_sdk.auto_annotation.functions: don't declare useless "N/A" labels

serverless/pytorch/dschoerk/transt/nuclio/model_handler.py, serverless/pytorch/foolwood/siammask/nuclio/model_handler.py
Now that GHSA-wq36-mxf8-hv62 is fixed, it is actually safe to use jsonpickle in this context.
I manually tested TransT.
=> Add bandit suppressions to tracker functions

changelog.d/20250124_175956_mzhiltso_optimize_quality_computation.md, cvat/apps/dataset_manager/formats/transformations.py, cvat/apps/dataset_manager/util.py, cvat/apps/quality_control/quality_reports.py
Most noticeable in tasks with large images (e.g. 2k x 4k pixels) and with ellipse annotations. The result is that for a sample task with 157 GT frames and with lots of small ellipse annotations, peak memory consumption falls from 20GB to under 2GB.
- Added lazy ellipse mask / RLE computation (OpenCV's `ellipse()` is quite slow with big masks)
- Removed simultaneous mask materialization for all masks on the image in segmentation matching
- Added batch size restriction in bulk saving of quality reports
=> Optimize quality computation

changelog.d/20250130_123343_roman_refactor_annotation_mapper.md, cvat-sdk/cvat_sdk/auto_annotation/__init__.py, cvat-sdk/cvat_sdk/auto_annotation/driver.py, cvat-sdk/cvat_sdk/auto_annotation/exceptions.py, cvat-sdk/cvat_sdk/auto_annotation/interface.py, site/content/en/docs/api_sdk/sdk/auto-annotation.md, tests/python/sdk/test_auto_annotation.py
This has two main goals:
1. Move all validation that does not depend on the task we're annotating from `_AnnotationMapper` and to `DetectorFunctionSpec`. This a) splits the code into more manageable chunks, and b) works better with the agent workflow, because the CLI `function` commands can reject an invalid function spec immediately (rather than waiting until the first request).
(Frankly, I don't know why I didn't put this code in `DetectorFunctionSpec` in the first place, given that it implements the restrictions described in the docstring...)
Validating the spec upon construction requires that the spec is not modified afterwards. This has always been my intention, but to make it clearer, state it explicitly in the docstring.
2. Restructure the rest of the code into smaller functions. …
=> Refactor `_AnnotationMapper`

tests/cypress/e2e/actions_objects/regression_tests.js, tests/cypress/e2e/features/ground_truth_jobs.js, tests/cypress/e2e/features/requests_page.js, tests/cypress/e2e/issues_prs2/issue_1568_cuboid_dump_annotation.js, tests/cypress/support/commands.js
=> Updated command to create headless objects in Cypress

serverless/onnx/WongKinYiu/yolov7/nuclio/function-gpu.yaml, serverless/onnx/WongKinYiu/yolov7/nuclio/function.yaml, serverless/openvino/dextr/nuclio/function.yaml, serverless/openvino/omz/intel/face-detection-0205/nuclio/function.yaml, serverless/openvino/omz/intel/person-reidentification-retail-0277/nuclio/function.yaml, serverless/openvino/omz/intel/semantic-segmentation-adas-0001/nuclio/function.yaml, serverless/openvino/omz/intel/text-detection-0004/nuclio/function.yaml, serverless/openvino/omz/public/faster_rcnn_inception_resnet_v2_atrous_coco/nuclio/function.yaml, serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio/function.yaml, serverless/openvino/omz/public/yolo-v3-tf/nuclio/function.yaml, serverless/pytorch/dschoerk/transt/nuclio/function-gpu.yaml, serverless/pytorch/dschoerk/transt/nuclio/function.yaml, serverless/pytorch/facebookresearch/detectron2/retinanet_r101/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/detectron2/retinanet_r101/nuclio/function.yaml, serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml, serverless/pytorch/facebookresearch/sam/nuclio/function.yaml, serverless/pytorch/foolwood/siammask/nuclio/function-gpu.yaml, serverless/pytorch/foolwood/siammask/nuclio/function.yaml, serverless/pytorch/mmpose/hrnet32/nuclio/function.yaml, serverless/pytorch/saic-vul/fbrs/nuclio/function.yaml, serverless/pytorch/saic-vul/hrnet/nuclio/function-gpu.yaml, serverless/pytorch/saic-vul/hrnet/nuclio/function.yaml, serverless/pytorch/shiyinzhang/iog/nuclio/function.yaml, serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio/function-gpu.yaml, serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio/function.yaml
`maxWorkers` deprecated in nuclio 1.13.x (currently suggested by CVAT)
Warning message suggest to replace with `numWorkers`
https://docs.nuclio.io/en/1.13.x/reference/function-configuration/function-configuration-reference.html
=> Replace deprecated `maxWorkers` by `numWorker`

changelog.d/20250130_185457_roman.md, docker-compose.https.yml
These are unnecessary and when they're not updated in sync with `docker-compose.yml` (like now) they cause HTTPS deployments to use an outdated version of Traefik.
=> Remove duplicate settings from docker-compose.https.yml

changelog.d/20250128_144218_roman_aa_fun_label_types.md, cvat-sdk/cvat_sdk/auto_annotation/driver.py, cvat-sdk/cvat_sdk/auto_annotation/functions/_torchvision.py, cvat-sdk/cvat_sdk/auto_annotation/functions/torchvision_detection.py, cvat-sdk/cvat_sdk/auto_annotation/functions/torchvision_instance_segmentation.py, site/content/en/docs/api_sdk/sdk/auto-annotation.md, tests/python/sdk/test_auto_annotation.py
These changes are meant to enforce several conditions:
1. A function should not be able to create shapes of type incompatible with the type of the label it declares (for example, if a 
function's label has type `rectangle`, it should not be able to create ellipses with that label).
2. A function should not be able to create shapes of type incompatible with the type of the label in the task being annotated.
3. If a function's declared label has a type incompatible with the type of the corresponding task label, then it should not run at all (since it would be impossible for it to output a shape with that label that wouldn't violate either condition 1 or 2).
Altogether, these restrictions ensure that we don't create any shapes in a task that aren't compatible with that task's label types.
In …
=> AA functions: add more stringent label/shape type compatibility checking

.github/workflows/stylelint.yml, cvat-ui/src/components/export-backup/styles.scss, cvat-ui/src/components/export-dataset/styles.scss, cvat-ui/src/components/global-error-boundary/styles.scss, cvat-ui/src/components/layout-grid/styles.scss, cvat-ui/src/components/storage/styles.scss, cvat-ui/src/components/update-cloud-storage-page/styles.scss, site/assets/scss/_variables_project.scss
This is the equivalent of #5720, but for Stylelint. Inspired by the CI failures in #8998.
Fix all remaining Stylelint warnings, so that CI stays green.
=> CI: run Stylelint on all files, not just changed ones

cvat-ui/src/components/annotation-page/styles.scss
There are two problems with frame filename in player:
- There is no 'ellipsis' if filename is large
- The tooltip appears in wrong position if filename is large
With fix of the frame name styles:
=> Fixed frame name text & tooltip in case of large names

.github/workflows/docs.yml, .github/workflows/eslint.yml, .github/workflows/full.yml, .github/workflows/main.yml, .github/workflows/remark.yml, .github/workflows/schedule.yml, .github/workflows/stylelint.yml, .github/workflows/update-yarn-lock.yml
=> Update Node.js in CI workflows to the latest LTS version

changelog.d/20250205_104118_sekachev.bs_fixed_implicit_change.md, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/consts.ts, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/shared.ts, cvat-core/src/object-utils.ts, cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
=> Fixed: In some cases effect of drag/resize may be reset implicitly for a user

cvat-canvas/src/typescript/canvasView.ts
=> Fixed sometimes edit changes implicitly aborted

changelog.d/20250207_153348_roman_native_function_label_type.md, cvat-cli/src/cvat_cli/_internal/commands_functions.py
This will enable more accurate label type information in the function API, which is used in a few places (for example, in the "From model" feature available when configuring labels for a task).
There will be tests in the private repo.
=> CLI: Let `function create-native` submit label types to the server

cvat-core/src/core-types.ts, cvat-core/src/enums.ts, cvat-core/src/ml-model.ts, cvat-ui/src/components/labels-editor/pick-from-model.tsx, cvat-ui/src/components/model-runner-modal/detector-runner.tsx, cvat-ui/src/components/model-runner-modal/labels-mapper.tsx, cvat-ui/src/cvat-core-wrapper.ts
Recent changes to the Enterprise version make the following simplifications possible:
* A label type may no longer be `unknown`, which means that the type of `MLModelLabel.type` can be changed to `LabelType`, and all special handling for `unknown` can be removed.
* Roboflow and Hugging Face models now correctly report their label types, which makes the dedicated `return_type` field unnecessary. The `ModelReturnType` enum is unnecessary as well, as it's just an arbitrary subset of `LabelType`.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull- …
=> cvat-ui: simplify code related to model label types

changelog.d/20250220_003314_ravinduwe_resource_path_fix.md, cvat-sdk/cvat_sdk/core/proxies/tasks.py
=> Fixing SDK task.upload_data() to accept resources of the Path type

Dockerfile, Dockerfile.ci
* The ones in `Dockerfile` appears to be a remnant of a feature deleted in #1767.
* The ones in `Dockerfile.ci` are irrelevant since #6173 and #8985.
- ~~[ ] I submit _my code changes_ under the same [MIT License](
Feel free to contact the maintainers if that's a concern.~~
=> Remove unnecessary files from Docker images

changelog.d/20250224_114044_sekachev.bs_display_dimensions_support.md, cvat-canvas/src/scss/canvas.scss, cvat-canvas/src/typescript/canvasModel.ts, cvat-canvas/src/typescript/canvasView.ts, cvat-canvas/src/typescript/shared.ts, cvat-ui/src/components/header/settings-modal/workspace-settings.tsx, cvat-ui/src/reducers/settings-reducer.ts, site/content/en/docs/manual/basics/settings.md
Added setting to display shape size of rectangles and ellipses without dragging/resizing them:
=> Added feature to display dimensions of rectangles and ellipses

changelog.d/20250228_163221_mzhiltso_fix_included_frame_handling.md, cvat-core/src/frames.ts, cvat-core/src/server-response-types.ts, cvat-ui/src/components/quality-control/task-quality/allocation-table.tsx
Fixes #9097
- Added a temporary emulation in UI for the upcoming server changes in `/api/task|job/data/meta` `.frames`
- Updated related GT allocation table code
- Fixed type for the `included_frames` field in the related meta API response class
[data_with_related_images.zip](https://github.com/user-attachments/files/19028777/data_with_related_images.zip)
[random_200.zip](https://github.com/user-attachments/files/19028782/random_200.zip)
[random_video_10s.mp4](https://github.com/user-attachments/assets/2e229289-13dc-43e5-9baa-c6361f4e312d) …
=> Fix included frames handling on UI

cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
Currently when we have a following problem:
If a job has frames for example 330-340. And we want to navigate from 335 to 331, we press backspace to delete 5 from input which resets to frame 330 instead of temporary input of 33. We should be able to delete 5 and add 1 without problems
To fix the problem I've added a min and max params into the input. This prevents the input from firing [onChange](https://github.com/cvat-ai/cvat/blob/develop/cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx#L210) event in case when the input number is outside of correct frame range
The problem is that  …
=> Fix a problem with frame player

changelog.d/20250219_184104_roman_agent_skeletons.md, cvat-cli/src/cvat_cli/_internal/agent.py, cvat-cli/src/cvat_cli/_internal/commands_functions.py, cvat-sdk/cvat_sdk/auto_annotation/interface.py, site/content/en/docs/api_sdk/sdk/auto-annotation.md, tests/python/sdk/test_auto_annotation.py
All of the support code in the auto-annotation SDK layer is already there, we just need to send sublabel information when creating a native function, and validate it when running an agent.
In addition, force keypoint sublabel types to be "points", since this is how the UI creates them for tasks/projects.
Tests will be added in the private repository.
=> Add skeleton support for native functions

cvat-ui/src/components/header/styles.scss
- Max width set to 128px instead of fixed 64px
- Logo is not resized anymore to max dimensions by CVAT
=> Adjusted customizable logo size

changelog.d/20250314_163649_roman_superchart_env.md, helm-chart/templates/_helpers.tpl, helm-chart/values.yaml
I have a need to add an environment variable for backend containers in the Enterprise version. `additionalEnv` doesn't work very well for this, because:
* It is an array, so if a user specifies a different value for it with `--set`, any defaults set by the superchart will disappear.
* It is inserted into the resource definition verbatim, so you can't refer to things like the release name.
This patch introduces a separate setting for this purpose. It takes a map, and runs the variable values through `tpl` to support interpolation.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-t …
=> Helm: support adding backend environment variables from supercharts

changelog.d/20250320_144532_maria_fix_500_status_code_in_requests_api.md, cvat/apps/engine/rq.py, cvat/apps/events/export.py, cvat/apps/events/handlers.py
This PR addresses the `KeyError` by making user/request fields in the meta nullable. The issue with empty meta should still be investigated.
=> Fixed 500 status code that could occur when listing requests by `GET /api/requests`

changelog.d/20250321_125005_dmitrii.lavrukhin_memory_optimization_for_task_import.md, cvat/apps/dataset_manager/task.py
When annotations are imported into a task, they are being kept in RAM, even though they are not used.
Stop doing it
=> do not keep in memory task annotations on import

cvat-ui/src/components/consensus-management-page/consensus-management-page.tsx, cvat-ui/src/components/quality-control/quality-control-page.tsx, cvat-ui/src/utils/location-utils.ts
- Applied changes from #9039 to consensus management page
- Unset event listeners on unmount
- Reduced code duplication a little bit
=> Removed code duplication and unset event listeners

cvat/apps/consensus/signals.py, cvat/apps/engine/signals.py, cvat/apps/iam/signals.py, cvat/apps/quality_control/signals.py, cvat/apps/webhooks/signals.py, tests/python/shared/assets/annotations.json, tests/python/shared/fixtures/init.py
To setup test DB CVAT runs `python manage.py loaddata ...`. This command populates the DB with objects from `tests/python/shared/assets/cvat_db/data.json`. This action also invokes signals on the server normally, as specified for models. In some cases it can lead to unexpected errors with duplicate keys in DB - because, for example, a parent object is loaded first, a signal runs to create a nested object, and then the nested object is created once again by `loaddata` when time comes. I'm surprised the current test startup is working without extra steps to disable signals.
References:
- https://stackoverflow.com/questions/3499791/how-do-i-prevent-fixtures-from-conflicting-with-django-post-save-signal-code
- the `raw` parameter in `post_data` …
=> Prevent signals in test db setup

changelog.d/20250325_151144_dmitrii.lavrukhin_less_ram_on_job_annotations_import.md, cvat/apps/dataset_manager/task.py
When annotations are imported into a job, previous annotations are deleted. But after deletion they are kept in memolry for no reason, which can be a problem if they are large.
Dont keep deleted annotations in memory anymore.
=> do not keep deleted annotations in ram

cvat/apps/dataset_manager/tests/test_rest_api_formats.py, cvat/apps/engine/tests/test_rest_api.py, cvat/apps/engine/tests/test_rest_api_3D.py, cvat/apps/engine/tests/utils.py, cvat/apps/lambda_manager/tests/test_lambda.py
There are two different versions of these methods, in `ApiTestBase` and in `_LambdaTestCaseBase`. Since the latter inherits from the former, Pylint warns that the overridden methods are incompatible (and they are!). To fix this, merge these two sets of methods into one, with all needed capabilities.
Some notes on the decisions I made WRT the merged methods:
1. In `_post_request` I emulated the `query_params` parameter from Django 5.1.
2. In `_get_request` I renamed `data` to `query_params` for consistency.
3. In `_patch_request` I decided not to add a `query_params` parameter for now, since it wasn't needed. While some lambda tests called `_patch_request` with an org ID, this parameter was unnecessary, so I just removed it.
4. I set the default format to "json" everywhere, since CVAT's …
=> Merge the `_xxx_request` helper methods in unit tests

changelog.d/20250409_175541_maria_fix_test_check_import_error_on_wrong_file_structure.md, cvat/apps/dataset_manager/formats/cvat.py, tests/python/rest_api/test_tasks.py
There were several issues with this test, like:
- the archive being created was not closed
- exception capture details were never checked
- not all formats return expected error format
=> Fix `test_tasks.py::TestImportTaskAnnotations::test_check_import_error_on_wrong_file_structure`

cvat-ui/package.json, cvat/apps/iam/serializers.py, cvat/settings/development.py, site/content/en/docs/contributing/development-environment.md
Webpack uses `CVAT_UI_HOST` and `CVAT_UI_PORT`
Server uses `UI_HOST` and `UI_PORT`.
This patch removes the duplication. 
Additionally webpack dev server may be initialized by `CVAT_HOST` now. 
=> Re-use common env variables in dev env

cvat-ui/package.json, cvat-ui/webpack.config.js
Without this header CVAT backend generates wrong links for logo, exports, etc when webpack dev server is running on something else rather than `localhost`.
Alternative solution we used before is to expose backend server together with frontend server, however:
1. Additional configuration is required to run django server outside. 
2. It works, but URLs anyway have different ports. 
3. Two exposed ports worse than one exposed port. 
=> Use x-forwared-host on debug web server

changelog.d/20250417_121137_sekachev.bs_truncate_rotation.md, cvat-core/src/annotations-objects.ts
In #9289 we truncate rotation with precision 5 digits because of floating arithmetics. 
However for existing rotated shapes saved with higher precision the first resizing the issue is still relevant 
Resolved #9308
=> Fixed rotation of shapes existing in CVAT before #9289

changelog.d/20250425_104058_sekachev.bs_fixed_exception.md, cvat-canvas/src/typescript/drawHandler.ts, cvat-canvas/src/typescript/editHandler.ts, cvat-canvas/src/typescript/svg.patch.ts
Scenario
1. Draw a 2D cuboid
2. Copy it
3. Paste it with ctrl several times
UI crashes. 
Reason?
So, different things are not looks good. For example canvas should not be called .configure method on any change in annotations. `configure` probably should not call `transform` when unnecessary. Or unnecessary `paintHandler` objects should not be created when transform called for different shapes.
But the core reason for this error is that we call `transform` on any drawInstance when it only defined for `rect`, `polygon`, `points`. I tried to understand why we added these custom methods 5 years ago, unsuccessfully. Then I tried to remove them and everything works in latest Chrome and Mozilla. So, maybe we just do not need them. 
https://help.github.com/en/github/managing-your-work-on-github/li …
=> Fixed exception when paste polygon with ctrl hold

changelog.d/20250428_153328_fix_service_name.md, docker-compose.external_db.yml
- In docker-compose.external_db.yml, update service name cvat_utils to cvat_worker_utils
Change is required for CVAT deployments that connect to an external DB
This resolved an observed issue with a CVAT deployment that connects to an external DB
- [x ] I submit my changes into the `develop` branch
- [x ] I have linked related issues (see [PR #9200 Rework startup of container processes breaks External DB docker compose up](
https://github.com/cvat-ai/cvat/issues/9334))
- [ x] I submit _my code changes_ under the same [MIT License]( …
=> Update service name cvat_utils to cvat_worker_utils

tests/python/shared/utils/dump_objects.py
This involves two things:
1. Make the output directory configurable.
2. Instead of hardcoding resource types, rewrite every file that already exists.
=> Make the dump_objects.py script easier to use in the private repo

cvat-ui/src/base.scss, cvat-ui/src/components/common/cvat-table.tsx
Minor improvements in CVAT Table component
Search tooltip:
Empty position fixed:
=> Added tooltip for search, adjusted styles, fixed types

changelog.d/20250429_164556_roman_cli_password_prompt.md, cvat-cli/src/cvat_cli/_internal/common.py
The current behavior is mildly inconvenient, since if the user asks for `--help` or enters an invalid command, they are still prompted for the password, even though that password isn't used.
I also added a minor usability improvement, adding the server and username into the password prompt.
=> CLI: don't prompt for the password until arguments are parsed

changelog.d/20250501_200258_roman_deprecate_schema_autodetection.md, cvat-cli/src/cvat_cli/_internal/common.py, cvat-sdk/cvat_sdk/core/client.py, site/content/en/docs/api_sdk/cli/_index.md, site/content/en/docs/api_sdk/sdk/auto-annotation.md, site/content/en/docs/api_sdk/sdk/highlevel-api.md, site/content/en/docs/api_sdk/sdk/pytorch-adapter.md
This feature is fundamentally insecure. If a user makes use of this, then a MitM could trivially block the HTTPS connection attempt, causing the SDK to downgrade to HTTP. Even in the absence of an active attacker, a transient error could cause a downgrade, leading to request details and credentials being exposed in cleartext.
In addition, this feature creates a usability problem, because if the autodetection fails, the user is given no information about the cause. This could be fixed, but given the main issue, I don't think it's worthwhile.
I don't think we can just remove this feature immediately, given that the SDK has worked this way for a long time, and there are certainly people relying on it. Therefore, in this patch I just add a big warning, and recommend specifying the scheme …
=> SDK: Deprecate server URL scheme autodetection

changelog.d/20250423_093422_justinehlert_fix_match_labels.md, helm-chart/templates/cvat_backend/server/deployment.yml, helm-chart/templates/cvat_backend/worker_annotation/deployment.yml, helm-chart/templates/cvat_backend/worker_chunks/deployment.yml, helm-chart/templates/cvat_backend/worker_consensus/deployment.yml, helm-chart/templates/cvat_backend/worker_export/deployment.yml, helm-chart/templates/cvat_backend/worker_import/deployment.yml, helm-chart/templates/cvat_backend/worker_qualityreports/deployment.yml, helm-chart/templates/cvat_backend/worker_utils/deployment.yml, helm-chart/templates/cvat_backend/worker_webhooks/deployment.yml, helm-chart/templates/cvat_frontend/deployment.yml, helm-chart/templates/cvat_kvrocks/statefulset.yml, helm-chart/templates/cvat_opa/deployment.yml
Fixes #9357 
Since matchLabels are immutable, the deployment breaks if you try to add new labels to one of the cvat or worker pods.
To avoid this, use a subset of unique but unchanging labels for your matchLabels - in this case these are defined by the selectorLabels template.
Tested with our helm deployment. In order to redeploy I had to run the following commands:
```
kubectl -n cvat delete --cascade=false deployment --all
kubectl -n cvat delete --cascade=false sts cvat-kvrocks
```
=> Use selectorLabels helper for matchLabels in helm

cvat/apps/engine/tests/test_rest_api.py
This PR migrates from `unittest.assertEquals` to `unittest.assertEqual` which is deprecated from Python2.7:
```python
DeprecationWarning: Please use assertEqual instead.
```
Run tests.
=> Resolve warnings of testing library

cvat/apps/engine/views.py
As far as I can see, `CloudStorage` is not used for anything else in this module, so there's no conflict. Removing the alias makes the imports a bit more readable.
=> Remove unnecessary import alias

cvat/apps/dataset_manager/util.py, cvat/apps/engine/filters.py, cvat/apps/engine/views.py
Which, as it happens, is all of them. In all these cases, using `format` results in more compact, easier-to-read code.
I was looking into blackening some of these source files, and I saw that the `format_map` usage results in uglier formatting than it could be if we used `format`.
=> Remove unnecessary uses of `str.format_map`

cvat/apps/engine/management/commands/initcontentsize.py
This filter does not seem to be necessary.
Initially I added it to calculate only those objects where data were extracted, segments prepared, etc.
However it is not really necessary, even if the command calculates not ready tasks yet, that is not scary. 
At the same time we want to know content_size for any Data object (including "broken" in the past)
=> Removed extra filter in initcontentsize

changelog.d/20250615_142005_sekachev.bs_fixed_project_search_width.md, cvat-ui/src/components/setup-webhook-pages/styles.scss
=> Fixed incorrect width of project field on webhook setup page

changelog.d/20250630_130504_roman_validate_annotation_id.md, cvat/apps/engine/serializers.py, cvat/apps/engine/tests/test_rest_api_3D.py, cvat/apps/engine/views.py, tests/python/rest_api/test_quality_control.py, tests/python/rest_api/test_tasks.py, tests/python/sdk/test_auto_annotation.py, tests/python/sdk/test_datasets.py, tests/python/sdk/test_pytorch.py
This has no legitimate purpose, since a client cannot predict which IDs are available ahead of time. Moreover, if the specified ID is already taken, the client will receive a 500 error (on a PUT request) or a 400 error with a cryptic message (on a PATCH request).
For symmetry, also prohibit deleting annotations with no ID, although I believe such deletions were previously no-ops anyway.
I originally wanted to also require IDs on an `action=update` request, but tests show that a) currently "update" can also work as "create", and b) it's really easy to accidentally rely on this behavior. So for compatibility I decided to keep it. Maybe we could revisit this later. I updated the tests to fix such mistakes, though.
- ~~[ ] …
=> Prohibit creating annotations with preset ID

.github/workflows/docs.yml, site/README.md, site/build_docs.py
Currently, we build the documentation for every repository tag starting from 1.5.0. This results in large list of the versions which do not differ too much between themselves. The drop-down menu in the website overflows the visible area at this point.
This PR limits the number of versions to 6 (changeable in `build_docs.py`). It also reverses the versions, so in the drop-down menu on the website, the versions go from the latest to the earliest top-down.
So far, the main blog had only one link to old version documetation, and it is changed now. I hope there are no other links to the old versions, so nothing is broken with this PR.
- Run the website as for production (see site/README.md for instructions). Deploy with `python -m http.server -d <...>/public`
- Open the website
- Open the …
=> [Documentation] Limit the documentation versions to the 6 ones

tests/cypress/e2e/features/case_113_new_organization_pipeline.js
Test `cypress/e2e/features/case_113_new_organization_pipeline.js` fails too much in our CI
Examples: [1](https://github.com/cvat-ai/cvat/actions/runs/16305366557/job/46050308820), [2](https://github.com/cvat-ai/cvat/actions/runs/15936847174/job/44958464729)
Logs:
```New organization pipeline.
Testing case "113"
✓ The first user creates an organization and activates it. (11576ms)
✓ Open the organization settings. Invite members. (2954ms)
✓ Search within organizations: All members shoould be queryable (1099ms)
✓ Search within organizations: Filters work correctly (517ms)
✓ Create a project, create a task. Deactivate organization. (12991ms)
✓ The project, the task are invisible now. (13
9ms)
✓ Admin tries to leave from organization (not successfully because he is not a member of it). …
```
=> Fix test on creating new organization pipeline

site/content/en/docs/administration/basics/installation.md
The current installation guide does not follow the current official Docker installation guide!
apt-key is deprecated
Finally, the links to the Docker official website are outdated
=> Update Docker Installation commands and links in documentation

cvat/apps/events/cache.py
- `request_id` used for getting cache may be None, what seems to be normal when deletion from shell or some workers. 
- after calling `cache.clear()` for the first time, it removes default value initialized in constructor
- further deletion from the same process/shell does not work
=> Fixed deletion cache on server level if request id is None

changelog.d/20250730_113447_sekachev.bs_user_deletion.md, cvat/apps/engine/management/commands/deleteuser.py, cvat/apps/engine/user_deletion.py
- The manager supports validation (e.g. in community version user should not have organizations with other members, in SaaS user also should not have any active subscriptions)
- Added command: `python manage.py deleteuser <user_id>` 
=> Added user deletion manager that removes user together with all data

.gitignore
Yarn leaves behind a file named `.yarn/install-state.gz`, which should be gitignored. I just added the recommended settings from the Yarn website.
=> Add gitignore entries for new Yarn

.github/workflows/main.yml
Reproducibility of some bugs in dev wip is dependent on whether the `CVAT_ALLOW_STATIC_CACHE` is enabled. This PR adds an extra worker that runs the 'not test_task_data' tests with and without caching.
=> parametrize fast batch of rest_api tests by cache 

cvat-ui/src/components/bulk-wrapper.tsx
There is a bug, e.g.:
1. Select two items
2. Click menu of non selected element
3. Menu will be opened as like the bulk action will be applied to two previous elements
4. However it will be applied only to the current (not selected)
5. I believe correct behaviour is to reset selection of previous elements in this case
=> Reset selection when clicking menu of non-selected element

Dockerfile, changelog.d/20250821_170901_roman_non_root.md, helm-chart/templates/cvat_backend/initializer/job.yml, helm-chart/templates/cvat_backend/server/deployment.yml, helm-chart/templates/cvat_backend/worker_annotation/deployment.yml, helm-chart/templates/cvat_backend/worker_chunks/deployment.yml, helm-chart/templates/cvat_backend/worker_consensus/deployment.yml, helm-chart/templates/cvat_backend/worker_export/deployment.yml, helm-chart/templates/cvat_backend/worker_import/deployment.yml, helm-chart/templates/cvat_backend/worker_qualityreports/deployment.yml, helm-chart/templates/cvat_backend/worker_utils/deployment.yml, helm-chart/templates/cvat_backend/worker_webhooks/deployment.yml
While the backend does not actually run as root, Kubernetes is unable to determine that from the username recorded in the Docker image. Fix it by using a numeric UID/GID. Also, set the UID explicitly when creating the user, to make sure it remains stable.
Add the setting itself to the Helm chart, so that we can verify that the change works.
A client requires this for their deployment, and it seems like a useful thing to implement in general.
Note that there are several other containers in the Helm chart that are still incompatible with `runAsNonRoot` (including ones that actually run as root). I plan to deal with those separately.
- ~~[ ] I have linked related issues …
=> Make the server Docker image compatible with the k8s runAsNonRoot setting

cvat-ui/src/components/cvat-app.tsx, cvat-ui/src/reducers/index.ts, cvat-ui/src/reducers/notifications-reducer.ts, tests/cypress/e2e/features/bulk_actions.js, tests/cypress/support/commands.js
The bulk_actions test seems to be unstable as it incorrectly closes notifications for export. This PR adds className for export notifications and improves closing notification command
=> Fix instability in bulk actions test

.github/workflows/main.yml
Currently, tests in the private repository cannot run due to a workflow error:
```
The workflow is not valid. .github/workflows/main.yml (Line: 573, Col: 3): Error calling workflow. The nested job 'generate_report' is requesting 'id-token: write', but is only allowed 'id-token: none'
```
=> Skip running the `generate_report` job in private repo

changelog.d/20250909_200043_roman.md, cvat-ui/src/actions/tasks-actions.ts
Currently, there's an unwanted space between the end of the sentence and the period when the percentage is not displayed.
=> Fix spacing in the task creation status messages

changelog.d/20250919_132616_77135162+NobisIndustries.md, helm-chart/Chart.yaml
fixes https://github.com/cvat-ai/cvat/issues/9839
The helm chart kubeVersion constraint accidentally dropped pre-release versions of K8s from its compatibility requirements - so it can't be rolled out in EKS clusters (which use AWS specific pre-release versions of K8s). This change reintroduces the old behavior.
Worked for the helm charts before the dropped "-0" part, so this is a simple fix with no problems foreseen.
~~- [] I have updated the documentation accordingly~~
~~- [] I have added tests to cover my changes~~ …
=> fix: re-enable k8s pre-release compatibility for helm chart

ai-models/detector/yolo/func.py
I wrote in the README that the default is CPU, but I forgot to actually implement it. :facepalm: 
=> ai-models/detector/yolo: add a default for the `device` parameter

tests/package.json, tests/yarn.lock
This is needed so that matrix jobs in private repo workflows can utilize the correct version of yarn when running the e2e tests in private repo
https://github.com/cvat-ai/app.cvat.ai/pull/669
CI Nightly passes: https://github.com/cvat-ai/cvat/actions/runs/17865769503
=> denote currently used yarn version in cvat/tests

changelog.d/20250911_182534_roman_task_create_without_labels.md, cvat-ui/src/components/annotation-page/annotation-page.tsx, cvat-ui/src/components/create-task-page/create-task-content.tsx, cvat/apps/engine/serializers.py, tests/cypress/e2e/actions_projects_models/case_57_project_label_deleting_feature.js, tests/cypress/e2e/actions_tasks/case_58_task_label_deleting_feature.js, tests/python/rest_api/test_tasks.py
The requirement to specify labels in advance seems entirely artificial and unnecessary. Sometimes it's more convenient to create the task first and add labels later. It's also inconsistent with projects, which can already be created without labels.
In this patch I also fixed a couple error messages related to labels.
Unit tests for the backend; frontend tested manually.
=> Allow creating tasks without specifying the labels

changelog.d/20250912_194630_roman_no_tuspy.md, cvat-sdk/cvat_sdk/core/uploading.py, cvat-sdk/requirements/base.txt, tests/python/sdk/test_tasks.py
The version we're depending on (0.2.5) has a dependency on python-future, which had a CVE filed against it (PythonCharmers/python-future#650). While the CVE itself seems to be bogus (and in fact, tuspy doesn't actually _use_ python-future), it would still be nice to get rid of this dependency to placate various security dependency scanners.
tuspy did remove this dependency in version 1.0.2. However, this version isn't immediately compatible with the various hacks we have applied to marry it to the API client. Instead of adapting them, I chose to throw tuspy out, and reimplement the TUS protocol. I think this is better for a few reasons:
* We won't have to keep adapting the hacks every time we need to update the dependency.
* The SDK can now be installed in an environment together with …
=> Remove the tuspy dependency

changelog.d/20250929_124206_klakhov_fix_points_undefined.md, cvat-canvas/src/typescript/sliceHandler.ts
The `Cannot read properties of undefined (reading 'points')` error occurs in the `initializeWithContour` method when an incorrect `undefined` argument is passed.
This happens in the callback provided by the slice handler to the object selector. The selection callback can be invoked with an empty array, but the slice handler callback always expects at least one element. As a result, the error occurs.
Can be reproduced via different user actions that trigger this chain: `canvasInstance.setup -> UpdateReasons.OBJECTS_UPDATED -> objectSelector.resetSelected`, for example:
1. Enable slice tool
1. Delete an object via sidebar
2. Change z layer of an object via sidebar
3. Enable gamma filter
4. Add new Z layer
2. Get an error
https://help.github.com/en/github/managing-your-work-on-github/linking- …
=> Fix `Cannot read properties of undefined (reading 'points')`

changelog.d/20251006_193945_roman_no_getouterframes.md, cvat/apps/dataset_manager/util.py
Datumaro depends on the pyemd library, which fails to be imported in the CVAT Docker image, because it uses `pkg_resources` without declaring a dependency on setuptools (see also wmayner/pyemd#67).
Normally this isn't a problem, because Datumaro imports it lazily (and the Datumaro component that triggers its actual loading is not used by CVAT). However, the `current_function_name` function calls `inspect.getouterframes`, which indirectly causes every lazy-imported module to be loaded (this behavior might be a Python bug). In particular, this loads pyemd, which raises an exception.
`current_function_name` is usually called while handling another exception, so when this problem occurs, that original exception becomes lost.
Work around this by replacing `inspect.getouterframes` with custom …
=> Work around spurious "No module named 'pkg_resources'" errors
