cvat-ai/cvat

- cvat/apps/engine/static/engine/js/player.js
> Player navigation has been fixed if window was scrolled

- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/base.js
- cvat/apps/engine/static/engine/js/player.js
- cvat/apps/engine/static/engine/js/polyshapeEditor.js
- cvat/apps/engine/static/engine/js/shapeCreator.js
- cvat/apps/engine/static/engine/js/shapeFilter.js
- tests/eslintrc.conf.js
> CVAT links to specific frame or object/objects

- cvat/apps/documentation/user_guide.md
Fix #22 (Improve documentation for overlap parameter)
> Improve documentation for overlap parameter

- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapes.js
* Bug has been fixed: invisible points actually are visible 
* Bug has been fixed: impossible to lock/occlude object in AAM
> Release 0.2 fix

- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/base.js
- cvat/apps/engine/static/engine/js/player.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapeFilter.js
- cvat/apps/engine/static/engine/js/shapes.js
- cvat/apps/engine/templates/engine/annotation.html
- tests/eslintrc.conf.js
* Virtual URL instead of changing real URL
* Context menu for player.
* Ability to copy object URL, frame URL and job URL via context menus
> Now we store virtual URL instead of update it in the browser address bar

- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapes.js
> Bug has been fixed: label UIs don't update after changelabel

- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapeCreator.js
- cvat/apps/engine/static/engine/js/shapeGrouper.js
- cvat/apps/engine/static/engine/js/shapeMerger.js
- cvat/apps/engine/static/engine/js/userConfig.js
* Unified shortcut for cancel of a current mode (aam/merge/create/grouping).
* Shortcuts for outside and keyframe properties
Resolved #113
> Shortcuts patch

- CHANGELOG.md
- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/player.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
* Several eslint warnings/errors have been fixed
* Changelog has been updated
* Ability to cancel poly editing with Esc (I forget about it early)
> Minor changes

- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapeCreator.js
- cvat/apps/engine/static/engine/js/shapeMerger.js
- cvat/apps/engine/static/engine/js/shapeSplitter.js
* Fixed: single point wasn't created in right scenario, double press N (without any point) created a point
* Fixed: merge didn't create outside objects in some cases 
* Fixed: split didn't work right 
* Enhancement:  Object selection propagated to next frame
Resolved #172
> Some minor fixes

- README.md
Adding the Questions section and inserting an entry to this section in the Documentation part, so users having a quick view will be aware of it.
> Add Questions section to Readme.md

- cvat/apps/engine/static/engine/js/shapeCollection.js
Now data is imported properly if server returns client_id = -1 for all shapes.
> Fixed shapeCollection.import() for old tasks.

- cvat/apps/engine/static/engine/js/player.js
- cvat/apps/engine/static/engine/js/shapes.js
> Fixed: A context menu can be invisible in some cases

- cvat/apps/engine/static/engine/js/attributeAnnotationMode.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapes.js
This patch is part of [this](https://github.com/opencv/cvat/pull/96) pull request.
There aren't any changes for an user. There is attribute annotation mode refactoring only. It encapsulates AAM functionality inside a single file.
> Attribute annotation mode encapsulation

- cvat/apps/engine/static/engine/js/logger.js
> Used loop instead spread to initialize array

- Dockerfile
It has worked invalid in cases without socks_proxy
> Dockerfile has been fixed 

- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/history.js
- cvat/apps/engine/static/engine/js/shapeBuffer.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapeCreator.js
- cvat/apps/engine/static/engine/js/shapeMerger.js
- cvat/apps/engine/static/engine/js/shapes.js
Resolved #306
Same situation like in the issue have been fixed for draw, copy, propagate, split, merge scenarious.
> Fixed 400 code after undo/redo

- CHANGELOG.md
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/userConfig.js
Resolved #273
Next shape: Alt + >
Prev shape: Alt + <
> Keyboard shortcut for change shape type (Alt + 1,2,3,4)

- cvat/apps/auto_annotation/static/auto_annotation/js/dashboardPlugin.js
- cvat/apps/dashboard/static/dashboard/js/dashboard.js
- cvat/apps/dashboard/templates/dashboard/dashboard.html
- cvat/apps/git/git.py
- cvat/apps/git/static/git/js/dashboardPlugin.js
- cvat/apps/git/urls.py
- cvat/apps/git/views.py
- cvat/apps/tf_annotation/__init__.py
- cvat/apps/tf_annotation/static/tf_annotation/js/dashboardPlugin.js
- cvat/apps/tf_annotation/static/tf_annotation/js/tf_annotation.js
- cvat/apps/tf_annotation/views.py
Moreover there are updates which fix `auto annotation` and `tensorflow annotation` in the updated dashboard.
> Different request to clone a git repository

- cvat/requirements/base.txt
redis 2.10.6 -> 3.2.0
rq 0.10.0 -> 0.13.0
django-rq 1.0.1 -> 1.3.0
> Required packages versions updated.

- cvat/apps/engine/static/engine/js/shapeFilter.js
> Fixed syntax for legacy chrome

- cvat/apps/engine/static/engine/js/shapeFilter.js
- cvat/apps/engine/static/engine/js/shapes.js
- cvat/apps/engine/templates/engine/annotation.html
> The shape filter has been expanded

- cvat/apps/dashboard/static/dashboard/js/dashboard.js
- cvat/apps/dextr_segmentation/views.py
- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapes.js
- Dashboard filtration
- Fixed deep extreme cut
- Changeable job status
- Share icon for files
> Integration of REST/API in client #3

- cvat/apps/tf_annotation/views.py
> Fixed tensorflow annotation without OpenVINO

- cvat/apps/engine/static/engine/js/annotationSaver.js
- cvat/apps/engine/static/engine/js/annotationUI.js
- cvat/apps/engine/static/engine/js/bootstrap.js
- cvat/apps/engine/static/engine/js/logger.js
- cvat/apps/engine/static/engine/js/server.js
- cvat/apps/engine/static/engine/js/shapeCollection.js
- cvat/apps/engine/static/engine/js/shapeFilter.js
- cvat/apps/engine/static/engine/js/shapes.js
* Fixed bug: invalid for new objects after saving
* Fixed links to objects
* Fixed exceptions
* Fixed logs
* Some codacy issues resovled
> Integration of REST/API in client #5

- utils/README.md
- utils/tfrecords/converter.md
- utils/tfrecords/converter.py
- utils/tfrecords/requirements.txt
add a converter to tfrecords with the proper documentation in one clean commit.
> add a converter to tfrecords to cvat/utils

- utils/coco/converter.md
- utils/coco/merge_annotations.py
@nmanovic Please take a look. It is a script to merge some datasets in COCO representation into one. It is useful when we have several tasks for one dataset or just different datasets and we want to use them as one train or validation dataset.
> Feature: merge annotations

- cvat/apps/auto_annotation/model_manager.py
- cvat/apps/auto_annotation/views.py
> Integration of REST/API in client (Part 7) 

- cvat/apps/git/views.py
- cvat/simpleworker.py
> Fixed permissions for push to a git repository

- components/openvino/install.sh
> [WIP] Fixed openvino installation

- cvat/apps/authentication/auth.py
- cvat/apps/dashboard/static/dashboard/js/dashboard.js
* Dashboard filtering
* Get task permissions
> Couple of fixes for Rest API

- Dockerfile
- docker-compose.ci.yml
(workaround for https://www.traviscistatus.com/incidents/kyf149kl6bvp issue)
> used network: host option 

- CHANGELOG.md
- cvat/apps/engine/annotation.py
- cvat/apps/engine/static/engine/js/shapeCreator.js
- cvat/apps/engine/static/engine/js/shapes.js
Feature: Support of interpolation for a single point.
> Single-point interpolation

- cvat/apps/engine/static/engine/js/shapes.js
* Fixed case when previous position in undo/redo doesn't exist
* Prevented editing of interpolation points
> Fixed: Cannot read property 'split' of undefined for interpolation points

- cvat/apps/engine/annotation.py
Hi @BrunoLansacSBD , @nmanovic ,
I have opened a pull request that fixes issue #56.
> video_name in database and dumped file for interpolation mode

- CHANGELOG.md
- cvat/apps/auto_annotation/static/auto_annotation/js/dashboardPlugin.js
Resolved #466
We also need to create the new release
> Fixed interaction with the server share in the auto annotation plugin

- CHANGELOG.md
- cvat/apps/engine/static/engine/js/base.js
> Fixed dump for case when task name has a slash

- CHANGELOG.md
- cvat/apps/engine/annotation.py
> fixed auto_annotation for multijob tasks

- cvat/apps/authentication/urls.py
- cvat/apps/authentication/views.py
- cvat/settings/development.py
- cvatjs/src/server-proxy.js
@nmanovic, @zankevich FYI: https://fractalideas.com/blog/making-react-and-django-play-well-together-single-page-app-model/ 
@zankevich Please don't forget to rebuild the CVAT.js
> Fixed authentification for cross origin

- cvat/apps/auto_annotation/import_modules.py
- cvat/apps/auto_annotation/model_manager.py
Solves https://github.com/opencv/cvat/issues/516
> allow importing of modules in auto_annotation

- utils/open_model_zoo/Retail/object_detection/text/pixel_link_mobilenet_v2/0001/pixel_link_mobilenet_v2.py
Tested working in our production.
> Fixed Pixel Link Interp file API issues

- .gitattributes
- CHANGELOG.md
- components/openvino/eula.cfg
It is probably related with the problem of OpenVino installation within Windows
> Fixed line endings for *.cfg

- cvatjs/src/api-implementation.js
- cvatjs/src/api.js
- cvatjs/src/server-proxy.js
- cvatjs/src/session.js
* New API method: logout + documentation
* Fixed Task.delete() method. It had returned value earlier than server request was done.
> Logout API method, fixed deleteTask method

- cvat/requirements/base.txt
- utils/coco/requirements.txt
Upgrade Numpy to avoid Arbitrary Code Execution
Upgrade Django to avoid MitM
> Upgrade Numpy and Django to avoid security vulnerabilities

- CHANGELOG.md
- cvat/apps/engine/static/engine/js/attributeAnnotationMode.js
> Fixed exception in attribute annotation mode

- utils/yolo/converter.py
To solve the TypeError in line 235 & line 236, added int() parser to 'width' and 'height' variables.
Resolved #595
> TypeError Fix

- cvat-canvas/README.md
- cvat-canvas/dist/canvas.css
- cvat-canvas/package.json
- cvat-canvas/src/canvas.ts
- cvat-canvas/src/canvasController.ts
- cvat-canvas/src/canvasModel.ts
- cvat-canvas/src/canvasView.ts
- cvat-canvas/src/master.ts
- cvat-canvas/tsconfig.json
- cvat-canvas/tslint.config.js
- cvat-core/src/annotations-objects.js
- canvas rotation
- drawing
- dragging
- resizing
- scaling of shapes according to canvas scaling
> CVAT-Canvas: Integrated SVG.js

- cvat-core/src/api-implementation.js
- cvat-core/src/api.js
- cvat-core/src/server-proxy.js
@zankevich 
This method should be used to determine whether user is authorized now
> Added method cvat.server.authorized()

- cvat/apps/auto_annotation/inference.py
- docker-compose.yml
Added missing import for adding models in the tool and OPENVINO_TOOLKIT param in docker-compose which will help to set up the model manager.
Fix #659
> Auto annotation

- Dockerfile
- cvat/apps/engine/annotation.py
- cvat/settings/base.py
- docker-compose.yml
> added settings for setup timezone

- utils/yolo/converter.py
> fixed label order

- README.md
> Added information about django REST API to docs

- cvat/apps/annotation/coco.py
> fixed annotation ids, start category id from 1

- cvat/apps/engine/serializers.py
- cvat/apps/engine/tests/test_rest_api.py
> Fixed update of a task via REST

- cvat-core/src/annotations-saver.js
- cvat-core/tests/api/annotations.js
- cvat-core/tests/api/tasks.js
- cvat-core/tests/mocks/dummy-data.mock.js
- cvat-core/tests/mocks/server-proxy.mock.js
- cvat/apps/engine/static/engine/js/annotationSaver.js
Resolved #692 
- Fixed issue in cvat-core
- Fixed issue in cvat prod
- Added API test in cvat-core
> Fixed save for case when a job has a shape and a track with the same id

- cvat-data/src/js/cvat-data.js
- cvat/apps/engine/media_extractors.py
fix problems with last frame and invalid chunk preparing
> fix problem with last frame and invalid chunk preparing

- cvat-ui/src/components/cvat-app.tsx
It is just duty fix to unblock my development.
> Fix login problem: unauthorised user cannot login

- cvat/apps/engine/views.py
> Fix redirect for dataset export rest api

- cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
- cvat-ui/src/components/create-task-page/basic-configuration-form.tsx
- cvat-ui/src/components/labels-editor/label-form.tsx
> Improved some hints

- cvat-ui/package.json
- cvat-ui/src/components/cvat-app.tsx
- cvat-ui/src/components/task-page/job-list.tsx
- cvat-ui/src/stylesheet.css
- cvat-ui/src/utils/copy-to-clipboard.ts
Resolved #909
Submitted codacy issue: https://github.com/codacy/codacy-eslint/issues/153
> Added button to copy jobs info to clipboard

- cvat-ui/src/actions/tasks-actions.ts
- cvat-ui/src/components/header/header.tsx
- cvat-ui/src/components/tasks-page/task-item.tsx
- cvat-ui/src/components/tasks-page/tasks-page.tsx
- cvat-ui/src/containers/tasks-page/task-item.tsx
- cvat-ui/src/containers/tasks-page/tasks-page.tsx
- cvat-ui/src/reducers/interfaces.ts
- cvat-ui/src/reducers/tasks-reducer.ts
- cvat-ui/src/stylesheet.css
Also tasks page was a little bit improved
> Ability to show hidden tasks by a user request

- cvat-ui/src/components/file-manager/file-manager.tsx
Resolved #921
P.S. border in 5 files has been chosen to display all model files (when upload OpenVINO model)
> Names of selected files when creating a new task

- CONTRIBUTING.md
- cvat-ui/package.json
- cvat/settings/base.py
> Updated CONTRIBUTING.md

- cvat-ui/src/components/labels-editor/label-form.tsx
- cvat-ui/src/components/labels-editor/labels-editor.tsx
> Ability to copy labels to clipboard without IDs

- docker-compose.yml
Don't fix minor/patch version to get security updates and bug fixes.
> Update docker base images

- cvat-ui/src/utils/git-utils.ts
> Fixed "leave" method for git plugin

- cvat-ui/src/components/create-model-page/create-model-content.tsx
- cvat-ui/src/components/create-task-page/create-task-content.tsx
Small change to improve UI/UX, I suppose **Submit** button mustn't be in danger color
> Change-submit-button-style

- cvat/apps/annotation/coco.py
- datumaro/datumaro/components/extractor.py
Closes #955 
Added:
- Polygon point count checks in COCO annotations import and export
> Add polygon point count checks

- cvat/apps/engine/views.py
Fixes date overflow issue when using timezone for "old" dataset export tasks.
> Fix timezone bug

- datumaro/datumaro/components/algorithms/rise.py
- datumaro/datumaro/components/converters/ms_coco.py
- datumaro/datumaro/components/converters/tfrecord.py
- datumaro/datumaro/components/converters/voc.py
- datumaro/datumaro/components/converters/yolo.py
- datumaro/datumaro/components/dataset_filter.py
- datumaro/datumaro/components/importers/cvat.py
- datumaro/datumaro/components/importers/datumaro.py
- datumaro/datumaro/components/importers/ms_coco.py
- datumaro/datumaro/components/importers/tfrecord.py
- datumaro/datumaro/components/importers/voc.py
- datumaro/datumaro/components/importers/yolo.py
- datumaro/datumaro/components/project.py
- datumaro/tests/test_project.py
Fixes:
- The infinite loop issue described in #970
- Export of grayscale images
- Wrong `.git` dir creation
- Wrong `options` values in the project config after import
> [Datumaro] Fix project loading

- cvat/apps/engine/serializers.py
> align serializer max length of attribute value with the model

- cvat/apps/dataset_manager/task.py
> Update method call

- cvat-canvas/src/typescript/canvasView.ts
- cvat-canvas/src/typescript/drawHandler.ts
- cvat-canvas/src/typescript/editHandler.ts
- cvat-canvas/src/typescript/svg.patch.ts
- cvat-core/src/annotations-objects.js
- cvat-ui/package-lock.json
- cvat-ui/package.json
Now it is possible to use left mouse button to move image during all these actions
Mouse wheel is also usable for that
> React UI: Improved mouse behaviour during draw/merge/edit/group/split

- components/cuda/docker-compose.cuda.yml
- components/cuda/install.sh
- cvat/requirements/base.txt
- utils/tfrecords/requirements.txt
> updated CUDA to version 10

- cvat/requirements/base.txt
- datumaro/requirements.txt
Fixes the issue with `gitdb.utils.compat` import in git module internals.
> Bump gitpython version

- docker-compose.yml
https://www.postgresql.org/docs/current/auth-trust.html
resolve #1145
> Fix postgres startup

- datumaro/datumaro/plugins/transforms.py
- datumaro/tests/test_transforms.py
Added:
- `MapSubsets` transform, which allows to rename subsets
`datum project transform -t map_subsets -- -s 'a:b' -s 'train:val' -s ':test'`
- `ShapesToBoxes` transform, which converts masks, points, polygons and lines to polygons
> [Datumaro] Add offline subset remapping and bbox conversion

- cvat/apps/dataset_manager/export_templates/plugins/cvat_rest_api_task_images.py
- cvat/apps/dataset_manager/task.py
- datumaro/datumaro/plugins/tf_detection_api_format/extractor.py
Fixed:
- Exported datumaro project now named after the source task
- Server image paths are not exposed to the user
- Tensorflow forward compatibility issue in tfrecord reading
- Setuptools' `find_packages()` compatibility
> [Datumaro] Remote project export fixes

- datumaro/datumaro/components/extractor.py
- datumaro/datumaro/components/project.py
- datumaro/datumaro/plugins/labelme_format.py
- datumaro/datumaro/plugins/transforms.py
- datumaro/datumaro/util/mask_tools.py
- datumaro/tests/test_labelme_format.py
- Added LabelMe format support
- All plugin import errors are catched
> [Datumaro] LabelMe format

- cvat-core/package.json
- cvat-core/src/enums.js
- cvat-core/src/log.js
- cvat-core/src/logger-storage.js
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/actions/boundaries-actions.ts
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/merge-control.tsx
- cvat-ui/src/components/cvat-app.tsx
- cvat-ui/src/components/global-error-boundary/global-error-boundary.tsx
- cvat-ui/src/components/global-error-boundary/styles.scss
- cvat-ui/src/index.tsx
- cvat-ui/src/reducers/about-reducer.ts
- cvat-ui/src/reducers/annotation-reducer.ts
- cvat-ui/src/reducers/auth-reducer.ts
- cvat-ui/src/reducers/formats-reducer.ts
- cvat-ui/src/reducers/interfaces.ts
- cvat-ui/src/reducers/models-reducer.ts
- cvat-ui/src/reducers/notifications-reducer.ts
- cvat-ui/src/reducers/settings-reducer.ts
- cvat-ui/src/reducers/share-reducer.ts
- cvat-ui/src/reducers/shortcuts-reducer.ts
- cvat-ui/src/reducers/tasks-reducer.ts
- cvat-ui/src/reducers/users-reducer.ts
- cvat-ui/src/utils/redux.ts
* Added react boundary page which allows to restore broken UI 
* Added global error handler
* Added sendException logs
> React UI: Better exception handling

- cvat-canvas/src/typescript/canvasView.ts
- cvat-ui/src/actions/annotation-actions.ts
@azhavoro 
What is wrong with old UI?
> React UI, data streaming: Disabled UI till first frame is ready

- cvat/apps/engine/data_manager.py
- cvat/apps/engine/tests/test_data_manager.py
- cvat/apps/engine/tests/test_rest_api.py
Fixes #1336
- fixed single point interpolation
> Fix point interpolation

- cvat-canvas/src/typescript/canvasView.ts
Minor additional fix to the previous PR #1370 related with the issue #1368
Manual testing
> React UI: Fixed points visibility when go between frames

- cvat/apps/dataset_manager/bindings.py
- cvat/apps/engine/frame_provider.py
- added chuck iterator cache to support random frame access without performance loss for sequential access
- added output type support for `get_frame()`
> Add chunk iterator cache to frame provider

- CHANGELOG.md
- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/annotation-page.tsx
- cvat-ui/src/reducers/annotation-reducer.ts
- cvat-ui/src/reducers/interfaces.ts
- cvat/apps/dextr_segmentation/dextr.py
- cvat/apps/reid/reid.py
I've found some issues and fixed them in this PR: 
- Job cannot be opened in some cases when the previous job was failed during opening
- Deactivated shape is still highlighted on the canvas 
- AttributeError: 'tuple' object has no attribute 'read' in ReID algorithm
- Wrong semi-automatic segmentation near edges of an image 
Manual testing
~~- [ ] I have raised an issue to propose this change ([required](https://github.com/opencv/cvat/issues))~~
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-req …
> Batch of fixes

- cvat-ui/src/utils/dextr-utils.ts
- cvat/apps/dextr_segmentation/dextr.py
Small important fix for the patch that was merged yesterday
Manual testing
~~- [ ] I have raised an issue to propose this change ([required](https://github.com/opencv/cvat/issues))~~
~~- [ ] My issue has received approval from the maintainers~~
~~- [ ] I've read the [CONTRIBUTION](https://github.com/opencv/cvat/blob/develop/CONTRIBUTING.md) guide~~
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request- …
> React UI fix: Failed to execute removChild..

- cvat-canvas/src/typescript/canvasView.ts
- cvat-canvas/src/typescript/cuboid.ts
- cvat-canvas/src/typescript/svg.patch.ts
PR between dev branches
This is not ready feature
I am going to finish it later
PR is just to sync changes and show you example of working with events
> Resize using frontal face of a cuboid

- cvat-ui/src/components/annotation-page/top-bar/annotation-menu.tsx
Fixes remove annotation typo.
Applied the patch and clicked on remove annotations in the new UI.
~~- [ ] I have updated the license header for each file (see an example below)~~
```python
#
```
> annotation-menu: fix remove annotation typo

- CHANGELOG.md
- supervisord.conf
When CVAT server container is killed during PC restart it leads to problems to start the container again. Apache leaves temporary files and cannot restart after that.
Fixes #1035 
Manually. I run `docker kill cvat` and `docker up -d` and it worked as expected. 
~- [ ] I have updated the [documentation](
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~
~- [ ] I have added tests to cover my changes~
```python
#
```
> Fix apache startup

- .travis.yml
Merges coverage results correctly
```python
#
```
> Fix coverage merging

- CHANGELOG.md
- README.md
Swagger documentation is served on Allowed Hosts, These instruction were missing in the CVAT document. This will fix an open issue [https://github.com/opencv/cvat/issues/1495](https://github.com/opencv/cvat/issues/1495)
Instruction is updated, Viewed markdown content on Github markdown beautification.
```python
#
```
> Updating instructions to serve Swagger documentation 

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Fixed issue with unnecessary tag activation in cvat-canvas (Resolve #1540 )
Manually
```python
#
```
> fixed false tag activation

- .github/PULL_REQUEST_TEMPLATE.md
Added new item in PR template checklist
Not applicable
```python
#
```
> Added item with npm package version increasing to the PR template

- cvat-ui/src/components/create-task-page/styles.scss
- cvat-ui/src/components/register-page/register-form.tsx
- cvat-ui/src/components/register-page/register-page.tsx
- cvat-ui/src/components/register-page/styles.scss
- cvat-ui/src/components/settings-page/styles.scss
- cvat-ui/src/components/tasks-page/top-bar.tsx
This PR change some layout spacings
Manually …
> React UI: Layout styles fixes

- cvat/apps/documentation/AWS-Deployment-Guide.md
When I tried to deploy cvat to AWS, I got invalid yaml format error just by copying and pasting this example (but I changed ip address). This change makes the document more gentle.
I pasted new changes to [yamllint.com](http://www.yamllint.com/) and checked the format is valid. …
> Fix example yaml format

- cvat/apps/documentation/user_guide.md
This PR contains the removal of a duplicate of the "Annotation with points" item.
N/A
```python
#
```
> Delete duplicate item in User Guide

- cvat-core/README.md
> Fix typo in readme

- cvat/apps/dataset_manager/formats/pascal_voc.py
Adds missing import for PASCAL VOC format.
Addresses the comment in #1463.
Manual test
```python
#
```
> Add missing import for VOC format

- cvat/apps/dataset_manager/bindings.py
When uploading annotations with unregistered labels, the upload fails with no details on the error (late error due to None label_id).
Uploaded annotations with new labels.
```python
#
```
> Show error on upload when labels are missing

- cvat/apps/dataset_manager/formats/cvat.py
- datumaro/datumaro/cli/contexts/project/diff.py
- datumaro/datumaro/plugins/datumaro_format/converter.py
- datumaro/datumaro/plugins/image_dir.py
- datumaro/datumaro/plugins/labelme_format.py
- datumaro/datumaro/plugins/voc_format/converter.py
- datumaro/datumaro/plugins/yolo_format/converter.py
- datumaro/datumaro/util/image.py
- datumaro/tests/test_image.py
Preparation commit for #1463 
Added a check for directory existence and a parameter for `save_image` function to avoid silent fails when saving images into non existent dirs.
> Add directory check on image save

- README.md
- cvat/apps/documentation/faq.md
Initial version of the 'Frequently Asked Questions' page
It's nice to have a 'Frequently Asked Questions' page with the most common user questions.
N/A
```python
#
```
> added initial version of frequently asked questions page

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-annotation-sidebar.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
Fixes a bug reported by community and internal data annotation team
Manual testing
```python
#
```
Resolve #1750
Resolve #1614
> [CVAT-UI] Fixed AAM bug: #1750

- datumaro/datumaro/cli/contexts/project/__init__.py
- datumaro/datumaro/cli/contexts/project/diff.py
- datumaro/datumaro/components/project.py
- datumaro/datumaro/plugins/transforms.py
- Added info on unmatched dataset items in `diff` output
- Added `Rename` transform to rename dataset items by a regex
- Fixed an issue, where `Ctrl+C` led to exit without removing of output directories
Manual test
Feel free to contact the maintainers …
> [Datumaro] CLI updates

- datumaro/datumaro/cli/contexts/model/__init__.py
- datumaro/datumaro/cli/contexts/project/__init__.py
- datumaro/datumaro/cli/util/project.py
- datumaro/datumaro/components/launcher.py
- datumaro/tests/test_project.py
- Added a check for labels existence in model output
- Little refactoring for CLI
- Removed extra output when adding a model to a project
Unit tests
```python
#
```
> [Datumaro] Refactorings

- cvat/apps/documentation/faq.md
> Added a couple of question to the FAQ page.

- cvat-core/package.json
- cvat-core/src/api-implementation.js
- cvat-core/src/api.js
- cvat-core/src/lambda-manager.js
- cvat-core/src/server-proxy.js
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/utils/dextr-utils.ts
- cvat-ui/src/utils/plugin-checker.ts
Internal PR to run dextr via lambda manager on client side
> Running dextr via lambda manager

- Dockerfile
Removed the redundant installation of libldap2-dev library in the Dockerfile. This is fixing for https://github.com/opencv/cvat/issues/1852.
Tested locally by pulling and checking if the build works.
- [] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file
- [] I have updated the [documentation](
- [] I have added tests to cover my changes
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) …
> Remove redundant installation of libldap2-dev

- cvat-core/src/lambda-manager.js
- cvat-core/src/server-proxy.js
- cvat-ui/src/utils/dextr-utils.ts
- cvat-ui/src/utils/plugin-checker.ts
> Use ID instead of name for DEXTR

- CONTRIBUTING.md
- README.md
- cvat/apps/documentation/installation.md
- serverless/deploy.sh
Add `--platform local` command line argument for nuclio as suggested by nuclio maintainers. Also add a table with DL models for automatic labelling into README.md for better visibility of the feature.
N/A …
> Table with serverless functions in README.md

- Dockerfile.ci
- cvat-core/.gitignore
- cvat-core/package-lock.json
```
DEPRECATION WARNING
Node.js 9.x is no longer actively supported!
You will not receive security or critical stability updates for this version.
You should migrate to a supported version of Node.js as soon as possible.
Use the installation script that corresponds to the version of Node.js you
wish to install. e.g.
* https://deb.nodesource.com/setup_10.x — Node.js 10 LTS "Dubnium"
* https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium" (recommended)
* https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium"
```
The package lock file should fix possible regression bugs like this https://github.com/babel/babel/issues/11914.
Manually + CI …
> Added package-lock.json to cvat-core.

- components/analytics/docker-compose.analytics.yml
- cvat/apps/documentation/installation.md
- docker-compose.yml
Added instructions how to deploy CVAT behind a proxy
Some users have experienced issues when deploying CVAT with serverless functions behind a proxy. This PR should simplify the process.
Manually …
> Added instructions how to deploy CVAT behind a proxy

- cvat-data/package-lock.json
- cvat-data/package.json
- cvat-data/src/js/cvat-data.js
- cvat-data/src/js/unzip_imgs.worker.js
- cvat-ui/src/components/annotation-page/annotation-page.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
- cvat-ui/src/components/create-task-page/styles.scss
- cvat-ui/src/components/cvat-app.tsx
- cvat-ui/src/components/feedback/styles.scss
- cvat-ui/src/components/models-page/deployed-models-list.tsx
- cvat-ui/src/components/models-page/styles.scss
- cvat-ui/src/components/models-page/top-bar.tsx
- cvat-ui/src/components/task-page/styles.scss
- cvat-ui/src/components/tasks-page/styles.scss
Some fixes for Safari browser related with image decoding and styles.
These fixes are not enough to correct working. It is only the first part. 
Quite serious issue probably related with this issue: https://github.com/svgdotjs/svg.draggable.js/issues/114 
Safari returns incorrect transformation matrix when svg element is scaled. 
Need additional time to investigate and finding workaround.
Now canvas doesn't work correctly
Some of our users use Safari, but CVAT doesn't work well there. 
Manual testing
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-c …
> Batch of fixes for Safari

- tests/cypress/integration/issue_1429_check_new_label.js
Add Cypress test for issue [1429](https://github.com/opencv/cvat/issues/1429)
```python
#
```
> Cypress test for issue 1429

- cvat-ui/src/index.html
Need to provide some valid meta information for search engines
N/A 
```python
#
```
> Added html meta description for cvat.org

- tests/cypress/integration/issue_1439_blocked_object_info.js
Add Cypress test for issue [1439](https://github.com/opencv/cvat/issues/1439)
```python
#
```
> Cypress test for issue 1439

- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-switcher.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-switcher.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-cuboid-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-points-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polygon-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-polyline-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/draw-rectangle-control.tsx
- cvat-ui/src/components/annotation-page/top-bar/player-buttons.tsx
We need more classes to cypress testing
Manual testing 
```python
#
```
> More classes to cypress testing

- tests/cypress/integration/issue_1750_err_aam_switch_frames.js
Add Cypress test for issue [1750](https://github.com/opencv/cvat/issues/1750)
```python
#
```
> Cypress test for issue 1750.

- tests/cypress.json
- tests/cypress/integration/issue_1810_login_logout.js
- tests/cypress/support/commands.js
Add Cypress test for issue [1810](https://github.com/opencv/cvat/issues/1810)
```python
#
```
> Cypress test for issue 1810

- tests/cypress/integration/issue_1819_first_part_splitted_track_visible.js
- tests/cypress/support/commands.js
Cypress test for issue [1819](https://github.com/opencv/cvat/issues/1819)
```python
#
```
> Cypress test for issue 1819

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/labels-editor/common.ts
The PR is needed for correct cypress testing
Manual testing
```python
#
```
> Added label validators

- README.md
Update yotube links in README.md
N/A
N/A
```python
#
```
> Update yotube links in README.md

- tests/cypress/integration/issue_1882_polygon_interpolation.js
- tests/cypress/integration/issue_1886_point_coordinates_not_duplicated.js
- tests/cypress/support/commands.js
Add Cypress tetsts for issues [1882](https://github.com/opencv/cvat/issues/1882) and [1886](https://github.com/opencv/cvat/issues/1886)
```python
#
```
> Cypress tests for issues 1882, 1886.

- tests/cypress/integration/issue_1444_filter_property_shape.js
- tests/cypress/support/commands.js
Cypress test for issue [1444](https://github.com/opencv/cvat/issues/1444)
```python
#
```
> Cypress test for issue 1444.

- Dockerfile
fix #1851
Failed to build CVAT image with the last version of setuptools
CI
```python
#
```
> Fix version of setuptools

- CHANGELOG.md
- cvat/__init__.py
> Update CHANGELOG and version.

- .travis.yml
- tests/cypress.json
- tests/cypress/integration/remove_users_tasks.js
- tests/cypress/support/index.js
Added a Firefox browser for running Cypress tests.
Added browser verification functionality.
Added user and tasks removing functionality.
```python
#
```
> Cypress tests via Firefox browser.

- tests/cypress/integration/issue_1540_add_remove_tag.js
- tests/cypress/support/commands.js
Cypress test for issue [1540](https://github.com/opencv/cvat/issues/1540)
```python
#
```
> Cypress test for issue 1540.

- cvat/apps/dataset_manager/formats/cvat.py
Related: #2046 
Allow image saving in `CVAT` format without decoding and encoding. This helps to keep source quality and file extension.
Manual test
```python
#
```
> Image copying in CVAT format

- tests/cypress/integration/issue_1433_hide_functionality.js
Cypress test for issue [1433](https://github.com/opencv/cvat/issues/1433).
```python
#
```
> Cypress test for issue 1433.

- tests/cypress/integration/issue_1425_highlighted_attribute_correspond_chosen_attribute.js
- tests/cypress/support/commands.js
Cypress test for issue [1425](https://github.com/opencv/cvat/issues/1425).
```python
#
```
> Cypress test for issue 1425.

- tests/cypress/integration/issue_1438_cancel_multiple_paste_ui_not_lock.js
- tests/package-lock.json
- tests/package.json
Cypress test for issue [1438](https://github.com/opencv/cvat/issues/1438).
Update Cypress to 5.0.0
```python
#
```
> Cypress test for issue 1438.

- tests/cypress/integration/issue_1825_tooltip_hidden_mouseout.js
Cypress test for issue [1825](https://github.com/opencv/cvat/issues/1825).
```python
#
```
> Cypress test for issue 1825.

- cvat/apps/lambda_manager/views.py
Don't allow the lambda manager to return objects with a label which doesn't exist in the task.
Manually in debugger.
```python
#
```
> Fix labels mapping in invoke for serverless functions

- cvat/apps/documentation/installation.md
Installing python3-setuptools was required on a fresh ubuntu 18.04 VM image. Otherwise the next line fails with "no module setuptools"
```python
#
```
> Add python3-setuptools to install list

- README.md
After migration from opencv to openvinotoolkit group, need to update badges.
N/A
```python
#
```
> Fix badges for travis, codacy, coveralls

- tests/cypress/integration/issue_1216_Check_if_UI_not_fails_with_shape_dragging_over_sidebar.js
Cypress test for issue [1216](https://github.com/opencv/cvat/issues/1216).
```python
#
```
> Cypress test for issue 1216.

- tests/cypress/integration/issue_1368_points_track_invisible_next_frame.js
- tests/cypress/support/commands.js
Cypress test for issue [1368](https://github.com/opencv/cvat/issues/1368).
```python
#
```
> Cypress test for issue 1368.

- tests/cypress/integration/issue_1391_delete_point.js
- tests/cypress/support/commands.js
Cypress test for issue [1391](https://github.com/opencv/cvat/issues/1391).
```python
#
```
> Cypress test for issue 1391.

- tests/cypress.json
- tests/cypress/integration/case_1_create_delete_task.js
- tests/cypress/support/commands.js
Cypress test to check creating and deleting an annotation task.
```python
#
```
> Cypress test to check creating and deleting an annotation task.

- tests/cypress/integration/case_4_assign_taks_job_users.js
Cypress test to check:
- Register two more users
- Login with one of users and create a task
- Assign the task to the second user
- Login with the second user and check if the user is able to open the task
- Login with the third user and check if the user doesn’t see the task
- Login with the first user and assign the third user to a job
- Login with the third user and check if the user now is able to open the task
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#vers …
> Cypress test to check users, task, jobs assign

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/utils/enviroment.ts
Recently CVAT was suffering because of failures in 3rdparty script. The patch preventing it in the future
Manual testing
```python
#
```
> Prevent CVAT failure when web analytics is failure

- CHANGELOG.md
- cvat/apps/engine/apps.py
- cvat/apps/engine/signals.py
- cvat/apps/engine/tests/_test_rest_api.py
> delete task data after delete task

- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/cursor-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/fit-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/group-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/merge-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/move-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/resize-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/rotate-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/setup-tag-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/split-control.tsx
Our testing team requested more CSS selectors to perform some of cypress tests
Manual testing
```python
#
```
> Added more css selectors to cypress testing

- cvat-canvas/package-lock.json
- cvat-canvas/package.json
- cvat-ui/package-lock.json
- cvat-ui/package.json
> Updated high volnurabilities from dependabot & npm audit

- tests/cypress/integration/case_7_image_scale_roi.js
Cypress test to check if image was scaled to ROI
```python
#
```
> Cypress test to check if image was scaled to ROI

- cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
Cannot read property "label" of undefined
We have a regular exception. It is clear where the exception happens, but not clear why (cannot reproduce)
This temporary code might help us with it. 
Manual testing  …
> Additional code has been added to investigate exception

- CONTRIBUTING.md
- Motivation: To fix contribution guideline 
- Context: All docs below the last collapsible sections are hidden due to missing </details> tag
- Since this is documentation only change, it has been tested manually. …
> Add missing closing details tag in nuctl testing step so text below is not hidden

- CHANGELOG.md
Adding PR link in CHANGELOG
- [] ~~I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
> adding PR link in changelog

- cvat/settings/base.py
> Fix LOGS_ROOT mkdir

- tests/cypress/integration/case_8_rectangle_shape_track_label.js
- tests/cypress/integration/issue_1216_Check_if_UI_not_fails_with_shape_dragging_over_sidebar.js
- tests/cypress/integration/issue_1425_highlighted_attribute_correspond_chosen_attribute.js
- tests/cypress/integration/issue_1429_check_new_label.js
- tests/cypress/integration/issue_1433_hide_functionality.js
- tests/cypress/integration/issue_1438_cancel_multiple_paste_ui_not_lock.js
- tests/cypress/integration/issue_1439_blocked_object_info.js
- tests/cypress/integration/issue_1444_filter_property_shape.js
- tests/cypress/integration/issue_1750_err_aam_switch_frames.js
- tests/cypress/integration/issue_1785_propagation_latest_frame.js
- tests/cypress/integration/issue_1819_first_part_splitted_track_visible.js
- tests/cypress/integration/issue_1870_cursor_not_jump_to_end.js
- tests/cypress/integration/issue_1919_check_text_attr.js
- tests/cypress/integration/pr_1370_check_UI_fail_with_object_dragging_and_go_next_frame.js
- tests/cypress/support/commands.js
Cypress test for actions on rectangle.
Try to draw a rectangle shape in two ways (by 2 points, by 4 points)
Try to draw a rectangle track
Try to switch a label and draw one more rectangle
Check if objects are drawn and they are shapes/tracks with right labels …
> Cypress test for actions on rectangle.

- .nycrc
- .travis.yml
- package.json
- tests/cypress/plugins/index.js
- tests/cypress/support/index.js
- tests/package-lock.json
- tests/package.json
CVAT-UI: measure coverage.
Measuring code coverage. Analysis and writing of texts on the basis of the analysis.
```python
#
```
> CVAT-UI: measure coverage.

- cvat/apps/documentation/installation.md
> Updated docker-compose versions in installation guide

- cvat/requirements/development.txt
Resolve #2181 
Removed some 3rd-party dependencies from development.txt that caused installation errors when using the new pip dependency resolver. These packages are not used directly and are pylint dependencies:
```
pylint==2.6.0
- astroid [required: >=2.4.0,<=2.5, installed: 2.4.2]
- lazy-object-proxy [required: ==1.4.*, installed: 1.4.3]
- six [required: ~=1.12, installed: 1.15.0]
- wrapt [required: ~=1.11, installed: 1.12.1]
- isort [required: >=4.2.5,<6, installed: 5.5.4]
- mccabe [required: >=0.6,<0.7, installed: 0.6.1]
- toml [required: >=0.7.1, installed: 0.10.1]
```
Coming PIP updates causes installation issues
Manually tested with pip==20.2.3 and `--use-feature=2020-resolver` option
- ~~[ ] I have added description of my changes into …
> Removed 3rdparty dependencies from development.txt to fix `pip install` command with new pip resolver.

- tests/cypress/integration/case_9_cuboid_shape_track_label.js
- tests/cypress/integration/issue_1568_cuboid_dump_annotation.js
- tests/cypress/support/commands.js
Try to draw a cuboid shape in two ways (by 2 points, by 4 points)
Try to draw a cuboid track
Try to switch a label and draw one more cuboid
Check if objects are drawn and they are shapes/tracks with right labels
Rebuild function for create cuboid. Adapt other test which use this function. …
> Cypress test. Actions on cuboid.

- tests/cypress/integration/case_10_polygon_shape_track_label_points.js
- tests/cypress/integration/issue_1444_filter_property_shape.js
- tests/cypress/integration/issue_1882_polygon_interpolation.js
- tests/cypress/integration/issue_1886_point_coordinates_not_duplicated.js
- tests/cypress/support/commands.js
Try to draw a polygon shape/track
Try to use parameter “number of points”, polygon drawing should automatically stop after this number of points is achieved
Try to switch a label and draw one more polygon
Check if everything works here.
Adapt the tests to use the updated polygon drawing function.
Redesigned the polygon drawing function for using an object as an argument. …
> Cypress test. Actions on polygon.

- tests/cypress/integration/case_12_points_shape_track_label.js
- tests/cypress/integration/issue_1368_points_track_invisible_next_frame.js
- tests/cypress/integration/issue_1841_hidden_points_cuboids_grouping.js
- tests/cypress/support/commands.js
Try to draw a points shape/track
Try to use parameter “number of points”, points drawing should automatically stop after this number of points is achieved
Try to switch a label and draw one more points
Check if everything works here.
Adaptation of several tests, which use the function of drawing points. …
> Cypress test. Actions on points.

- tests/cypress/integration/case_6_image_scale_fit.js
Dynamically retrieving values for calculating the correctness of scale.
```python
#
```
> Update Cypress test for case 6.

- cvat/apps/engine/serializers.py
- serverless/openvino/dextr/nuclio/model_handler.py
- serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio/model_handler.py
- serverless/openvino/omz/intel/semantic-segmentation-adas-0001/nuclio/model_handler.py
- serverless/openvino/omz/intel/text-detection-0004/nuclio/model_handler.py
- serverless/openvino/omz/public/faster_rcnn_inception_v2_coco/nuclio/model_handler.py
- serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio/model_handler.py
- serverless/openvino/omz/public/yolo-v3-tf/nuclio/model_handler.py
- serverless/pytorch/foolwood/siammask/nuclio/model_handler.py
- serverless/pytorch/saic-vul/fbrs/nuclio/model_handler.py
- serverless/tensorflow/matterport/mask_rcnn/nuclio/model_loader.py
Fixed some linter issues
- ~~[ ] I have added description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning), …
> Fixed some issues found by code scanning tool

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/create-task-page/advanced-configuration-form.tsx
Change the default way of a task creating
```python
#
```
> Use cache default

- cvat/apps/engine/views.py
Reduced the preparation time of the user list on the backend
The `users` request is currently taking too long.
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~~~
- ~~[ ] I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cvat-canvas#versioning), …
> Reduced the preparation time of the user list on the backend

- cvat-ui/src/components/tasks-page/styles.scss
- cvat-ui/src/components/tasks-page/task-item.tsx
To reliable cypress end-to-end testing we need some additional classes that are introduced in the PR
Manual testing
```python
#
```
> Added css classes for cypress testing

- tests/.eslintrc.js
Missed one file in the previous patch
Manual testing
```python
#
```
> Added .eslintrc.js for tests

- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/object-item-buttons.tsx
Testing team request
Manual testing
```python
#
```
> Additional CSS classes in CVAT to cypress testing

- cvat-canvas/package-lock.json
- cvat-canvas/package.json
- cvat-ui/package-lock.json
- cvat-ui/package.json
Previous node-sass version breaks the built. 
Resolved #2365
Tried to build
```python
#
```
> Updated sass

- README.md
Per my conversation with @nmanovic, I'm proposing adding a "Project using CVAT" section to CVAT README. I've also added Onepanel as the first project but the idea is to have other contributors to feature certain projects that use or build on CVAT here as well. 
Questions:
1. Can an animated gif or image be added here?
2. Should this section be under **Links** section or higher up? …
> Include Projects using CVAT section, add Onepanel

- CHANGELOG.md
> Release 1.2.0-alpha

- tests/cypress/integration/actions_tasks_objects/case_15_group_features.js
Cypress test. Group features.
```python
#
```
> Cypress test. Group features.

- tests/cypress/integration/actions_tasks_objects/case_16_z_order_features.js
Cypress test. Z-order feature.
```python
#
```
> Cypress test. Z-order feature.

- cvat-ui/src/components/annotation-page/appearance-block.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/color-picker.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/label-item.tsx
New set of classes for end-to-end tests
Manual testing
```python
#
```
> Additional css classes for testing

- serverless/openvino/dextr/nuclio/function.yaml
- serverless/openvino/omz/intel/person-reidentification-retail-300/nuclio/function.yaml
- serverless/openvino/omz/intel/semantic-segmentation-adas-0001/nuclio/function.yaml
- serverless/openvino/omz/intel/text-detection-0004/nuclio/function.yaml
- serverless/openvino/omz/public/faster_rcnn_inception_v2_coco/nuclio/function.yaml
- serverless/openvino/omz/public/mask_rcnn_inception_resnet_v2_atrous_coco/nuclio/function.yaml
- serverless/openvino/omz/public/yolo-v3-tf/nuclio/function.yaml
- serverless/pytorch/foolwood/siammask/nuclio/function.yaml
- serverless/pytorch/saic-vul/fbrs/nuclio/function.yaml
- serverless/tensorflow/faster_rcnn_inception_v2_coco/nuclio/function.yaml
- serverless/tensorflow/matterport/mask_rcnn/nuclio/function.yaml
> fix for kubrenetes name (DNS-1123)

- tests/cypress/integration/actions_tasks_objects/issue_2411_deleting_attributes.js
Cypress test for #2411 
```python
#
```
> Cypress test. Issue 2411

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/labels-editor/label-form.tsx
We need it to implement some end-to-end tests
Manual testing
```python
#
```
> Added css classes to cypress

- tests/cypress/integration/actions_users/issue_2440_value_must_be_a_user_instance.js
Cypress test. Issue #2440 .
```python
#
```
> Cypress test. Issue 2440.

- tests/cypress/integration/actions_tasks_objects/issue_1922_error_canvas_is_busy_at_resize_element.js
- tests/cypress/support/commands.js
Cypress test. Error canvas is busy at resize element.
```python
#
```
> Cypress test. Error canvas is busy at resize element.

- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/objects-list-header.tsx
- cvat-ui/src/components/header/settings-modal/player-settings.tsx
Some additional selectors were requested to cypress testing
Manual testing
```python
#
```
> Added css classes for end-to-end testing

- tests/cypress/integration/actions_tasks_objects/issue_1823_opening_context_menu_when_switching_another_frame.js
- tests/cypress/support/commands.js
Cypress test. Issue #1823 .
```python
#
```
> Cypress test. Issue 1823.

- tests/cypress/integration/actions_tasks_objects/case_18_filters_functionality.js
- tests/cypress/support/commands.js
Cypress test. Filters features.
I also slightly modified 2 tests in which elements are selected by label name on the labels tab. Made a selection using a regular expression.
```python
#
```
> Cypress test. Filters features.

- tests/cypress/integration/actions_tasks_objects/case_23_canvas_grid_feature.js
Cypress test. Canvas grid feature.
```python
#
```
> Cypress test. Canvas grid feature.

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/reducers/review-reducer.ts
Resolved #2524
Manual testing
```python
#
```
> Reset state after logout & changing a job

- tests/cypress/integration/actions_tasks_objects/case_25_canvas_bitmap_feature.js
Cypress test. Canvas bitmap feature.
```python
#
```
> Cypress test. Canvas bitmap feature.

- tests/cypress/integration/actions_tasks_objects/issue_2486_not_edit_object_aam.js
Cypress test. Issue #2486 
```python
#
```
> Cypress test. Check ability to edit positions in AAM.

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/top-bar/player-buttons.tsx
- tests/cypress/integration/actions_tasks_objects/case_13_merge_split_features.js
- tests/cypress/integration/actions_tasks_objects/issue_2485_navigation_empty_frames.js
- tests/cypress/support/commands.js
Cypress test. Issue #2485 
Added some Cypress commands. Test adaptation.
```python
#
```
> Cypress test. Issue 2485.

- CHANGELOG.md
- cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
- tests/cypress/integration/actions_tasks_objects/issue_2486_not_edit_object_aam.js
Editing positions in AAM is returned by a request of one of our customers
Manual testing
```python
#
```
> Abort PR #2506 by customer request

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-editor.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/attribute-switcher.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-basics-edtior.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/attribute-annotation-sidebar/object-switcher.tsx
- cvat-ui/src/components/annotation-page/attribute-annotation-workspace/styles.scss
- tests/cypress/integration/actions_tasks_objects/case_32_attribute_annotation_mode_zoom_margin_feature.js
- tests/cypress/integration/actions_tasks_objects/issue_1425_highlighted_attribute_correspond_chosen_attribute.js
- tests/cypress/integration/actions_tasks_objects/issue_1750_err_aam_switch_frames.js
- tests/cypress/support/commands.js
Cypress test. Attribute annotation mode zoom margin feature.
Several cssSelectors added for elements.
several tests improved with new cssSelectors.
```python
#
```
> Cypress test. Attribute annotation mode zoom margin feature.

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/task-page/details.tsx
- tests/cypress/integration/actions_users/issue_1810_login_logout.js
Upgrade cypress test. Login and logout.
Add cssSelector for task name element.
```python
#
```
> Upgrade cypress test. Login and logout.

- tests/cypress/integration/actions_tasks_objects/issue_2487_extra_instances_canvas_grouping.js
Cypress test for issue #2487 
```python
#
```
> Cypress test. Issue 2487.

- tests/cypress/integration/actions_tasks_objects/case_33_button_continue_label_editor.js
- tests/cypress/support/commands.js
Cypress test. Button “Continue” in label editor.
```python
#
```
> Cypress test. Button “Continue” in label editor.

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/project-page/top-bar.tsx
Resolved #2625 
Manual testing
```python
#
```
> Fixed project removing

- cvat-canvas/src/typescript/canvas.ts
- cvat-ui/src/cvat-canvas-wrapper.ts
- cvat-ui/src/reducers/interfaces.ts
Related https://github.com/webpack/webpack/issues/7378
Manual testing
```python
#
```
> Fixed annoying warnings from cvat-canvas

- cvat-ui/src/components/projects-page/actions-menu.tsx
- tests/cypress.json
- tests/cypress/integration/actions_projects/issue_2625_delete_project_via_actions.js
- tests/cypress/integration/actions_projects/registration_involved/base_actions_project_task_user.js
- tests/cypress_cron_type.json
Cypress test for issue #2625.
Add css class.
Rework main cypress config files.
```python
#
```
> Cypress test. Issue 2625.

- tests/cypress/integration/actions_tasks_objects/case_37_object_make_copy.js
Cypress test. Object make a copy.
```python
#
```
> Cypress test. Object make a copy.

- cvat-ui/src/components/feedback/feedback.tsx
- tests/cypress/integration/actions_users/case_38_feedback_button.js
Cypress test. Feedback button.
```python
#
```
> Cypress test. Feedback button.

- cvat/requirements/base.txt
Now when using pip version  20.3.3:
```bash
ERROR: Cannot install -r cvat/requirements/base.txt (line 37), -r cvat/requirements/base.txt (line 38), -r cvat/requirements/base.txt (line 42), -r cvat/requirements/base.txt (line 47), -r cvat/requirements/base.txt (line 48) and numpy==1.18.5 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested numpy==1.18.5
datumaro 0.1.4 depends on numpy>=1.17.3
h5py 2.10.0 depends on numpy>=1.7
open3d 0.11.2 depends on numpy
opencv-python-headless 4.4.0.42 depends on numpy>=1.17.3
tensorflow 2.4.0 depends on numpy~=1.19.2
```
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#lin …
> Update numpy version

- README.md
Displays the status of CI performed in GitHub Actions.
```python
#
```
> Change badge for CI to GitHub Actions.

- .eslintrc.js
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
> Updated license year

- cvat-ui/src/components/annotation-page/annotations-filters-input.tsx
- tests/cypress/integration/actions_tasks_objects/issue_2690_filters_help_window.js
Add Cypress test Issue #2690 
```python
#
```
> Cypress test. Annotation filters help window.

- tests/cypress/integration/actions_tasks_objects/case_45_open_the_task_button.js
> Cypress test. "Open the task" button.

- tests/cypress/integration/actions_tasks_objects/case_47_export_dataset.js
> Cypress test. Export as a dataset.

- tests/cypress/integration/actions_tasks_objects/case_49_settings_show_all_interpolation_tracks.js
> Cypress test. Settings. Show all interpolation tracks.

- tests/cypress/integration/actions_tasks_objects/issue_2661_displaying_attached_files_when_creating_task.js
- tests/package-lock.json
- tests/package.json
Add Cypress test for issue #2661 
```python
#
```
> Cypress test. Show attached files when creating task.

- CHANGELOG.md
I made a mistake in changelog for previous PR, that was merged. So now I want to fix it. 
```python
#
```
> Changelog small fix

- tests/cypress/integration/actions_tasks_objects/case_48_issue_2663_annotations_statistics.js
Add Cypress test. Contains the issue #2663 check
```python
#
```
> Cypress test. Annotations statistics.

- cvat/requirements/base.txt
Fix build error:
```
import pycocotools._mask as _mask
File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versio …
> updated numpy and tensorflow versions

- tests/cypress/integration/actions_tasks_objects/case_51_settings_auto_save.js
> Cypress test. Settings. Auto save.

- cvat-canvas/package-lock.json
- cvat-canvas/package.json
- cvat-core/package-lock.json
- cvat-data/package-lock.json
- cvat-data/package.json
- cvat-ui/package-lock.json
> Fixed a lot of low & several high vulnerabilities found by npm audit

- cvat/apps/dataset_manager/bindings.py
- Fixes filename matching after Datumaro update 1.5 (no affected CVAT releases)
- Fixes a problem with intermediate dots in imported filenames, that were considered as extension separators …
> Add image ext in filename matching

- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/issues-list.tsx
- tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
- tests/cypress/support/commands_review_pipeline.js
At the moment, test checks the highlighting of the issue region when hovering the mouse over the sidebar issue item elements in order from top to bottom. There may be a situation where the server returns these elements in reverse order. In this case, the test will fail with an error. This patch adds an ```id``` to the sidebar issue elements. The ```id``` corresponds to the ```id``` of the issue region. And the test checks that when hover the mouse over the sidebar issue item with ```id``` N, the element of the issue region with the same ```id``` will be highlighted.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keywo …
> Add "id" to sidebar issue item. Update Cypress test.

- cvat-core/src/labels.js
- cvat-ui/src/components/labels-editor/label-form.tsx
- cvat/apps/engine/serializers.py
Enable label name edition 
```python
#
```
> Label name editing

- components/analytics/docker-compose.analytics.yml
Not applicable
Not applicable
Not applicable
> Change the docker image for cvat_kibana_setup

- tests/cypress/integration/actions_tasks_objects/case_31_label_constructor_color_name_label.js
Update Cypress test. Check PR #2806 
```python
#
```
> Cypress. Update case "Label constructor. Color label." Added a change label name.

- CHANGELOG.md
> Changelog date error

- .github/workflows/eslint.yml
- .github/workflows/linters.yml
- cvat-ui/.eslintrc.js
A written script for static code analysis using eslint of all files in PR.
For example:
To get the files into the commit, I added one EOF to the file from the cvat-* directory. Result: https://github.com/dvkruchinin/cvat/actions/runs/569756587
Feel free …
> Linters. Eslint.

- cvat/apps/lambda_manager/views.py
Receive and send max_distance value.
Resolve #2767 
```python
#
```
> Receive and send max_distance value.

- .github/workflows/pylint.yml
Installing only the python module ```Django``` from ```base.txt``` requirements.
Link to check: https://github.com/dvkruchinin/cvat/pull/27/checks?check_run_id=1972372787
```python
#
```
> Pylint. Disabling the installation of all django-* modules.

- Dockerfile
- cvat/requirements/base.txt
Resolve #2799
Also pip, setuptools and wheel packages have been updated.
CI …
> Fixed numpy version mismatch

- .github/workflows/bandit.yml
- .github/workflows/eslint.yml
- .github/workflows/pylint.yml
Changing the logic of getting the file list from PR.
```python
#
```
> Workflow. Change getting files from PR.

- .github/workflows/bandit.yml
- .github/workflows/eslint.yml
- .github/workflows/pylint.yml
This patch will help avoid errors in the future when the utility tries to perform a static analysis of the code of a file that is removed from the repository as part of PR.
The check will include files that do not have the ```removed``` status.
Feel …
> Linters. Selecting files if the status is not "removed".

- cvat/apps/dataset_manager/formats/camvid.py
- cvat/apps/dataset_manager/formats/coco.py
- cvat/apps/dataset_manager/formats/cvat.py
- cvat/apps/dataset_manager/formats/imagenet.py
- cvat/apps/dataset_manager/formats/labelme.py
- cvat/apps/dataset_manager/formats/mask.py
- cvat/apps/dataset_manager/formats/mot.py
- cvat/apps/dataset_manager/formats/mots.py
- cvat/apps/dataset_manager/formats/pascal_voc.py
- cvat/apps/dataset_manager/formats/tfrecord.py
- cvat/apps/dataset_manager/formats/yolo.py
- cvat/apps/dataset_manager/tests/test_formats.py
- cvat/requirements/base.txt
- Updates Datumaro dependency to use v0.1.6.1
- Simplifies format implementations
- Improves performance of mask export (read Datumaro release notes)
Unit tests
Manual performance tests
```python …
```
> Update CVAT formats to use changes in Datumaro API

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/create-task-page/project-search-field.tsx
Fixed #2900
Manually
```python
#
```
> Fixed project search field

- .github/workflows/main.yml
- .github/workflows/publish_docker_images.yml
- .github/workflows/schedule.yml
If cypress tests fail with an error, the screenshots folder will be uploaded as an artifact.
Changed the command to run cypress tests in ```.github/workflows/publish_docker_images.yml``` to exclude cypress messages that there are no instrumented files …
> Upload cypress screenshots folder as an artifact if the tests failed with an error.

- tests/cypress/integration/actions_projects/registration_involved/base_actions_project_task_user.js
- tests/cypress/integration/actions_tasks_objects/registration_involved/case_39_issue_2572_rename_task.js
- tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
- tests/cypress/integration/actions_users/registration_involved/case_2_register_user_change_pass.js
- tests/cypress/integration/actions_users/registration_involved/case_4_assign_taks_job_users.js
- tests/cypress/integration/actions_users/registration_involved/issue_1599_ch_user_registration.js
- tests/cypress/integration/actions_users/registration_involved/issue_1599_pl_user_registration.js
- tests/cypress/support/commands.js
The test uses the credential generation function. It may match so that the generated password will not meet the CVAT requirements. In this case, the test will fail.
```python
#
```
> Rework Cypress test "Register user, change password, login with new password".

- cvat/apps/engine/media_extractors.py
- cvat/apps/engine/task.py
Unified ChunkWriters interfaces: quality setting from 0..100 range for both writers
Fix unit tests for https://github.com/openvinotoolkit/cvat/pull/2875
```python
#
```
> Fixed tests for nm/libx264

- CHANGELOG.md
- cvat/apps/documentation/backup_guide.md
- cvat/apps/documentation/faq.md
- docker-compose.yml
> Added backup/restore guide

- cvat-core/tests/api/projects.js
- cvat-core/tests/api/tasks.js
- cvat-core/tests/mocks/dummy-data.mock.js
- cvat-ui/src/components/annotation-page/annotation-page.tsx
- cvat-ui/src/components/labels-editor/labels-editor.tsx
- cvat-ui/src/reducers/notifications-reducer.ts
- tests/cypress/integration/actions_projects/case_57_project_label_deleting_feature.js
- tests/cypress/integration/actions_tasks_objects/case_58_task_label_deleting_feature.js
- tests/cypress/support/commands.js
Add Cypress/unit tests for the feature "Label deleting".
```python
#
```
> Cypress/unit tests. Label deleting feature.

- tests/cypress/integration/actions_tasks_objects/case_44_changing_default_value_for_attribute.js
Check issue #2968 
```python
#
```
> Update Cypress test for check issue 2968.

- cvat/apps/engine/serializers.py
- cvat/apps/engine/views.py
Added API documentation for `deleted` parameter. Added missed params `without_tasks`, `names_only` description.
Manually …
> Deleted API param description

- tests/cypress/integration/actions_tasks_objects/case_65_create_task_with_manifest.js
- tests/cypress/integration/actions_tasks_objects/case_66_rename_label_raw_editor.js
Add cypress test.
```python
#
```
> Cypress test. Change a label name/color via raw editor.

- tests/cypress/integration/actions_tasks_objects/case_67_intelligent_polygon_cropping.js
Cypress test for #3021 feature
```python
#
```
> Cypress test. Intelligent polygon cropping.

- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/header/settings-modal/settings-modal.tsx
Fixed warning message for settings load error
Manually …
> Fixed settings warning message

- cvat-ui/src/components/header/settings-modal/settings-modal.tsx
- tests/cypress/integration/actions_tasks_objects/case_68_saving_settings_local_storage.js
- tests/cypress/support/commands.js
Add Cypress test for feature #3017 
```python
#
```
> Cypress test. Saving settings to local storage.

- cvat-ui/src/components/shortcuts-dialog/shortcuts-dialog.tsx
- tests/cypress/integration/actions_tasks_objects/case_71_shortcuts_window.js
Add the Cypress test.
```python
#
```
> Cypress test. Shortcuts window.

- README.md
Added a couple of nice badges for Docker Hub. Also slightly improve badges section.
Recently we added images on dockerhub. It will be great to have links with some statistics as badges on our README.md page.
N/A …
> Badges for dockerhub

- .github/workflows/cancel.yml
- .github/workflows/main.yml
To prevent a workflow startup queue from occurring.
Using the tool https://github.com/potiuk/cancel-workflow-runs it is possible to cancel previous workflow launches for a specific branch from which the PR was created.
An important condition for this feature to work is that it must be merged in the default branch. …
> CI. Canceling previous workflow runs.

- cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
- cvat-ui/src/components/annotation-page/standard3D-workspace/controls-side-bar/photo-context.tsx
- tests/cypress/integration/canvas3d_functionality/case_56_canvas3d_functionality_basic_actions.js
Added checks:
- Count of control buttons
- Tooltip
```python
#
```
> Update cypress test. Canvas 3D functionality. Basic actions.

- .github/workflows/remark.yml
Rework script to check length of ```messages```. If the size is greater than zero the script exits with code 1.
Add ```--quiet```
```output only warnings and errors```
```python
#
```
> CI. Remark linter. Check length of messages.

- tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
- tests/cypress/support/commands_review_pipeline.js
Added a step to re-open the issue.
```python
#
```
> Update cypress test. Review pipeline feature.

- tests/cypress/integration/actions_tasks3/case_74_drag_canvas.js
Check feature. Increase coverage.
```python
#
```
> Cypress test. Drag canvas.

- .github/workflows/remark.yml
Error creating a json report when updating the version of ```vfile-reporter-json``` to 3.0.0
```python
#
```
> Remark linter. Installing a specific version of the module for creating a json report.

- README.md
Helping users find annotation services for their projects. The main tool we use is CVAT.
```python
#
```
> Update README.md, add DataIsKey under "Projects using CVAT"

- .github/workflows/main.yml
- tests/cypress/integration/actions_tasks/case_51_settings_auto_save.js
Attaching container logs to artifacts in case of unsuccessful tests.
```python
#
```
> CI. Creating a "cvat" container log as an artifact.

- cvat/apps/dataset_manager/annotation.py
- cvat/apps/dataset_manager/tests/test_formats.py
- cvat/apps/engine/tests/test_rest_api.py
Fixes [#2924](https://github.com/openvinotoolkit/cvat/issues/2924)
test and manually
```python
#
```
> Fix duplicate points in polygons at upload CVAT for video

- tests/cypress/integration/actions_users/registration_involved/case_28_review_pipeline_feature.js
As a test drop elimination workaround.
An error occurs from time to time click on a set of elements of the same name. In this case, such elements occur in the form of a notification.
For example: https://github.com/dvkruchinin/cvat/pull/122/checks?check_run_id=2601980677. The situation of two notifications was reproduced, but the test was successful. …
> Cypress. Update test "Review pipeline feature".

- tests/cypress/integration/actions_tasks3/case_7_image_scale_roi.js
Increase code coverage for ```/cvat-canvas/src/typescript/zoomHandler.ts```
The code coverage of this file increases to 97.4%
```python
#
```
> Cypress. Update test "Check if image was scaled to ROI". Add check "cancel".

- utils/dataset_manifest/utils.py
A couple of missed commits from the merged patch
Manual testing
```python
#
```
> Support of context images for 2D tasks (Missed commits)

- .github/workflows/github_pages.yml
Fixed generation of documentation due config changes: `relativeURLs=true` https://gohugo.io/content-management/urls/#relative-urls
https://azhavoro.github.io/cvat/
```python
#
```
> fixed documentation workflow

- site/content/en/docs/for-users/user-guide/advanced/context-images.md
This PR resolve issue #3214
To add a section, I used the "add child page" button on the website. The images were added via insert, so they were uploaded to the https://user-images.githubusercontent.com/ and are not in the repository.
Feel free to …
> Add item "Context images" in User Guide

- site/content/en/docs/for-users/formats/format-specifications/format-cvat.md
Documented that CVAT for Video doesn't support `Tag` annotations for each frame.
Close #2923
```python
#
```
> Fix documentation for CVAT format

- site/assets/scss/_custom.scss
- site/content/en/about/_index.html
This PR contains improvements with high priority:
Remove "leadership" block on about page
Update block "the team" on about page
```python
#
```
> Update "about page" on website

- README.md
- site/content/en/docs/for-developers/CONTRIBUTING.md
This PR add contributing section to website and add link to this section in README.md
```python
#
```
> Publication CONTRIBUTING.md on the website

- README.md
> Add hmt.ai to CVAT

- cvat/apps/dataset_manager/tests/assets/annotations.json
- cvat/apps/dataset_manager/tests/assets/tasks.json
- cvat/apps/dataset_manager/tests/test_rest_api_formats.py
Add test for bug with duplicate points in polygon #3187
```python
#
```
> Add test for bug with duplicate points in polygon

- cvat/apps/dataset_manager/tests/assets/annotations.json
- cvat/apps/dataset_manager/tests/assets/tasks.json
- cvat/apps/dataset_manager/tests/test_rest_api_formats.py
- cvat/requirements/base.txt
- Update Datumaro version to 0.1.9
- Add test for bug with attribute in WiderFace #2944 
```python
#
```
> Add test for bug with attribute in WiderFace

- tests/cypress/integration/actions_tasks/case_96_create_save_undo_save_redo_save.js
Cypress test for #3292 
```python
#
```
> Cypress test. Create an object, save, undo, save, redo, save.

- utils/cli/core/core.py
Hi, I am currently trying to parse the output of the command `cli.py ls --json`, but it breaks. I looked and it seems the current implementation returns the tasks as isolated json elements. That is fine when we have a single task, but when we have multiple tasks the command output is an invalid json. It looks like this:
```
{
...
}
{
...
}
```
This commit aims to fix this by returning the tasks as a Json array. I believe that would be the expected result when the user uses the --json flag. Let me know if I'm missing something here.    …
> fix json output of CLI command ls

- cvat-canvas/src/typescript/master.ts
- cvat-ui/src/containers/annotation-page/review-workspace/controls-side-bar/controls-side-bar.tsx
This code was reported as unused by @dvkruchinin 
It works after the code removed
```python
#
```
> Removed some unused code

- tests/cypress/integration/canvas3d_functionality/case_83_canvas3d_functionality_cuboid_grouping.js
- tests/cypress/integration/canvas3d_functionality/case_85_canvas3d_functionality_cuboid_сancel_drawing.js
Updating tests to increase the coverage.
```python
#
```
> Cypress tests. Update tests for CVAT-3D.

- cvat/apps/engine/views.py
Resolved #2839
Manual testing
```python
#
```
> Fixed django exception when get data for unknown task

- .github/workflows/github_pages.yml
- site/build_docs.py
Build documentation for major releases
https://azhavoro.github.io/cvat/docs/ …
> Documentation versioning

- tests/cypress/integration/actions_objects/case_37_object_make_copy.js
- tests/cypress/integration/canvas3d_functionality/case_80_canvas3d_functionality_cuboid_make_copy.js
Add some scenarios. 
```python
#
```
> Cypress tests. Update "Make a copy" for 2D, 3D.

- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
Small improvement of vs-code settings to the proper launch of server and UI tasks
Manually …
> Small improvement of vs-code settings

- cvat/apps/dataset_repo/tests.py
Code coverage tests for Dataset repo module using mock functions. 
```python
#
```
> Add tests for Dataset repo.

- CHANGELOG.md
> Fixed remark issues

- CHANGELOG.md
- cvat-ui/package-lock.json
- cvat-ui/package.json
- cvat-ui/src/components/move-task-modal/move-task-modal.tsx
Fixed #3403
Manually
```python
#
```
> Fixed cannot read property 'newLabelName' of undefined

- site/content/en/docs/administration/_index.md
- site/content/en/docs/administration/advanced/_index.md
- site/content/en/docs/administration/advanced/analytics.md
- site/content/en/docs/administration/advanced/backup_guide.md
- site/content/en/docs/administration/advanced/installation_automatic_annotation.md
- site/content/en/docs/administration/advanced/mounting_cloud_storages.md
- site/content/en/docs/administration/basics/AWS-Deployment-Guide.md
- site/content/en/docs/administration/basics/REST_API_guide.md
- site/content/en/docs/administration/basics/_index.md
- site/content/en/docs/administration/basics/installation.md
- site/content/en/docs/contributing/_index.md
- site/content/en/docs/contributing/branching-model.md
- site/content/en/docs/contributing/bug-reports.md
- site/content/en/docs/contributing/coding-style.md
- site/content/en/docs/contributing/development-environment.md
- site/content/en/docs/contributing/feature-requests.md
- site/content/en/docs/contributing/new-annotation-format.md
- site/content/en/docs/contributing/pull-requests.md
- site/content/en/docs/contributing/rest-api-design.md
- site/content/en/docs/contributing/setup-additional-components.md
- site/content/en/docs/contributing/using-the-issue-tracker.md
This PR adds descriptions for pages in Administration and Contributing sections.
```python
#
```
> Documentation update, adding descriptions for pages in Administration and Contributing sections.

- tests/cypress/integration/canvas3d_functionality/case_85_canvas3d_functionality_cuboid_сancel_drawing.js
Temporarily disabling the test step in the case 85.
```python
#
```
> Cypress. Temporarily disabling the test step in the case 85.

- cvat-ui/src/components/export-dataset/export-dataset-modal.tsx
- tests/cypress/integration/actions_projects_models/case_103_project_export.js
- tests/cypress/support/commands_projects.js
Cypress test for project export feature.
```python
#
```
> Cypress test. Project export feature.

- site/config.toml
This PR adds a link to the GitHub repository to the top menu of the documentation site.
```python
#
```
> Add a link to GitHub repository to the top menu 

- cvat-ui/src/components/export-dataset/export-dataset-modal.tsx
- tests/cypress/integration/actions_tasks/case_52_dump_upload_annotation.js
- tests/cypress/integration/actions_tasks3/case_47_export_dataset.js
- tests/cypress/integration/canvas3d_functionality/case_91_canvas3d_functionality_dump_upload_annotation_point_cloud_format.js
- tests/cypress/integration/canvas3d_functionality/case_92_canvas3d_functionality_dump_upload_annotation_velodyne_points_format.js
- tests/cypress/integration/canvas3d_functionality/case_93_canvas3d_functionality_export_dataset.js
- tests/cypress/integration/issues_prs2/issue_1568_cuboid_dump_annotation.js
- tests/cypress/support/commands.js
- tests/cypress_canvas3d.json
Coverage of updated functionality by dump, upload annotations. Added scenario for renaming the archive.
```python
#
```
> Cypress test. Update cases dump/upload annotations.

- Dockerfile.ui
> Security upgrade nginx from stable-alpine to mainline-alpine

- site/content/en/docs/manual/advanced/cli.md
* These features exist in the code but not in documentation
```python
#
```
> Update cli.md with missing features (upload, export, import)

- site/README.md
- site/assets/scss/_custom.scss
- site/build_docs.py
- site/config.toml
- site/content/en/_index.html
- site/layouts/404.html
- site/layouts/partials/footer.html
- site/layouts/partials/navbar-version-selector.html
- site/layouts/partials/navbar.html
- updated `site/build_docs.py` thus, when using `git checkout` from another version, only the "docs" and "Images" folders are added, and not the entire structure, this is necessary for the correct operation of the rest of the site.
- add `navbar-version-selector.html` to ensure that when you change the version, the current page in a different version opens and not the root of the site
- in `_index.html` adding meta tag for redirecting to about page https://tosmanov.github.io/cvat/
https://tosmanov.github.io/cvat/docs/ …
> Improved documentation versioning

- site/content/en/docs/manual/basics/creating_an_annotation_task.md
- site/content/en/docs/manual/basics/tasks-page.md
This PR corrects the "Creating an annotation task" page structure and adds a separate page for the tasks page information. 
```python
#
```
> Improve documentation, correction of the "Creating an annotation task" page structure

- .github/workflows/main.yml
- tests/cypress/integration/actions_tasks/case_52_dump_upload_annotation.js
- tests/cypress/integration/canvas3d_functionality/case_91_canvas3d_functionality_dump_upload_annotation_point_cloud_format.js
- tests/cypress/integration/canvas3d_functionality/case_92_canvas3d_functionality_dump_upload_annotation_velodyne_points_format.js
- tests/cypress/integration/issues_prs2/issue_1823_opening_context_menu_when_switching_another_frame.js
- tests/package-lock.json
- tests/package.json
Cypress update.
Updating plugins. The modules used.
Adaptation of tests. CI configurations.
```python
#
```
> Migration to the latest version of Cypress

- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/components/annotation-page/canvas/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/canvas/canvas-wrapper3D.tsx
- cvat-ui/src/reducers/annotation-reducer.ts
- cvat-ui/src/reducers/interfaces.ts
The code has been added on initial state of development React UI (#1106) and it is not used anyhow.
Maybe I intended to implement multiple objects selection. 
```python
#
```
> Removed unused code

- cvat-ui/src/components/cloud-storages-page/styles.scss
Resolve #3718
Manually
~~- [ ] I have updated the license header for each file (see an example …
> Fix cloud storage preview cropping

- tests/cypress/integration/actions_users/case_106_email_confirmation_page.js
Added Cypress test for feature #3573 
```python
#
```
> Cypress test. Email confirmation page.

- cvat/apps/engine/serializers.py
Resolved #3831
Related lines are not tested.
https://github.com/opencv/cvat/blob/develop/README.md#documentation) accordingly~
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioning))~
```python
#
```
> Enables to call storage.Client without service account path (GoogleCloudStorage)

- utils/dataset_manifest/create.py
> Fixed linter issue

- .github/workflows/main.yml
- tests/cypress/integration/canvas3d_functionality_2/case_56_canvas3d_functionality_basic_actions.js
This PR temporarily disabled the test due to its mailfunction
No testing. …
> Disabled some 3d tests for GitHub CI

- README.md
- https://www.cogitotech.com/partners
- https://cogitotech.medium.com/managing-computer-vision-tasks-with-cvat-dbe94a65f648
```python
#
```
> Cogito company as a partner

- cvat-ui/src/reducers/notifications-reducer.ts
> Fix cloud storage delete notification

- tests/cypress/integration/canvas3d_functionality_2/case_78_canvas3d_functionality_cuboid_label.js
Hi @azhavoro,
As we agreed, I have some reworked the test for your PR. Please take a look.
Comparing images:
Apparently, ```jimp``` does not see any difference in them and an error occurs that the images are not different.
Added a color change for the second label to red. …
> Cypress. Fix case 78 for PR 4007. Set color for second label.

- components/analytics/docker-compose.analytics.yml
- components/analytics/kibana/setup.py
Updated ELK to 6.8.21 and slightly improved setup script 
Manually …
> Updated ELK 6.4.0 -> 6.8.21

- .github/workflows/bandit.yml
- .github/workflows/eslint.yml
- .github/workflows/hadolint.yml
- .github/workflows/pylint.yml
- .github/workflows/stylelint.yml
At the moment, when checking with linters, additional pages with a list of files in the pull request are not taken into account. This patch fixes this.
```python
#
```
> Update workflows for linters.

- tests/cypress/integration/actions_tasks2/case_111_settings_text_size_position_label_content.js
Related on #4029 
Updating the test to check the feature.
```python
#
```
> Cypress. Update case 111. Added check ability to setup text labels content.

- CHANGELOG.md
- components/analytics/docker-compose.analytics.yml
Updated ELK to 6.8.22 (https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.22.html)
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versi …
> Updated ELK 6.8.21 -> 6.8.22

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> Fix grammarly issues

- tests/cypress/integration/email_system/check_email_verification_system.js
> Cypress. Fix the test for check Email verification system.

- tests/cypress/integration/canvas3d_functionality/case_91_canvas3d_functionality_dump_upload_annotation_point_cloud_format.js
- tests/cypress/integration/canvas3d_functionality/case_92_canvas3d_functionality_dump_upload_annotation_velodyne_points_format.js
The tests failed on the https://github.com/openvinotoolkit/cvat/runs/4614225884?check_suite_focus=true
Adding ```trigger('mouseout')```.
```python
#
```
> Cypress. Fixing cases 91, 92.

- .github/workflows/bandit.yml
- .github/workflows/eslint.yml
- .github/workflows/hadolint.yml
- .github/workflows/pylint.yml
- .github/workflows/stylelint.yml
Sometimes there is a problem with action ```jitterbit/get-changed-files@v1```.
```Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.```
Modified according to the recommendation ```https://github.com/jitterbit/get-changed-files/issues/11``` …
> CI. Fix linters workflows.

- tests/cypress/integration/actions_tasks/registration_involved/case_39_issue_2572_rename_task.js
The test adaptation to the develop branch.
```python
#
```
> Cypress. Case 39 reworking. Activating the step.

- .github/workflows/main.yml
- tests/cypress/integration/actions_users/registration_involved/case_4_assign_taks_job_users.js
- tests/cypress/support/commands.js
Test processing due to changes in the develop branch.
Added additional checks to the task deletion function.
A function for deleting users, tasks, and projects has been added to main.yml. This is due to the fact that Cypress did not catch the task deletion error in the test. The order of deleting tasks and users in the test has been changed to avoid dropping the test. The error was detected in https://github.com/openvinotoolkit/cvat/runs/4637596430?check_suite_focus=true. …
> Cypress. Update test case_4. 

- cvat/apps/engine/backup.py
Resolved #4097 
```python
#
```
> Fixed project restore within an organization

- tests/cypress/integration/actions_tasks/registration_involved/case_69_filters_sorting_jobs.js
Test crash due to interaction with dropdown menu.
Added additional menu visibility checks.
```python
#
```
> Cypress. Case 69. Added additional check dropdown menu visibility.

- cvat-ui/src/components/export-dataset/export-dataset-modal.tsx
Issue #4127
It fixes a spelling error in a modal that appears after exporting a task's dataset.
This shouldn't have any adverse effects.
~~- [] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~
~~- [] I have added tests to cover my changes~~ …
> Fix misspelling of automatically

- cvat/requirements/base.txt
* `--no-binary=pycocotools` isn't necessary since pycocotools 2.0.4.
* Installing Cython manually hasn't been needed since pycocotools 2.0.1
(and nothing else needs Cython to be installed).
Removing obsolete code/comments. Removing Cython also slightly reduces the Docker image size.
I built the Docker image and made sure that importing `pycocotools.mask` still worked.
- ~~[ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~ doesn't seem significant enough …
> Remove workarounds for pycocotools issues

- tests/cypress/integration/actions_users/registration_involved/case_4_assign_taks_job_users.js
Related to #4144 
Update case 4. Added the step to check the issue 4140.
```python
#
```
> Cypress. Update case 4. Added the step to check the fix 4144.

- cvat/requirements/base.txt
Security upgrade numpy from 1.19.5 to 1.22.0
```python
#
```
> Update numpy to 1.22.0, tensorflow to 2.7.0

- cvat/requirements/base.txt
Update django-filter to 2.4.0
```python
#
```
> Update django-filter to 2.4.0

- .eslintrc.js
- .github/PULL_REQUEST_TEMPLATE.md
- LICENSE
> Updated license year.

- tests/cypress/integration/actions_users/issue_2524_2633_issue_not_reset_after_change_task_issue_point_firefox.js
- tests/cypress/support/commands_review_pipeline.js
The tests adaptation to develop brunch. Enabling the steps.
```python
#
```
> Cypress test. Adjust, enabling tests for issues 2524 2633.

- CHANGELOG.md
- components/analytics/docker-compose.analytics.yml
Security ELK update, https://www.elastic.co/guide/en/elasticsearch/reference/6.8/release-notes-6.8.23.html
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-data#versioni …
> Update ELK to 6.8.23

- tests/cypress/integration/actions_objects/case_37_object_make_copy.js
- tests/cypress/integration/actions_objects2/case_108_rotated_bounding_boxes.js
- tests/cypress/integration/actions_objects2/case_115_ellipse_shape_track_label.js
- tests/cypress/integration/actions_tasks3/case_18_filters_functionality.js
- tests/cypress/support/commands.js
- tests/cypress/support/utils.js
Adding a test for an ellipse shape.
Drawing shapes, tracks/rotation/interpolation, copy/paste, rotation, filter.
```python
#
```
> Cypress test. Ellipse actions.

- cvat-canvas/package-lock.json
- cvat-canvas/package.json
- cvat-canvas/src/typescript/canvasView.ts
- cvat-canvas/src/typescript/drawHandler.ts
- cvat-canvas/src/typescript/shared.ts
To make ellipses behavior consistent with bbox 
```python
#
```
> Displaying shape size for ellipses

- site/content/en/docs/manual/advanced/cli.md
- site/content/en/docs/manual/advanced/xml_format.md
Resolved #3998 
Resolved #4244 
In this PR:
- Update `xml_format.md`
- The `Version 1` section has been removed from the `xml_format.md` file because it is not supported for export in the current version of CVAT and the text is duplicated in the `Version 1.1` section.
- Added node `<tag>` in example.
- Added attribute "source" for track in example.
- Fix mistakes in `cli.md` …
> Update documentation. Fix mistakes in cli section and update xml_format section

- site/content/en/docs/administration/advanced/backup_guide.md
An user tries to restore old DB backup for a new CVAT version:
https://github.com/openvinotoolkit/cvat/issues/4268#issuecomment-1026678433
> Add a warning about restore DB

- tests/cypress/integration/actions_tasks/task_changes_status_after_initial_save.js
- tests/cypress/integration/actions_users/issue_2524_2633_issue_not_reset_after_change_task_issue_point_firefox.js
> Added 2 cypress tests

- Dockerfile.ui
- cvat-ui/react_nginx.conf
- cvat-ui/webpack.config.js
resolve #4273 
**workers**
---
**main js bundle**
---
**index.html** …
> Don't cache index.html

- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx
- cvat-ui/src/components/annotation-page/standard-workspace/styles.scss
- tests/cypress/integration/actions_tasks2/case_101_opencv_basic_actions.js
- tests/cypress/support/commands_opencv.js
Add test for recently added new browser OpenCV TrackerMIL tool #4200
```python
#
```
> Cypress. Add test for OpenCV TrackerMIL tool

- cvat/apps/iam/serializers.py
> Fixed reset password functionality

- serverless/pytorch/ultralytics/yolov5/nuclio/function.yaml
Resolve https://github.com/openvinotoolkit/cvat/issues/4341
Manually
```python
#
```
> Fix YOLOv5 serverless function

- cvat/apps/engine/tests/test_rest_api.py
- cvat/apps/iam/permissions.py
Closes #4323 
The state and stage of a job can be changed by anyone, without any permission checks, since the scopes haven't been passed to OPA, bypassing authorization.
The change has been tested through a development environment set up on an ubuntu server. The changes were tested with the cvat UI through the use of the "Finish the job" button described in the connected issue, that can be found in the annotation topbar menu, when a job isn't in the "acceptance" stage and "completed" state. It has also been tested through api calls with users in all 4 groups in both sandbox and organization environments.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a …
> Fix stage and state modification permission

- site/content/en/docs/administration/basics/installation.md
This PR added the solution to the problem outlined in the #4261 to the Installation Guide
preview: https://tosmanov.github.io/cvat/docs/administration/basics/installation/#https-is-not-working-because-of-a-certificate …
> Updating the documentation. Adding Troubleshooting to the Installation Guide

- README.md
> Added Face Detection model to the list in README

- site/content/en/docs/manual/advanced/dataset_manifest.md
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~ …
> Fix typo in dataset manifest docs

- cvat/settings/production.py
- helm-chart/templates/cvat_backend/deployment.yml
> Fixed helm not using the configured pg port when installing cvat

- README.md
> Added ATLANTIS in README.

- SECURITY.md
> Intel® Bug Bounty Program

- CHANGELOG.md
- Dockerfile
Added missing dependency, otherwise it won't build on macos:
https://github.com/openvinotoolkit/cvat/issues/4426
> Added missing geos dependency

- cvat-ui/src/components/file-manager/cloud-storages-tab.tsx
> Fix filter for getting cloud storage on task creation page

- tests/python/rest_api/test_remote_url.py
> Fix rest api test

- lint-staged.config.js
> Added stylelint check to precommit git hook

- tests/cypress/integration/actions_users/case_38_feedback_button.js
> Fixed actions_users/case_38_feedback_button

- cvat-core/.eslintrc.js
- cvat-core/tests/api/annotations.js
- tests/cypress/integration/actions_users/case_38_feedback_button.js
> Fixed jest tests

- cvat-core/src/annotations-collection.ts
- cvat-core/src/annotations-objects.ts
- tests/cypress.json
- tests/cypress/integration/skeletons_pipeline.js
- tests/cypress/support/commands.js
- tests/docker-compose.file_share.yml
> Added end-to-end Cypress tests for Skeletons pipeline

- site/content/en/docs/faq.md
Added the information to the FAQ about DL models adding
> updated the FAQ.md

- CHANGELOG.md
- components/serverless/docker-compose.serverless.yml
- docker-compose.yml
> Fixed invocation of serverless functions

- cvat-sdk/cvat_sdk/core/proxies/model_proxy.py
Fixes the python3.7 compatibility issue from https://github.com/opencv/cvat/issues/4827#issuecomment-1239740097
- Changed `Literal` import from `typing` to `typing_extensions`
Manual running of unit tests on py3.7 …
> Fix python3.7 compatibility

- cvat-cli/requirements/base.txt
- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/gen/generate.sh
- tests/python/requirements.txt
> Bump sdk version and update deps

- site/content/en/docs/administration/basics/installation.md
Added information about default docker images to the installation guide.
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file~~ …
> updated installation guide

- .github/workflows/full.yml
- .github/workflows/main.yml
- .github/workflows/schedule.yml
Recently we have changed tags for our CVAT images in compose files, but we didn't change workflow configs accordingly.
> Update workflow configs

- .github/workflows/full.yml
- .github/workflows/main.yml
> Workflows: fix typo

- .github/workflows/publish_docker_images.yml
Currently workflow that publish CVAT images on dockerhub doesn't work (see [here](https://github.com/opencv/cvat/actions/runs/3040373763)). This PR resolved this problem.
> Fix publishing docker images workflow

- cvat-ui/src/containers/file-manager/file-manager.tsx
> Removed extra line

- site/content/en/about/_index.html
- Change the location
- Removed the map with our team
- Slightly modified text (inappropriate references to Intel)
> Update about page for documentation

- site/content/en/about/_index.html
> Docs: update about page

- components/serverless/docker-compose.serverless.yml
nuclio produces to many logs
manually
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and …
> set max size of nuclio log file

- .github/workflows/helm-nightly.yml
- .github/workflows/helm.yml
- tests/python/rest_api/test_remote_url.py
- tests/python/shared/fixtures/init.py
> Helm tests

- helm-chart/Chart.yaml
- helm-chart/values.yaml
> Fix Django admin page

- .github/workflows/comment.yml
Full check currently falls for PR from forked repository, this PR resolved this problem
> Full check: use sha instead of branch name

- cvat-ui/src/components/common/cvat-dropdown-menu-paper/index.scss
- cvat-ui/src/components/common/cvat-dropdown-menu-paper/index.tsx
- cvat-ui/src/components/create-task-page/create-task-content.tsx
- cvat-ui/src/components/project-page/project-page.tsx
- cvat-ui/src/components/tasks-page/styles.scss
- cvat-ui/src/components/tasks-page/top-bar.tsx
- tests/cypress/integration/actions_projects_models/issue_2900_creating_more_one_tasks_from_project_per_time.js
- tests/cypress/support/commands.js
> add link to create of many tasks from project page

- .github/workflows/black.yml
- .github/workflows/isort.yml
- tests/python/rest_api/test_analytics.py
- tests/python/rest_api/test_cache_policy.py
- tests/python/rest_api/test_check_objects_integrity.py
- tests/python/rest_api/test_cloud_storages.py
- tests/python/rest_api/test_invitations.py
- tests/python/rest_api/test_issues.py
- tests/python/rest_api/test_jobs.py
- tests/python/rest_api/test_memberships.py
- tests/python/rest_api/test_organizations.py
- tests/python/rest_api/test_projects.py
- tests/python/rest_api/test_remote_url.py
- tests/python/rest_api/test_resource_import_export.py
- tests/python/rest_api/test_server.py
- tests/python/rest_api/test_tasks.py
- tests/python/rest_api/test_users.py
- tests/python/rest_api/test_webhooks.py
- tests/python/shared/fixtures/data.py
- tests/python/shared/fixtures/init.py
- tests/python/shared/fixtures/util.py
- tests/python/shared/utils/config.py
- tests/python/shared/utils/dump_objects.py
- tests/python/shared/utils/helpers.py
- tests/python/webhook_receiver/server.py
- Enabled black and isort for `tests/python`
- Python tests autoformatted
> Autoformat python tests

- serverless/pytorch/foolwood/siammask/nuclio/function-gpu.yaml
Updates old docker image tag which are no longer available as discussed in 
https://github.com/opencv/cvat/issues/4912
Deployed siammask using the new image.
- [] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file
- [] I have updated the [documentation](
- [] ~~I have added tests to cover my changes~~
- [] ~~I have increased versions of npm packages if it is necessary ([cvat-canvas](https://github.com/cvat-ai/cvat/tree/develop/cvat-canvas#versioning), …
> Fix tensorflow docker image tag for siammask

- CHANGELOG.md
- serverless/pytorch/saic-vul/fbrs/nuclio/function.yaml
- serverless/pytorch/shiyinzhang/iog/nuclio/function.yaml
> Fix serverless functions

- CHANGELOG.md
- cvat-canvas/package.json
- cvat-canvas/src/typescript/canvasView.ts
> Fixed changing label color on canvas

- helm-chart/README.md
> Fix broken link

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/components/export-backup/export-backup-modal.tsx
> Fixed double modal export/backup a task/project

- .github/workflows/full.yml
- .github/workflows/main.yml
- cvat-sdk/cvat_sdk/core/client.py
- cvat/settings/base.py
- tests/python/rest_api/test_auth.py
> Fix SDK tests

- tests/cypress/integration/actions_objects2/case_15_group_features.js
- tests/cypress/integration/actions_tasks/case_72_hotkeys_change_labels.js
- tests/cypress/support/commands.js
> Added cypress tests for issue 4966

- site/content/en/docs/api_sdk/sdk/developer-guide.md
Related https://github.com/opencv/cvat/issues/5063#issuecomment-1272968601
> Extend SDK package developer installation instructions

- cvat/settings/base.py
> Increase throttle rate

- .github/workflows/black.yml
- tests/python/sdk/test_users.py
Black linter does not show what changes developer should apply, this PR resolve this issue.
Despite this fact that code formatting performed automatically it can be useful to see full information about Black linter to prevent such mistakes in next PRs.
See improved log artifacts [here](https://github.com/opencv/cvat/actions/runs/3250641902)
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-u …
> Improve report information for Black linter

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/actions/boundaries-actions.ts
> Fixed CVAT annotation view restoring

- .github/workflows/bandit.yml
- .github/workflows/black.yml
- .github/workflows/cache.yml
- .github/workflows/eslint.yml
- .github/workflows/full.yml
- .github/workflows/hadolint.yml
- .github/workflows/helm.yml
- .github/workflows/isort.yml
- .github/workflows/main.yml
- .github/workflows/publish_docker_images.yml
- .github/workflows/pylint.yml
- .github/workflows/remark.yml
- .github/workflows/schedule.yml
- .github/workflows/stylelint.yml
Since Node 12 has been mark as deprecated for Github Actions this PR updates versions for github actions that our repo uses.
> Update Github Actions

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/actions/annotation-actions.ts
> Propagate angle when use 'propagate' feature

- CHANGELOG.md
- cvat/requirements/base.txt
Fixes #5048.
I reproduced #5048, then made sure it no longer reproduces with this change.
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#versioning), [cvat-data](https://github.com/cvat-ai/cvat/tree/develop/cvat-data#versioning) and [cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#ve …
> Bump Datumaro commit

- cvat/requirements/base.txt
Fixes #5031
Follow-up for #5056, fixes mask export for other formats that were not covered by #5056 
Unit tests
> Fix mask export when background color has nonzero index in Cityscapes and KITTI

- site/content/en/docs/manual/basics/workspace.md
Fix Remark error that appeared after #5154
> Fix Remark lint error

- CHANGELOG.md
- cvat-ui/src/components/annotation-page/canvas/canvas-context-menu.tsx
> Fixed wrong issue position when create a quick issue on a rotated shape

- helm-chart/Chart.yaml
- helm-chart/values.yaml
> Fix ingress route for `static` path

- .github/workflows/cleanup.yml
- .github/workflows/full.yml
- .github/workflows/main.yml
> Extend logs for CI workflows

- site/content/en/docs/contributing/pull-requests.md
> Fix PR link

- cvat-core/package.json
- cvat-core/src/api-implementation.ts
- cvat-core/src/api.ts
- cvat-core/src/server-proxy.ts
Specifically:
* `padded-blocks`
* `@typescript-eslint/no-var-requires`
* `@typescript-eslint/return-await`
As far as I know, "go to definition" in VS Code only works with ES6-style imports. Since I was examining code in this file, I updated the imports to make it easier. I fixed the other ESLint errors, because otherwise it wouldn't let me commit the code. 🙂 
I'm relying on CI for this. …
> Fix ESLint errors in cvat-core/src/server-proxy.ts

- site/content/en/docs/contributing/development-environment.md
Since Arch Linux-based systems are quite popular, especially in home use and on older hardware, I assume that cvat installation instructions for this type of medium could benefit the community.
Tested the installation on a desktop home system (CPU i5 Skylake 6600K, 32 GB RAM, GPU AMD RX 480, pure Arch with XFCE), which is updated daily. The repos enabled are core, extra, community and multilib. AUR is managed by [pikaur](https://github.com/actionless/pikaur).
The packages and other related steps required for installation were found by trial and error. …
> Add dev environment installation instructions for Arch Linux-based systems

- site/content/en/docs/contributing/development-environment.md
> Fix line length in the installation docs

- .github/workflows/main.yml
> Extend main workflow

- cvat-ui/src/components/annotation-page/top-bar/filters-modal.tsx
- tests/cypress/integration/actions_objects/case_36_always_show_object_details_feature.js
- tests/cypress/integration/actions_tasks3/case_19_all_image_rotate_features.js
- tests/cypress/integration/issues_prs2/issue_1439_blocked_object_info.js
- tests/cypress/support/commands_filters_feature.js
>  Tried to fix one test

- CHANGELOG.md
- cvat/apps/dataset_manager/bindings.py
> Fixed: Oriented bounding boxes broken with COCO format

- cvat/apps/engine/mixins.py
- cvat/apps/engine/views.py
- cvat/apps/organizations/views.py
Fixes pylint warnings introduced in #4863 
- `perform_create()` in model-based ViewSets now allow to pass extra kwargs. This is aligned with what Django offers for `serializer.save()`
> Fix linter warnings

- cvat/apps/dataset_manager/task.py
- cvat/apps/dataset_repo/models.py
- cvat/apps/engine/backup.py
- cvat/apps/engine/cloud_provider.py
- cvat/apps/engine/location.py
- cvat/apps/engine/models.py
- cvat/apps/engine/tests/test_rest_api.py
- cvat/apps/engine/utils.py
- cvat/apps/engine/views.py
- cvat/apps/lambda_manager/views.py
- cvat/apps/webhooks/models.py
This reverts commit 43df70b08b318875d44018f8695c9fc5a8f90cdb, which can introduce some errors on CI
> Revert "Refactor server enums (#5062)"

- cvat/apps/engine/mixins.py
- cvat/apps/engine/views.py
- cvat/apps/organizations/views.py
Reverts opencv/cvat#5188, which breaks CI.
> Revert "Fix linter warnings"

- site/content/en/docs/getting_started/product_tour/cvat-intro.md
- site/content/en/docs/getting_started/product_tour/introduction-to-cvat-and-datumaro.md
added "introduction to cvat and datumaro" video
> CVAT docs: introduction to cvat and datumaro video

- tests/cypress.json
- tests/cypress/integration/masks/masks_basics.js
- tests/cypress/support/commands.js
> Added basic masks tests

- .github/workflows/main.yml
- tests/python/shared/fixtures/init.py
> Fix cvat version for CI

- site/content/en/docs/contributing/development-environment.md
Added missed port forwarding option to the development guide.
> Development guide update

- cvat-core/src/api-implementation.ts
- cvat-core/src/api.ts
- cvat-core/src/frames.ts
- cvat-core/tests/api/annotations.js
- cvat-core/tests/api/cloud-storages.js
- cvat-core/tests/api/frames.js
- cvat-core/tests/api/jobs.js
- cvat-core/tests/api/object-state.js
- cvat-core/tests/api/plugins.js
- cvat-core/tests/api/projects.js
- cvat-core/tests/api/server.js
- cvat-core/tests/api/tasks.js
- cvat-core/tests/api/user.js
- cvat-core/tests/api/webhooks.js
- cvat-core/tsconfig.json
This fixes ESLint errors in these files.
Set the `resolveJsonModule` setting, so that TypeScript can recognize the `package.json` import.
I like fixing ESLint errors.
I ran the UI with this version of the code and checked that basic operations still work.
- ~~[ ] I have …
> Convert `api.ts`, `api-implementation.ts` and `frames.ts` to ES6 modules

- .github/workflows/full.yml
- .github/workflows/main.yml
- .github/workflows/schedule.yml
https://docs.cypress.io/guides/guides/command-line#cypress-verify
- [x ] I submit _my code changes_ under the same [MIT License](
> Fix CI due to cypress verify works too long

- cvat/requirements/base.txt
Currently we have red develop branch (look [here](https://github.com/opencv/cvat/actions/runs/3503815625/jobs/5875192950)). This PR fix this problem
> Fix SDK build

- README.md
Link to the old videos removed as there were changes made in CVAT interface and now these videos are a bit confusing Links to playlists of the updated videos were added with the description what these videos contact Contacts sections updated
General proofreading
https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that …
> Videos link updated, contacts updated

- cvat-core/src/server-proxy.ts
Currently, all properties of the server proxy object are created using `Object.defineProperties` in the constructor, which means that IDEs like VS Code can't analyze the file's static structure to determine what properties there are and what types they have.  Consequently, things like autocomplete and go-to-definition don't work.
Fix that by removing the `ServerProxy` class altogether and exporting an anonymous object with all properties defined statically.
This makes viewing and editing API-adjacent code in VS Code easier. It also eliminates spurious "property not found" errors from VS Code.
Manual smoke testing. …
> Make the server proxy's properties visible to static analysis

- tests/python/rest_api/test_webhooks_sender.py
Added wait for delivery response in tests for webhook sender
> Test webhooks sender: wait for delivery response

- cvat/requirements/base.txt
- utils/dataset_manifest/requirements.txt
* rq 1.5.1 uses `collections.Iterable` (long deprecated and deleted in Python 3.10). 1.5.2 fixes this issue. To avoid potential regressions, don't bump the version further.
* av 8.0.2 was built with old Cython, which generates C code incompatible with Python 3.10. The newest version is av 10.0.0, but that drops support for FFmpeg<4.3, which would make it unbuildable using the default Ubuntu 20.04 FFmpeg packages. To avoid that problem, use the previous version, 9.2.0.
This makes it possible to run CVAT on Python 3.10.
Fixes #5262. 
I'm relying on CI.
https://github.com/cvat-ai/cvat/blob/develop/README.md#documentatio …
> Bump dependency versions to fix compatibility with Python 3.10

- site/content/en/docs/administration/advanced/k8s_deployment_with_helm.md
> Update docs about k8s deployment

- site/content/en/docs/administration/advanced/mounting_cloud_storages.md
s3fs mount command requires also a path to a custom passwd_file with keys.
~~- [ ] I have added a description of my changes into [CHANGELOG](https://github.com/cvat-ai/cvat/blob/develop/CHANGELOG.md) file~~ …
> Update s3fs mount command

- site/content/en/docs/contributing/running-tests.md
- tests/python/rest_api/__init__.py
- tests/python/shared/fixtures/init.py
Fix https://github.com/opencv/cvat/issues/5214
1. Stable names for containers (_ vs -)
2. Improve documentation
> Fix several issues with testing system

- CHANGELOG.md
- cvat-canvas3d/package.json
- cvat-canvas3d/src/typescript/canvas3dView.ts
- tests/cypress/integration/canvas3d_functionality/case_86_canvas3d_functionality_move_image_button.js
- tests/cypress/integration/canvas3d_functionality_2/case_56_canvas3d_functionality_basic_actions.js
> Allow dragging 3D canvas in IDLE mode

- README.md
Some links on readme.md page included `cvat-ai` part instead of `opencv`
This links were updated 
Issue: https://github.com/opencv/cvat/issues/5379
Some links on readme.md page included `cvat-ai` part instead of `opencv`
- [x ] I have updated the [documentation](
https://github.com/cvat-ai/cvat/blob/develop/LICENSE) that …
> [Documentation] links on readme.md page fixed

- site/content/en/docs/contributing/running-tests.md
> Remove old CLI tests from unit test docs

- site/content/en/docs/administration/advanced/k8s_deployment_with_helm.md
> Added note about use of existing PVs to store CVAT data

- cvat-canvas3d/src/typescript/canvas3d.ts
- cvat-ui/webpack.config.js
The cause of the warning is explained here:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports
Add a webpack configuration option to treat such warnings as errors, to prevent any more of them from appearing in the future.
Warnings are annoying.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using- …
> Fix an "export was not found" webpack warning in canvas3d.ts

- tests/python/cli/test_cli.py
- tests/python/cli/util.py
- tests/python/rest_api/test_check_objects_integrity.py
- tests/python/rest_api/test_webhooks_sender.py
- tests/python/sdk/test_jobs.py
- tests/python/sdk/test_tasks.py
- tests/python/sdk/util.py
- tests/python/shared/fixtures/data.py
- tests/python/shared/fixtures/init.py
- tests/python/shared/utils/config.py
- tests/python/shared/utils/dump_objects.py
`pathlib` improves code readability and type safety. It is already used in some of the tests; convert all remaining `os.path` usage to `pathlib` equivalents.
I ran the unit tests. …
> Migrate tests/python to from os.path to pathlib

- tests/python/rest_api/test_resource_import_export.py
- tests/python/shared/utils/s3.py
Extracted some enhancements from https://github.com/opencv/cvat/pull/4819
- Extracted common s3 manipulations in tests
- Refactored import/export tests to be more clear
> Refactor resource import export tests

- site/content/en/docs/manual/basics/registration.md
> [Documentation] Typo in Navbar corrected

- cvat/settings/development.py
> Fix health check in development env

- tests/python/pytest.ini
- tests/python/requirements.txt
This should protect us from unnoticed hangs, which happen sometimes and waste CI and developer time.
Currently, the limit is 15s per test, which should be enough in normal conditions.
> Limit test execution time

- cvat-cli/requirements/base.txt
- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/cvat_sdk/core/client.py
- cvat-sdk/gen/generate.sh
- Updated package versions
- Extended server version list in SDK to 2.4 for the public instance
> SDK / CLI v2.3.0

- CHANGELOG.md
- helm-chart/Chart.yaml
- helm-chart/templates/cvat-redis-secret.yml
- helm-chart/templates/cvat-server-secret.yml
- supervisord/utils.conf
Fix `Error: UPGRADE FAILED: error validating "": error validating data: unknown object type "nil" in Secret.stringData.redis-password` …
> Allow empty redis pass

- .github/workflows/helm.yml
> Run Helm tests for all PRs

- .github/workflows/helm.yml
- helm-chart/Chart.yaml
- helm-chart/templates/cvat_backend/cvat_worker_webhooks/deployment.yml
- helm-chart/templates/cvat_backend/server/deployment.yml
- helm-chart/templates/cvat_backend/utils/deployment.yml
- helm-chart/templates/cvat_backend/worker_default/deployment.yml
- helm-chart/templates/cvat_backend/worker_low/deployment.yml
- helm-chart/templates/cvat_frontend/deployment.yml
- helm-chart/templates/cvat_opa/deployment.yml
- helm-chart/values.yaml
- tests/values.test.yaml
> Added missed imagePullPolicy for all CVAT deployments

- docker-compose.yml
> Added missed CVAT_REDIS_PASSWORD for cvat_utils

- cvat-core/src/download.worker.js
- cvat-core/src/project-implementation.ts
- cvat-core/src/project.ts
All of which are about old-style imports.
[cvat-core](https://github.com/cvat-ai/cvat/tree/develop/cvat-core#v …
> Fix some ESLint errors in cvat-core

- tests/python/rest_api/test_tasks.py
- tests/python/shared/fixtures/init.py
Follow up for #5538 
The previous fix fixed the situation for local environments, but broke the CI. This PR tries to use another way.
> Fix docker command

- cvat-core/src/api.ts
- cvat-core/src/session-implementation.ts
- cvat-core/src/session.ts
The main problem is the circular dependency between `session.ts` and `annotations.ts`. To fix it, split the second half of `session.ts` into a separate file, like what is currently done with `project.ts` and `project-implementation.ts`.
- ~~[ ] I have increased …
> Fix ESLint errors in session.ts

- tests/python/shared/fixtures/init.py
Turns out that #5456 had a nasty side effect. Session hooks are called when pytest is run with `--collect-only` (even though no tests are actually run in this case), and Visual Studio Code periodically runs `pytest --collect-only` in order to learn what tests exist in the project. As a result, it keeps restarting the services and restoring the database in the background.
Work around this by skipping all logic in the hooks if `--collect-only` is in the options.
`pytest --collect-only` 🙂 
- ~~[ ] I have added tests to cover my …
> Python tests: skip the session hooks if --collect-only is used

- .github/workflows/full.yml
- .github/workflows/main.yml
- site/content/en/docs/administration/basics/installation.md
> Updated installation guide and workflows

- cvat-ui/src/reducers/notifications-reducer.ts
Recently we changed error messages, so this code stopped working because it was dependent on error message
> Hotfix: Fixed continiously popping error notification on `GET /api/lambda/requests`

- CHANGELOG.md
- cvat/apps/engine/cloud_provider.py
> Fix Upload data annotation from CVAT to Azure Blob storage

- cvat/apps/webhooks/serializers.py
- tests/python/rest_api/test_webhooks.py
- tests/python/shared/assets/webhooks.json
Fix problem that occurred [here](https://github.com/opencv/cvat/actions/runs/3965534088/jobs/6795468314)
> Fix webhooks

- cvat-sdk/cvat_sdk/core/proxies/tasks.py
I missed this in #5435. The function itself can already handle path objects, I just forgot to update the type annotation. …
> SDK: Update parameter type annotation in TasksRepo.create_from_data

- CHANGELOG.md
- cvat-canvas3d/src/typescript/canvas3dView.ts
- cvat-canvas3d/src/typescript/cuboid.ts
> Reduced number of noisy information on ortho views for 3D canvas

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
* Move the reproduction recipe above the expected & actual behavior. Otherwise it's a bit awkward to fill out the template, because you have to describe what happens before you describe how to get there.
* Fix references to the old `cvat-ai/cvat` GitHub project.
* Update/remove broken links.
* Fix wording.
Just fixing some things that keep annoying me when I create issues/PRs. …
> Update issue and pull request templates

- .github/workflows/main.yml
Our HTML documentation template slaps a `<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">` on every page unless the `HUGO_ENV` environment variable is set to `production`, thereby excluding the entire documentation website from web search results. Set the variable to fix it.
This behavior is inherited from Docsy, although they have changed it since: <https://github.com/google/docsy/pull/653>.
I have long had trouble finding the CVAT manual via Google, and finally realized that something fishy must be going on. 
I checked that setting `HUGO_ENV` to production does indeed remove `NOINDEX, NOFOLLOW` from the generated pages.
- ~~[ ] I have updated the …
> Allow the documentation website to be indexed by search engines

- cvat/apps/iam/views.py
- tests/python/rest_api/test_webhooks.py
When we use `BadRequest` our responses doesn't contain error message, so it's better to use exceptions from `rest_framework.exceptions`
> Use 'ParseError' instead of 'BadRequest'

- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/components/models-page/deployed-models-list.tsx
- cvat-ui/src/components/models-page/models-page.tsx
- cvat-ui/src/components/models-page/styles.scss
- cvat-ui/src/reducers/annotation-reducer.ts
- cvat-ui/src/utils/opencv-wrapper/intelligent-scissors.ts
- cvat-ui/src/utils/opencv-wrapper/opencv-interfaces.ts
- cvat-ui/src/utils/opencv-wrapper/opencv-wrapper.ts
- Added pagination
- Fixed trackers & interactors
> Hotfix: Fix models page issues

- cvat-core/src/core-types.ts
- cvat-core/src/lambda-manager.ts
- cvat-core/src/ml-model.ts
- cvat-core/src/server-proxy.ts
- cvat-core/src/server-response-types.ts
- cvat-ui/src/actions/models-actions.ts
- cvat-ui/src/components/models-page/deployed-models-list.tsx
- cvat-ui/src/components/models-page/models-page.tsx
- cvat-ui/src/reducers/models-reducer.ts
> Fixed model pagination

- .github/workflows/cache.yml
- .github/workflows/full.yml
- .github/workflows/helm.yml
- .github/workflows/main.yml
- .github/workflows/schedule.yml
> Fix Helm tests

- cvat-ui/src/components/models-page/deployed-model-item.tsx
> Added special description to built-in models

- README.md
> Anna petrovicheva ap/enhance readme

- .github/workflows/full.yml
> Fix version of buildx for full.yml workflow

- cvat/apps/engine/serializers.py
> Added more logs to try debuging the issue with labels

- helm-chart/Chart.yaml
- helm-chart/templates/cvat-redis-secret.yml
> fix empty redis password

- cvat-sdk/gen/generate.sh
- cvat-sdk/gen/generator-config.yml
- cvat-sdk/gen/templates/openapi-generator/api_summary.mustache
- site/process_sdk_docs.py
In #5678, I thought that the extra README that eventually ended up in `cvat-sdk/docs/README.md` was unused, which turned out to be not quite true. One section from it _was_ used to generate the online API index page. Since I removed the file, the online docs now fail to build.
Rather than restore the entire README, restore just that one section as a standalone file. This achieves the same result as before, but with simpler code.
I ran the `site/process_sdk_docs.py` script.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-req …
> Fix the documentation build

- .github/workflows/main.yml
I broke the documentation build in #5678 and I want to make sure it doesn't happen again. …
> Build the documentation as part of PR checks

- cvat-canvas3d/src/typescript/canvas3dView.ts
- tests/cypress/e2e/actions_projects_models/case_114_backup_restore_project.js
- tests/cypress/e2e/canvas3d_functionality/case_83_canvas3d_functionality_cuboid_grouping.js
- tests/cypress/e2e/canvas3d_functionality/case_84_canvas3d_functionality_cuboid_redraw.js
- tests/cypress/e2e/canvas3d_functionality/case_86_canvas3d_functionality_move_image_button.js
- tests/cypress/e2e/canvas3d_functionality/case_87_canvas3d_functionality_cuboid_delete.js
- tests/cypress/e2e/canvas3d_functionality/case_88_canvas3d_functionality_save_job_remove_annotation.js
- tests/cypress/e2e/canvas3d_functionality/case_89_canvas3d_functionality_filters.js
- tests/cypress/e2e/canvas3d_functionality/case_91_canvas3d_functionality_dump_upload_annotation_point_cloud_format.js
- tests/cypress/e2e/canvas3d_functionality/case_92_canvas3d_functionality_dump_upload_annotation_velodyne_points_format.js
- tests/cypress/e2e/canvas3d_functionality/case_93_canvas3d_functionality_export_dataset.js
- tests/cypress/e2e/canvas3d_functionality_2/case_64_canvas3d_functionality_cuboid.js
- tests/cypress/e2e/canvas3d_functionality_2/case_78_canvas3d_functionality_cuboid_label.js
- tests/cypress/e2e/canvas3d_functionality_2/case_79_canvas3d_functionality_cuboid_context_menu.js
- tests/cypress/e2e/canvas3d_functionality_2/case_80_canvas3d_functionality_cuboid_make_copy.js
- tests/cypress/e2e/canvas3d_functionality_2/case_81_canvas3d_functionality_cuboid_propagate.js
- tests/cypress/e2e/canvas3d_functionality_2/case_82_canvas3d_functionality_cuboid_opacity_outlined_borders.js
- tests/cypress/e2e/canvas3d_functionality_2/cuboid_interpolation_pipeline.js
- tests/cypress/support/commands_canvas3d.js
> Added cypress test for 3D cuboids interpolation

- cvat-core/src/server-proxy.ts
- cvat-ui/src/components/models-page/models-page.tsx
This PR fixes two annoying notifications:
1. On models page if there is no models (Resolves #5728)
2. On login page if token sesssion is expired
> Fix excessive notifications

- cvat-sdk/gen/postprocess.py
- cvat/settings/email_settings.py
- manage.py
- site/process_sdk_docs.py
- tests/json_to_html.py
All scripts require Python 3; this change lets them be used in environments where `python` is either Python 2 or missing.
`email_settings.py` is not a script, so it doesn't need a shebang line at all.
I'm relying on CI.
([cvat-canvas](https://github.com/opencv/cvat/tree/develop/cva …
> Make Python shebang lines refer to `python3`

- cvat/apps/log_viewer/views.py
As far as I can tell, these aren't supposed to be part of the public API, and they break the SDK generator due to not being in the `/api/` namespace (if you get the schema from a server with analytics enabled).
I checked the output of `/api/schema/` before and after. …
> Remove the /analytics endpoints from the OpenAPI schema

- site/content/en/docs/contributing/development-environment.md
Often, there are typos in the code and documentation. This PR tries to prevent them in future by adding a recommendation to install a VS code extension.
> Add spell checker extension to recommendations

- cvat-core/src/cloud-storage.ts
> Fixed infinite preview loading for cloud storages

- cvat/apps/engine/models.py
- cvat/apps/events/handlers.py
> Fixed missed job_id for Issue and Comment models

- site/content/en/docs/contributing/running-tests.md
- Removed social authentication from running-tests.md
> Remove social authentication from running-tests.md

- cvat/requirements/base.txt
~~- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~ …
> Update djnago allauth version

- cvat/apps/iam/rules/lambda.rego
- cvat/apps/iam/rules/tests/configs/lambda.csv
> Allow lambda requests for worker user

- components/analytics/grafana/dashboards/monitoring.json
- components/analytics/vector/vector.toml
Added filtering by error,
added timestamp column
set `batch.timeout_secs` to default value(1s) for Vector
> Minor improvements of monitoring dashboard

- .github/workflows/cache.yml
currently our cache doesn't work due to typo in cache.yml config
> Fix cache workflow

- site/content/en/docs/administration/advanced/k8s_deployment_with_helm.md
> Updated analytics section of k8s guide

- components/analytics/clickhouse/init.sh
- helm-chart/templates/analytics/clickhouse/secret.yml
- helm-chart/values.yaml
Removed custom user creation code from init script and uses environment variables provided by images.
> Improved clickhouse initialization

- cvat/apps/engine/filters.py
- cvat/apps/engine/views.py
- cvat/apps/organizations/views.py
- cvat/apps/webhooks/views.py
> Rid of check on swager_fake_view in viewsets

- tests/python/rest_api/test_analytics.py
> Enabled existing tests for analytics

- site/content/en/docs/enterprise/_index.md
- site/content/en/docs/enterprise/social-accounts-configuration.md
Social Auth documentation updated
New features were added, 
> sso documentation updated

- tests/python/rest_api/test_tasks.py
> Fix test with adding skeleton

- site/content/en/docs/administration/advanced/upgrade_guide.md
> Update upgrade script for 2.2.0 to 2.3.0

- cvat-ui/src/components/premium-features-modal/premium-features-modal.tsx
- cvat-ui/src/components/premium-features-modal/styles.scss
> Adjusted text on premium features notification

- .github/workflows/main.yml
buildkit made the [patch](https://github.com/moby/buildkit/issues/2631) and now this problem is fixed
> Fix main workflow

- cvat/apps/engine/signals.py
creating task from 45k images with segment_size=1 takes about 4h
```
2023-03-13 13:10:05,084 DEBG 'rqworker_import_1' stderr output:
INFO:cvat.server:Found frames 45000 for Data #18
[2023-03-13 13:10:05,082] INFO cvat.server: New segment for task #19: idx = 0, start_frame = 0,             stop_frame = 0
INFO:cvat.server:New segment for task #19: idx = 0, start_frame = 0,             stop_frame = 0
...
2023-03-13 17:02:01,987 DEBG 'rqworker_import_1' stderr output:
[2023-03-13 17:02:01,987] INFO cvat.server: New segment for task #19: idx = 44999, start_frame = 44999,             stop_frame = 44999
```
After:
```
2023-03-14 09:28:50,818 DEBG 'rqworker_import_1' stderr output:
INFO:cvat.server:Found frames 45000 for Data #18
2023-03-14 09:28:50,826 DEBG 'rqworker_import_1' stderr output: …
```
> Don't update task status for newly created jobs

- cvat-ui/src/components/cvat-app.tsx
> Disabled premium features notification

- cvat/apps/engine/backup.py
- cvat/apps/engine/middleware.py
- cvat/apps/engine/utils.py
- cvat/apps/engine/views.py
- cvat/apps/events/handlers.py
- cvat/settings/base.py
- tests/python/rest_api/test_analytics.py
- tests/python/rest_api/test_tasks.py
- tests/python/rest_api/utils.py
- Added middleware that assigns a UUID for each request.
- Stores the request UUID in the event payload
- Returns the UUID as the `X-Request-Id` response header
Feel free to …
> Request tracking middleware

- tests/values.test.yaml
Fix release tests https://github.com/opencv/cvat/actions/runs/4426950434/attempts/1
> Helm tests: dont pull frontend image

- .github/workflows/full.yml
- .github/workflows/main.yml
The full workflow is broken, because some changes from the main workflow weren't applied to it. Update them both to minimize differences between them. …
> Synchronize the main and full workflows

- .github/workflows/full.yml
I accidentally broke it in cb72be0d.
```bash
git diff --no-index .github/workflows/{full,main}.yml
``` …
> Fix the schema check in the full workflow

- cvat-sdk/cvat_sdk/core/client.py
- cvat-sdk/gen/generate.sh
> SDK: fix the list of supported versions

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/components/actions-menu/actions-menu.tsx
- cvat-ui/src/containers/actions-menu/actions-menu.tsx
- site/content/en/docs/manual/basics/tasks-page.md
- tests/cypress/e2e/actions_projects_models/case_94_move_task_between_projects.js
> Stricted moving a task from a project

- tests/cypress/e2e/canvas3d_functionality_2/case_56_canvas3d_functionality_basic_actions.js
- tests/cypress/support/commands_canvas3d.js
Helpful materials:
https://github.com/jaredpalmer/cypress-image-snapshot/issues/143
https://www.cypress.io/blog/2021/03/01/generate-high-resolution-videos-and-screenshots
> Unstable 3D test, last check

- cvat-canvas/package.json
- cvat-canvas/src/typescript/masksHandler.ts
- cvat-canvas/tsconfig.json
- cvat-canvas/webpack.config.js
- cvat-canvas3d/package.json
- cvat-canvas3d/tsconfig.json
- cvat-canvas3d/webpack.config.js
- cvat-core/jest.config.js
- cvat-core/package.json
- package.json
- yarn.lock
> Fixed typescript & webpack configs for canvas module

- site/content/en/docs/contributing/repo-structure.md
Fixes #5683
- Added a repo structure description page in docs
> Add repo structure info

- dev/format_python_code.sh
- site/content/en/docs/contributing/coding-style.md
This PR adds a script to autoformat Python code.
> Add python code formatting script

- cvat/requirements/production.txt
This version supports Python 3.10+.
`pip install -r cvat/requirements/production.txt` …
> Bump the version of mod_wsgi

- site/content/en/docs/administration/advanced/upgrade_guide.md
Fixes https://github.com/opencv/cvat/issues/5698
It seems like `v` is missing in the version string for the last command. This PR fixes the problem.
> Fix 2.2.0 upgrade commands in docs

- cvat-core/package.json
- yarn.lock
This gets rid of a whole bunch of duplicate transitive dependencies. …
> Synchronize the versions of jest and jest-config

- tests/cypress/support/commands_organizations.js
Intuitively, it is right that cypress command to create a resource, should return some resource information, like id.
We are using it in our production tests. 
N/A
> Updated cypress command to return created org id

- cvat/settings/base.py
- docker-compose.yml
- supervisord/utils.conf
A separate RQ queue used for notifications
> Added queue for notifications

- .github/workflows/main.yml
Verifying API schema before running tests will allow seeing errors earlier.
> Verifying API schema before running tests

- Dockerfile
- Dockerfile.ui
This applies several minor improvements that together shave off a little bit of build time (on my machine, it goes down from 14:10 to 13:20) and a little bit of size of the final image (likely just a few megabytes, so I didn't measure it exactly).
I also have a bigger improvement in the works, but it's a lot more complicated (and might not work out in the end), so I'd like to get these out of the way first.
Copious amounts of `docker build .`. I haven't really tested if the resulting image still works, so I'm relying on CI for this.
- ~~[ ] I have linked …
> Make mild improvements to the main Dockerfile

- Dockerfile
Update base image ubuntu 20.04 -> 22.04
update python 3.8 -> 3.10
update sqlite3 from 3.31 -> 3.37
> Update base imege to ubuntu:22.04

- CHANGELOG.md
> Added missed line to changelog

- CHANGELOG.md
> Add missing line CHANGELOG.md

- CHANGELOG.md
- cvat/apps/engine/views.py
- tests/python/rest_api/test_tasks.py
Fixes https://github.com/opencv/cvat/issues/6098
Fixes #6034
- Fixed completed task job count reporting in the task summary
- Added a test
> Fix completed job count reporting

- cvat-core/src/lambda-manager.ts
> Increase lambda requests timeout

- cvat-ui/react_nginx.conf
> Fixed headers on prod

- docker-compose.yml
Our workflows fail (e.g. [1](https://github.com/opencv/cvat/actions/runs/4956755413?pr=6075), [2](https://github.com/opencv/cvat/actions/runs/4956806970?pr=5892), [3](https://github.com/opencv/cvat/actions/runs/4956552204)) due to [problem with new version of postgres:15-alpline image](https://github.com/docker-library/postgres/issues/1076).
This PR fix the version of postgres image …
> Fix version of postgres image

- cvat-ui/webpack.config.js
> Correct destructuring plugins array

- .vscode/settings.json
> Update license header for new files

- CHANGELOG.md
- cvat-core/package.json
- cvat-core/src/logger-storage.ts
> Fix array length check condition

- CHANGELOG.md
- cvat-canvas/package.json
- cvat-canvas/src/typescript/drawHandler.ts
> Fixed area checking for skeleton in case with two points

- cvat-ui/react_nginx.conf
> Enable gzip compression for UI assets

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/components/labels-editor/label-form.tsx
- cvat-ui/src/components/labels-editor/skeleton-configurator.tsx
> Fixed skeleton dumping 

- site/content/en/docs/contributing/development-environment.md
- site/content/en/docs/contributing/running-tests.md
- tests/python/README.md
Updated development environment documentation (fixed links, moved some steps)
> Fix development environment documentation

- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/gen/generate.sh
> Bump SDK and CLI versions

- docker-compose.https.yml
Just to match version used in docker-compose.yml
I just think Someone forgot about updating it when version from docker-compose.yml was updated ( https://github.com/opencv/cvat/commit/980c019427422e4a13e9f5b3c7c20de3264513cb )
Does even such a small change need a changelog entry?
> Update traefik version used in HTTPS config

- tests/python/rest_api/test_analytics.py
Fix https://github.com/opencv/cvat/actions/runs/5138114448/jobs/9247193220
> Fix analytics tests

- .github/workflows/schedule.yml
> Fix nightly build

- cvat/apps/engine/cache.py
> Added logs for chunk cache

- tests/cypress/e2e/actions_tasks3/case_115_use_custom_storage_for_import_export_annotations.js
> Test for exporting annotations into CS folder

- CHANGELOG.md
> wording update

- CHANGELOG.md
- cvat/__init__.py
- cvat/apps/engine/media_extractors.py
- cvat/schema.yml
- docker-compose.yml
- helm-chart/values.yaml
> Release 2.4.8

- cvat-ui/src/components/annotation-page/top-bar/right-group.tsx
- tests/cypress/e2e/actions_organizations/case_113_new_organization_pipeline.js
- tests/cypress/e2e/actions_projects_models/markdown_base_pipeline.js
- tests/cypress/e2e/actions_projects_models/registration_involved/base_actions_project_task_user.js
- tests/cypress/e2e/actions_tasks/registration_involved/case_39_issue_2572_rename_task.js
- tests/cypress/e2e/actions_users/registration_involved/case_28_review_pipeline_feature.js
- tests/cypress/e2e/actions_users/registration_involved/case_2_register_user_change_pass.js
- tests/cypress/e2e/actions_users/registration_involved/case_4_assign_task_job_users.js
- tests/cypress/e2e/actions_users/registration_involved/issue_1599_ch_user_registration.js
- tests/cypress/e2e/actions_users/registration_involved/issue_1599_pl_user_registration.js
- tests/cypress/support/commands.js
> Added basic pipeline for markdown guide

- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/opencv-control.tsx
- cvat-ui/src/components/task-analytics-page/quality/mean-quality.tsx
- cvat-ui/src/components/task-analytics-page/styles.scss
- cvat/apps/dataset_manager/annotation.py
- cvat/apps/dataset_manager/formats/registry.py
- cvat/apps/dataset_manager/project.py
- cvat/apps/dataset_repo/dataset_repo.py
- cvat/apps/engine/backup.py
- cvat/apps/engine/migrations/0017_db_redesign_20190221.py
- cvat/apps/engine/serializers.py
- cvat/apps/engine/task.py
- cvat/apps/engine/tests/test_rest_api.py
- cvat/apps/events/views.py
- cvat/apps/iam/templates/account/email/email_confirmation_subject.txt
- cvat/apps/quality_control/quality_reports.py
- cvat/schema.yml
> Fix a bunch of typos

- cvat-ui/src/components/task-page/styles.scss
Before
After
Manually
~~- [ ] I have added a description of my changes into the [CHANGELOG](https://github.com/opencv/cvat/blob/develop/CHANGELOG.md) file~~ …
> Fix task preview styles

- CHANGELOG.md
- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/reducers/annotation-reducer.ts
> Fixed: 3d job can not be opened in validation mode

- CHANGELOG.md
- cvat-ui/plugins/sam_plugin/src/ts/index.tsx
> Fixed SAM plugin (403 code for workers in organizations)

- CHANGELOG.md
> release notes update

- cvat-ui/src/components/labels-editor/skeleton-configurator.tsx
Causes issues on Chrome in Cypress context starting from v115
> Get rid of resize observer

- cvat/settings/base.py
- cvat/settings/testing.py
- supervisord/server.conf
> Using a separate event cache file for each process

- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/gen/generate.sh
> Bump SDK & CLI versions

- cvat-ui/src/components/annotation-page/top-bar/player-navigation.tsx
> Quick fix for navigation in jobs with one image

- CHANGELOG.md
- cvat-cli/src/cvat_cli/cli.py
- cvat-cli/src/cvat_cli/parser.py
- cvat-sdk/cvat_sdk/auto_annotation/functions/torchvision_detection.py
- cvat-sdk/cvat_sdk/auto_annotation/functions/torchvision_keypoint_detection.py
- site/content/en/docs/api_sdk/cli/_index.md
- site/content/en/docs/api_sdk/sdk/auto-annotation.md
- tests/python/cli/example_parameterized_function.py
- tests/python/cli/test_cli.py
- tests/python/sdk/test_auto_annotation.py
These serve as a replacement for YOLOv8n that was removed in #6632.
To support these functions, I also add an ability to define parameterized functions for use with the CLI.
Unit tests. …
> SDK: Add predefined functions based on torchvision

- tests/cypress/e2e/analytics/ground_truth_jobs.js
- tests/cypress/e2e/issues_prs/issue_5381_empty_project_formats.js
- tests/cypress/support/commands.js
- tests/cypress/support/commands_projects.js
- tests/cypress/support/commands_webhooks.js
> Minor Cypress tests refactoring

- cvat-ui/src/components/signing-common/cvat-signing-input.tsx
There was a small typo in field types: changed passord to password
> typo in password

- tests/cypress/support/commands.js
> Fixed unstable test

- tests/cypress/e2e/actions_users/issue_2524_2633_issue_not_reset_after_change_task_issue_point_firefox.js
- tests/cypress/support/commands_projects.js
> Reworked test

- CHANGELOG.md
- cvat-core/package.json
- cvat-core/src/session.ts
- cvat-ui/package.json
- cvat-ui/src/components/job-item/job-item.tsx
- tests/cypress/e2e/actions_users/registration_involved/case_4_assign_task_job_users.js
- tests/cypress/support/commands_review_pipeline.js
> Fixed removing job assignee

- CHANGELOG.md
- cvat/apps/engine/views.py
> Updated response code for cloud storage preview not found 204 -> 404

- tests/package.json
- tests/yarn.lock
Mainly to get rid of the dependency on a vulnerable version of jpeg-js. …
> tests: upgrade jimp

- README.md
Just making the limitations of cvat.ai explicit for readers
> Update README to explicitly state the limitations of cvat.ai

- .github/workflows/main.yml
- dev/update_version.py
- utils/update_version/update_version.py
The main motivation was to add SDK and schema-related version updates, which were missing from the original script. I also did a bunch of refactoring to make changing the replacement rules easier, and added a checking mode to make sure that version numbers are consistent across the project (adding a corresponding check to CI).
- ~~[ …
> Multiple updates to the update_version.py script

- CHANGELOG.md
- cvat-canvas/package.json
- cvat-canvas/src/typescript/canvasView.ts
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/review/create-issue-dialog.tsx
- cvat-ui/src/components/annotation-page/review/hidden-issue-label.tsx
- cvat-ui/src/components/annotation-page/review/issue-dialog.tsx
* Resolved:  issues created extra times
* Resolved #5639
> Fixed double issues & scaling

- backend_entrypoint.sh
- helm-chart/Chart.yaml
- helm-chart/templates/_helpers.tpl
- helm-chart/templates/cvat_backend/cvat_worker_webhooks/deployment.yml
- helm-chart/templates/cvat_backend/server/deployment.yml
- helm-chart/templates/cvat_backend/utils/deployment.yml
- helm-chart/templates/cvat_backend/worker_analyticsreports/deployment.yml
- helm-chart/templates/cvat_backend/worker_annotation/deployment.yml
- helm-chart/templates/cvat_backend/worker_export/deployment.yml
- helm-chart/templates/cvat_backend/worker_import/deployment.yml
- helm-chart/templates/cvat_backend/worker_qualityreports/deployment.yml
This reduces duplication between deployment templates.
[cvat-data](https://github.com/opencv/cvat/tree/develop/cvat-dat …
> helm-chart: move more variables to sharedBackendEnv

- CHANGELOG.md
- cvat-ui/src/components/jobs-page/styles.scss
- cvat-ui/src/components/models-page/styles.scss
- cvat-ui/src/components/models-page/top-bar.tsx
- cvat-ui/src/components/projects-page/styles.scss
- cvat-ui/src/components/tasks-page/styles.scss
- cvat-ui/src/components/tasks-page/top-bar.tsx
This PR fixes some small issues on different pages
- Task page
- Projects page
-~~[ ] I have updated the documentation accordingly~~ …
> Fixed paddings on tasks/projects/models pages

- CHANGELOG.md
- cvat-ui/package.json
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/handle-popover-visibility.tsx
> Improved click handling on left sidebar

- CHANGELOG.md
- cvat-cli/requirements/base.txt
- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/cvat_sdk/core/client.py
- cvat-sdk/gen/generate.sh
- cvat/__init__.py
- cvat/schema.yml
- docker-compose.yml
- helm-chart/values.yaml
> Az/dev release 2.7.0

- cvat-core/package.json
- cvat-core/src/plugins.ts
> Added plugin option: preventMethodCallWithReturn

- CHANGELOG.md
- cvat/requirements/base.txt
See <https://github.com/advisories/GHSA-v8gr-m533-ghj9>.
Feel free to …
> Security update cryptography from 41.0.3 to 41.0.4

- cvat/apps/iam/templates/account/email/email_confirmation_message.html
Sometimes a see this in my emails:
> Remove preheader for email confirmation message

- tests/cypress/e2e/actions_tasks/registration_involved/case_69_filters_sorting_jobs.js
`case_69_filters_sorting_jobs.js` fails from time to time, this pr tries to fix it.
It seems functions, that set filters lack some checks
> Try to fix unstable `case_69`

- cvat-ui/src/components/header/header.tsx
- cvat-ui/src/reducers/index.ts
- cvat-ui/src/reducers/plugins-reducer.ts
> Add support for about plugins

- site/content/en/docs/manual/basics/attach-cloud-storage.md
Updated documentation for Cloud Storages
Reported issue: [5972](https://github.com/opencv/cvat/issues/5972)
> Documentation: removed outdated links

- tests/python/README.md
Instructions on updating .json assets for REST API tests are not working. This PR fixes it.
> Update README for REST API tests

- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
- cvat/apps/lambda_manager/views.py
> Support rotation in detector results

- tests/cypress/e2e/actions_tasks2/case_26_canvas_color_settings_feature.js
> Added persist image filters test

- changelog.d/20231012_123219_andrey_x_frame_options.md
- cvat-ui/react_nginx.conf
- cvat/nginx.conf
> Added X-Frame-Options: deny

- changelog.d/20231013_110048_klakhov_remove_need_help.md
- cvat-ui/src/components/header/header.tsx
- cvat-ui/src/config.tsx
Gitter channel is not available anymore
> Removed `Need help` gitter link

- changelog.d/20231016_131815_andrey_helm_update_clickouse_config.md
- helm-chart/Chart.yaml
- helm-chart/values.yaml
> Disable zookeeper

- docker-compose.yml
This improves maintainability of the file.
I brought CVAT up using Docker Compose, and checked that the environment variables in containers were as expected. …
> Factor out shared environment variables in docker-compose.yml

- .github/workflows/publish-artifacts.yml
Manually with a modified version of the pipeline that uploads to TestPyPI. See successful run here: <https://github.com/SpecLad/cvat/actions/runs/6509890509/job/17745596516>. …
> Add a job for publishing Python packages upon release

- .github/workflows/main.yml
The job spends about a minute downloading and loading the CVAT server image, but I don't think it's used at all. …
> Remove unneeded steps in the generate_github_pages CI job

- .github/workflows/main.yml
- .github/workflows/publish-artifacts.yml
- .github/workflows/schedule.yml
v1 of this action produces several deprecation warnings, which should hopefully be fixed in the most recent version. I don't think v2 has any problems, but I might as well bump it.
For example: https://github.com/opencv/cvat/actions/runs/6624722303
I can't test this easily, because the affected pipelines all push Docker images to the production Docker Hub repositories. I'll monitor nightly builds after this is merged to make sure nothing is broken.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using- …
> Bump the docker/login-action version

- .github/workflows/regallint.yml
- cvat/apps/iam/rules/.regal/config.yaml
- cvat/apps/iam/rules/analytics.rego
- cvat/apps/iam/rules/analytics_reports.rego
- cvat/apps/iam/rules/annotationguides.rego
- cvat/apps/iam/rules/cloudstorages.rego
- cvat/apps/iam/rules/comments.rego
- cvat/apps/iam/rules/conflicts.rego
- cvat/apps/iam/rules/events.rego
- cvat/apps/iam/rules/invitations.rego
- cvat/apps/iam/rules/issues.rego
- cvat/apps/iam/rules/jobs.rego
- cvat/apps/iam/rules/labels.rego
- cvat/apps/iam/rules/lambda.rego
- cvat/apps/iam/rules/memberships.rego
- cvat/apps/iam/rules/organizations.rego
- cvat/apps/iam/rules/projects.rego
- cvat/apps/iam/rules/quality_reports.rego
- cvat/apps/iam/rules/quality_settings.rego
- cvat/apps/iam/rules/server.rego
- cvat/apps/iam/rules/tasks.rego
- cvat/apps/iam/rules/users.rego
- cvat/apps/iam/rules/utils.rego
- cvat/apps/iam/rules/webhooks.rego
- site/content/en/docs/contributing/running-tests.md
Hello CVAT friends! 👋😃
This PR introduces [Regal](https://github.com/styrainc/regal)) for linting the Rego included in this project. The policy code here is generally in a really good shape, so the linter did not have too much to do. Good work on that!
Violations of a few rules were fixed as part of this PR, as they do not change the semantics of evaluation:
* [line-length](https://docs.styra.com/regal/rules/style/line-length)
* [unconditional-assignment](https://docs.styra.com/regal/rules/style/unconditional-assignment)
* [use-assignment-operator](https://docs.styra.com/regal/rules/style/use-assignment-operator)
A few other ones were ignored using Regal's configuration file. Whether some of them should be fixed in the future I'll leave up to the project's maintainers.
I've also added …
> Add Regal for linting Rego

- site/content/en/docs/manual/advanced/formats/format-mot.md
- site/content/en/docs/manual/basics/attach-cloud-storage.md
- Added videos to Cloud Storages
- Updated wording in Cloud Storages
- Updated data format for MOT Import
> Documentation retouch: cloud storages and mot data format

- docker-compose.yml
- helm-chart/Chart.yaml
- helm-chart/values.yaml
> Update keydb to 6.3.4

- site/content/en/docs/faq.md
> Removed not relevant FAQ item

- changelog.d/20231116_153601_andrey_update_traefik.md
- docker-compose.yml
> Update traefik to 2.10.*

- changelog.d/20231111_000533_yta56116_patch_1.md
- serverless/pytorch/dschoerk/transt/nuclio/function-gpu.yaml
`nvidia/cuda:11.7.0-devel-ubuntu20.04` does not exist. update cuda image version to 11.7.1.
> Bump cuda image version from 11.7.0 to 11.7.1

- CHANGELOG.md
- cvat-cli/requirements/base.txt
- cvat-cli/src/cvat_cli/version.py
- cvat-sdk/gen/generate.sh
- cvat/__init__.py
- cvat/schema.yml
- docker-compose.yml
- helm-chart/values.yaml
This release has changes only in the Enterprise version.
> Release 2.9.1

- cvat-ui/webpack.config.js
> Added default value for DISABLE_SOURCE_MAPS

- changelog.d/20231214_203449_roman_update_clickhouse.md
- cvat/apps/analytics_report/report/primary_metrics/objects.py
- docker-compose.yml
- helm-chart/Chart.yaml
The main reason for this is to update the Helm chart, because the current one conflicts with the Redis chart I want to add (in #7245).
But also the version we have is quite old and out of support, so it's due for an update anyway.
The change in `objects.py` is due to the fact that with the new version of Clickhouse, the value of `date` somehow became a timezone-aware datetime object, so the output of `isoparse` now includes a UTC offset, and appending a "Z" now creates a malformed date. I chose to replace this with a custom format string, which is consistent with other date formatting code in the `analytics_report` app.
I manually tried both the Helm chart and the Compose file, making sure that the analytics are still recorded and displayed.
I also checked that a database created with the …
> Update Clickhouse to the latest version

- changelog.d/20231227_104741_maria_fix_rq_scheduler_launch.md
- supervisord/utils.conf
> Fix rq scheduler launch

- cvat-ui/src/components/labels-editor/constructor-viewer-item.tsx
- cvat-ui/src/components/model-runner-modal/object-mapper.tsx
- cvat-ui/src/utils/compute-text-color.ts
> Adjusted text color for label matcher

- README.md
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
> Fixed CI badge URL

- site/content/en/docs/faq.md
Fix a typo.
refer to docker-compose.yml
> Fix a typo. "cvat" service does not exist. It should be "cvat_server".

- site/content/en/docs/enterprise/subscription-managment.md
> Subscription management documentation updated 

- site/content/en/docs/manual/advanced/specification.md
> Added documentation to open guides automatically

- cvat/settings/base.py
- supervisord/server.conf
- supervisord/utils.conf
- supervisord/worker.analytics_reports.conf
- supervisord/worker.annotation.conf
- supervisord/worker.export.conf
- supervisord/worker.import.conf
- supervisord/worker.quality_reports.conf
- supervisord/worker.webhooks.conf
This will let us more easily identify PostgreSQL sessions that come from CVAT. See <https://www.postgresql.org/docs/15/runtime-config-logging.html#GUC-APPLICATION-NAME>.
```sql
SELECT * FROM pg_stat_activity;
```
[cvat-core](https://github.com/opencv/cvat/tree/develop/cvat-core#version …
> Add an `application_name` PostgreSQL connection parameter

- changelog.d/20240208_180435_sekachev.bs_remove_exception_from_analytics.md
- cvat/apps/events/handlers.py
> Exception event: 'not authentificated' was removed from analytics

- site/content/en/docs/administration/basics/installation.md
In the documentation (site/content/en/docs/administration/basics/installation.md) as follows
the registry mirror list comprises two duplicated items:
- "https://https://mirror.ccs.tencentyun.com"
- "https://mirror.ccs.tencentyun.com"
The first one is a broken URL, since it has two `https://` schemes. Using the registry mirror list in the documentation incurs an error when starting the docker service. In this PR, I remove the `"https://https://mirror.ccs.tencentyun.com"` entry in the registry mirror list to avoid breaking the docker service. …
> Fix docker registry mirror list

- site/content/en/docs/contributing/development-environment.md
I have updated minimum Python version in development environment.md from 3.9 to 3.10 which I think would be valuable for new contributors trying to set up the development environment locally on their systems. It resolves the issue #7522 .
This is just an edit in the documentation.
> Updated Python version in development-environment.md to 3.10 🐍

- docker-compose.dev.yml
This way, it's possible to debug event-related functionality. …
> Expose Vector and Clickhouse ports in `docker-compose.dev.yml`

- cvat/settings/base.py
There doesn't seem to be much point in having it, because the entrypoint script already ensures that all migrations have been applied. So it only serves to put more load on the server. …
> Remove the migration health check

- site/content/en/docs/manual/advanced/specification.md
> open spec auto

- tests/python/shared/assets/cvat_db/data.json
There've been a couple of patches that introduced minor changes to object representations. Recreate the test dump so that these changes don't pollute the diff in future pull requests. …
> Redump the test data

- site/content/en/docs/administration/basics/installation.md
- site/content/en/docs/contributing/development-environment.md
> Update installation guide

- site/content/en/docs/contributing/development-environment.md
- site/content/en/docs/contributing/running-tests.md
> Add notes to Mac users to installation doc

- changelog.d/20240326_150326_vidit.agarwal.eee20_changelog_confusion_matrix.md
Fixes opencv/cvat#7678 as it breaks the CI.
> Fix invalid changelog entry

- site/build_docs.py
- site/layouts/home.html
It seems much simpler than the current approach, and it avoids hardcoding the `/cvat` prefix.
[cvat-ui](https://github.com/opencv/cvat/tree/develop/cvat-ui#versioni …
> Use relative path in layouts/home.html

- cvat/requirements/base.txt
- cvat/requirements/development.txt
- cvat/requirements/production.txt
Launched the command from the server requirements [readme](https://github.com/opencv/cvat/blob/6273b48ae66de565f740b2f839266dc5aeeaffcb/cvat/requirements/README.txt). Helps to clean other PRs from irrelevant changes. …
> Bump server deps

- cvat/apps/analytics_report/views.py
- cvat/apps/engine/views.py
- cvat/apps/events/views.py
- cvat/apps/organizations/views.py
- cvat/apps/quality_control/views.py
- cvat/apps/webhooks/views.py
- cvat/schema.yml
The current summaries are much too verbose. This makes it hard to find the endpoint you're looking for in the API docs, because it takes longer to read & understand each summary.
Rewrite them to be more brief. Move any details that are too long to keep, but too important to omit, to the description.
Reading `/api/docs/`. …
> Streamline API endpoint summaries

- .github/workflows/docs.yml
- site/build_docs.py
- site/layouts/404.html
> Migrate docs to a custom domain

- .github/workflows/cache.yml
- .github/workflows/full.yml
- .github/workflows/helm.yml
- .github/workflows/main.yml
- .github/workflows/schedule.yml
> Switch the most time-consuming pipelines to the large runner

- changelog.d/20240402_143458_boris.md
- cvat-ui/package.json
- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/reducers/annotation-reducer.ts
> Fixed annotation menu for GT objects in GT job

- tests/cypress/support/commands.js
> Fix sometimes failed tests problem

- changelog.d/20240401_213256_tahamukhtar20_No_Shortcut.md
> Fix incorrect changelog fragment

- Dockerfile.ci
- site/content/en/docs/contributing/development-environment.md
> Upgrade Node 16 => 20

- cvat/apps/iam/rules/tests/configs/auth.csv
As far as I can see, there's no corresponding `auth.rego` or `auth_test.gen.rego`, and there never was. Also, there wouldn't be much point in having one, as none of the endpoints in `auth/` seem to use OPA-based permissions. …
> Remove unused IAM test config

- cvat-ui/src/components/annotation-page/standard-workspace/objects-side-bar/styles.scss
Fix small issue with jumping sidebar scrollbar
Before:
After:
> Fixed issue with y-slider of objects sidebar

- tests/cypress/e2e/actions_objects/count_objects.js
> Refactored one test case

- serverless/pytorch/facebookresearch/sam/nuclio/function-gpu.yaml
- serverless/pytorch/facebookresearch/sam/nuclio/function.yaml
- serverless/pytorch/facebookresearch/sam/nuclio/model_handler.py
- serverless/pytorch/saic-vul/fbrs/nuclio/function.yaml
- serverless/pytorch/saic-vul/fbrs/nuclio/main.py
- serverless/pytorch/saic-vul/fbrs/nuclio/model_handler.py
- serverless/pytorch/saic-vul/hrnet/nuclio/function-gpu.yaml
- serverless/pytorch/saic-vul/hrnet/nuclio/function.yaml
- serverless/pytorch/saic-vul/hrnet/nuclio/main.py
- serverless/pytorch/saic-vul/hrnet/nuclio/model_handler.py
- serverless/pytorch/shiyinzhang/iog/nuclio/function.yaml
- serverless/pytorch/shiyinzhang/iog/nuclio/main.py
- serverless/pytorch/shiyinzhang/iog/nuclio/model_handler.py
> Removed extra code from serverless functions

- site/content/en/docs/enterprise/subscription-managment.md
> refund policy updated

- changelog.d/20240520_161903_boris_ignore_gt_jobs.md
- cvat/apps/analytics_report/report/create.py
> Ignore ground truth jobs when compute analytics report for a task/project

- .vscode/settings.json
> Delete extra comma

- changelog.d/20240527_144126_boris_fix_7879.md
- cvat-core/src/annotations-objects.ts
- cvat-core/src/annotations-saver.ts
> Cannot set properties of undefined (setting 'serverID')

- cvat/apps/engine/cloud_provider.py
> Fix memory consumption when exporting to azure blob storage

- changelog.d/20240607_120601_sekachev.bs_fixed_login_with_token.md
- cvat-ui/src/components/login-with-token/login-with-token.tsx
> Fixed login with token without next parameter

- tests/cypress/e2e/features/single_object_annotation.js
Wait until the canvas is ready to paint points
> Fix unstable e2e test

- cvat-sdk/gen/postprocess.py
- cvat-sdk/gen/templates/openapi-generator/api.mustache
- cvat-sdk/gen/templates/openapi-generator/api_client.mustache
- cvat-sdk/gen/templates/openapi-generator/configuration.mustache
This is a continuation of #8626.
[cvat-ui](https://github.com/cvat-ai/cvat/tree/develop/cvat-ui#versioning))~~ …
> Remove deprecated typing imports from generated SDK sources

- tests/python/rest_api/test_tasks.py
- Fixed invalid test inheritance in task tests, which led to extra ~10-15 minutes of testing
> Fix invalid inheritance in tests

- cvat-ui/src/components/job-item/job-item.tsx
- Job dates in the task job list now occupy less space
Old:
New:
> Narrow job dates in task job list

- tests/cypress/support/commands.js
My assumption why one of tests does not work stable
> Return Promise like object from a cypress command to create a user

- pyproject.toml
- utils/dataset_manifest/core.py
- utils/dataset_manifest/create.py
- utils/dataset_manifest/errors.py
- utils/dataset_manifest/types.py
- utils/dataset_manifest/utils.py
Another step towards auto-formatting the whole codebase.
In `utils.py` I slightly edited the comment so that black wouldn't insert unnecessary blank lines into it.
> Blacken dataset_manifest

- .codacy.yml
- .eslintrc.cjs
- .github/CODEOWNERS
- cvat-ui/README.md
Code owners are definitely outdated. Some of them do not support CVAT anymore. 
> Updated codeowners and minor cleanups

- changelog.d/20250129_190931_andrey_change_event_cache_dir.md
- cvat/settings/base.py
- helm-chart/Chart.yaml
- helm-chart/templates/cvat_backend/server/deployment.yml
- helm-chart/templates/cvat_backend/utils/deployment.yml
- helm-chart/templates/cvat_backend/worker_annotation/deployment.yml
- helm-chart/templates/cvat_backend/worker_chunks/deployment.yml
- helm-chart/templates/cvat_backend/worker_export/deployment.yml
- helm-chart/templates/cvat_backend/worker_import/deployment.yml
> Change location of events cache dir

- .vscode/settings.json
- site/content/en/docs/contributing/development-environment.md
- site/content/en/docs/contributing/running-tests.md
> Removed minor outdated part of documentation

- cvat-ui/src/components/job-item/job-actions-menu.tsx
An extract from https://github.com/cvat-ai/cvat/pull/8953
- Refactored job actions menu implementation to be aligned with task actions menu
> Refactor job actions menu

- cvat-ui/src/components/labels-editor/label-form.tsx
- cvat-ui/src/components/labels-editor/labels-editor.tsx
> Slightly improved warning message

- cvat/apps/engine/cache.py
- cvat/apps/engine/frame_provider.py
- dev/requirements.txt
> Update black to 25.x

- cvat/apps/dataset_manager/formats/camvid.py
- cvat/apps/dataset_manager/formats/cityscapes.py
- cvat/apps/dataset_manager/formats/coco.py
- cvat/apps/dataset_manager/formats/cvat.py
- cvat/apps/dataset_manager/formats/datumaro.py
- cvat/apps/dataset_manager/formats/icdar.py
- cvat/apps/dataset_manager/formats/imagenet.py
- cvat/apps/dataset_manager/formats/kitti.py
- cvat/apps/dataset_manager/formats/labelme.py
- cvat/apps/dataset_manager/formats/lfw.py
- cvat/apps/dataset_manager/formats/market1501.py
- cvat/apps/dataset_manager/formats/mask.py
- cvat/apps/dataset_manager/formats/mot.py
- cvat/apps/dataset_manager/formats/mots.py
- cvat/apps/dataset_manager/formats/openimages.py
- cvat/apps/dataset_manager/formats/pascal_voc.py
- cvat/apps/dataset_manager/formats/pointcloud.py
- cvat/apps/dataset_manager/formats/registry.py
- cvat/apps/dataset_manager/formats/transformations.py
- cvat/apps/dataset_manager/formats/utils.py
- cvat/apps/dataset_manager/formats/velodynepoint.py
- cvat/apps/dataset_manager/formats/vggface2.py
- cvat/apps/dataset_manager/formats/widerface.py
- cvat/apps/dataset_manager/formats/yolo.py
- pyproject.toml
Continuing to remove black exceptions.
> Blacken formats

- changelog.d/20250210_172119_roman_missing_kwargs.md
- cvat-sdk/cvat_sdk/auto_annotation/interface.py
Another test I'm writing depends on this.
> Add a missing kwargs forward in `skeleton_label_spec`

- changelog.d/20250211_145801_roman_aa_attributes.md
> Fix a typo in a changelog entry

- cvat/apps/lambda_manager/views.py
- cvat/apps/quality_control/quality_reports.py
This PR is a continuation of https://github.com/cvat-ai/cvat/pull/9102.
> Fix more potential race conditions when fetching and enqueuing RQ jobs

- Dockerfile
- Dockerfile.ui
> Update golang and nginx Docker base images

- cvat/settings/__init__.py
- cvat/settings/base.py
- cvat/settings/development.py
- cvat/settings/email_settings.py
- cvat/settings/production.py
- cvat/settings/testing.py
- cvat/settings/testing_rest.py
- pyproject.toml
Continuing to remove Black exceptions.
> Blacken settings

- changelog.d/20250307_155335_andrey_fix_frontend_template.md
- helm-chart/Chart.yaml
- helm-chart/templates/cvat_frontend/deployment.yml
> Fix frontend helm template

- docker-compose.https.yml
- docker-compose.yml
This makes them easier to read, as the key is visually separated from the value. Also, it emphasizes the key-value nature of labels.
> Compose: set labels via maps rather than arrays

- cvat/apps/engine/tests/test_rest_api.py
> [`engine/tests/test_rest_api.py`] Fix pylint warnings

- changelog.d/20250312_181456_roman_upgrade_traefik.md
- docker-compose.yml
- helm-chart/Chart.yaml
- helm-chart/templates/analytics/middlewares/forwardauth.yaml
- helm-chart/templates/analytics/middlewares/stripprefix.yaml
- site/content/en/docs/faq.md
The Traefik 2.x release series goes EOL in under two months (and the 2.10 minor that we currently use has reached EOL more than a year ago). Upgrading will let us keep getting security fixes.
In addition, I'm currently working on a patch that would have to be changed after the Traefik upgrade. So I'd rather do the upgrade now and not have to update my patch again.
> Upgrade Traefik to v3

- .vscode/launch.json
Worker  configuration is still present after #9174 causing an error in vscode debug config launch
> Removed excessive worker config from launch

- .vscode/launch.json
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
Small grammatical improvement of interactor message
> Improved interactor text message

- tests/python/requirements.txt
The current version is incompatible with Python 3.12, which has broken the Helm CI job. Why the job worked up until this point is unclear.
> Bump the version of pytest-cases

- Dockerfile.ui
- changelog.d/20250321_142154_andrey_add_robots_txt.md
- cvat-ui/robots.txt
> Added robots.txt file

- cvat/apps/engine/apps.py
- cvat/apps/engine/handlers.py
- cvat/apps/engine/location.py
- cvat/apps/engine/log.py
- cvat/apps/engine/middleware.py
- cvat/apps/engine/plugins.py
- cvat/apps/engine/renderers.py
- cvat/apps/engine/schema.py
- cvat/apps/engine/signals.py
- cvat/apps/engine/urls.py
- pyproject.toml
> Remove a few more Black exceptions

- .github/workflows/hadolint.yml
- serverless/openvino/dextr/nuclio/Dockerfile
> Run Hadolint on all files, not just changed ones

- tests/python/rest_api/test_requests.py
- tests/python/shared/fixtures/init.py
https://github.com/cvat-ai/cvat/pull/9236#issuecomment-2747239737
> Regression test for 9236 PR

- changelog.d/20250331_162516_maria_fix_redis_migration.md
- cvat/apps/engine/redis_migrations/002_update_meta_in_export_related_jobs.py
> Fix `002_update_meta_in_export_related_jobs` Redis migration

- changelog.d/20250401_165109_roman_agent_realtime_notifications.md
- cvat-cli/requirements/base.txt
- cvat-cli/src/cvat_cli/_internal/agent.py
- tests/python/cli/test_cli_misc.py
Currently, agents poll the server for new work every minute. This means that there is, on average, a half-minute delay between the creation of an annotation request and when the agent starts processing it. This PR lets agents watch the AR queue by listening to notifications on a persistent connection.
> Implement agent support for real-time notifications

- changelog.d/20250410_082557_klakhov_fix_import_link.md
- cvat-ui/src/reducers/notifications-reducer.ts
There is an error in link for job import. The link in notification doesnt actually open the job
This PR fixes that + adds some consistency in links naming (adding leading #)
-~~[ ] I have added tests to cover my changes~~
> Fixed link for import job

- cvat-ui/src/components/task-page/user-selector.tsx
It is more relevant for Cypress testing.
As sometimes cypress logs out faster than search happens (because of debounce) and we get the test failed.
> Handle situation when user logged in during user search debouncing

- cvat-ui/src/components/common/resource-link.tsx
- cvat-ui/src/components/consensus-management-page/consensus-management-page.tsx
- cvat-ui/src/components/quality-control/quality-control-page.tsx
- cvat-ui/src/reducers/index.ts
- cvat-ui/src/utils/hooks.ts
Just refactoring to re-use these components in other code (quality, analytics)
> Added ResourceLink component and hooks to get instance type and id

- changelog.d/20250422_230912_dmitrii.lavrukhin_memory_optimize_cvat_export.md
- cvat/apps/dataset_manager/bindings.py
- cvat/apps/dataset_manager/formats/cvat.py
> less ram on export to cvat

- .gitignore
We have committed files matching this pattern, and VS Code refuses to search for them, because it excludes files listed in `.gitignore`.
> Un-gitignore `/helm-chart/*.values.yaml`

- changelog.d/20250429_100052_sekachev.bs_optimized_lazy_list.md
- cvat/apps/engine/lazy_list.py
It significantly accelerates convertation between CVAT RLE and COCO RLE (and probably other staff)
RLE converter:
Export to YOLO Ultralytics Segmentation:
Export to Datumaro:
> Optimized lazy list implementation

- changelog.d/20250429_101431_maria_fix_scope_defining_when_check_permissions.md
- cvat/apps/consensus/permissions.py
- cvat/apps/engine/permissions.py
- cvat/apps/events/permissions.py
- cvat/apps/iam/permissions.py
- cvat/apps/lambda_manager/permissions.py
- cvat/apps/log_viewer/permissions.py
- cvat/apps/organizations/permissions.py
- cvat/apps/quality_control/permissions.py
- cvat/apps/webhooks/permissions.py
- tests/python/rest_api/test_server.py
By default, DRF returns a 405 status code when an unexpected API method is used for an existing URL. However, the code that handles this is not called since permissions are checked before that, and our code did not assume that unsupported actions could be used.
Manually
> Fix 500 status code returned when an API method is not allowed

- site/content/en/docs/manual/advanced/formats/coco-keypoints.md
- site/content/en/docs/manual/advanced/formats/format-coco.md
Openvinotoolkit was renamed to open-edge-platform.
Fixing urls accordingly.
> Fixing some urls in docs

- changelog.d/20250501_143354_sekachev.bs_enhancement_1.md
- cvat-ui/src/components/common/cvat-table.tsx
- cvat/apps/events/export.py
- cvat/apps/events/utils.py
- cvat/apps/events/views.py
- cvat/schema.yml
- tests/python/rest_api/test_analytics.py
> Enhanced filtration of CSV export

- changelog.d/20250428_142130_roman_agent_interactive_detection.md
- cvat-cli/src/cvat_cli/_internal/agent.py
- cvat-sdk/cvat_sdk/datasets/__init__.py
- cvat-sdk/cvat_sdk/datasets/common.py
- cvat-sdk/cvat_sdk/datasets/task_dataset.py
- tests/python/sdk/test_datasets.py
This fills one of the feature gaps between agent-based and Nuclio functions.
> Implement support for interactive detection via agents

- changelog.d/20250509_191403_roman.md
- cvat-sdk/cvat_sdk/auto_annotation/interface.py
> Correct outdated docstring of `DetectionFunction.detect`

- cvat/apps/dataset_manager/bindings.py
- cvat/apps/engine/views.py
- cvat/apps/events/tests/test_events.py
- serverless/pytorch/facebookresearch/sam/nuclio/main.py
- tests/python/rest_api/test_cloud_storages.py
- tests/python/rest_api/test_issues.py
- tests/python/rest_api/test_jobs.py
- tests/python/rest_api/test_labels.py
- tests/python/rest_api/test_projects.py
- tests/python/rest_api/test_requests.py
- tests/python/rest_api/test_tasks.py
- tests/python/rest_api/test_webhooks.py
- tests/python/rest_api/test_webhooks_sender.py
It improves readability.
Done with:
ruff check . --select=UP034 --fix
> Remove useless parentheses

- site/content/en/docs/manual/advanced/analytics-and-monitoring/analytics.md
> Documentation: Fix mistype in Analytics

- cvat/apps/dataset_manager/annotation.py
- cvat/apps/dataset_manager/bindings.py
- cvat/apps/dataset_manager/formats/cvat.py
- cvat/apps/dataset_manager/formats/transformations.py
- cvat/apps/dataset_manager/formats/utils.py
- cvat/apps/dataset_manager/util.py
- cvat/apps/dataset_manager/views.py
- cvat/apps/engine/backup.py
- cvat/apps/engine/cache.py
- cvat/apps/engine/migrations/0016_attribute_spec_20190217.py
- cvat/apps/engine/migrations/0020_remove_task_flipped.py
- cvat/apps/engine/models.py
- cvat/apps/engine/rules/tests/generators/annotationguides_test.gen.rego.py
- cvat/apps/engine/rules/tests/generators/comments_test.gen.rego.py
- cvat/apps/engine/rules/tests/generators/issues_test.gen.rego.py
- cvat/apps/engine/rules/tests/generators/jobs_test.gen.rego.py
- cvat/apps/engine/rules/tests/generators/tasks_test.gen.rego.py
- cvat/apps/engine/serializers.py
- cvat/apps/engine/task.py
- cvat/apps/events/rules/tests/generators/events_test.gen.rego.py
- cvat/apps/events/signals.py
- cvat/apps/lambda_manager/rules/tests/generators/lambda_test.gen.rego.py
- cvat/apps/log_viewer/rules/tests/generators/analytics_test.gen.rego.py
- cvat/apps/webhooks/rules/tests/generators/webhooks_test.gen.rego.py
- cvat/apps/webhooks/signals.py
- tests/python/rest_api/test_tasks.py
- utils/dataset_manifest/utils.py
These are more concise and (IMO) more idiomatic. Done via:
ruff check . --select=C417 --unsafe-fixes --fix
ruff check . --select=UP034 --fix
> Replace map-with-lambda with comprehensions

- cvat/apps/dataset_manager/util.py
- cvat/apps/dataset_manager/views.py
- cvat/apps/engine/filters.py
- cvat/apps/engine/parsers.py
- cvat/apps/engine/utils.py
- cvat/apps/engine/view_utils.py
- pyproject.toml
> Remove some more Black exceptions

- changelog.d/20250602_142727_andrey_pin_grafana_ds.md
- docker-compose.yml
- helm-chart/values.yaml
> Pin version of grafana-clickhouse-datasource plugin

- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
External and agent-based functions have integer IDs. Because the code in `checkTrackedStates` uses function IDs as object keys, they are implicitly coerced to strings, and therefore comparisons like `_tracker.id === trackerID` don't work as intended.
Fix this by changing the `statefull` and `stateless` objects to maps. Also, fix the spelling of `stateful`.
I manually tested the tracking tool with both a Nuclio function and a (prototype) agent-based tracking function.
https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request …
> UI: support trackers with integer IDs

- changelog.d/20250527_165509_mzhiltso_optimize_export_requests.md
- cvat/apps/dataset_manager/task.py
- cvat/apps/engine/frame_provider.py
- Optimized extra DB requests in dataset export
- Fixed misleading variable name
1. Create a task with several jobs
2. Try to put the following code in one of the endpoints to enable silk profiling
```
from cvat.apps.dataset_manager.views import export_task_as_dataset
export_task_as_dataset(42, "Datumaro 1.0")
```
3. Call the endpoint
4. Check DB requests in the profiler
> Optimize db requests in dataset export

- changelog.d/20250610_135205_sekachev.bs_adaptive_zoom.md
- cvat-canvas/src/typescript/canvasController.ts
- cvat-canvas/src/typescript/canvasModel.ts
- cvat-canvas/src/typescript/canvasView.ts
- cvat-ui/src/actions/settings-actions.ts
- cvat-ui/src/components/annotation-page/canvas/views/canvas2d/canvas-wrapper.tsx
- cvat-ui/src/components/header/settings-modal/workspace-settings.tsx
- cvat-ui/src/containers/header/settings-modal/workspace-settings.tsx
- cvat-ui/src/reducers/index.ts
- cvat-ui/src/reducers/settings-reducer.ts
> Experimental adaptive zoom algorithm applicable for touchpads

- .github/workflows/generate-allure-report.yml
- .github/workflows/main.yml
This change provide a convenient way of working with the Allure reports. Now the latest report is available with the `/latest` URL. 
> Allure report generation improvement

- changelog.d/20250610_122953_roman_non_rectangle_tracking.md
- cvat-core/src/core-types.ts
- cvat-core/src/lambda-manager.ts
- cvat-core/src/ml-model.ts
- cvat-ui/src/components/annotation-page/standard-workspace/controls-side-bar/tools-control.tsx
- cvat-ui/src/cvat-core-wrapper.ts
- cvat-ui/src/reducers/models-reducer.ts
- cvat/apps/lambda_manager/tests/assets/functions.json
- cvat/apps/lambda_manager/tests/test_lambda.py
- cvat/apps/lambda_manager/views.py
This is a preliminary step towards supporting agent-based tracking functions.
Note that this does not add the ability to actually use trackers with non-rectangles from the UI. That'll have to be added separately.
Manual testing with TransT and SAM2.
> Update the interface for tracker function calls to support non-rectangle shapes

- Dockerfile
> Update Golang base image to 1.24.4

- changelog.d/20250617_133658_mzhiltso_fix_quality_report_reuse.md
- cvat/apps/quality_control/quality_reports.py
- tests/python/rest_api/test_quality_control.py
- Fixed incorrect variable access in task report relevancy checks
> Fix task quality report reuse in project reports

- cvat/apps/dataset_manager/annotation.py
- cvat/apps/dataset_manager/serializers.py
- pyproject.toml
> Blacken a couple more files

- cvat-core/src/annotations-actions/annotations-actions.ts
- cvat-core/src/api-implementation.ts
- cvat-core/src/api.ts
- cvat-core/src/index.ts
Some actions may exist only in a certain context (let's say an organization or personal workspace).
Thus when context changed, we need to unregister previous actions. 
> Added method to unregister annotations action

- cvat/apps/dataset_manager/project.py
- cvat/apps/dataset_manager/task.py
- pyproject.toml
> Blacken more files

- cvat/apps/profiler.py
It makes stack traces harder to understand.
> Remove pointless wrapper function

- cvat-canvas/package.json
- cvat-canvas3d/package.json
- cvat-core/package.json
- cvat-data/package.json
- cvat-ui/package.json
- yarn.lock
Updated a list of target browsers to generate less number of polyfills and reduce target bundle size. 
> Updated set of target browsers

- tests/python/rest_api/test_analytics.py
- tests/python/rest_api/utils.py
> Increase timeout for wait background job

- cvat-cli/src/cvat_cli/_internal/agent.py
This allows us to monkeypatch the state ID generation algorithm, which is useful in tests.
Unit tests (in the private repository).
> Make the tracking agent implementation more testable

- ai-models/README.md
- ai-models/tracker/sam2/README.md
- ai-models/tracker/sam2/func.py
- ai-models/tracker/sam2/requirements.txt
This also creates a directory for future AA function implementations that are problematic, in one way or another, to include in the SDK proper.
> Add a SAM2 tracker as a native auto-annotation function

- .github/workflows/main.yml
- helm-chart/test.values.yaml
- tests/python/rest_api/utils.py
> Increase number of replicas for utils worker in helm tests

- .gitignore
Turns out, a slash in the middle of the pattern implicitly means that the pattern can only match at the repository root. The more you know!
I verified that both `.yarn/install-state.gz` and `tests/.yarn/install-state.gz` are ignored.
> Modify the Yarn ignores so that they also cover the `tests` directory

- changelog.d/20250724_141058_roman_aa_tags.md
- cvat-cli/src/cvat_cli/_internal/agent.py
- cvat-sdk/cvat_sdk/auto_annotation/__init__.py
- cvat-sdk/cvat_sdk/auto_annotation/driver.py
- cvat-sdk/cvat_sdk/auto_annotation/functions/torchvision_classification.py
- cvat-sdk/cvat_sdk/auto_annotation/interface.py
- site/content/en/docs/api_sdk/sdk/auto-annotation.md
- tests/python/sdk/test_auto_annotation.py
This fills in another functionality gap between native AA functions and Nuclio functions.
Note that there is no server counterpart to this PR, because the server-side agent code already works correctly with function results containing tags.
Unit tests.
> Support tags in detection functions

- tests/yarn.lock
- yarn.lock
I ran `yarn dedupe` on the project, which eliminated ~30 redundant dependencies.
> Deduplicate yarn packages

- changelog.d/20250819_103930_sekachev.bs_org_transfer_bulk.md
- cvat-core/src/server-proxy.ts
- cvat-ui/src/actions/bulk-actions.ts
- cvat-ui/src/actions/cloud-storage-actions.ts
- cvat-ui/src/components/common/label-with-count.tsx
- cvat-ui/src/components/jobs-page/actions-menu-items.tsx
- cvat-ui/src/components/move-task-modal/move-task-modal.tsx
- cvat-ui/src/components/organization-page/actions-menu.tsx
- cvat-ui/src/components/project-page/details.tsx
- cvat-ui/src/components/project-page/project-page.tsx
- cvat-ui/src/components/project-page/top-bar.tsx
- cvat-ui/src/components/projects-page/actions-menu-items.tsx
- cvat-ui/src/components/projects-page/actions-menu.tsx
- cvat-ui/src/components/selectors/organization-selector.tsx
- cvat-ui/src/components/task-page/details.tsx
- cvat-ui/src/components/task-page/task-page.tsx
- cvat-ui/src/components/task-page/top-bar.tsx
- cvat-ui/src/components/tasks-page/actions-menu-items.tsx
- cvat-ui/src/components/tasks-page/actions-menu.tsx
- cvat-ui/src/components/update-linked-cs-modal/select-cs-updating-scheme-modal.tsx
- cvat-ui/src/reducers/cloud-storages-reducer.ts
- cvat-ui/src/reducers/index.ts
- cvat-ui/src/utils/modals.ts
> Support bulk organization transfer

- changelog.d/20250821_134503_dmitrii.lavrukhin_lightweight_backups_for_static_cache.md
- cvat/apps/engine/backup.py
- cvat/apps/engine/task.py
- cvat/apps/engine/tests/test_rest_api.py
- tests/python/rest_api/test_tasks.py
> lightweight backups for tasks with static cache

- changelog.d/20250826_181936_roman_message_image_compression_errors.md
- cvat/apps/engine/media_extractors.py
> Better message for image compression errors

- changelog.d/20250818_171014_simplify_custom_requests_in_sdk.md
- cvat-sdk/gen/templates/openapi-generator/api_client.mustache
- cvat-sdk/gen/templates/openapi-generator/rest.mustache
- site/content/en/docs/api_sdk/sdk/lowlevel-api.md
- tests/python/rest_api/utils.py
- tests/python/sdk/test_api_client.py
Closes https://github.com/cvat-ai/cvat/issues/9252
While using low-level SDK API, in some cases users have to send custom requests. For example, when downloading exported files. This is doable, but can definitely be improved, and should also be documented. This PR tries to improve the situation.
- \[SDK\] Improved the API of `ApiClient.update_params_for_auth()`. This function serves as a key step required to apply `ApiClient` authentication configuration to a request.
- Reduced the number of required parameters from 7 to 2
- This function now inserts the `'Origin'` header if any of the `'csrfAuth', 'csrfHeaderAuth'` are configured (instead of only `'csrfAuth'`)
- \[SDK\] Added more API documentation for `ApiClient.request()`
- \[SDK\] Added documentation on sending custom requests with …
> Simplify sending custom requests with ApiClient

- cvat/apps/dataset_manager/bindings.py
- cvat/apps/dataset_manager/formats/cvat.py
- cvat/apps/dataset_manager/tests/test_streaming_efficiency.py
In https://github.com/cvat-ai/cvat/pull/9694 I introduced CommonData.LazyFrame, and here I remove it.
Now CommonData.Frame can be initialised as lazy - without `labeled_shapes`, `tags`, `shapes`, `labels` fields, and init them the moment any one of them is accessed
> Removing LazyFrame

- .github/workflows/main.yml
- changelog.d/20250918_142605_petr.iosipov_DEV_711.md
- helm-chart/Chart.yaml
- helm-chart/values.yaml
Need to get rid of Bitnami image repos
Testing with CI in progress
> [DEV-711][Bitnami] updated values for images that use our public ECR

- dev/requirements.txt
> Upgrade to isort 6.x

- Dockerfile.ui
- cvat/requirements/base.txt
> Update Nginx base image to 1.29.1-alpine3.22-slim
